### ISSUE TITLE
fix DNS names & wiki deployments

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1002]
the following is wrong

     - https://deploy3bot.testnet.grid.tf/threebot_deployer/#/

suggest to go to better DNS handling

- create a list of DNS names we need for hub, deployer, ...
- define what the endpoints are for the services on tesnet
- deploy a chosen DNS solution which takes all config from a github dir (rob kubernetes?)
-  point to this DNS solution

dns names (... = .testnet.grid.tf)

- 3bot_deploy...
- vdc_deploy...
- hub...
- wiki...
- explorer...
- boot...
- token_stats... -> points to our statistics around tokens (page made in Dubai)
- cloud_manual...  -> points to gridsome based wiki manual for planetary fs and evdc
- 3bot_manual... -> points to wiki based manual (our original wiki format, is now sdk manual)
- iac_manual... -> points to a new wiki based manual

did we forget something?

**Comment by despiegk** [comment]
see https://threefold.testlodge.com/projects/40893/suites/179711?expand_section=268577#case_3061081

**Comment by despiegk** [comment]
make sure manuals are all up to date

**Comment by weynandkuijpers** [comment]
This issue has not been update for a long time.  Please reconsider if this is part if this release or the next.  I'll remove it if not update and considered part of this release.  Bump it up to in progress is this needs to be done in this release or push it to the next one.

**Comment by xmonader** [comment]
Don't think this is deliverable in 2.5 (end of this week)

**Comment by xmonader** [comment]
according to the last update from @Vilnite , all websites/wikis are in order, for other services they're suffixed with .testnet.grid.tf or .devnet.grid.tf properly
