### ISSUE TITLE
2.5 needs to be properly prepared

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1006]
- components defined well
- link between releases & components
- version nr's prepared on right repo's (use the new jumpscale repos, see #1005)
- make sure all open issues of what to do are in the repo's and visible in release repo;s
- cleanup funnel of bugs/fr in all repo's
- make sure main projects can be chosen in the relevant repo's

**Comment by despiegk** [comment]
use the 2.5 mindmap, check all is in, let Kristof check

**Comment by sasha-astiadi** [comment]
see issue #996
theres already a pr for the home repo 3bot and grid 2.5 on https://github.com/threefoldtech/home/pull/996 since 2 weeks

**Comment by sasha-astiadi** [comment]
release note draft in progress
