### ISSUE TITLE
STORY: basic power management for TFGrid farmers & reserved flag for these nodes

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1009]
- we need ability for farmers to only boot parts of their nodes once a day and be registered in explorer
- ansible???
- need to check that registration happened
- need reserved flag for nodes in explorer
    - a reserved flag means node is shown with all capacity used, so it cannot be used for deploying stuff
    - it only needs to contact explorer once a day

**Comment by sasha-astiadi** [comment]
this issue need to be reworked on for 3.0

**Comment by muhamadazmy** [comment]
Requires specifications.
