### ISSUE TITLE
Preparation go-live: farms, IP addresses, ...

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#1016]
Needed for go live VDC: 

- [ ] List of farms that are VDC provider, with capacity
   - [ ] Ghent
   - [ ] Bancadati - as from March
   - [ ] GreenEdge

- [ ] List of Network farmers and number of available IP addresses per network farmer
   - [ ] Ghent
   - [ ] Lugano
   - [ ] GreenEdge

**Comment by andhartl** [comment]
lives now here: https://github.com/threefoldtech/tf_operations/issues/113
