### ISSUE TITLE
ThreeFold connect app does not verify my email

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1017]
Have installed the ThreeFold connect app on a new phone Android phone.

3bot account: weynandkuijpers.3bot

- have been successful in verifying my phone with SMS 
- have been unsuccessful in verifying my Threefold Connect app by email (and therefore cannot use it to use it for SSO.

Android version 12 QKQ1 200512.002

I never receive the email on the email account listed in the 3bot account.

**Comment by ken-de-moor** [comment]
@weynandkuijpers in the logs it seems your email address is weynand@threefokd.io

could you delete and recover account using the correct email?

**Comment by ken-de-moor** [comment]
Going to close as it's obviously a typo, and verify worked when I did the flow again on 3 different devices.

**Comment by weynandkuijpers** [comment]
Did not see that - apologies.
