### ISSUE TITLE
TFNOW: marketplace cleanup

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1018]
- now.threefold.io : which is the commercial website about marketplace and has all solutions described (team promotion)
- content from gridsome wiki ex now.threefold.io -> the new now.threefold.io which is based on new web framework (team promotion)
- on each commercial page there is "deploy now button" -> go to auth page, see who user is, redirect to their evdc and their marketplace for that solution 
    - if you don't exist, ask to install TF Connect https://github.com/threefoldtech/js-sdk/issues/2623

TODO: specs about the flow ...

**Comment by OmarElawady** [comment]
Created an [issue](https://github.com/threefoldtech/js-sdk/issues/2623) for the last point to be tracked in js-sdk

**Comment by Vilnite** [comment]
For tracing this issue on Foundation: https://github.com/threefoldfoundation/www_threefold_marketplace/issues/10

**Comment by sasha-astiadi** [comment]
duplicate from https://github.com/threefoldfoundation/www_threefold_marketplace/issues/10
