### ISSUE TITLE
planetary filesystem how to get started in cloud_info.threefold.io

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1022]
- how to use docker build file to build the components
     - needs to have ipv6 on host
     - need to have /64   
- how to use those components on an ubuntu to get a FS 
- lets create a script on vlang for
    - using the components and startup a filesystem
    - use the flist mounter #1021 
    - use tmux to see the components running
   

see also https://github.com/threefoldtech/js-sdk/issues/2262

**Comment by maxux** [comment]
Standalone Planetary Filesystem deployment on Linux is ready in bash script: https://gist.github.com/maxux/b4e07d03ed3cf4cb9a9dcffc53545dc4

Any dependencies are updated to support the expected workflow.

This will be ported in V to get binary ready to deploy everything without dependencies. This is ongoing.

**Comment by sasha-astiadi** [comment]
closing , moved to https://github.com/threefoldfoundation/info_threefold/issues/3
