### ISSUE TITLE
tfgrid3: enable tf-connect app to support digital twin

### ISSUE THREAD

**Issue by maxux** [threefoldtech/home#1028]
The ThreeFold Connect app will need some changes in order to support TF Grid 3.0: the app will need to be able to create/talk with a digital twin.

In a first step, the app will be used to create a trusted entity into tfgrid database
In a second step, the app will be used to fund the digital twin wallet

The app will need to support Farmer Bot calls. This will be explained more in details.

**Comment by despiegk** [comment]
we need to review more about this
