### ISSUE TITLE
legal link returns 404 - Not found

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1036]
The Terms & Conditions people agree to and linked under app settings link to **wiki.threefold.io/#/legal**

Since this is an app, we do not have control over what version people are using, it is not possible to just update the link in our app and have everyone correctly link to the right place.

When legal links are moved they should always have a redirect. 

Anyone agreeing to terms and conditions as this link is returning 404 will have no legal basis.

**Comment by sasha-astiadi** [comment]
followup on https://github.com/threefoldfoundation/home/issues/134

**Comment by despiegk** [comment]
this link needs to put into our redirect section of our publishing tools
see #1039
