### ISSUE TITLE
publishingtools 2.8

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1039]
# publishingtools 2.8

## features of publishing tools

- [x] webserver for publishing tools (wiki & webserver content)
- [x] support ACL based on ThreeFold Connect and Secret (no login, only secret)
- [x] dns server which returns hosted services + forwards unknown requests
- [ ] 3 types of content (as specified in sites.json config file)
    - [ ] static = is just static html, files (pdf, zip, ...), javascript which is hosted underneath domain and/or prefix
    - [x] wiki
    - [x] web = gridsome generated content
- [ ] support hyperdrive
    - [ ] import drive as source for static,wiki,web (in stead of git source)
    - [ ] export drive from source (filesystem, git source) -> to a hyperdrive folder
    - [ ] all this info is from sites.json config file
    - [ ] ... tbd ...
- [ ] wizard in threefold now = evdc (input: secret, dnsname for mgmt so we can do the ingress, ssh yes or no, ...)
- [ ] redirect feature, a domain name redirects to other location (for backwards compatibility) 

## admin features on digital twin frontend

- [ ] All above features need to be able to be expressed in the sites.json file
- [x] secret for remote management (as given from helm template)
- [ ] rest interface for some admin functions (protected by secret)
     - [ ] ability to upload new (version) of sites.json config file 
     - [x] ability to add ssh authorised key to server and enable ssh
     - [x] ability to retrieve internal ip addr (useful to see how to connect over internal network)
     - [x] ability to use publishtools to pull all repo's (run as sub process)
     - [x] ability to use publishtools to flatten and get content to digital twin server, reload DTWin Server
     - [x] ability to update publishtools (use the update feature)
- [ ] vlang based client using above rest interface with the secret
- [ ] rest interface exposed on kubernetesip by using a defined dns hostname as specified during install

## deliverables

- [ ] docker image with basic requirements for publishing env
    - [ ] ubuntu 20.10 or 21.04 based
    - [ ] docker build script to build it
    - [ ] use publishtools itself to install all requirements (get the publishtool file from github release)
    - [ ] when docker is started it uses secret as ENV variable for allowing the rest functions to work
- [ ] publishtools released on github repo, make sure the boehmc is part of it so only 1 file
- [ ] documentation as wiki on the publishtools repo

## project

- project info see https://github.com/orgs/crystaluniverse/projects/2

**Comment by despiegk** [comment]
see https://github.com/threefoldfoundation/www_config_private (private) for example how to publish something & example config files (internal to TF Admin team only)

**Comment by rkhamis** [comment]
project is tracked here: https://github.com/orgs/crystaluniverse/projects/2
