### ISSUE TITLE
Separate VDC code from SDK

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#1046]
it's time to move vdc code from https://github.com/threefoldtech/js-sdk to https://github.com/threefoldtech/vdc.

things to keep track of:
 - [ ] code itself
 - [ ] docs
 - [ ] tests
 - [ ] easy installation
 - [ ] update docs on sdk

**Comment by xmonader** [comment]
I moved it to 2.10 as we are addressing the backup and some moving parts atm
