### ISSUE TITLE
bring tokenstat.threefold.io down

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1048]
new tokenstat will live on wiki
https://wiki.threefold.io/#/threefold__token_overview

- [x] bring old tokenstat tokenstat.threefold.io  and https://tokenstats.threefoldtoken.com/ down
- [ ] make sure the url tokenstat.threefold.io  and https://tokenstats.threefoldtoken.com/ DNS name points / redir to https://wiki.threefold.io/#/threefold__token_overview

**Comment by hossnys** [comment]
Domain name tokenstats.threefold.io removed now and no redirection could be done to this link as this is not available on the new publishingtool structure and the way it's handling links there .

**Comment by sasha-astiadi** [comment]
@hossnys i got it wrong, updsted the story

**Comment by hossnys** [comment]
This record https://tokenstats.threefoldtoken.com/ also taken down

**Comment by sasha-astiadi** [comment]
@hossnys can we redir https://tokenstats.threefoldtoken.com/ to https://wiki.threefold.io/#/threefold__token_overview

**Comment by hossnys** [comment]
No , as we discussed before in the issue of terms and conditions link , these links likehttps://wiki.threefold.io/#/threefold__token_overview is generated internally and we can't do redirection to it , I think Hamdy explained this before also he can provide more info about it.

**Comment by sasha-astiadi** [comment]
fair enough thanks samir
