### ISSUE TITLE
reliable message bus (june end)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1060]
- [x] move code to threefoldtech https://github.com/threefoldtech/rmb
- [x] document code & how to use in wiki: info_digitaltwin
- [x] spec the following usecases (low level protocol over redis, message, return, ...)
    - [x] wallet management (TFT) @maxux already added an example https://github.com/threefoldfoundation/info_digitaltwin/pull/19
    - [x] TFGrid DB edits https://github.com/threefoldtech/rmb/issues/1 https://github.com/threefoldfoundation/info_digitaltwin/pull/21
    - [x] hypercore/drive mgmt ->  https://github.com/threefoldfoundation/info_digitaltwin/blob/development/src/specs/twin_proxy_commands/hyperdrive.md https://github.com/threefoldfoundation/info_digitaltwin/blob/development/src/specs/twin_proxy_commands/ftp.md
- [x] get kristof to validate the specs 
- [x] implement previous use cases is used 
    - [x] example client which runs those usescases in vlang (client only) (backend logic in the server)
    - [x] use twin front to implement it (examples in server.js in rmb repo https://github.com/threefoldtech/rmb/blob/master/soft-client/server.js)  
- [x] integration with TFGrid DB for destination (if specify twin id or twin name) 

## remarks

- the usecases are running inside twin front see https://staging.threefold.io/info/twin#/dev_architecture
- vlang code in repo in tftech call reliable_message_bus

**Comment by sasha-astiadi** [comment]
pr review
