### ISSUE TITLE
digital twin hub consolidate (June end)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1062]
digital twin code has multiple parts now, this needs to be consolidated.

- [x] filemanager backend
- [x] chat backend (maybe same)
- [x] twin frontend https://github.com/threefoldtech/digitaltwin/issues/269
- [x] rest interface for twin back

- [x] we need good organized code

- [ ] document what is where and how to use

- [ ] deploy using github actions and flist https://github.com/threefoldtech/digitaltwin/issues/270

**Comment by jdelrue** [comment]
Digitaltwin - publishingtools location:
https://github.com/threefoldtech/digitaltwin
Temporary spawner:
https://github.com/threefoldtech/digitaltwin_spawner

**Comment by jdelrue** [comment]
@JensMeire  will make both startup so every DT has its own publishingtools

**Comment by ken-de-moor** [comment]
Implementing publishingserver is in progress. Meeting yesterday about how to tackle it and we've started work on it.

**Comment by Hamdy** [comment]
publishtools supports now vuejs apps as well including (digitaltwin) frontend
I mvoed the frontend repo to https://github.com/threefoldtech/www_digitaltwin so may be it's a good idea to continue development from there @ken-de-moor ?

**Comment by sasha-astiadi** [comment]
need reestimation

**Comment by sasha-astiadi** [comment]
@JensMeire please reestimate

**Comment by sasha-astiadi** [comment]
ken is on holiday, @JensMeire take over this story

**Comment by sasha-astiadi** [comment]
any spec changes please write here @JensMeire

**Comment by JensMeire** [comment]
Currently in a working , stable state. Making changes for CI/CD for staging and production.

**Comment by jdelrue** [comment]
Backend is now npm package and is added to publisher. https://www.npmjs.com/package/@threefoldjimber/digitaltwin-backend

Finishing up our deployment for demo platform, after that ticket can be closed

**Comment by Hamdy** [comment]
everything is working now

**Comment by JensMeire** [comment]
Deployed on staging, to be tested

**Comment by sasha-astiadi** [comment]
@xmonader ready to move forward with deploy using github actions and flist prepare digitaltwin docker image + flist digitaltwin#270

**Comment by Hamdy** [comment]
Staging: http://Digitaltwin-test.jimbertesting.be
we still missing 2 things
- adjust to the new configuration style for publishtools (finished but not yet ported to staging)
- more docs
