### ISSUE TITLE
developers infrastructure/process check

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1066]
## requirements

- [x] good enough camera / microphone
- [x] good enough laptop and extra screen (if not buy we will buy m1 laptop apple in Dubai)
- [x] room to work from which is ok
- [x] check quality network
- [x] check they understand the process & they are part of 1 team and scrums happen per day
- [x] at least 2 screens (notebook + separate screen)

## deliverable

- [ ] list of people with tests of above

**Comment by sasha-astiadi** [comment]
@despiegk is this for dubai only or for every engineer? egypt? belgium too?

**Comment by rkhamis** [comment]
for Egypt: @nayer-sobhy is providing hw for the cairo team

**Comment by rkhamis** [comment]
Egypt is done.
