### ISSUE TITLE
TFJukebox 1.0

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1067]
As per partners request they need an easier way to provision blockchain nodes on top of the grid 

## System requirement

System that is easy to provision blockchain nodes (public, private)

- user can create X blockchain nodes on a random or specific locations
- user can list their blockchain nodes
- Should the user have ssh access to the node?
- check node status/info
- external authentication/payment system using threefold connect app
- user can delete their blockchain nodes
- user can access their blockchain nodes?

## Story Items

- [x] Repo https://github.com/threefoldtech/tf_jukebox/issues
- [x] Specs  https://github.com/threefoldtech/tf_jukebox/blob/development/docs/specs/Readme.md
- [x] Prepare wiki https://github.com/threefoldfoundation/info_blockchain_jukebox
- [x] Technical issues
  - [x] Prepare repo structure https://github.com/threefoldtech/tf_jukebox/issues/15 
  - [x] backend https://github.com/threefoldtech/tf_jukebox/issues/17
    - [x] SALs https://github.com/threefoldtech/tf_jukebox/issues/17
    - [x] API server https://github.com/threefoldtech/tf_jukebox/issues/18
    - [x] monitoring https://github.com/threefoldtech/tf_jukebox/issues/10
  - [x] frontend https://github.com/threefoldtech/tf_jukebox/issues/16
    - [x] mockups https://github.com/threefoldtech/tf_jukebox/issues/14
    - [x] logo https://github.com/threefoldtech/tf_jukebox/issues/20
    - [x] frontend website https://github.com/threefoldtech/tf_jukebox/issues/16

**Comment by sasha-astiadi** [comment]
@xmonader @ashraffouda 

i think the spec/requirement can be divided with:
type_story
|
jukebox front end
jukebox back end
jukebox blockchain node creation
jukebox blockchain node management

**Comment by despiegk** [comment]
- lets move all to wiki
- organize well
- reem-kristof to review
