### ISSUE TITLE
TFChain 2.8 improvements (June 20)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1069]
- [x] 3.0 farming needs to work with TFGrid 2.x
- [x] hardening of Binance smartchain bridge
- [x] persistent storage for our bridges and make sure HA ok

**Comment by sasha-astiadi** [comment]
needs reestimation

**Comment by sasha-astiadi** [comment]
investing being put to later because the pricing hasnt been up to average of  0.1 , and we have more urgent issues to do
