### ISSUE TITLE
Freeflow application to use TFGrid DB

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1070]
Freeflow app is a fork of threefold connect app with only authentication functionality, data source is TFGrid DB 

- [ ] Create new app in Android/IOS stores under a new organization
- [ ] Remove all functionality except authentication & settings
- [ ] Seperate data source compared to ThreeFold Connect, using TFGrid DB
- [ ] Freeflow branding

To be discussed :

- Who will provide freeflow branding? Who decides how this is branded?
- How do we access TFGrid DB from the app? Do we have all calls needed to validate if users already exist and create new users?
- Do we allow existing TGGrid DB users to recover using seed phrase? Or do we start with a clean new userbase?

**Comment by jdelrue** [comment]
Kds said it should be under a new organisation?

**Comment by ken-de-moor** [comment]
Scrapped to be done in TF Connect

**Comment by Florian-ootopia** [comment]
Hello @ken-de-moor  for what I understand this will be a temporary solution while we will be working on FF Connect UX/UI for public launch right? @despiegk do you know if the selected few for the beginning could access Peertube and Gallery through a web browser with a FreeFlow identity with their TF Connect ID? I see that it was asked in that issue who would provide the Brand identity. I will take care of that part. I will be going around and interacting getting used to this.
