### ISSUE TITLE
TF Connect improvements (June 24)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1071]
## Requirements

- [x] Better planetary network integration (not as text on top, need to be better integrated) 
   - [x]  Android 
   - [x] iOS
  
- [x] New menu 
- [x] Digital Twin reservation https://github.com/threefoldtech/threefold_connect/issues/232
- [x] Digital Twin product code buy 
  
## remarks

~~- email / tel not required~~
~~- will later have verification system by peers, not for now~~

**Comment by jdelrue** [comment]
- Who will create the company on which to release the app, both Android and Apple?

**Comment by jdelrue** [comment]
- DNS integration to be researched if that is technically doable on mobile, I doubt this.
- Who can create the Token? @robvanmieghem ?

**Comment by robvanmieghem** [comment]
@jdelrue sure I can, please create a github issue for it

**Comment by ken-de-moor** [comment]
Original plan was to make a seperate FreeFlow app, going to integrate identity management, inside ThreeFold Connect instead.

Freeflow app plan is scrapped for the foreseeable future.

See linked issue comment : https://github.com/threefoldtech/home/issues/1070

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/home/issues/1078 facial recognition

**Comment by sasha-astiadi** [comment]
bug fix important:  authenticatior doesnt load for some people

**Comment by jdelrue** [comment]
Development has started - however we will end somewhere beginning of july  ; not june 24

**Comment by sasha-astiadi** [comment]
Needs to be re-estimate

**Comment by jdelrue** [comment]
More info about impl

https://github.com/threefoldtech/threefold_connect/issues/261

**Comment by xmonader** [comment]
funding service is implemented thanks to @DylanVerstraete 
https://github.com/threefoldtech/substrate-activation-service
![image](https://user-images.githubusercontent.com/64129/123129866-9063e180-d44c-11eb-9213-bcd6bda066fc.png)

https://api.substrate01.threefold.io for testing

**Comment by sasha-astiadi** [comment]
`need to know of whether identity management is blocked by https://github.com/threefoldtech/tfgrid-substrate/issues/12 @MathiasDeWeerdt

**Comment by xmonader** [comment]
@sasha-astiadi this shouldn't be blocked, we provided a functional environment 16 days ago for the team to develop and test against..

**Comment by xmonader** [comment]
It seems the development is blocked https://github.com/threefoldtech/threefold_connect/issues/261#issuecomment-872782633

**Comment by jdelrue** [comment]
Meeting with KDS today

**Comment by sasha-astiadi** [comment]
@jdelrue Please update the status on this issue

**Comment by JonasWijne** [comment]
Ticket is unblocked; see https://github.com/threefoldtech/threefold_connect/issues/261#issuecomment-872782633

**Comment by jdelrue** [comment]
We will discuss ETA later this week when we have more info

**Comment by jdelrue** [comment]
Backend is now npm package and is added to publisher. https://www.npmjs.com/package/@threefoldjimber/digitaltwin-backend

**Comment by sasha-astiadi** [comment]
two separate releases :

TF Connect App (release 1)
next release will include:
1. Digital Twin reservation 
2. UX app menu Redesign 
3. Deposit fee info text on BTC-TFT asset 
4. Planetary network new UI android

TF Connect App (release 2)
4. Planetary network new UI apple

TF Connect App (release 3)
4.  identity management

**Comment by sasha-astiadi** [comment]
socketio is not working and being investigateds. Its blocking  app from being released on staging.

**Comment by sasha-astiadi** [comment]
- [ ] identity management
    - [ ] identity managed on TFChain (parity/substrate backend) -TFGridDB
    - [ ] ask for the unique 2part name (min 5 char's each)
    - [ ] if already exists from other user, warn
    
    moved to the other story https://github.com/threefoldtech/home/issues/1114
