### ISSUE TITLE
telegram bot vlang (June 10)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1074]
please fork https://github.com/dariotarantini/vgram to crystaluniverse and work further on it

- make sure all new telegram features are supported
- more examples
- make sure vlang libs used properly (Http client), check quality of code, improve if needed
- more documentation

I need this before Friday this week, please

add info to our vlang info (wiki)

**Comment by rkhamis** [comment]
https://github.com/crystaluniverse/tf-telegram-bot#create-your-own-bot-with-payment-support

**Comment by rkhamis** [comment]
currently waiting on feedback from the marketing team, but initial work is done
