### ISSUE TITLE
vlang wiki (june 10)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1075]
- in crystal universe
- create wiki (see below for config)
- copy all docs from vlang to the wiki, nice layout in sidebar
- add more examples
- link to the library docs in navbar

config for sites.json (see kristof_wiki example)

```json
	{
		"name": "info_vlang",
		"url": "git@github.com:crystaluniverse/info_vlang.git",
		"branch": "",
		"pull": false,
		"reset": false,
		"cat": 0,
		"shortname": "vlang",
		"path_code": "",
		"domains": [
			"vlang.threefold.me"
		],
		"descr": "",
		"groups": [],
		"acl": [],
		"trackingid": ""
	}
```

**Comment by rkhamis** [comment]
initial work is done here: https://github.com/threefoldtech/info_vlang

**Comment by rkhamis** [comment]
all done here: https://github.com/threefoldtech/info_vlang

**Comment by rkhamis** [comment]
staging set up: https://staging.threefold.io/info/vlang#/
