### ISSUE TITLE
editor publishing tools

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1077]
- [x] Digitaltwin frontend integration with publishtools (it includes filebrowser)
   - [x] [Vuejs apps integration into publishing tools](https://github.com/crystaluniverse/publishtools/issues/105) since digitaltwin frontend is a vue.js app
   - [x] [Support Digitaltwin frontend by publishtools](https://github.com/crystaluniverse/publishtools/issues/106)
      - [x] Digitaltwin Frontend is now separated into : https://github.com/threefoldtech/www_digitaltwin
- [ ] Digitaltwin backend integration with publishtools
   - [x] [Backend integration](https://github.com/threefoldtech/digitaltwin/issues/269)
   - [x]  Use publisher 3bot connect login mechanism  (in progress)   (working on this today ) with @JensMeire 
   - [x]  Support admin (owner) of digitaltwin in config file. so we can verify logged in user is admin
   - [x] Support adding staff members (admins) for the publisher so they can edit pages from UI
 - [ ] Editor
   - [ ] add edit button on each markdown page (only appears for logged in users with write permissions)
   - [ ] Editor should open the source page from source repo not the flattened version in separate protected page having [stackedit](https://github.com/benweet/stackedit )
   - [ ] if user is editing older version of the page, save operation should fail (they need to refresh)
   - [ ] Add a new adming page where admins can see (edited) wikis with 2 buttons besides each entrry `see on staging` & `publish to production` once staging  and `revert to original` only commit changes and push  `in case of production`
   

runs as part of the first digital twin, which launches on the TFGrid using 3.0 primitives

**Comment by sasha-astiadi** [comment]
whats the status? need reestimation

**Comment by Hamdy** [comment]
- [x] Digitaltwin frontend integration with publishtools (it includes filebrowser)
- [ ] Digitaltwin backend integration with publishtools
   - [x] Backend integration
   - [ ] Remove auto 3bot connect login from frontend  (working on this today ) with @JensMeire 
   - [ ]  Use publisher login mechanism  (in progress)   (working on this today ) with @JensMeire 
 - [ ] Editor
   - [ ] Allow a mechanism for users to login into publisher as admins may be 
   - [ ] add edit button on each markdown page (only appears for logged in users with write permissions)
   - [ ] Editor should open the source page from source repo not the flattened version and does flatten on each save

**Comment by rkhamis** [comment]
the storycard is edited with the proposed approach.
@despiegk please check, if all good, we'll create issues and put an estimation

**Comment by rkhamis** [comment]
on hold for now
