### ISSUE TITLE
FFFL token

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1080]
- [ ] super easy to buy FFFL
    - [ ] wallet (like in TFConnect) but has add FFFL token
    - [ ] also show FFFL token (FreeFlow for life token, just another trustline on Stellar for now)
    - [ ] allow people to buy X nr of FFFL with TFT, can be centralized (see rob) = 999 TFT 
    - [ ] allow people to buy X nr of FFFL with BTC (will underneith go to TFT first)
- [ ] referral system 
    - [ ] when people want to register they need to specify in the FFConnect name of their referral, the referral person need to accept . We need to remember somewhere who referred who

**Comment by Florian-ootopia** [comment]
Hello @jdelrue , very pleased to meet you and to see that you are a biker too :) I am new in the use of GitHub so starting to go around and interact. Not sure yet of what I can edit or not. Is there only one referral person needed or should it be 2 or 3? Is that connected to another document? Thanks!
