### ISSUE TITLE
Decentralize TfGrid DB 3.0 consensus

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1083]
- Currently the TfGridDB 3.0 is running in dev mode on a single node
- In order to have this more decentralised and use the power of the Substrate blockchain technology this needs to be set up differently
- The consensus needs to be distributed over 9 nodes with their own substrate identity.

**Comment by despiegk** [comment]
we need to deploy, lets just do
lets see if we can do it with smart contract for IT with our wisdom council
if not then lets do now but then we will have to upgrade later

or we can deploy 3 of them for now in our redundant env

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/tfgrid-substrate/issues/13
