### ISSUE TITLE
zos3: tfgateway support (WRONG, DONT USE)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1084]
# tfgateway

- tfgateway: github.com/threefoldtech/tfgateway
- coredns: threefoldtech/coredns-redis

Current setup  requires:
- redis
- coredns
- wireguard 

As a farmer I expect I can deploy just the gateway infrastructure on zos3 as primitive

https://github.com/threefoldtech/vgrid/pull/4
```v
pub struct ReqZOSGateway {
	name string // unique per deployment? it will be only one on server
	redis_endpoint: "", // redis master endpoint (note the setup should be a redis cluster) ? or should be relative to the node? ? subdomain pallet over gridb ?
	corefile: "",  // coredns config overriden by our default Corefile, maybe shouldn't be exposed at all	
	wg_enabled: true, // can be used for 4to6?
	managed_domains: "", // domains managed by that gateway (comma separated domains) vdc.devnet.grid.tf ,3bot.devnet.grid.tf
	nameservers: "",  // the managed domains should be configured on external provider (comma separate names)
	stats_endpoint:"", // where to push metrics? can't be empty, needs to have a liveness endpoint
	tid int32  // farmer tid, should it be included or we need to verify the request initiator is a farmer already?
}
```

## expected errors:
- invalid managed domains
- invalid redis
- broken Corefile? 
- invalid nameservers
- already reserved domains/name servers

## Questions:
- where to store the domain records? 
  - are we going to continue using redis? or maybe have a better option using some substrate pallet?
  - if we are going to use redis, who is going to provision it? who is going to ensure the high-available setup? please note the current setup isn't HA

- if gateway is going to be a primitive, how the redis wil be spawned? should be  done over the zos provisoner? or use tfgriddb instead?
- how to ensure to have a cluster of redis? means we need to be able to specify more than single redis to connect and recover from? but probably we can do anything if the node is itself is dead which defeats the HA anyhow, or could it be respawned on a different farm? who is going to manage that?
- gateway will require a public IP (guess it can be done over one of the access nodes too)
- should we use griddb for the records? what about tcp router client (please note the even if the trc initiates connection to multiple gateways, you can't continue an existing session from another gateway, which will break the session most probably)
- single node can have only one gateway
  - port authority? and most likely having multiple gateways actually on the same node won't be needed
- spawning the VM: in the current setup we have systemd services (redis, tcprouter, coredns), Probably all needs to get configured to use zinit? or systemd is just fine in case of the VM? -requires building a separate flist-
- should we use 4to6 over wireguard? can't we use plain socats? 

## registering the gateway
- there is a negotiation happening between the gateway and explorer to validate the domains, nameservers, but I guess that logic can already be validated in the registration phase with palllet module logic

## applying workloads
- now that explorer is gone we won't be able to push / pull from the curent exlorer
- data needs to be validated/stored using a gateway pallet anyhow

## extending gateway
- right now we only have http  and https, tcp for http we redirect to https based on host header and redo over https -> will move to tcp level after

## metrics
as the gateway is going to multiplex traffic against X nr of tcprouter running over X domains, we can aggregate the traffic data per domain (incoming, outgoing) and push to some sort of grafana 

## billing 
the farmerbot probably can be allowed to access the metrics and invoice the users owning subdomains

### TFGateway
- list gateways

- returns a list of gateway nodes, location, number of workloads, configured nameservers list, managed domains list

```
[{"id":5,"node_id":"9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2","farm_id":15,"os_version":"master@a1b9831","created":1607875697,"updated":1623841051,"uptime":15983636,"address":"","location":{"city":"Unknown","country":"Netherlands","continent":"Europe","latitude":52.3529,"longitude":4.9415},"public_key_hex":"7caa026f883c05cdf32a4630573a880e3463ab75981f2e2f7facb48d2c915bdd","workloads":{"network":0,"network_resource":0,"volume":0,"zdb_namespace":0,"container":0,"k8s_vm":0,"generic_vm":0,"proxy":0,"reverse_proxy":197,"subdomain":884,"delegate_domain":0},"managed_domains":["webg1dev.grid.tf","webg2dev.grid.tf","vdcdev.grid.tf","3botdev.grid.tf"],"tcp_router_port":18000,"dns_nameserver":["ns-gwdev.grid.tf"],"free_to_use":false}]
```
- register_gateway

**Comment by muhamadazmy** [comment]
This require some research but this perfectly can run inside a container on a zos node. with right network setup (public IPs, and such). looking into this into details might show unforeseen issues or reveal a better solution
