### ISSUE TITLE
funding service TFGRID DB

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1088]
- faucet for TFChain money (TFCT= ThreeFold Chain Token) & account
- everyone get 500 TFCT (is for 50 transactions for now), every person can only get one
- the verified SMS is the proof of unicity
- there is a whitelist on the service which allows developers to get more...
- we need make sure TFCT are used for each manipulation of the TFGrid DB

**Comment by DylanVerstraete** [comment]
Code wise complete, need to deploy to devnet now but first:

https://github.com/threefoldtech/substrate-activation-service/issues/1

**Comment by DylanVerstraete** [comment]
Devnet funding service running on:

https://api.substrate01.threefold.io
