### ISSUE TITLE
gitpod for gridsome website

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1089]
for our main website

**Comment by xmonader** [comment]
make sure to check  https://github.com/crystaluniverse/publishtools/blob/development/.gitpod.yml and https://github.com/crystaluniverse/publishtools/blob/development/.gitpod.Dockerfile

**Comment by hossnys** [comment]
threefold.io website is depending on https://github.com/threefoldfoundation/data_threefold and it's private repo which need to be pulled by publishing tool to run website , so can't add env variables through gitpod setting or through docker file script , so there is a suggestion from Hamdy to have an argument  github_user and github_pass to be  passed to publishtools command to aviod private repos access issue, but this will take some time if agreed on it

**Comment by xmonader** [comment]
@hossnys I made the repo public, let's see if that unblocks you

**Comment by hossnys** [comment]
gitpod [dockerfile](https://github.com/threefoldfoundation/www_threefold_io/commit/6bd341da13a7af8951c5f4d2f14aaccb2a4c8af9) and other needed [configuration](https://github.com/threefoldfoundation/www_threefold_io/commit/f7169dfee768d212018f6f54a7a88d7ee8fd806e)  added to www_threefold_io repo and it's showing a running version for the website now when clicking on Gitpod button but just need to allow pop-up from browser settings to allow opening new tap for the website.
