### ISSUE TITLE
DigitalTwin v1 beta - filesharing

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1093]
- [x] Filesharing between users, ability to send message over chat
- [x] files are opened from originating digitaltwin
- [x] include collaboration mode

**Comment by sasha-astiadi** [comment]
detail here https://github.com/threefoldtech/digitaltwin/issues/278

**Comment by JonasWijne** [comment]
Most work is done; release planned july 20

**Comment by sasha-astiadi** [comment]
error on staging, investigating

**Comment by jdelrue** [comment]
Staging ok, testing planned for today by @ken-de-moor
