### ISSUE TITLE
Kubernetes to run on zos3

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1095]
as the kubernetes workload got removed from zos3, we need to be able to run kubernetes as normal VMs with a specific flist on top of zos3

check: github.com/threefoldtech/cloud-container

**Comment by ashraffouda** [comment]
image is here
https://github.com/threefoldtech/tf-images/pull/46
currently we are trying to do deployment with exteranl etcd

**Comment by xmonader** [comment]
verified
