### ISSUE TITLE
Grid 3.0 on Substrate

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/home#1098]
We came to an agreement that we want to have workloads and billing on Substrate.

Things that we need to do in order to achieve this:

- [x] https://github.com/threefoldtech/substrate-pallets/issues/3
- [x] https://github.com/threefoldtech/substrate-pallets/issues/2
- [x] https://github.com/threefoldtech/zos/issues/1330
- [x] https://github.com/threefoldtech/tfgrid-substrate/issues/18
- [ ] https://github.com/threefoldfoundation/tft-parity/issues/5
- [x] https://github.com/threefoldtech/tfgrid-substrate/issues/19

**Comment by despiegk** [comment]
please note we will try to do all on substrate but will also try with tendermint,
we need to see what is best/most secure

we already have a leadway on substrate for sure

**Comment by DylanVerstraete** [comment]
Spec doc:

https://github.com/threefoldtech/substrate-pallets/blob/master/pallet-smart-contract/spec.md

Flow for 3.0 with substrate:

https://github.com/threefoldtech/substrate-pallets/blob/master/pallet-smart-contract/flow.png

TF Grid DB ER model:

https://github.com/threefoldtech/substrate-pallets/blob/master/pallet-tfgrid/diagram.png

**Comment by DylanVerstraete** [comment]
We can already start doing some testing. The specs are implemented and is live on Devnet (Zero-OS and Substrate)
