### ISSUE TITLE
Multi wallets for internal tokens (gig, tf, ...)

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#11]
# description

- need script to deploy in ZOS (through ZOS client)
- functions
    - create container with Rivine wallet, retrieve seed and store in config mgr
    - create 1 or more addresses on the wallet
- need rivine client which can do transactions with
    - multisig
    - lockup period
    - combination of both

# goal
 
- create wallet on testnet to simulate our token distribution
- allow us to make scripts to do this

- run multiple wallets

# Related tickets:
- [x] [Add support for Multisig feature](https://github.com/Jumpscale/lib9/issues/353)
- [x] [Document MultiSig](https://github.com/Jumpscale/lib9/issues/348)

**Comment by ahussein** [comment]
why this is in progress. I still have no idea how to sandbox jumpscale with the new code and create flists ?

**Comment by rkhamis** [comment]
This storycard is obsolete
