### ISSUE TITLE
payments / pools stability 2.x

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1102]
- [x] https://github.com/threefoldtech/tf_operations/issues/185
- [x] https://github.com/threefoldtech/tfexplorer/issues/339
- [x] https://github.com/threefoldtech/tfexplorer/issues/340
- [ ] https://github.com/threefoldtech/tfexplorer/issues/336
- [x] https://github.com/threefoldtech/tf_operations/issues/202
- [x] https://github.com/threefoldtech/tf_operations/issues/204
- [x] https://github.com/threefoldtech/tf_operations/issues/199
- [x] https://github.com/threefoldtech/js-sdk/issues/3246
- [x] https://github.com/threefoldtech/tf_operations/issues/157
 
Currently, it's in a very sad state 
![image](https://user-images.githubusercontent.com/64129/125263842-a5bd8480-e303-11eb-9ed6-56e3eaa7cc6d.png)

**Comment by despiegk** [comment]
please tell kristof how relevant and what is state

**Comment by xmonader** [comment]
payments is still broken on 2.x 

https://github.com/threefoldtech/tfexplorer/issues/339 and the custom stellar node isn't ready as well https://github.com/threefoldtech/tf_operations/issues/185
