### ISSUE TITLE
ZOS/VLANG integration 3.0

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1103]
- [x] locate repo for this code (can be private for now) https://github.com/threefoldtech/zos3_v_examples
- [ ] make sure it runs using gitpod (so everyone can play with it using some ZOS nodes in development)

## Version one

- planetary network only
- VM (flists) & ZDB only

## Minimal requirements

- [x] https://github.com/threefoldtech/zos3_v_examples/issues/1
- [x] https://github.com/threefoldtech/vgrid/issues/10
- [ ] https://github.com/threefoldtech/vgrid/issues/8
- [x] https://github.com/threefoldtech/vgrid/issues/9
- [x] https://github.com/threefoldtech/vgrid/issues/6
- [ ] example of how to access your TFT wallet info, send money, ... (over twin frontend)
- [ ] example how to update node/farmer/... in TFGrid DB (over twin frontend)

## remark

- will need planetary network to run in gitpod (have pre-build binary ready & install with script)
- redis/rmb/twinfrontend needs to start auto in gitpod

**Comment by xmonader** [comment]
## couple of things that needs to be worked out
1- the current work needs a patch in v to work
2- the creation of the account, twin is all done using the website https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fexplorer.devnet.grid.tf%2Fws#/explorer should work from the cli-tool
3- there's a dependency on https://github.com/threefoldtech/tfgrid-substrate/tree/master/cli-tool to create contracts, canceling contracts
4- the loading of the seed isn't that easy, we do it from python to get the secret, pubkey https://github.com/threefoldtech/vgrid/blob/review-types/testdeployment.v#L109 
5- redis timeout https://github.com/crystaluniverse/crystallib/pull/23 should get merged, but awaiting on maxime (that's for the rmb messages)

## what is available
- scripts to query node by location, county https://github.com/threefoldtech/vgrid/tree/main/examples
- script to get deployment https://github.com/threefoldtech/vgrid/blob/review-types/getdeployment.v
- script to create deployment https://github.com/threefoldtech/vgrid/blob/review-types/testdeployment.v (this one has wireguard, zmount, zmachine + ssh)

**Comment by despiegk** [comment]
needs to use nodejs : twin_server as middle way over RMB
need to use enduser API specs
