### ISSUE TITLE
TFConnect backend services grid migration

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1105]
All services running on old box in Lochristi will be moved to TFGrid using helm charts

- [x] create helm charts for tfcconnect wallet
Status files for:
- [x] wallet
- [x] -> production
- [x] -> staging
- [x] -> testing

- ---
- [x] threefold-connect-news
- [x] -> production
----
- [x] openkyc
---
- [x] 3botlogin
- [x] -> production
- [x] -> staging
- [x] -> testing
- [x] persistant volumes
---

- [x] pkid
- [x] -> production
- [x] -> staging
- [x] redis
- [x] persistant volume

------
#### GENERAL
- [x] service account
- [x] tls
- [x]  DOCUMENTATION
- [x]  cicd integration
- [x]  persistent storage
-----

**Comment by ldruwel** [comment]
Status files for:
-  wallet
- [ ] tested
- [ ] deployed
-  threefold-connect-news
- [ ] tested
- [ ] deployed
- openkyc
- [ ] tested
- [ ] deployed
- 3botlogin
 - [ ] tested
- [ ] deployed
- actionwidget_frontend
- [ ] tested
- [ ] deployed
- actionwidget_backend
- [ ] tested
- [ ] deployed
- pkid
- [ ] tested
- [ ] deployed
- redis
-  [ ] tested
-  [ ] deployed

**Comment by sasha-astiadi** [comment]
finish this week, hope rob will review next week . @robvanmieghem

**Comment by despiegk** [comment]
need update

**Comment by jdelrue** [comment]
Services are done and deployed, CI/CD is working. Will check with Bert where we add the documentation.

**Comment by ken-de-moor** [comment]
Migration is fully finished.
