### ISSUE TITLE
3bot: onboarding phase 2

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#112]
- User clicks on link in email goes to his 3bot over web.
- 3bot start UI 
- we ask
  - Country
  - City
  - If someone referred you (optional)
  - Private key (existing or new)
    - The mnemonic words if user already has them
    - Otherwise we generate private key
  - We ask user to write down.
  - Screen refreshes we ask user to re-enter the private key again, this for verification purposes.

**Comment by robvanmieghem** [comment]
@robvanmieghem todo:Link to mnemonic documentation

**Comment by robvanmieghem** [comment]
Todo : define recovery options in case of lost username/pass or totp key

**Comment by jdelrue** [comment]
We have this story twice; closed

**Comment by robvanmieghem** [comment]
@jdelrue  can you link the other story here?

**Comment by jdelrue** [comment]
phase1: https://github.com/threefoldtech/home/issues/117
phase2: 
https://github.com/threefoldtech/home/issues/111
https://github.com/threefoldtech/home/issues/116

I mixed them up and ended up with extra story, my bad

**Comment by robvanmieghem** [comment]
@jdelrue the description in #111 is phase1, not phase2

**Comment by jdelrue** [comment]
Fixed
