### ISSUE TITLE
project management (taiga)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1123]
- [ ] new version of taiga
    - [ ] make sure we have this reproducible in line with newer versions of taiga, if possible
- [ ] vlang client for listing, creating issues, stories, projects, ...
- [ ] deploy on gitpod 
    - [ ] vlang client script (test) calling the API on the just deployed taiga
- [ ] upgrade production server once all above is done

**Comment by rkhamis** [comment]
vlang client for taiga: 
  - [x] listing issues, stories, projects....
  - [x] creating issues, stories, projects....
  - [ ] import/export
  
  
  
  new version of taiga is currently being integrated with tf auth
