### ISSUE TITLE
CapRover deployer/support 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1133]
# CapRover on Grid v3

We need an easy way to provision CapRover itself, and also to modify CapRover to make it easy to extend its cluster with grid VMs.

## Provisioning (Grid v3)
It's recommended to use a VM (ubuntu 18) with docker for CapRover installation, we need to:

- Prepare an flist
- Deploy on Grid v3 through
  - Terraform (available for now)
  - Custom Deployer app (fully client side)
  - OR UI Builder which needs to support
    - Deployment through RMB-proxy
    - Ready-to-deploy CapRover VM
    - Storing entity (mnemonics) in the client side (e.g. browser local storage)
    - Data backup/restore (e.g. deployments...) to local file system and other backends (google drive...etc)

## CapRover Modifications

CapRover itself supports adding new VMs to its cluster using only SSH credentials, but we need to make it easy to utilize the grid and deploy a VM then add it without the need to setup/deploy it manually.

- Ability to extend CapRover cluster by directly deploying a node on grid v3
  - Given entity (mnemonics)
  - Deploy through RMB-proxy

Using RMB-proxy is easier than having the full setup to access grid v3 nodes.

**Comment by abom** [comment]
To add worker node, it should have docker and CapRover installed.

- SSH
![Screenshot from 2021-09-28 17-45-44](https://user-images.githubusercontent.com/511438/135120964-aedb2288-1252-4724-8630-90097600f4f3.png)
- Alternative method:
![Screenshot from 2021-09-28 17-45-51](https://user-images.githubusercontent.com/511438/135127616-52571ab6-1826-43a3-bbb9-f98acf2a4a8a.png)
