### ISSUE TITLE
Fix test steps for listed testlodge scenarios

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1137]
add tests here

**Comment by mhost39** [comment]
https://app.testlodge.com/a/26076/projects/40893/suites/193856?expand_section=305799#case_3354715
https://app.testlodge.com/a/26076/projects/40893/suites/193856?expand_section=305799#case_3354716

**Comment by ranatrk** [comment]
scenarios missing adjustments in https://app.testlodge.com/a/26076/projects/40893/suites/194096
TC243: should be npm or yarn as mentioned in the repo docs
TC244-...: `RMB server should be installed and running` should include option RMB server or RMB proxy usage

**Comment by waleedhammam** [comment]
in qsfs
![image](https://user-images.githubusercontent.com/10658229/142759902-a29e83f9-7678-4c1c-862f-45237d7af352.png)

Add link to the documentation

**Comment by RafyAmgadBenjamin** [comment]
in `Javascript client basics` 
No.2 - TC323 - can deploy using TS client, example in manual
the description link address  is not found
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3360450

**Comment by RafyAmgadBenjamin** [comment]
in Test suite: Virtual Machine Deployment

![image](https://user-images.githubusercontent.com/46320202/142854884-e9535f12-ed81-48a0-9531-7937fe02ab33.png)
The three specified flists should be mentioned here to be used directly
