### ISSUE TITLE
Mattermost features

### ISSUE THREAD

**Issue by lucarioams** [threefoldtech/home#1139]
For Mattermost to be adopted there are a few essential features that are missing and some that would be useful to have.

## Essential Features
- Enable threefold connect on mobile app 
- When clicking the "+" button on direct messages show all members, so that people don't have to guess who is in the account and what their 3.bot name is... (see direct.message.overview.of.members.feature.mov) 
- Enable to see the overview of all teams (see overview.of.teams)

## Useful Features
- Enable the ability to invite people to the entire server or multiple teams at once via a specific link or email address
- When you reply to a message it creates a thread (similar to slack)

https://user-images.githubusercontent.com/80516439/151691003-621a9aae-a28e-4127-bead-7d6894c69317.mov
https://user-images.githubusercontent.com/80516439/151691137-b493958c-06bc-49f3-9f17-4c42b6b46c01.mov

**Comment by despiegk** [comment]
we don't have time to change features of mattermost itself, unless its a small thing, we will have to live with how it works I am afraid.

**Comment by despiegk** [comment]
@sasha-astiadi move this issue to repo where we manage mattermost

**Comment by xmonader** [comment]
https://github.com/freeflowuniverse/freeflow_teams_frontend/issues/3
