### ISSUE TITLE
TFConnect  3.X.0 - v2-v3 Migration (Farmer Tool)

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1142]
In the Threefold wallet a new tab is added "Farmers"

<img src="https://user-images.githubusercontent.com/1687505/152300209-112d981a-12cd-4122-9a1b-a551be080d0e.png" width="150">
First version was Wallet centered, has been changed after request from TF to make it more Farm centered.

A list of farms on v2 will be shown, migration to V3 will be possible. Creation of new V3 farms also possible.

 <img src="https://user-images.githubusercontent.com/1687505/152300401-855c0122-ff61-481f-8f62-dab464272857.png" width="150">

Release planned 4/2

Technical info on TF side before development: https://github.com/threefoldtech/tf_operations/issues/320
Repo board: https://github.com/threefoldtech/wallet-next/projects/1

**Comment by despiegk** [comment]
more info? https://github.com/threefoldtech/tf_operations/issues/320

**Comment by ken-de-moor** [comment]
Released on 11/02

Closing and removing from project board in favour of following ticket: https://github.com/threefoldtech/home/issues/1172
