### ISSUE TITLE
STORY: TFConnect 3.6.0

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1144]
Following functionality will be added:

Configuration for new wallet
Deletion of GDPR sensitive data
Removal of .3bot extension for usernames 

Bug fixes

Repo: https://github.com/threefoldtech/threefold_connect/projects/8

**Comment by sasha-astiadi** [comment]
more elaborate story: https://github.com/threefoldtech/home/issues/1170

**Comment by ken-de-moor** [comment]
Updated to 3.6.0 to match actual live versions better.
