### ISSUE TITLE
Uhuru V1.1 beta 

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1146]
EDIT: **Scope change on KDS request**, RMB and grid launch will be shelved for now. We will work on bug fixes and making the version more stable. See board for specific tickets and bugs/features.

BOARD: https://github.com/threefoldtech/twin_aydo/projects/4

~~A big backend change is required to actually communicate using the RMB(Remote Message Bus) and include the full stack on the grid. In this version we won't change anything functionally, but include the backend changes needed to be able to execute this.~~

~~To decentralize this entirely, we will search other addresses on the blockchain, through RMB.~~

~~Included as a result of these major backend changes will be a lot of bug fixing and rewriting flows/code to work with the new backend.~~

Uhuru V1.1 beta

Todo:
~~- Inclusion of RMB~~
~~- Launch / start on grid~~

**Comment by sasha-astiadi** [comment]
duplicate [STORY: Uhuru Beta](https://github.com/threefoldtech/home/issues/1125)

**Comment by ken-de-moor** [comment]
Huge refactor to fix a lot of bugs is currently main focus.

This ticket can be followed up here: 

https://github.com/threefoldtech/twin_aydo/issues/288

**Comment by ken-de-moor** [comment]
Full retesting done, all bugs logged on project board to be included in this release. Refactor almost finished.

**Comment by ken-de-moor** [comment]
We're going to set up a staging env Wednesday with all the current changes and try to prioritize again from there.

**Comment by ken-de-moor** [comment]
Staging version is live, being validated. QA Still not really convinced it's good enough.

**Comment by ken-de-moor** [comment]
Version is live on beta.uhuru.me

Sabrina is helping us with some followup and testing, we are going to slowly introduce more people to help test and validate and recommend improvements.
