### ISSUE TITLE
TF-Connect 3.5.0

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#1147]
EDIT: New blocking issue (405) added 28/02/2022, KYC Provider made breaking changes on new flutter package.

REPO BOARD: https://github.com/threefoldtech/threefold_connect/projects/7

- [x] [As a user, sign a document](https://github.com/threefoldtech/threefold_connect/issues/376)
- [x] https://github.com/threefoldtech/threefold_connect/issues/323
- [x] https://github.com/threefoldtech/threefold_connect/issues/223
- [x] https://github.com/threefoldtech/threefold_connect/issues/363
- [x] https://github.com/threefoldtech/threefold_connect/issues/405

**Comment by sasha-astiadi** [comment]
include small fixes, reopen.

**Comment by ken-de-moor** [comment]
Updated version number since current live version is 3.4.6

**Comment by ken-de-moor** [comment]
All tasks done, ready for verification on staging. Need to plan in QA for this build.

**Comment by ken-de-moor** [comment]
Moved back to in progress as QA determined it not ready yet. 

https://github.com/threefoldtech/threefold_connect/projects/7

**Comment by ken-de-moor** [comment]
Handed in to app store and play store. Live after approval
