### ISSUE TITLE
Node Pilot Light v0.1.0 - VLANG based pokt.net deployment, first gen

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1149]
Deploy PoktNetwork to Terraform Grid Provider

- [ ] [Write script for Node Pilot Light](https://github.com/threefoldtech/node-pilot-light#run)

Pocket Network is a blockchain data platform built for applications that uses cost-efficient economics to coordinate and distribute data at scale, enabling seamless interactions between blockchains and applications. 

In order to deploy PoktNetwork to TF Terraform Grid Provider, we need to reverse engineer the Pokt node pilot into Node pilot light. It is a similar to node-pilot but open-source and stripped down. the scripts are being written into this [repository.](https://github.com/threefoldtech/node-pilot-light)

**Comment by despiegk** [comment]
more specs needed from kristof

**Comment by xmonader** [comment]
@despiegk this issue is still in blocked now for 21 days.

**Comment by sasha-astiadi** [comment]
@maxux Any update?

**Comment by maxux** [comment]
Busy on #1168

**Comment by sasha-astiadi** [comment]
@maxux moved it to a-6 backlog

**Comment by sasha-astiadi** [comment]
@maxux please resolve issue and followup with another ticket if needed this week

**Comment by maxux** [comment]
Follow up: https://github.com/threefoldtech/home/issues/1246
