### ISSUE TITLE
 TF OwnCloud V0.1.0 - Deployer custom website

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1151]
Full spec: https://github.com/threefoldtech/www_owncloud/issues/1

- [x] spec
- [x] prepare owncloud image
- [x] prepare deployer with admin board
- [ ] add terms n condition

project: https://github.com/threefoldtech/www_owncloud/projects/1

ThreeFold has teamed up with Owncloud to provide a time-limited freemium experience of Owncloud product on the TFGrid as a SaaS product. 

Users would soon be able to deploy their freemium TF Owncloud solution by signing up for an account on the new TF Owncloud deployer website using their TFConnect SSO (ThreeFold ID).
Enable TFConnect SSO on deployable solutions

Users would soon be able to sign up on some of the community tools like Mattermost, Gitea, and Discourse that they have deployed on TFGrid by using their ThreeFold ID only. Therefore we are now looking at ways on how to integrate TFConnect SSO (ThreeFold ID) to each of the solution’s code packages.

**Comment by xmonader** [comment]
is this one good to go as part of alpha5?

**Comment by xmonader** [comment]
@weynandkuijpers please check the terms &  conditions

**Comment by sasha-astiadi** [comment]
product is technically finished but moved to a7 due to lacking t^c and because marketing prefers to not include it on release note of alpha6 since they want to launch on later dates

**Comment by sasha-astiadi** [comment]
GE Question: how do customer pay? or do ge need another website etc???

**Comment by xmonader** [comment]
@sasha-astiadi the users pay nothing for 3 month. they get an owncloud instance for free.

**Comment by rkhamis** [comment]
I'm removing this from the project until we get the greenlight from the bizdev team
