### ISSUE TITLE
TFGrid Unified Explorer v0.1.0

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1152]
- [ ] Support V3 networks]https://github.com/threefoldtech/explorer-api/projects/1

Spec[ here](https://docs.google.com/document/d/1i1BRr1VcceyTefwm9w0LlyZYc3JMv0A9LtklOEgYIAM/edit?usp=sharing)

we found a lot of ux/ui mistakes on the tfgrid 3 explorer .   
a lot of improvements are needed. all improvements recorded on the github projects.

**Comment by xmonader** [comment]
this project is replaced with https://github.com/threefoldtech/explorer-api
