### ISSUE TITLE
Weblets v1.2.0

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1153]
Project: https://github.com/threefoldtech/grid_weblets/projects/8

## Some features

On this release we also aim to create UX improvements on the existing [TF Playground website ](https://play.grid.tf/)that could create a better experience for our users. One of them is by simplifying solution deployment processes by creating deployment sizing. 

We would add capacity sizing for each deployment, such as: "small", "medium" and "large". Each size requires a different capacity amount. For example, an ‘S’ size for Funkwhale deployment, would need a different capacity amount to ‘S size for Peertube deployment.

On this release, we will add more community and blockchain solutions such as Mattermost, Discourse (forum), Presearch Node and Casperlabs validator node.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/grid_weblets/issues/406#issuecomment-1047759237

**Comment by rkhamis** [comment]
released
