### ISSUE TITLE
TFChain v1.2.0 - DAO request pt.2

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1154]
github issues on project v1.2.0:
- https://github.com/threefoldtech/tfchain/issues/172
- https://github.com/threefoldtech/tfchain/issues/161

The ThreeFold [DAO](https://library.threefold.me/info/threefold#/tfgrid/threefold__dao) allows autonomous operation of the [TFChain](https://library.threefold.me/info/threefold#/tfgrid/threefold__tfchain) and [ThreeFold Grid](https://library.threefold.me/info/threefold#/tfgrid/threefold__threefold_grid) .

From version 3.0 on, [ThreeFold Grid operates as a DAO](https://library.threefold.me/info/threefold#/tfgrid/threefold__dao). On the last release of TFChain v1.0.0,  we have successfully implemented The first TF-DAO that allows farmers to request to become DAO council members. 

On this release we would like to implement ThreeFold DAO Request part 2 where any farmer could request to become an adjoint validator-council member: by running a a validator node, not only that they become a validator, they would also gain a seat as DAO council member that give them the right to vote for organizational changes.

more about tfdao: https://library.threefold.me/info/threefold#/tfgrid/farming/threefold__tfdao

**Comment by robvanmieghem** [comment]
@sasha-astiadi It's not any farmer, it's anyone

**Comment by despiegk** [comment]
what is this, still needed?
