### ISSUE TITLE
threefold hub 3.0.0 alpha 1

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1158]
see https://github.com/threefoldtech/threefold_hub/projects/1

**Comment by xmonader** [comment]
Currently the team is doing the research on cosmos, how it works and how to write modules.

**Comment by xmonader** [comment]
Results of research https://github.com/threefoldtech/threefold_hub/blob/development/research/README.md

covering 
- running chain
- creating accounts
- minting
- bridges
- consensus
- pocs: polls, dwitter, kvstore, idgenerator


things still to do
- investigating ibc
- multisig wallets
- frontend integration

**Comment by xmonader** [comment]
multisig https://github.com/threefoldtech/threefold_hub/issues/7
ibc: https://github.com/threefoldtech/threefold_hub/blob/development/research/ibc.md

**Comment by sasha-astiadi** [comment]
@robvanmieghem please update issue with project and issues, todos

**Comment by robvanmieghem** [comment]
The project is in the initial comment by Kristof

**Comment by xmonader** [comment]
Frontend for money, and governance being built right now.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfchain/issues/255 plan B for locking up tokens

**Comment by xmonader** [comment]
UI for money transfers & governance is being worked on https://github.com/threefoldtech/threefold_hub/issues/14

here're some images https://github.com/threefoldtech/threefold_hub/issues/14#issuecomment-1090425684

**Comment by xmonader** [comment]
- UI for money is done
- UI for gov is done (no system upgrades supported _can be done next_)

There's an active work for providing  images for the hub

**Comment by xmonader** [comment]
delegation been added in the UI
