### ISSUE TITLE
STORY: blocking issues for alpha 4

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1162]
> TODO: link to projects on repo level where blocking bugs are

- [x] crash of the tfchain-Stellar bridge: https://github.com/threefoldtech/tfchain_tft_bridge/projects/4
- [x] yggdrassil issues https://github.com/threefoldtech/tf_operations/issues/654
~- [ ] mainnet graphql hitting query limit https://github.com/threefoldtech/tf_operations/issues/634~ 
- [x] move pvc tchain nodes from kadalu to local https://github.com/threefoldtech/tf_operations/issues/607

**Comment by xmonader** [comment]
- The main blocking thing is Yggdrasil instability which is being investigated atm
- graphql should be no issue in the future, given it will be hidden anyhow.

**Comment by hossnys** [comment]
this issue is still happening till now https://github.com/threefoldtech/threefold_connect/issues/360#issuecomment-1046287412 
could it be added to this blocking list ??

**Comment by xmonader** [comment]
Yggdrassil issues are partially fixed (Seems to be ok enough for now)
