### ISSUE TITLE
 validators extra for TFChain

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1164]
Everyone should be able to run validators extra for tfchain

## some with voting

- we need procedure to get asap to 9 validators

## most without voting

- we need docu how to all deploy our validators if we want

TODO:
- [x] Document how to run a validating tfchain node
    - [x] using the tfchain binary https://github.com/threefoldtech/tfchain/blob/development/substrate-node/doc/creating_validator.md
    - [x] using k8s with a helm-chart 
~~- [ ] Create an flist for tfchain and document how to run it~~ (moved to https://github.com/threefoldtech/home/issues/1199)

**Comment by xmonader** [comment]
@coesensbert can you please link the relevant docs here.

**Comment by coesensbert** [comment]
This is a rough version i made for our own documentation: https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/Kubernetes-clusters/hagrid-prod2/applications/tfchainmainnet/Adding-validators.md

Allowing a validator is still done with the sudo key.

**Comment by sasha-astiadi** [comment]
@DylanVerstraete please update the issue progress thank zyou

**Comment by sasha-astiadi** [comment]
@rkhamis please edit the story and put it in verification for whats done
