### ISSUE TITLE
ThreeFold HUB & Binance bridge

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1165]
there is an existing project which exists, lets see if this can be used.

or to stellar which is also fine

> TODO: document more

project: https://github.com/threefoldtech/threefold_hub/projects/1
Issue: https://github.com/threefoldtech/threefold_hub/issues/13

**Comment by xmonader** [comment]
initial research https://github.com/threefoldtech/threefold_hub/blob/development/research/bridges.md

**Comment by robvanmieghem** [comment]
project: https://github.com/threefoldtech/threefold_hub/projects/1
Issue: https://github.com/threefoldtech/threefold_hub/issues/13

**Comment by xmonader** [comment]
testversion is live https://threefoldhub.test.gridtesting.xyz
```
- this is how you add bsc testnet to metamask:  https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain
- And you can get BUSDs from here https://testnet.binance.org/faucet-smart
- and you can create a new account with keplr
- and transfer to it and back to bsc
```
