### ISSUE TITLE
Stellar - Unvesting

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1166]
Enable TFT Unvesting
Vesting services has been successfully created and running on v1.4.2. As agreed, locked TFTs from vested accounts would be released monthly, when TFT average price is higher or equal than $0.1 on the particular month.

 github project:[tft-stellar v1.5.0](https://github.com/threefoldfoundation/tft-stellar/projects/15)

**Comment by despiegk** [comment]
many people want a solution for this now, its not fair to also keep them locked up
it doesn't mean they would sell , but the ones who meant well are now disadvantaged

**Comment by despiegk** [comment]
see also
TFT stellar project: https://github.com/threefoldfoundation/tft-stellar/projects/15
Wallet issue: https://github.com/threefoldtech/wallet-next/issues/114

**Comment by robvanmieghem** [comment]
I would not create an entire  cosigner unvesting application anymore since we just want to release the funds.
Let's just prepare the unvest transactions (send all of the TFT back to the owner), have them signed by the cosigners and make them available. The owner then has to sign it too and submit it to the Stellar network.

**Comment by robvanmieghem** [comment]
First thing to do:
- [ ] [Deprecate vesting service](https://github.com/threefoldfoundation/tft-stellar/issues/456)

Next:
- [ ] Generate transactions to return the vested amount to the owners
- [ ] Program for the guardians to sign the transactions
- [ ] Have the guardians sign
- [ ] Publish the signed unvesting transactions
- [ ] An easy way for vesters to fetch the unvest transaction, sign it and submit it

**Comment by robvanmieghem** [comment]
The website still needs some text changes and we'll wait to deploy to production until I'm back from vacation.

**Comment by robvanmieghem** [comment]
Production URL: https://tokenservices.threefold.io/unvest/

The easiest is to open it on your phone so you can copy-paste the address and secret from the TF connect app

**Comment by DylanVerstraete** [comment]
Confirmed unvesting works! :tada:
