### ISSUE TITLE
STORY: crystal lib, vgrid, ... for 3.7.x

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1168]
set of fixes & feature requests for vlang libraties & vgrid client

see 

- https://github.com/threefoldtech/vgrid/projects/1
- https://github.com/freeflowuniverse/crystallib/projects/2
- https://github.com/freeflowuniverse/crystaltools/projects/3

is needed to conclude on rmb in rust, vlang client for tfgrid, hub3

## features

- usage of new httpconnection client
- lots of small fixes on crystal lib

**Comment by sasha-astiadi** [comment]
@maxux whats the latest status

**Comment by maxux** [comment]
Worked on 0-db-fs to support latest feature needed for Pokt read-only layer. https://github.com/threefoldtech/0-db-fs/issues/30
Deployment of Discourse and gitea works with appsbox. Deployment of postgres with management too. Testing integration now.

Mattermost is not yet done and doc still use mysql for now, but support of postgres is integrated.
