### ISSUE TITLE
GetTFT Shop v1.0.4 - UX/UI Improv

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1171]
Minor UX / UI improvements
Project:[ https://github.com/threefoldfoundation/it_as_energy_shop/projects/10](https://github.com/threefoldfoundation/it_as_energy_shop/projects/10)

On this release we aim to create minor UX improvements on the existing GetTFT Shop website that could create a better experience for our customers, such as improved interactivity, fixed embedded media, revised UX content, improved screen responsiveness, and many more.

**Comment by xmonader** [comment]
How was this story created and added to sprint without engineering being involved?
