### ISSUE TITLE
STORY: Provide a weblet to deploy a Subsquid Indexer

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/home#1174]
There is a potential partnership with Subsquid (https://www.subsquid.io/) if we provide a prepared solution for their Indexer software. 

A Subsquid indexer is a piece of software that reads all the blocks from a Substrate based blockchain, decodes and stores them for processing in a later stage. They recently released `FireSquid` which can index a lot faster then their previous version. We saw a great increase in substrate based project using this technology to query on chain data. 

For more information about the setup please contact me.

Firesquid: https://subsquid.medium.com/indexing-for-next-gen-dapps-unleashing-the-firesquid-56312ec4e952

**Comment by AhmedHanafy725** [comment]
Is there a flist for it?

**Comment by DylanVerstraete** [comment]
Hey, no flist for it yet.

**Comment by DylanVerstraete** [comment]
Can we create an flist out of a docker-compose file? https://github.com/subsquid/squid-archive-setup

**Comment by DylanVerstraete** [comment]
Advanced setup guide: https://docs.subsquid.io/archives/archives-advanced-setup/

**Comment by sasha-astiadi** [comment]
its in 3.7 project but not in roadmap.... pls escalate to prio

**Comment by A-Harby** [comment]
[Verified on devent](https://github.com/threefoldtech/grid_weblets/issues/951#issuecomment-1225492694)
Test case/verification steps can be found [here](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3678431).
