### ISSUE TITLE
TF Connect: Wallet v3.1

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1177]
- https://github.com/threefoldtech/wallet-next/projects/4

Main feature: Token unlocking.
Side features: Various Quality Of Life improvements and bug fixes.

- [x] Implement webpack for better IOS version support.
- [x] Fix farmer/wallet version inconsistencies leading to a potential farmers tab load issue.
- [x] Add asset sorting
- [x] Implement contacts
- [x] Show locked tokens
- [x] Unlock tokens
- [x] Add notifications
- [x] White screen improvements.
- [x] Allow token sending to token issuer ( 1 specific address that couldn't receive tokens )
- [x] Improve tap handling for IOS

**Comment by ken-de-moor** [comment]
Updated v2.9 to 3.1 as this will likely be released after the Substrate integration ( V3.0)

**Comment by ken-de-moor** [comment]
Have a meeting later today with development to see next steps needed for validation and finishing this version.

**Comment by sasha-astiadi** [comment]
please do a release note on the repo @ken-de-moor
