### ISSUE TITLE
Create bundle/menu entries for jumpscale scripts 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#118]
Use a bundling tool like pyinstall/py2app to create jumpscale installation on the filesystem with accessible menu items on the host operating system.

that's a two step process
1- bundling using pyinstaller (works on mac/linux)
2- using a suitable installer different ones for each platform like (innosetup, mojosetup) or something cross platform like (izpack, installbundler -free for opensource applications-)

**Comment by sabrinasadik** [comment]
@xmonader is this high prio or not?

**Comment by xmonader** [comment]
@sabrinasadik it was 2nd prio after the slides2html tool 

@despiegk at which milestone is this expected to be delivered?
