### ISSUE TITLE
Testnet + Maininet capacity unavailable

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1180]
Testnet and Mainnet nodes present on the explorer:
![image](https://user-images.githubusercontent.com/13766992/155114455-5d61283a-40e5-4511-a77e-bb1ae6be7a6f.png)

I am due a demo/discussion with the GreenEdge technical team and need to be able to deploy some workloads.....

**Comment by weynandkuijpers** [comment]
trying deployment on terraform:

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

grid_network.net2: Creating...

Error: couldn't reach node 20: non ok return code: 400, body: {"status": "error", "message": "failed to Submit the message: 400 Bad Request (message is too old, sent since 457090h51m23.816170777s, sent time: 0, now: 1645527083)"}

  on main.tf line 14, in resource "grid_network" "net2":
  14: resource "grid_network" "net2" {
```

and:
![image](https://user-images.githubusercontent.com/13766992/155117958-96823d6a-33d6-4e5f-af2c-bb6bd0b9d113.png)

**Comment by DylanVerstraete** [comment]
Should be fixed

**Comment by weynandkuijpers** [comment]
tested and can deploy - no more "failed to fetch resource info"
