### ISSUE TITLE
Wallet V3.0 - Add substrate to the TF Connect wallet

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1181]
# Add (substrate-based) TFChain Wallet
threefoldtech/wallet-next#38
https://github.com/threefoldtech/wallet-next/projects/2

TFGrid v3 is powered by substrate-based blockchain. A TFT is moveable from Stellar blockchain to TFChain through the use of a bridge.

ThreeFold Wallet needs to add (substrate-based) TFChain Wallet in order to support the bridge transaction.

However, TFT is still the native currency on TFChain. As such, there is no need for an external service to transfer tokens on TFChain. A transaction fee is charged (currently 0.01 TFT) for every transaction/extrinsic call.

**Comment by sasha-astiadi** [comment]
please update eta @ken-de-moor

**Comment by ken-de-moor** [comment]
@sasha-astiadi planned to move it this week to verification. Then we'll probably ask some people for help/input to validate and provide some text improvements and depending on that we'll see when it can actually go to production.

**Comment by ken-de-moor** [comment]
Launched on production but with flagsmith config. Need tester/input or someone who has the authority to validate the texts. If people give us their 3bot names we can enable the new version.

**Comment by ken-de-moor** [comment]
Team is meeting in lochristi today to evaluate the changes and potentially release them.

**Comment by sasha-astiadi** [comment]
@ken-de-moor please make the project boards column use the same labels like other projects

**Comment by ken-de-moor** [comment]
Live in production
