### ISSUE TITLE
Validator Deployer Tool (tooling + manual)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1184]
- [ ] vlang based deployment of validator (Kristof)
- [ ] manual how people can run their own validator + rest api + graphql 
- [ ] graphql for validators in manual to separate section

**Comment by xmonader** [comment]
actually duplicate of https://github.com/threefoldtech/home/issues/1164

**Comment by robvanmieghem** [comment]
this is not really a duplicate, this one also contains the tooling, the other one just requires a description of what is already there

**Comment by robvanmieghem** [comment]
@xmonader I suspect you mean Tfchain validators, right?

**Comment by xmonader** [comment]
> @xmonader I assume you mean Tfchain validators, right?

Yes, indeed.

**Comment by sasha-astiadi** [comment]
@robvanmieghem  is this still being implemented or not

**Comment by robvanmieghem** [comment]
It should
