### ISSUE TITLE
Use TF Connect to sign git comments for Gitea.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1186]
BOARD: https://github.com/threefoldtech/freeflowdevenv/projects/2

### GOAL: Have private key management ssh/openpgp as part of TFConnect
- Allow users to generate multiple openpgp keys in TFConnect
   - Allow to generate
   - Allow to delete
   - Allow to give/edit name per key

- Put mechanism in TFConnect Desktop Client (TDC) = planetary network
    - Get private chosen key from TFConnect mobile phone, do this is safe way !!!
    - Generate SSH key from that same key
    - Allow any webapp to ask the SSH & OpenPGP key from the TDC
    - Allow more than 1 key to be stored locally
    - Have a simple local rest api (only on unix socket) to allow manipulation of keys by local user, needs to be local only (see, delete, generate, …)
    - No need to bundle SSH or GPG (is like openpgp), will be on system
- If relevant for the app extract SSH key from OpenPGP key
    - https://superuser.com/questions/360507/are-gpg-and-ssh-keys-interchangable 
    - Seems to be possible but can this be done on TFConnect or do we do this always in TDC, see above, I am fine with that.
- Allow TFConnect enabled app to ask for OpenPGP & SSH pub key based on name
    - Allow user to select which OpenPGP key to use
    - Can be to mobile and/or TDC (am fine either way)

**Comment by sasha-astiadi** [comment]
move to a7

**Comment by ken-de-moor** [comment]
Followup here instead:

https://github.com/threefoldtech/home/issues/1214
