### ISSUE TITLE
Enhancements/Bugs for Alpha-5

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1187]
- [x] weblets bugs: https://github.com/threefoldtech/grid_weblets/projects/12
- [x]  caprover-frontend bugs https://github.com/freeflowuniverse/caprover-frontend/projects/1
- [x]  tfchain explorer: https://github.com/threefoldtech/tfchain_explorer/projects/4
- [x] tfexplorer: https://github.com/threefoldtech/tfexplorer/projects/3
- [x] https://github.com/threefoldtech/tf_operations/issues/768

**Comment by rkhamis** [comment]
- [ ] weblets bugs: https://github.com/threefoldtech/grid_weblets/projects/12
 - [ ] caprover-frontend bugs https://github.com/freeflowuniverse/caprover-frontend/projects/1

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/160352295-82ce0b85-c644-4f24-9e7e-7c1f5f6cd761.png)
https://github.com/threefoldtech/tf_operations/issues/768

**Comment by xmonader** [comment]
projects closed, testnet is back up
