### ISSUE TITLE
Lock down legal link in the wiki.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1191]
This is literally the 4th time that the legal link in the threefold connect app has broken due to the URL randomly being changed, it not being communicated and the previous URL not having a redirect. If we keep doing this then people signing up for TF connect will be able to claim they never actually agreed to any of the T&S as they were not correctly linked.

I recommend either CI/CD automated testing or build scripts or whatever to validate that the link still works and the correct data is displayed on the link. The wiki should not be allowed to go live without this test passing. If for technical reasons this redirect is impossible or the old link just HAS to be removed, then the TF Connect team needs to be informed to update this in the app.

Current link in app : https://wiki.threefold.io/#/legal => Wrongly redirects to https://library.threefold.me/info/threefold#/

Current actual link in production : https://library.threefold.me/info/legal/#/

**Comment by sasha-astiadi** [comment]
@ken-de-moor can we do hotfix and replace the broken link with https://library.threefold.me/info/legal/#/ so it works

**Comment by ken-de-moor** [comment]
@sasha-astiadi not on the app level, this isn't in a webview component, it's in the actual app code. So hotfixing is impossible.

Hotfixing should be possible on the redirect/wiki level though, but not on the app level.

**Comment by sasha-astiadi** [comment]
ok so we can redir  https://wiki.threefold.io/#/legal  to https://library.threefold.me/info/legal/#/ @ken-de-moor ? ill make a request to ops

**Comment by sasha-astiadi** [comment]
in this case, for this story, its the app upgrade itself, assign jonas on this ? @ken-de-moor

**Comment by ken-de-moor** [comment]
@sasha-astiadi will include it to be updated as well in the next app update. But this won't be live within a matter of days. So indeed in the meanwhile we need the redirect. Also keep in mind this still doesn't solve the main issue I logged the ticket for, this constantly breaks in production and I only randomly find out that it happens, we need a mechanism is place where this stops happening.
