### ISSUE TITLE
Research : UX Improvements -Unify look & feel of all our platforms

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#1195]
Looking at our platforms, there's no unification in the look & feel of our platforms. This raises questions and looks like these come from different companies. 

I suggest a unified UI for all of our platforms with focus on simplicity and well-thought design & user-friendlyness. 

- TF Connect
- Explorer v3
- Portal
- TF Authentification
- Wizard
- Minting overview (coming soon)

**Comment by xmonader** [comment]
I completely agree! awesome suggestion @sabrinasadik

**Comment by sasha-astiadi** [comment]
the goal for A6 is to validate feasability

**Comment by sabrinasadik** [comment]
What I would suggest is the following.

* Portal
- If your wallet is not connected to the portal, you should be able to see the explorer, which should be integrated into the portal. Once you are connected, you're able to see all other functionalities as well.
- Connect through the TF app instead of Polkadot extension.
- Integrate GETTFT into the portal so people can directly buy tokens through the portal since their wallet is already in there. 
- Signing transactions should be approved through the app with a pop-up. 
- Optimise https://alpha.minting.tfchain.grid.tf/ and make sure people can see their minting history and details when clicking on a node on the farmer section of the portal. 
- Eventually all of this can be integrated in the TF Connect App

**Comment by renauter** [comment]
Same issue as #1215
