### ISSUE TITLE
farming pool ghent up & running

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#12]
## requirements

- 10 ZOS nodes on the 2U machines
- +5 archive nodes on the 4U machines
- all connected to our zero-boot infrastructure (#4) (only on that network dhcp/pxe)
- https://docs.grid.tf/threefold/itenv_tfgrid1 config mgmt filled in & test scripts available to work with all assets in this pool
- test script works

## test script

- walk over all nodes and reboot/reinstall them with newest version zos
- walk over all nodes and do ping over zos client
- walk over all nodes & boot ubuntu in vm flist using 1 data disk

**Comment by zaibon** [comment]
https://docs.grid.tf/kristof_farm
