### ISSUE TITLE
STORY: TFGrid Stat A7 - capacity overview website

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1200]
# TFGrid Stat A7: a capacity overview website

at the moment, capacity overview / grid stat is being embed inside tf ecplorer. we would like to separate it into its own website. a TF Grid stat that only showcase capacity overview. simple and on the point.

## todos:
- simple overview with statistics
- simple map for the nodes
- no search or details about the node(s)

preferably to be done as web components so they can be included nicely in other websites.  

https://github.com/threefoldtech/tfgrid_stats/projects/1

## domains should be

- stats.dev.grid.tf
- stats.test.grid.tf
- stats.grid.tf

**Comment by sasha-astiadi** [comment]
whats the url: https:// ? please include it in the issue once released
@rkhamis @xmonader

**Comment by rkhamis** [comment]
current status:

![Image](https://user-images.githubusercontent.com/8425762/176172430-49e04a9e-c165-4a2f-8d89-c82666cea8c6.png)

**Comment by A-Harby** [comment]
> ## domains should be
> * stats.dev.grid.tf
> * stats.test.grid.tf
> * stats.grid.tf

`stats.test.grid.tf` 
![image](https://user-images.githubusercontent.com/109473873/185093577-d8426ad7-45cd-46f1-9e3d-47056fec2f21.png)

**Comment by khaledyoussef24** [comment]
##verified and the domains are now working fine
![Screenshot from 2022-08-23 15-52-35](https://user-images.githubusercontent.com/110984055/186176425-05d541c4-e789-4611-aee0-551c1acf6632.png)
