### ISSUE TITLE
Cosmos and potential blocking of evolving to ThorChain

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1209]
## TFT Blockchain Platform

- TFT is hosted on Cosmos as the main chain
- Native bridging (gravity) to
  - Ethereum
  - Binance Smart Chain (recently renamed BNB Chain)
- DEFI
  - 1Inch (as our main one)
  - Pancake Swap (BSC)
  - Suchi Swap (Ethereum)
- TFGrid Side Chains
  - Each TFGrid (now only 1) has its own wTFT (wrapped TFT)
  - A TFGrid sidechain based on Substrate is managing provisioning, farming, billing, … 
of cloud capacity
  - Farming happens for wTFT, wTFT can be converted/swapped to TFT and back

## To Change

- Move people away from Stellar
- Whenever people login, we move them over to Cosmos, they will have to sign with their private key, should be fully integrated in TFConnect (see #1210 )
- Use Cosmos as main chain, see where to make changes

## Questions

- [ ] Can we upgrade cosmos to do ThorChain features, in new future with support of our validators?
- [ ] Is there anything we cannot upgrade?
- [ ] Is there a DEFI system on Cosmos? or is this ThorChain?
- [ ] When will ThorChain support Cosmos based tokens (see Scott)?
- [ ] Can we create liquidity pool on current ThorChain (they have support for Ethereum Token)?
- [ ] How much work to launch our own ThorChain clone?

https://thorchain.org/

**Comment by scottyeager** [comment]
Cosmos ecosystem has a whole chain dedicated to AMM swaps between tokens from other chains in the ecosystem, it's called Osmosis. Getting TFT to Osmosis via IBC would be a great first step.

ThorChain is integrating the Cosmos Hub chain any day now. That means a pool on TC is possible, if we get TFT to Cosmos via IBC. I spoke with the TC technical lead, and he seemed interested in making this happen as part of a synergy where we also develop TC node deployments on the Grid. Better option than as ERC-20, which is also possible, in my opinion.

**Comment by sasha-astiadi** [comment]
deprecated
