### ISSUE TITLE
STORY TFConnect Web Wallet A7 TBD

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1210]
repo: https://github.com/threefoldtech/wallet-next
project: 3.3 (get link)
issue:

## Why is TFConnect Web Wallet needed

We want to create a secured channel between [TFConnect App](https://github.com/threefoldtech/threefold_connect) and web pages such as [TFChain Portal](https://github.com/threefoldtech/tfchain_portal)
With Substrate we have Polkadot web wallet (via browser extension)
If we do Cosmos we will have Keplr web wallet (via browser extension)
We want to go only with one web wallet! TFConnect Web Wallet 
Main objectives are
- facilitate user experience (no need to deal with multiple web wallets)
- get more security (no need to provide private key to an external web wallet) 

## What is TFConnect Web Wallet

TFConnect Web Wallet is the middle-man between TFConnect App and web pages
` /!\ TFConnect Web Wallet seeds on TFConnect App, this is not a browser extension /!\`
The private keys remains on TFConnect App and are NEVER sent to the web page (not safe!)
Avoid SSL key exchange security issues, maybe QR code would solve

## System requirements

- No need to use Keplr/Polkadot widget for signing
- Embedded in the browser (just like it works for Keplr and Polkadot extensions)
- Create a widget which is web wallet with following features
  - Select account (linked to subkey’s on TFConnect App)
  - Sign/Encrypt/Decrypt (through remote TFConnect App) = through API
  - Send/Receive money (only using Cosmos)
- Use TFConnect App to open the wallet widget & activate
  -  KEEP private key on TFConnect (is a subkey), do NOT transfer to web page
  - Need to be timeout e.g. 15 min 
- Make sure it's easy to use
- Make sure people can logout
- This Web Wallet needs to be able to be embedded in any webpage (html)

## Story Items

- [ ] Repo (TODO)
- [ ] Specs (TODO)
- [ ] Technical issues (TODO)
  - [ ] Prepare repo structure 
  - [ ] Frontend
  - [ ] Backend
- [ ] Documentation (TODO)

## Questions

- [ ] Can we use all wallet features as used in TFConnect?

**Comment by sasha-astiadi** [comment]
postponed to 3.8

**Comment by xmonader** [comment]
when is this planned? @jdelrue @ken-de-moor

**Comment by xmonader** [comment]
moved to 3.7, it was moved to 3.8 without stakeholders approval.

**Comment by robvanmieghem** [comment]
A suggestion is to use [WalletConnect](https://docs.walletconnect.com/2.0/) for this, no need to reinvent the wheel, libraries for both the website and the wallet are available, security has been audited  and it might provide interoperability with other websites and wallets.

**Comment by robvanmieghem** [comment]
The Web Wallet as described above is less important imo, the signing of transactions is.

**Comment by ken-de-moor** [comment]
Replaced by https://github.com/threefoldtech/home/issues/1296
