### ISSUE TITLE
TFHub 1.0.0-A2

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1211]
Functionality: 

## Staking support on TFHub
See specs on the related repo/issue:

https://tfhub.test.grid.tf/
repo: https://github.com/threefoldtech/threefold_hub
issue: https://github.com/threefoldtech/threefold_hub/issues/68

**Comment by xmonader** [comment]
Is this one for the hub of for tfchain?

**Comment by xmonader** [comment]
What does add/remove TFT mean?

**Comment by renauter** [comment]
I think this issue is the same as this [one](https://github.com/threefoldtech/home/issues/1231) referred in Alpha-6 maybe we should close it

**Comment by sasha-astiadi** [comment]
[find Easy way for anyone to install a tfhub validator #1253](https://github.com/threefoldtech/home/issues/1253)

**Comment by sasha-astiadi** [comment]
project: https://github.com/threefoldtech/threefold_hub/projects/3
