### ISSUE TITLE
TF Connect - Key Management

### ISSUE THREAD

**Issue by renauter** [threefoldtech/home#1214]
## Prepare TFConnect to do encrypt/sign-in/decrypt

- Let's standardize on the newest asymmetric encr/signing SR…
- There is a root key, this root key is not kept on phone
  - Users can manually input it when needed (mnemonic or QR)
  - Users can retrieve their root key by using a SECRET
  - Allow users to store there root key encrypted using a SECRET in TFCosmosChain 
    - Key Value Stor per user
    - If not ready for this now, use the infrastructure as used for TFConnect now
  - Export QR code from root key
    - On this QR code put text underneath with mnemonic 
- We create 1 or more sub keys 
  - Can be used for different use cases
  - At start there is 1 subkey called main and will be used for std operations
  - Subkeys need the root key, so if passphrase used then easy to retrieve/create, and remove again the root key private key, so it's not on phone
- TFConnect can sign/encrypt for remote web page
  - See how to make such a secure channel between the webpage & tfconnect
  - Maybe we can use something like QR code, to avoid SSL key exchange security issues

**Comment by jdelrue** [comment]
The idea for this story would be to create a mode where ppl can keep their key on a paper instead of the phone for extra security, but use the existing features of TF connect. Designs will be added soon.

**Comment by sasha-astiadi** [comment]
@renauter can you confirm to kds update the spec..... because we dont know what will happen tfcosmoschain ?

**Comment by sasha-astiadi** [comment]
anyupdate / prio for this one? if not for 3.7.0 ill escalate

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/home/issues/1296
