### ISSUE TITLE
STORY TFChain Portal A7 (Fixes and Improvements)

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1221]
## TFChain Portal A7 Maintenance/Fixes

Full spec: [here](https://docs.google.com/document/d/152fXU5cwcC1T7sVwHg_nA-AC2-D77kq0aKapp7N6xWE/edit?usp=sharing)
Repo: [TFChain_portal](https://github.com/threefoldtech/tfchain_portal)

### TFChain A7 Fixes 

- [ ] Allow farms to be deleted
- [ ] Why is it so slow to show farms/nodes (shouldn’t that come from the postgresql so be fast?) 
- [ ]  In farms view : No need to show certification status (there is no certified now)
- [ ]  In farms view: No need to show twin id, pricing policy
- [ ] Check why 3Nodes don’t popup sooner (shown after initial install)

### TFChain A7 Improvement / all-in-one portal

TFChain Portal A7 should all include: 
embed tfexplorer, tfplayground, and tf web wallet.

This is done so user can find everything within one portal, to simplify user experience.

todos:
- [ ] Integrate tf explorer natively in portal, use same look & feel
- [ ] We use TFConnect Web Wallet for everything
- [ ] Integrate tfplayground  (weblets deployment) into Portal (show as sort of marketplace)
- [ ] Make sure weblets use TFConnect Web Wallet (no longer the custom account mgmt weblet)

**Comment by renauter** [comment]
I think we should split this issue and go back with the original issues #1212 and #1215 to better separate the ideas in a technical point of view
