### ISSUE TITLE
Solve problems with tfchain validator adding

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1222]
Issue: https://github.com/threefoldtech/tfchain/issues/282
project:  https://github.com/threefoldtech/tfchain/projects/13

**Comment by sasha-astiadi** [comment]
still an issue? @robvanmieghem

**Comment by robvanmieghem** [comment]
yes

**Comment by robvanmieghem** [comment]
It's way better with the new session  implementation in parity
