### ISSUE TITLE
Explorer presents other quantities for resource units than physical installed numbers.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#1223]
*Hi Weynand, we have just upgraded one of our servers in our VCC Farm 136, Node 534 with RAM and SSD+HDD drives. Now while the Node reports shows CRU and SRU correctly, HRU and MRU shows wrong numbers. We have 128GB RAM installed, MRU reports 134,96 GB !! We have 9600GB of HDD installed, but HRU only reports 6TB?? Strange. see screenshot attached and a PDF summary of our Node (iLo report from our server). Can you have a look, please? many thanks, Peter*

![image](https://user-images.githubusercontent.com/13766992/164680246-428fa5d1-e298-4010-ab9a-87b1e92e2dc3.png)

**Comment by Pkgraz** [comment]
I can provide the detailed iLo report of our server (HPE ML350 Gen9) if needed. Thank you for following up on this issue

**Comment by despiegk** [comment]
if bug move to right repo, if not close and ask stakeholders if ok

**Comment by xmonader** [comment]
that portal is dead
