### ISSUE TITLE
gettft v1.1.1: bugfixes and small improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1227]
project: https://github.com/threefoldfoundation/it_as_energy_shop/projects/16

**Comment by dmitri-alleo** [comment]
Looks like the link https://github.com/threefoldfoundation/it_as_energy_shop/projects/16 is broken,

The link itself is mentioned on the board for alpha 6, get tft v1.1.1 here https://github.com/threefoldtech/home/projects/8
