### ISSUE TITLE
TFChain v1.10.0 - Farmer voting on tfchain

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#1228]
The goal is for farmers to be able to vote on proposals on tfchain. Proposals can either be generic (plain text) or a specific on chain action. In case of an on chain action, it is automatically executed after the vote passes. Only farmers can vote, in a weighted vote system.

Technical issues: 
- https://github.com/threefoldtech/tfchain/issues/287 (needed to automatically set the price after vote)
- https://github.com/threefoldtech/tfchain/issues/309

project: https://github.com/threefoldtech/tfchain/projects/16

**Comment by LeeSmet** [comment]
No - it was made clear that this has to be in a6

**Comment by sasha-astiadi** [comment]
@DylanVerstraete @LeeSmet @renauter please find out the real eta and figure it out when / what to release

**Comment by renauter** [comment]
When to release: deadline is too short to make it for A6 according @DylanVerstraete, in regard to related TFChain [specs](https://github.com/threefoldtech/tfchain/issues/309).
Also frontend will already be implemented for TFGrid dashboard instead of TChain portal 
So I moved the issue to A7
