### ISSUE TITLE
TF Connect - tfhub

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1234]
## Prepare TFConnect for Cosmos
  
- Cosmos
  - Support cosmos for money
  - When opening wallet we check for money in stellar & move to Stellar with help of user
- Can we integrate moving money from mainchain (cosmos) to BNC/Ethereum & back.
- Don’t support stellar, only import to Cosmos

**Comment by sasha-astiadi** [comment]
need a spec @despiegk

**Comment by sasha-astiadi** [comment]
@xmonader @robvanmieghem do u know if we will sitll be working on this?
