### ISSUE TITLE
Testplan 3.7.x

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1238]
#### Test plan for v 3.7.x should cover:
- development project: https://github.com/orgs/threefoldtech/projects/171
- Testlodge Run: https://app.testlodge.com/a/26076/projects/40893/runs/651690
- Known Issues: https://github.com/threefoldtech/home/issues/1259

### Schedule
- 3.7.x expected to be on QAnet ???? (@xmonader will confirm with a comment on this story that its ready on QAnet)
- All tests and verification should be within one week maximum.

#### Quick verification:
- [ ] https://github.com/threefoldtech/home/issues/1210
- [ ] https://github.com/threefoldtech/home/issues/1214
- [x] https://github.com/threefoldtech/home/issues/1247
- [ ] https://github.com/threefoldtech/home/issues/1234
- [x] https://github.com/threefoldtech/home/issues/1239
- [x] https://github.com/threefoldtech/home/issues/1258
- [x] https://github.com/threefoldtech/home/issues/1270
- [ ] https://github.com/threefoldtech/home/issues/1253
- [x] https://github.com/threefoldtech/vgrid/issues/5
- [ ] https://github.com/threefoldtech/home/issues/1269
- [ ] https://github.com/threefoldtech/home/issues/1268
- [x] https://github.com/threefoldtech/home/issues/1283

#### Validation and Add new testcases to testlodge:
- [x] https://github.com/threefoldtech/home/issues/1212
- [x] https://github.com/threefoldtech/home/issues/1256
- [x] https://github.com/threefoldtech/home/issues/1232
- [x] https://github.com/threefoldtech/home/issues/1215 **[TF Grid Dashboard Test Suite](https://app.testlodge.com/a/26076/projects/40893/suites/209098)**
- [x] https://github.com/threefoldtech/home/issues/1248
- [x] https://github.com/threefoldtech/home/issues/1198
- [x] https://github.com/threefoldtech/home/issues/1200 **[TF Grid Stats Test Suite](https://app.testlodge.com/a/26076/projects/40893/suites/211395)**
- [x] https://github.com/threefoldtech/home/issues/1228
- [x] https://github.com/threefoldtech/home/issues/1219
- [x] https://github.com/threefoldtech/home/issues/1258
- [x] https://github.com/threefoldtech/home/issues/1266
- [x] https://github.com/threefoldtech/home/issues/1275
- [x] https://github.com/threefoldtech/home/issues/1282
- [x] https://github.com/threefoldtech/home/issues/1174
- [x] https://github.com/threefoldtech/home/issues/1279

#### Acceptance criteria:
 - [x] vgrid proxy (https://gridproxy.qa.grid.tf/swagger/index.html):
    - [x] test all endpoints
    - [x]  pagination in each
  -  [x] RMB porting to Rust (https://github.com/threefoldtech/rmb-rs/projects/1)
     - [x]  documentation is clear 
     - [x] file transfers
     - [x] defined usecases are covered
  - [x] Dashboard (https://github.com/threefoldtech/tfgrid_dashboard/milestone/5):
     - [x] verify each of the issues in the 1.1.0 milestone
     - [x] as much as possible should be automated
   - [x] TF Voting on chain
       - [x] documentation on how to create a proposal
       - [x] documentation about the voting process
       - [x] should be able to create a proposal
       - [x] only farmers should be able to vote on a proposal
       - [x] votes are weighted according to resources of the farm
     - [x] Stats
        - [x] simple overview with statistics
        - [x] simple map for the nodes
        - [x] numbers should match data from gridproxy
 - [x] TFChain
      - [x]  graceperiod is 14 days
      - [x] DAO can set connection price
      - [x] Validation for Public Config (Node)
      - [x] Validation for Interfaces (Node)
      - [x]  Validation for Public IPs (Farm)
      - [x]  Validation for Twin IPs
      - [x]  Rework public IPs on Contract -> is now a list with the actual public IP object
      - [x]  Billing executed in a transactional 
      - [x]  Restriction of deployment  hash (32 bytes)
 - [x] grid3 client (https://github.com/threefoldtech/home/issues/1282)
       - [x] documentation is clear
 - [x] Subsquid weblet (https://github.com/threefoldtech/grid_weblets/issues/951)

**Comment by rkhamis** [comment]
QAnet is updated

**Comment by mohamedamer453** [comment]
**Terraform** test run was completed, everything is working fine except for:

 - peertube https://github.com/threefoldtech/terraform-provider-grid/issues/312
 - CPU validation https://github.com/threefoldtech/terraform-provider-grid/issues/313
 - Kubernetes Token Validation https://github.com/threefoldtech/terraform-provider-grid/issues/289

**Comment by A-Harby** [comment]
### Dashboard

**Dashboard** test run was completed, everything is working fine except for:

 - Validation issues:
   - Public config in node. https://github.com/threefoldtech/tfgrid_dashboard/issues/247
   - Gateway in Add ip in farm. https://github.com/threefoldtech/tfgrid_dashboard/issues/246
   - Amount in Withdraw and Transfer TFT. https://github.com/threefoldtech/tfgrid_dashboard/issues/244
   - IPV6 in create or edit IP. https://github.com/threefoldtech/tfgrid_dashboard/issues/243
 - Username UI. https://github.com/threefoldtech/tfgrid_dashboard/issues/239
 - Hide Node Uptime. https://github.com/threefoldtech/tfgrid_dashboard/issues/250
 - Memory data. https://github.com/threefoldtech/tfgrid_dashboard/issues/248

### Stats

The **Stats** test could not be run because there is no stats site in qanet.

**Comment by khaledyoussef24** [comment]
### Weblets
**Weblets** test run was completed, everything is working fine except for:
 

- manual node choosing(manual capacity filter). https://github.com/threefoldtech/grid_weblets/issues/990
- my account deployment list not updated. https://github.com/threefoldtech/grid_weblets/issues/989 
- worker in k8s is not removed from the weblets. https://github.com/threefoldtech/grid_weblets/issues/987
- Selecting Gateway Node is getting reset. https://github.com/threefoldtech/grid_weblets/issues/991

### Owncloud
**Owncloud** test run was completed, everything is working fine
