### ISSUE TITLE
TF Connect: Wallet v3.2

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1239]
https://github.com/threefoldtech/wallet-next/projects/9

Still to be specced out, main feature is improved logging/debugging. To be investigated what other features from backlog to include.

Preliminary specs:

- [ ] Improved logging/debugging.
- [ ] Transaction details being added.
- [ ] Transaction arrow directions.
- [ ] Re-enable TFChain bridge after twin changes.
- [ ] Fixing [object,object] alert bug.

**Comment by sasha-astiadi** [comment]
moved to a7

**Comment by ken-de-moor** [comment]
Currently shelved until unvesting backend side is done by rob. As soon as this is defined or created we will continue with this wallet release and re-asses what features should and shouldn't be included. Main feature is unvesting however.

**Comment by sasha-astiadi** [comment]
@ken-de-moor please split it to  two stories. label type_story

3.2: (done)

3.3 :
- unvesting feature

**Comment by ken-de-moor** [comment]
3.2 was released mainly to fix the object object bug, even though it was actually blocked due to unvesting. Bug fix was too important to keep delaying it. There's another ticket for unvesting already. We'll see what version it ends up in.

3.2 is live as of yesterday.
