### ISSUE TITLE
TF Connect 3.7.0

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1247]
For TF connect 3.7 we are releasing the IOS version of planetary network. We are also removing the concept of .3bot from the app registration and display and adding better wording and warnings to the login flow.

<Changed to 3.8.0>
~~Project Summary:  Some important changes have been delayed for a long time. We need to fix all these to be able to keep working on TF Connect longterm.~~

~~- Vue2 to Vue3~~
~~- Add typescript.~~
~~- Add tailwind.~~
~~- Remove vuetify.~~
...--~~

**Comment by ken-de-moor** [comment]
- Frontend finished.
- Backend still in progress.

**Comment by sasha-astiadi** [comment]
how about key mgmt? will it still be on 3.7?

**Comment by sasha-astiadi** [comment]
key mgmt not included on 3.7

**Comment by sasha-astiadi** [comment]
@ken-de-moor please update. thus story with screenshots of new features if any @ken-de-moor

**Comment by ken-de-moor** [comment]
Validated on staging and in the meantime also live on production. Planetary network tab is now also enable for IOS, used to be only for android.
