### ISSUE TITLE
Uhuru V1.3 Beta

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1248]
For the V1.3 Beta we continue tackling the UI/UX issues and bugs. This version we are also adding mobile support with a full scaleable layout.

https://github.com/threefoldtech/twin_aydo/projects/6

We now also are including more internal testing with help of Sabrina, the goal is still to not add much features except for main missing things like a logout option.

**Comment by ken-de-moor** [comment]
Still in process of verification. Closed some bugs, opened a critical blocking bug that is fixed today and a new version is being deployed so I can continue.

**Comment by sasha-astiadi** [comment]
office is having bugs , cannot open in live version

**Comment by sasha-astiadi** [comment]
everything is verified only open office issue @ken-de-moor  please link the repo issue here

**Comment by ken-de-moor** [comment]
Critical issue: https://github.com/threefoldtech/twin_aydo/issues/530

Everything else is validated and deployed, but this critical remains open and is being investigated and hopefully soon fixed.

**Comment by ken-de-moor** [comment]
Critical issue fixed, deployed.
