### ISSUE TITLE
Consistent jumpscale types [types]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#125]
Currently the functionality of methods implemented on jumpscale types are inconsistent.
 - Complex types like **enum** and **ipaddress** should be implemented using the [base class](https://github.com/threefoldtech/jumpscaleX/blob/1292bb15f912133784906adfc8b8b8fa86b017b8/Jumpscale/data/types/TypeBaseClasses.py)
 - `clean` should always return an object described by the type
 -`__eq__` should be implemented for object comparison
 - `__repr__` should be implemented where needed
 - `possible` (possibly to be refactored) should implement if value could be of that type... should return True/False
 - `get_default` should return default value for objects if logical. Raise Error if not.
 - `to_string` should ALWAYS return string. May be dense.
 - `to_data` should be a case by case implementation. May be not implemented if not logical to have in that specific type
 - `to_HR` should return a readable string. not necessary for some types
 - `to_dict` where required
 - `capnp_schema_get` should return the capnp schema representation

To be developed on [branch development_types](https://github.com/threefoldtech/jumpscaleX/tree/development_types)
 

See [document](https://github.com/threefoldtech/jumpscaleX/blob/1292bb15f912133784906adfc8b8b8fa86b017b8/docs/basetypes/readme.md) for further details

## dependencies

- [ ] #174

**Comment by despiegk** [comment]
types are ok now
