### ISSUE TITLE
TFHUB - Easy way for anyone to install a tfhub validator

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1253]
issue: https://github.com/threefoldtech/threefold_hub/issues/76
project:  https://github.com/threefoldtech/threefold_hub/projects/3

**Comment by xmonader** [comment]
What about the validator maintenance? This requires at least some skills, or is it not a concern?

**Comment by robvanmieghem** [comment]
Flow: https://github.com/threefoldtech/home/issues/1257

**Comment by sasha-astiadi** [comment]
moved to a7 since https://github.com/threefoldtech/home/issues/1257 is on a-7

**Comment by renauter** [comment]
Switch to #1257 which describes a way to address issue
