### ISSUE TITLE
DISCUSSION: Fork portal so it can be worked on in Gaia-X hackathon

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#1256]
## What ? 
I have made a proposal to prove our value, see proposal 3 in  [here](https://gitlab.com/gaia-x/gaia-x-community/gx-hackathon/gx-hackathon-4/-/wikis/Hackathon-4-Proposals#3-threefold-structura-x-proposal), but it requires small update in our portal during the hackathon (not to be pushed to testnet/mainnet for now, just a fork that accesses TFChain-devnet and where the Gaia-X APIs can be added). 

Proposal is intended to be simplistic, because you need to be able to do something within 2 days, and moreover invite others to collaborate on the open-source code. 
Basically what happens is that you connect your infrastructure to be trustworthy for being used in the Gaia-X ecosystem. And make it available as infrastructure for the about 90 use cases defined here : https://gaia-x.eu/use-cases/ . Many of these use cases have already been funded with millions, but they lack the technology to be realised (apart from what we bring). 

But in order to get that certification, you need to submit it to the compliance services that are created (see  https://compliance.gaia-x.eu/docs/ , https://registry.gaia-x.eu/docs/ ). 

It's connecting to a decentralized certification ecosystem (Gaia-X trust framework is a mechanism using DIDs, self-descriptions, Verifiable Credentials certified by trust anchors who 'sign' claims raised by farmers, service providers, users, ...)

## Rationale / Why ?

* Marketing instrument 
Our technology is perfectly fit to be used as federator technology for Gaia-X. 
This can be proven during the Gaia-X hackathon on June 20-21. 
* Longer term benefit 
In the longer run, this proposal can go different ways: 
  - many parties joining the TFGrid 
  - creation of a European 'regional' Gaia-X compatible TF Grid

This hackathon will put our technology in the spotlights, as we have by far the most advanced technology which is perfectly fit to fulfil the role of cloud federator, which is essential in the [Gaia-X Architecture](https://gaia-x.eu/wp-content/uploads/files/2022-01/Gaia-X_Architecture_Document_2112.pdf). Their vision is also to become a DAO, defining a level playing field among all cloud providers, so all have equal rights and obligations, and benefits. 
This whole activity contributes to the overall goal for countries (in this case the EU as a whole continent) to make their internet GDP positive. For Europe, it doesn't make sense to do this alone, as there is already a big project - Gaia-X - intending to do this (but lacking the technology to get there).

**Comment by renauter** [comment]
Indeed it would be a nice opportunity to show the technology on such event with such community.
Before, it would be good:
- to discuss with @despiegk about context/exposure to validate the idea
- then to technically see with @xmonader how would it be to update the required feature(s) on portal, or on the new grid dashboard
