### ISSUE TITLE
update development process in home

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1267]
see https://github.com/threefoldtech/home/tree/master/wiki/contribution

we are now using the new style project boards, lets make sure all content in home has been updated

**Comment by xmonader** [comment]
should be reflected now https://github.com/threefoldtech/home/blob/master/wiki/contribution/development_process.md

**Comment by mohamedamer453** [comment]
Verified.

The development process in [threefoldtech/home](https://github.com/threefoldtech/home) was updated.

- The new github project style is now used ex: [3.7.x](https://github.com/orgs/threefoldtech/projects/171)
- The new project style have different views like: stories, all, each linked repo, etc ..
- Each swimlane in the project is used correctly according to the [development process](https://github.com/threefoldtech/home/blob/master/wiki/contribution/development_process.md#the-used-swimlanes)
- Milestones and issue labels are added for all the issues in the project.
- [threefoldtech/home](https://github.com/threefoldtech/home) is the starting point of all the other repos and contains info and links about the products and all the issues in this repo that are included in the project are of [`type_story`](https://github.com/orgs/threefoldtech/projects/171/views/7)
