### ISSUE TITLE
TF Connect - Backend refactor.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1269]
Project Summary:  Some important changes have been delayed for a long time. We need to fix all these to be able to keep working on TF Connect longterm.

- Vue2 to Vue3
- Add typescript.
- Add tailwind.
- Remove vuetify.
- Much more code refactoring
- Full kubernetes test deploy stack.

**Comment by ken-de-moor** [comment]
Currently this is live on staging, BUT it is not yet with the correct kubernetes test stack. We will functionally validate it already, but then the deploy also needs to be validated since it's a high risk deploy that can't just be done in production.

**Comment by sasha-astiadi** [comment]
ETA?
end of month: 3.6.1,
next month: 3.7
@jdelrue

**Comment by ken-de-moor** [comment]
Next month for now, it's ready but the kubernetes setup/deploy is just too dangerous right now to try to rush it.

**Comment by sasha-astiadi** [comment]
move to 3.8?

**Comment by ken-de-moor** [comment]
Blocked right now, code is ready but we will continue to develop on old codebase for now due to too many other TF Connect changes needing to happen as well. The impact of doing a huge refactor + all the features at once is just too big.

**Comment by despiegk** [comment]
we need to know what state is, and how much work it would be

**Comment by ken-de-moor** [comment]
@despiegk Currently we are working on setting up the full refactored stack of all components using helm charts. The development for this is ready already but can't be tested yet as I don't have an environment yet. So operational work left but development is ready. This ties in with a lot of different stories right now that will all be tested and validated together.

**Comment by sasha-astiadi** [comment]
update ? @ken-de-moor

**Comment by sabrinasadik** [comment]
Reminder
