### ISSUE TITLE
JSX installer unattended

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#127]
JumpScale installer needs be completely automatable, meaning silent options are all supported with no manual intervention.

- [ ] The installer should have the support for both OSX and Ubuntu 18.04
- [ ] The installer should have sandbox mode
- [ ] The installer should have insystem mode
- [ ] Docker installation (`-d `) should be supported
- [ ] Installation of lua/openresty web framework should work with all of the above

**Comment by despiegk** [comment]
think all of this is possible now

can even use https://github.com/threefoldtech/jumpscaleX/blob/development_types/docs/Internals/kosmos_instruct.md
