### ISSUE TITLE
TF Connect Wallet v3.2.1 - Transaction details.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1270]
The wallet currently does not have transaction details.

We want to include the option to show transaction details with the following info.

- [x] Sender
- [x] Receiver
- [x] Memo
- [x] Blockchain hash
- [x] Amount
- [x] Asset
- [x] Date

**Comment by ken-de-moor** [comment]
This is live on beta but I have validated it and logged 7 improvements, sabrina also had some valid input as well. All tickets are logged and we will create a new version to be validated again.

Main feedback was that the terms were too technical and the flows weren't user friendly enough. We are improving all of this before putting it live.

**Comment by sasha-astiadi** [comment]
will move to 3.6.1 for this one...

**Comment by ken-de-moor** [comment]
Done and live
