### ISSUE TITLE
STORY: Minting 3.7.0 details in dashboard

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#1279]
The community has been asked what they want to see regarding minting (payouts, uptime, other info, ...) in a forum post (https://forum.threefold.io/t/community-feedback-on-minting-overview-tool/3137). 

# Things to add

We will add some overview in the dashboard for nodes, to show receipts of previous periods. Next to this, we also want to show some info for the current period.

## Previous periods

The receipts for previous periods are available at alpha.minting.tfchain.grid.tf. There are 2 API endpoints: 

- /api/v1/receipt/{receipt_hash} -> returns the receipt with the given hash
- /api/v1/node/{node_id} -> returns a map with all receipt hashes as key, and receipts as value, for the node.

The second one is probably the most useful. From the receipt, the period start and end can be extracted, as well as the uptime with the payout to make an overview list of past payouts. If one is then clicked, the full receipt can be shown

## Current period

For the current period, we mostly want to see when the period starts and ends, when the node was down (list of downtimes, start and end date), and the current uptime percentage. The uptime can be extracted from graphql

**Comment by despiegk** [comment]
- what exactly will we now see in the 3.7 release, what is timing for on devnet
- will user see the reward per day (just calculated, not given yet)?

**Comment by xmonader** [comment]
the [PR](https://github.com/threefoldtech/tfgrid_dashboard/pull/192) just got merged 

- a calendar showing the minting and f fixup receipts timespan 
- a receipts download button that generates a pdf containing a summary of all the node's receipts

**Comment by A-Harby** [comment]
Verified on devnet.

> * a calendar showing the minting and f fixup receipts timespan

![2022-08-25_15-51](https://user-images.githubusercontent.com/109473873/186683219-f97788ba-ca46-42f9-aaf8-56604a8eb272.png)



> * a receipts download button that generates a pdf containing a summary of all the node's receipts

[nodes_receipts.pdf](https://github.com/threefoldtech/home/files/9425317/nodes_receipts.pdf)

https://github.com/threefoldtech/tfgrid_dashboard/issues/207
