### ISSUE TITLE
Wiki Sites Production and Staging through flists

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#128]
Using a base flist that contains:
 - jumpscale
 - lapis
 - lua
 - the webserver dependencies

two more flists need to be produced. These flists will be used to have our websites always available and easy to deploy

The production flist should:
 - have all the wikis checked out to latest `master` branch

The staging flist should:
 - have all the wikis checkout to latest `development` branch

**Comment by BolaNasr** [comment]
we created Wiki Sites Production and Staging through merged flists
https://staging-wiki.grid.tf/ (development)
```
https://hub.grid.tf/bola_nasr_1/startup_development.flist
https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX-autostart-development.flist
```

https://wiki.grid.tf/ (master)
```
https://hub.grid.tf/bola_nasr_1/startup_master.flist.md
https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX-autostart-development.flist.md
```

**Comment by hossnys** [comment]
Just a little change here :
staging wiki is deployed on (development) : https://www2.wiki.grid.tf/ or https://wiki2.grid.tf/
Production wiki is deployed on (master) : https://wiki.grid.tf/
