### ISSUE TITLE
expand grid3_client_ts to support stellar, algorand, tfchain modules

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1282]
- [x] algorand https://github.com/threefoldtech/grid3_client_ts/issues/330
- [x] tfchain https://github.com/threefoldtech/grid3_client_ts/issues/331
- [x] stellar https://github.com/threefoldtech/grid3_client_ts/issues/334

**Comment by xmonader** [comment]
so far, stellar, and tfchain are up to all of the functionality, alogrand is under review

**Comment by A-Harby** [comment]
> * [x]  algorand [Support algorand grid3_client_ts#330](https://github.com/threefoldtech/grid3_client_ts/issues/330)

Test Case / Steps used to verify this issue can be found here [TC923 - Algorand](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3681445)
> * [x]  tfchain [support tfchain grid3_client_ts#331](https://github.com/threefoldtech/grid3_client_ts/issues/331)

Test Cases / Steps used to verify this issue can be found [here](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3678600)
> * [x]  stellar [Add sign, verify for stellar grid3_client_ts#334](https://github.com/threefoldtech/grid3_client_ts/issues/334)

Test Case / Steps used to verify this issue can be found here [TC928 - Stellar](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3681461)
