### ISSUE TITLE
pulumi integration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1287]
- [ ] initial investigation of [pulumi](https://www.pulumi.com/docs/)
- [ ] decide if we should go with typescript client (the most complete) or wait on the grid3-go library to be done
- [ ] tbd

**Comment by despiegk** [comment]
I suggest we don't put time in this right now, there are way more urgent items
also what we want to do with vlang is kind of replacing this and more strategic to us

**Comment by despiegk** [comment]
ringo supposedly wants to do this, lets see if we can reward in TFT or FFK's

**Comment by xmonader** [comment]
already implemented
