### ISSUE TITLE
Publishing Framework / Openresty improvements

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#129]
One aspect of openresty that could use a little love is the blogging. There are other small issues that we could give a little bit of attention to have a nicer product

- [x] [links](https://github.com/threefoldtech/jumpscaleX/issues/195)
- [ ] [document wiki](https://github.com/threefoldtech/jumpscaleX/issues/194)
- [ ] includes

**Comment by abom** [comment]
Includes, custom links and end-user documentation are done.

**Comment by abom** [comment]
Developer docs will be updated once the new publishing tool is finished.

**Comment by abom** [comment]
Links and includes have been verified at https://github.com/threefoldtech/digitalmeX/issues/42.
Developer docs progress is tracked at https://github.com/threefoldtech/home/issues/164.
