### ISSUE TITLE
make dedicated servers usable

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1290]
- right now cannot use dedicated servers because no-one marked them for dedicated server use
- if a server is empty, it can be reserved as dedicated server automatically and then becomes dedicated

I am afraid we still need to do this this release, because right now there are no dedicated servers on mainnet, if we do this improvement on 3.7 it will be on testnet so later in sept on mainnet

**Comment by xmonader** [comment]
It's already the case https://github.com/threefoldtech/tfchain/pull/337

**Comment by mohamedamer453** [comment]
Verified on devnet.

New endpoint in the grid_proxy was added to support the queries for nodes that can be rented and rented nodes and its working and verified in https://github.com/threefoldtech/tfgridclient_proxy/issues/183.

i was also able to find a node with no contracts on devnet and it was successfully rented through the [`renting.ts`](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/renting.ts) script available in grid3_client_ts

The mentioned node was `node 47` on devnet it's a normal node (not a dedicated one) with zero contracts and i was able to query it through the [`rentable`](https://gridproxy.dev.grid.tf/nodes?rentable=true) endpoint that was added to the grid_proxy.

![image](https://user-images.githubusercontent.com/101194226/186669983-e797050e-87bc-441b-a4ed-b14a036eb360.png)


![image](https://user-images.githubusercontent.com/101194226/186670415-198f0b77-821e-4cc2-9dc2-412ecb3a5f1d.png)
