### ISSUE TITLE
integrated UI  https://portal.test.grid.tf/

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1291]
we don't wanna do complicated or even new things we just want to integrate our UI experience

- [ ] integrate explorer, play, portal, stats, hub.grid.tf and bootstrap.grid.tf (can be iframe for now) = 1 UI
- [ ] name is https://portal.test.grid.tf

so basically there is only 1 UI to go to and have everything at one go, its important we can show more integrated offering
we need this for demo's its very important to fix this

## remarks

- ok that play key mgmt is still using separate widget for mnemonic and ssh key, can't we use this one for the portal today as well so at least we have 1 way how to do it (not the tfconnect one, of if tfconnect works then use that one everywhere but how to deal with ssh key?)
- portal: we should not have the separate accounts at left side, very confusing, the account chose is what we see all over the portal...

## hub.grid.tf improvements (optional for 3.7, mandatory for 3.8)

- login with private key of TFChain (so its seamless integrated with dashboard
- same color scheme if possible not a must

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/188307045-010ea1de-a6a6-4ada-aeec-793c05685bbb.png)


bootstrap is fully iframed, hub didn't work (login with tf connect and iframe caused issues) so it's a link for now, also the playground is linked

**Comment by mohamedamer453** [comment]
Verified in
 - https://github.com/threefoldtech/tfgrid_dashboard/issues/198
 - https://github.com/threefoldtech/tfgrid_dashboard/issues/231
 - https://github.com/threefoldtech/tfgrid_dashboard/issues/232

As mentioned above bootstrap.grid.tf was included in an iframe in the dashboard and links were added for the playgroud and hub.grid.tf in the sidebar.
