### ISSUE TITLE
TF Wallet - Farmers tab should be entirely over GraphQL

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1298]
Context: There are lots of performance issues on the farmers tab, people on bad connections sometimes simply can't use it as a result. We are changing this codebase to get all the data from graphQL instead of directly from the blockchain, which was causing the performance issues.

**Comment by ken-de-moor** [comment]
Ready on staging, will wait until sabrina is back from holiday for some extra validation/testing as well.

**Comment by xmonader** [comment]
@LeeSmet wasn't the plan is people use the gridproxy instead of the graphql?

**Comment by sasha-astiadi** [comment]
@ken-de-moor pls answer

**Comment by sasha-astiadi** [comment]
@ken-de-moor status pls comment

**Comment by sabrinasadik** [comment]
@ken-de-moor status

**Comment by ken-de-moor** [comment]
Shelved for now, focus is Freeflow Twin + FreeFlow app. Basically everything in this repo.

https://github.com/threefoldtech/freeflow_twin_main
