### ISSUE TITLE
FreeFlow Twin 1.6 Beta 

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1299]
Uhuru version: https://github.com/threefoldtech/twin_aydo/projects/11

- Bug fixes
- Lots of new features

Still a WIP to know exactly which features, some discussion going on still in old ticket : 

https://github.com/threefoldtech/home/issues/1275

**Comment by ken-de-moor** [comment]
Done and live in production. Release created

**Comment by sasha-astiadi** [comment]
new features like:
- **Whisper (chat feature)**: Mention a specific @username on Group chats
- **Quantum (Freeflow’s in-app file storage and document editing tool)**:
Upload, edit, and save code files (markdown, HTML) directly
- **Flow (social media feature)**: You can now start a ‘Comment Thread’: Multiple levels of comments on have been added. Comments can now have replies and these can also be liked.
