### ISSUE TITLE
zos: share cache volume to guest zos'

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/home#13]
parent to threefoldtech/0-core#23
parent to threefoldtech/jumpscale_lib#75

When running zos on top of another zos, it's more efficient if we share the host cache to guest zos to:
- Avoid re-downloading of files
- Save space

**Comment by muhamadazmy** [comment]
Progress: 70%

I managed to share the cache to the zos guests over plan9, I will be changing how we boot strap the node to check if there is a cache shared via plan9 and mount it if is available. 

Then once this is working we will do some tests to make sure files are shared correctly with no corruption

**Comment by muhamadazmy** [comment]
Progress: 100%

On zos machine creation, a shared_cache flag can be ticked to make sure the host cache is shared to guest vms. Zos will mount this automatically in the right place if it was exposed.

**Comment by AhmedHanafy725** [comment]
I can't access the guest zos ( https://github.com/threefoldtech/jumpscale_prefab/issues/32 )
