### ISSUE TITLE
Template to configure network for lochristi's farm

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#130]
Belongs to https://github.com/threefoldtech/home/issues/101

In order to be able to deploy s3 and web gateway on the farm in Lochristi, we need to develop new 0-robot template to configure the network node of the farm so they can :
- [x] have a storage network
- [x] be attached to the public network 

The public network in this farm needs to be access by joining a vlan network.
As far as I know, we can only configure vlan nics for container or VM, not the host itself.
But in our architecture the public node of a web gateway needs to be accessible publicly, and on the node we do a port forward of port 80,443 and 53 for traefik web proxy and coredns respectively.
So the traefik and coredns container don't need to have a vlan nic, but the host does.

**Comment by zaibon** [comment]
@muhamadazmy can you confirm/inform my assumption regarding vlan nic ?

**Comment by muhamadazmy** [comment]
Yes, joining a vlan is only available for containers and kvm, and only supported by ovs. U probably need to do some manual work to get it working for the node.

**Comment by zaibon** [comment]
We solved the problem for now by allowing to overwrite the default gateway of a node when configuring the storage network. This allow the node in the farm to be reachable publicly, and thus be used to host webgateways
