### ISSUE TITLE
github deprecates ubuntu 18.04 action runner

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/home#1300]
github suddenly pulled the plug on ubuntu 18.04 as per this issue [here](https://github.com/actions/runner-images/issues/6002). This affected zos in the following ways:
- ZOS image [0-initramfs](https://github.com/threefoldtech/0-initramfs) builds the base image on ubuntu 18.04. Which means all glibc libraries are from this version of ubuntu. Beside the fact these are getting old, but are well tested in production.
- ZOS also build some packages (flists) that are installed/updated during the node runtime. Those packages as well need to be either static builds (hence no dependencies on libraries on the platform). Or build against the same version of glibc (and friends).
- ZOS runtime packages, then used the same ubuntu runner to be compatible with the libraries already in the image. 
- ZOS does not have a package manager, we depend on the build system to produce compatible builds (for simplicity) it means installing new binaries was the matter of just copying the files from the flist to the correct locations.

Right now, it's not possible to rebuild the zos image, also runtime packages that required ubuntu 18.04 are also not possible. 

## Short term solution
We need to be able to build zos with current versions of libraries there might be multiple ways to do so:
- Stay with github actions but use an ubuntu container to do the build
- Use a [self-hosted github actions runner](https://github.com/threefoldtech/research/tree/development/github-actions) 
- Move to a custom CI runner @xmonader suggests we use [zeroci](https://github.com/threefoldtech/zeroci) which is self hosted. 
  - My only take on this is that we will need to change the build workflows to work on zeroci
  - That it's self hosted.
- Rebuild everything on latest ubuntu 
  - Which means runtime packages will now break on older zos nodes that was booted with older images.
  - This can had effect on the entire node if the pkg will also override one or more of the node existing libs.

## Long term solution
These are needed to be implemented anyway IMHO. because this will improve the robustness of the system anyway. It's basically make the system aware of versions of libraries, dependencies, system consistency and query ownership of files and detection of conflicts. This can all be accomplished by a simple package manger. The package manager will be able to test the consistency of a release and that published packages (with certain versions) are all compatible.

More on this here https://github.com/threefoldtech/zos/discussions/1789  

@maxux 
@xmonader

**Comment by xmonader** [comment]
I'm more in favor of using a self-hosted github actions runner that we can use [research been done before](https://github.com/threefoldtech/research/tree/development/github-actions) for a short term solution, it will almost cost us nothing in terms of changes

> These are needed to be implemented anyway IMHO. because this will improve the robustness of the system anyway. It's basically make the system aware of versions of libraries, dependencies, system consistency and query ownership of files and detection of conflicts. This can all be accomplished by a simple package manger. The package manager will be able to test the consistency of a release and that published packages (with certain versions) are all compatible.

I fully support the idea of having a decent more consistent package manager to be used within zos.

**Comment by muhamadazmy** [comment]
Can we deploy the self hosted runner, i can already try to build the tpm package against it

**Comment by maxux** [comment]
If we can stay on github, that would make things easier, we already moved from our custom self-hosted build system to github to make things easy, it's not to go back IMO :)

**Comment by xmonader** [comment]
Right now binaries are built in containers, and we have a custom github action runner for tfchain
