### ISSUE TITLE
Security Issue Report - Forum - full forum dump with sensitive data available

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/home#1308]
Details are available in PM from Nickolay or Weynand

**Comment by PeterNashaat** [comment]
- access blocked

**Comment by PeterNashaat** [comment]
- the link is blocked now.
- Updating forum could fix the issue as we run a older version

**Comment by PeterNashaat** [comment]
- https://github.com/threefoldtech/tf_operations/issues/749
