### ISSUE TITLE
All Jimber components - Improve documentation.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1309]
See https://github.com/freeflowuniverse/home/issues/12 for component list

Can't directly link the ticket since it's cross organization, creating this duplicate to track in 3.8 release.

- [ ] how to setup / technical explanation
- [ ] functional explanation / what the component is

**Comment by sasha-astiadi** [comment]
@ken-de-moor @sasha-astiadi edit this story with checklist of repo .readme list to edit, improve

**Comment by ken-de-moor** [comment]
Ongoing process, a lot of extra documentation has been done already but in my opinion it is not good enough yet. So a first phase is done already but more improvements are needed.

**Comment by despiegk** [comment]
will close here but is part of other story on freeflow
https://github.com/freeflowuniverse/home/issues/7
