### ISSUE TITLE
TFT on polygon + bridge

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1312]
Project: https://github.com/threefoldfoundation/tft/projects/12

**Comment by amiraabouhadid** [comment]
ran a bor node using https://wiki.polygon.technology/docs/develop/network-details/full-node-binaries
![Screenshot from 2022-10-20 11-18-53](https://user-images.githubusercontent.com/56790126/196909951-4c02f174-2b40-429f-9132-0df861dbf8da.png)

**Comment by sasha-astiadi** [comment]
@xmonader @amiraabouhadid status update this week?

**Comment by amiraabouhadid** [comment]
Building Polygon Solution on weblets to better understand polygon nodes (bor & heimdall)
Created bindings from contrat ABIs
Creating keystore, network (backend) to interact with generated bindings
Frontend of nextjs with typescript and reacf is also still in progress
