### ISSUE TITLE
ThreeFold Connect V3.7.3

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#1316]
https://github.com/threefoldtech/threefold_connect/projects/9

Backend update needed for the latest wallet update.

Breaking changes are required in the wallet update, because of this we first need to push an app update with these changes.

Goal is to push the fix, give everyone some time to update since auto-update policies on most phones aren't as strict as they used to be. Then once the app has been live for about a month we can push the new wallet code.

Some small fixes that were ready are also included in the release but it's not the goal of the release.

**Comment by ken-de-moor** [comment]
APK and testflight version have been created and are being validated.

**Comment by sasha-astiadi** [comment]
need to remind users later to manually update if the app itself doesnt auto update.

**Comment by despiegk** [comment]
there is nothing in the project?
