### ISSUE TITLE
3bot to deploy websites

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#133]
The idea here is to have an easy way to deploy any website.

The chatflow would ask about:
 - domain name - which the bot will configure the webgateway to expose
 - the website repo
 - the branch of the repo to deploy
 - parameters of the webgateway info (could be directly configured on the container running the chatbot)

**Comment by ranatrk** [comment]
Approach: 
- Deploy chat bot in a container (in the same node as the web gateway
- Take the information needed from the user via the chatflow (domain, website repo)
- The chatbot container will create a container for the website to be deployed on via zos client
- The website is loaded and deployed on the new container 
- The website is registered to the web gateway

**Comment by ranatrk** [comment]
Blocked: zos client is being fixed

**Comment by ranatrk** [comment]
Zos client container fix : https://github.com/threefoldtech/jumpscaleX/commit/25f76953bc0b9bdb5c243cf16a38d923359462e7

**Comment by ranatrk** [comment]
- [ ]  Deploy chatbot in a new container (Create an flist with the needed items)
- [ ] Via 3bot take from the user : domain_name, website_repo, jwt
- [ ] Via 3bot take from the user: path in github_repo to app, views and static files (used for creating links)
- [ ] 3bot used to created a new container for the website to be deployed using zos_client
- [ ] Website loaded from github_repo link to the container created
- [ ] Website is registered to the web gateway on the node

**Comment by ranatrk** [comment]
Flist used for the container with 3bot is to be tested

**Comment by ranatrk** [comment]
**Progress Update:**
-  Creating a new container from the 3bot still results in errors (cmds working independently from terminal)
-  Flist created by @BolaNasr is still being tested and Bola is working on some bug fixes in it

**Comment by ranatrk** [comment]
**Progress Update :**
 - Creating a new container from the 3bot was not working due to network issues, zerotier added in command and is being tested now 
 - Flist created by @BolaNasr and is working with 3bot :
     https://hub.grid.tf/bola_nasr_1/3bot_startup_development.flist

**Comment by ranatrk** [comment]
**Progress Update**:

**Comment by ranatrk** [comment]
**Progress Update:**
- 3bot is used to create the new container with the following flist : 
https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX-autostart-development.flist
- 3bot is then used to register the domain and container to the webgateway (@hossnys)
- https://github.com/threefoldtech/digitalmeX/commit/d2db9032f220fd64c2d4238329478c0c4b7b2bde

**Next Steps:**
- Not using the previous flist but rather use one of two base flists(to use caddy server or ngnix/Lapis)
- Creating the base flists
- Taking the information required to pass to a startup.toml file to be merged with the base flist
- Creating the container with the website using the merged flist ouput

**Comment by ranatrk** [comment]
**Progress Update:**
- 3bot is used to create the new container with the following flist : 
https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX-autostart-development.flist
- 3bot is then used to register the domain and container to the webgateway (@hossnys)
- https://github.com/threefoldtech/digitalmeX/commit/d2db9032f220fd64c2d4238329478c0c4b7b2bde

**Next Steps:**
- Not using the previous flist but rather use one of two base flists(to use caddy server or ngnix/Lapis)
- Creating the base flists
- Taking the information required to pass to a startup.toml file to be merged with the base flist
- Creating the container with the website using the merged flist ouput

**Comment by ranatrk** [comment]
**Progress Update:**
- Approach of merging (in the script) the 2 base flists is disregarded as the flists can be used directly with passing the required repo urls
- Server to be used can either be _Caddy_ or _ngnix(lua)_  by users' choice
- Flist with caddy (takes repo as env variable) is created (@PeterNashaat ): https://hub.grid.tf/nashaatp/generic_caddy.flist
- https://github.com/threefoldtech/digitalmeX/commit/a9ef0d31eaa4a632e8aa0d4f8192dd49d107b29b

**Next steps:** 
- Test on ovh nodes (the scenarios were tested seperatly after adding the caddy option
- The ngnix/lua flist's startup.toml needs to be updated as some links are already created in the flist before the use of the startup.toml

**Comment by ranatrk** [comment]
**Current Progress Update:**
- Due to recent changes in the jumpscaleX and digitalmeX, a new flist will be created and uploaded to be used directly with 3bot container and the deployed website container

**Comment by ranatrk** [comment]
**Progress:**
- 3bot deployment successful and website deployment successful on webgateway (ngnix/lapis and caddy)
-3bot flist startup.toml updated successfully: https://github.com/threefoldtech/jumpscaleX/blob/35239ca3db89db489a2993356aeea8d1d6afb62b/utils/flist.sh#L55-L90
- Landing page added to chatbot https://github.com/threefoldtech/digitalmeX/commit/4991397c679a44554b89160e993cfe82474168cd

**Next step:**
 - create a domain for the 3bot itself 
 - write documentation for deploying a 3bot and for using the 3bot to deploy a website

**Comment by ranatrk** [comment]
**Progress Update:** 
- Domain name created https://websites-3bot.grid.tf/ @hossnys

**Comment by rkhamis** [comment]
Great work @ranatrk, @hossnys and @PeterNashaat .

These are some changes I propose to improve UX:

In the questions asked

1. `What is the link to the website repo? (using https://github.com/)` ---> `Enter website repo URL (for example: www.github.com/threefoldfoundation/website_name)`
2. `What is the branch to be used in github?` ---> `Enter branch to deploy from` and pre-fill the answer with `master`
3. `What is your JWT token?` ---> `Enter your JWT token` with a help link to how to create JWT token
4. `What is the farm zerotier id?` ---> `Enter Farm Zerotier ID`, again with help link on how to fetch the Farm Zerotier ID
5. `What will the website run on ` ---> `The website will run on:` 
    - caddy
    - nginx and lapis


It would be nice also if the chatbot during deployment gives a message saying `Deploying your website now` and when it's done, it gives a link to the new website

**Comment by ranatrk** [comment]
Added new doc : how to create a JWT token with itsyouonline https://github.com/threefoldtech/jumpscaleX/commit/9c5032778420832642269b71c0d4191162e31924

**Comment by ranatrk** [comment]
Progress:

**Comment by ranatrk** [comment]
3bot is deployed with latest commits added to container manually.
Updated flist **blocked** until builders are working and autobuilder can be used again

**Comment by ranatrk** [comment]
3bot flist working for now: https://hub.grid.tf/three_bot_tft_1/3bot_autostart_development.flist

**Comment by hossnys** [comment]
a new 3bot container deployed using the last merged [flist](https://hub.grid.tf/three_bot_tft_1/3bot_autostart_development.flist) and it's working properly as shown down , for test deployed incubaid website on domain archive.tf
![Screenshot from 2019-04-08 12-58-32](https://user-images.githubusercontent.com/26298009/55719799-6787db00-59ff-11e9-9834-664c30d929db.png)

![Screenshot from 2019-04-08 12-57-41](https://user-images.githubusercontent.com/26298009/55719384-6a360080-59fe-11e9-9890-00e7f034843f.png)
