### ISSUE TITLE
cleanup tfgrid (non zos,tfchain) repo's

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1330]
for all other repo's

- [ ] make sure all issues are sorted , if needed linked to projects
- [ ] the ones we want to do in 3.8 or 3.9 need to be labeled a component release nr (version, done by milestone)
- [ ] make sure naming is good
- [ ] make sure home page filled in properly, so people know what it is
- [ ] help write the release notes for 3.8, see what changes there are

**Comment by xmonader** [comment]
that should be the case already grid_weblets, dashboard, rmb, terraform, gridproxy, gridclient
