### ISSUE TITLE
Design capacity tracking algorithm that allow to power off node that are not used

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#134]
In the spirit of trying to be as green as possible, we would like to come up with a scheme that allows a farmer to turn off the node that are not required (the capacity sold from the farm doesn't required these node to be up)

Currently we track the uptime of a node because the node does send heartbeats to the network. This makes things easy. But for this task, we need to come up with something that would allow us to still be sure the node is available while the node is turned off for power saving.

**Comment by zaibon** [comment]
My first idea regarding this is something like this:
- the node are powered on with a specific flag, e.g: powersave
- During the capacity tracking, the node detect the flag and send a special request to the capacity directory saying, I'm alive, here is my capacity,... but I will shut down, tell me when you want to hear from me again.
- the directory register that information and return a JWT to the node. This JWT contains identification information and expires in XHours. 
- the node then receives the JWT, save it, and based on the expiration time, know when it needs to come up again
- If the node come up again in time and is able to send the JWT back to the directory, we count the uptime of the node as complete (aka, like it was on all the time)
- If the node fails to come up online in time, then we consider the node to be really offline and we don't count the uptime

This schema allows us to still be sure the node are actually available and not just powered off and not providing capacity anymore.

This is still pretty rough ideas thought, needs more thinking

**Comment by maxux** [comment]
About node power reduction, we could investigate if hardware supports correctly `suspend-to-ram`, we could suspend and resume hardware quickly with low power impact using this. This could also help to check « does the machine can come back ? » without waiting +5 min hardware boot

**Comment by zaibon** [comment]
add a low priority on this one for now.
For now we will just allow farmer to have their node up once a day in order for them to get their farming token.
This give us time to come up with a proper solution on the long run.
