### ISSUE TITLE
ZSTOR and QSFS understood and well documented for use in VM

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1345]
## purpose

- know what it can do and not today
- get it usable & documented for in VM use case
- make good deployers for it

## TODO

- [ ] link to the repo's and milestones of what needs to be done
- [ ] mention deadline

**Comment by LeeSmet** [comment]
## Basic documentation

QSFS documentation: https://github.com/threefoldtech/quantum-storage. The README contains an overview of the components and links to the individual components repo's. All of these contain build and usage instructions. Next to this, the repo also contains a bootstrap tool in V to get a working system up and running by downloading pre build binaries on linux: https://github.com/threefoldtech/quantum-storage/tree/master/bootstrap. This can also be fed a config file to work with existing 0-db's.

## VM use case

Not _really_ sure what is meant here, either set up a system inside a VM, or attach a QSFS as mountpoint from zos to a VM.

- Inside VM: this is the same as any linux system. As mentioned above, all repos contain pre build binaries and detailed instructions, and there are packagers available:
  - V:  https://github.com/threefoldtech/quantum-storage/tree/master/bootstrap
  - Nixos package: https://github.com/threefoldtech/0-stor_v2/issues/102

- As mounted filesystem inside a zos VM: Zos supports creating of a QSFS container, which can then be mounted to a VM on the node. As long as the same config is used to create the QSFS, it is moveable to other nodes (though users should take care to only have 1 system active at all times to avoid corruption). Documentation:
  - Terraform: example deployment file: https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/qsfs/main.tf and explanation of the config options: https://github.com/threefoldtech/terraform-provider-grid/blob/development/docs/resources/deployment.md#nested-schema-for-qsfs

## Required work

- Proper stability testing of repair functionality https://github.com/threefoldtech/home/issues/1101
- Remove V2 explorer support https://github.com/threefoldtech/0-stor_v2/issues/106
- Investigate behavior when FS is full when mounted in 0-os: https://github.com/threefoldtech/zos/issues/1613

**Comment by sabrinasadik** [comment]
Seems like documentation about disk quota is not good enough, see multiple questions on forum
- https://forum.threefold.io/t/qsfs-mount-point-is-unusable-when-file-size-is-higher-than-storage-capacity/2337
- https://forum.threefold.io/t/how-to-access-deployed-qsfs/3311
- https://forum.threefold.io/t/disk-quota-exceeded/3319

**Comment by LeeSmet** [comment]
> https://forum.threefold.io/t/qsfs-mount-point-is-unusable-when-file-size-is-higher-than-storage-capacity/2337

https://github.com/threefoldtech/quantum-storage/issues/19

> https://forum.threefold.io/t/how-to-access-deployed-qsfs/3311

Reading through the discussion this seems answered?

> https://forum.threefold.io/t/disk-quota-exceeded/3319

Also seems anwered, also the issue is not specific to qsfs, but rather to using "micro VM's" in general, and should be covered there in  a section of the documentation (specifically, this kind of VM is not intended to write additional data, and doing so requires increasing the rootfs_size)

**Comment by robvanmieghem** [comment]
Rewrote the quantum storage readme https://github.com/threefoldtech/quantum-storage/tree/master
I also has docs for a manual setup, a troubleshooting and operations guide.
The docker image is now also published and has documentation

**Comment by robvanmieghem** [comment]
Quantum storage docs in the repo itself:
entry readme: https://github.com/threefoldtech/quantum-storage/blob/master/README.md
At the bottom there are links to other docs( like how to set it up manually): https://github.com/threefoldtech/quantum-storage/blob/master/README.md#other-documentation

**Comment by xmonader** [comment]
When can this be closed? @robvanmieghem @sabrinasadik ?
