### ISSUE TITLE
story: finalize support dedicated nodes

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1347]
- make sure docu is ok (mdbook)
- make sure pricing is better than OVH if tokens for 1Y
- make sure people understand this pricing (where documented)
- make sure people understand that they can select any node as dedicated of still free yet (even if powered off)
- see if all from see https://github.com/threefoldtech/home/issues/1257 addressed

**Comment by DylanVerstraete** [comment]
![Screenshot from 2022-11-15 14-34-07](https://user-images.githubusercontent.com/17138347/201936035-292e1c42-c6b1-4834-9fd0-02fa7f8c6444.png)

Pricing checks out even if there are not tokens in the user's wallet. With gold discount it's even half (70K tft in user's wallet)

**Comment by mohamedamer453** [comment]
> * make sure pricing is better than OVH if tokens for 1Y

by comparing the dedicated node price and OVH price it's cheaper on the grid with the same specs.

- CPU: 4 vCores, Memory: 8 GB, SSD: 200 GB 

it's `8.49$` on OVH & `7.42$` on the grid, even without applying discount for the user balance. 

![photo_2022-11-21_18-03-43](https://user-images.githubusercontent.com/101194226/203103195-bc028db7-c33e-4919-8854-e72b51642415.jpg)

![image](https://user-images.githubusercontent.com/101194226/203103283-8d40a030-4f79-4566-b55f-1cd0c6b05532.png)

**Comment by xmonader** [comment]
the dashboard is the entrypoint for dedicated nodes information

**Comment by sasha-astiadi** [comment]
> 7.42

can i know the link of the ovh price? cant find it. what i found:
<img width="221" alt="Screenshot 2023-01-17 at 17 20 44" src="https://user-images.githubusercontent.com/43240801/212858907-626c5697-b511-4cb5-a22d-9734f950a9e0.png">
https://www.ovhcloud.com/asia/vps/compare/
