### ISSUE TITLE
make gettft usable

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1348]
- make sure price is set properly (0.25)
- with money we get we buy back from market, to slowly slowly get price back up
- needs to be revisited every week (see with alexander/peter)
- check credit card payments, do they work
- maybe we need to change it to buy directly from stellar? and take small margin for TF

**Comment by nbabenko** [comment]
Current price is  0.025996332 USD
For the weekly price update, what % should we set above average market price?
For the credit card payments it works, but not very smooth (some users and some jursdictions having issues). We can swith or intergrate additionally Wyre, it may work better.

The last idea of redirecting it directly to stellar liquidity pool I think is really good and it will make it work more efficiently

**Comment by robvanmieghem** [comment]
For the price setting, I suggest to automate that and sell at 10% above Stellar dex market price.
This is something that can be done pretty easily.

**Comment by robvanmieghem** [comment]
Removing from 3.8 in favour of https://github.com/threefoldtech/home/issues/1354
