### ISSUE TITLE
NIXOS VM

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1350]
- [x]  image: https://github.com/threefoldtech/tf-images/issues/101
- [x] weblet support fullvm : https://github.com/threefoldtech/grid_weblets/issues/1103 fullvm
- [x] weblet support microvm https://github.com/threefoldtech/grid_weblets/issues/1123
- [x] docs https://github.com/threefoldfoundation/info_manual3/pull/125
- [x] terraform: https://github.com/threefoldtech/terraform-provider-grid/commit/16b13b9d4a5e2c4bc75b922b0ab9b7b0fcb9d050

**Comment by xmonader** [comment]
@ashraffouda is still investigating running the fullvm on the grid, he already managed to have one working with cloud init, but still didn't work on the grid yet

**Comment by xmonader** [comment]
required an upgrade of zos on devnet, seems to be working fine on devnet.  a limitation for now https://github.com/nix-community/nixos-generators/issues/193#issuecomment-1323700904, you will have to rebuild, but not update, this image should be considered as a final image.
