### ISSUE TITLE
Document how to acquire TFT using the Stellar dex

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1354]
In minimal steps

>I believe there is already something like this on forum or so

**Comment by robvanmieghem** [comment]
https://forum.threefold.io/t/useful-guides-and-information-how-to-buy-and-trade-tfts/904

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/info_threefold_pub/issues/106

**Comment by Mik-TF** [comment]
For now, we have those 2 complementary guides that fulfil the basic task demanded by @robvanmieghem:

* Create TF Connect Account and Wallet: https://forum.threefold.io/t/create-a-threefold-connect-account-and-wallet/3768
   * Video version: https://peertube.hostservice.nl/w/nFyNWrGH2qrUPcFUxhC4Xp
* Buy TFT with Lobstr: https://forum.threefold.io/t/how-to-buy-tft-on-lobstr/3755

In the tutorials, we link the TF Wallet to Lobstr, so buying on Lobstr dirctly goes to the TF Connect Wallet.

**Comment by xmonader** [comment]
@sabrinasadik @robvanmieghem @Mik-TF can we please have that in https://github.com/threefoldtech/info_grid

**Comment by Mik-TF** [comment]
@xmonader 

Of course. There's a pull request ongoing. Then we can close this issue.

https://github.com/threefoldtech/info_grid/pull/15

**Comment by xmonader** [comment]
Thanks @Mik-TF !
