### ISSUE TITLE
Easier deployment funding for weblets

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1359]
Log in with Threefold connect.
Best scenario: have the weblet ask Threefold connect to sign the deployment transaction

- [ ] Allow a user to login on weblets
- [ ] Make weblets construct calls offline and pass them back to Threefold connect
- [ ] Signing of and submitting call should be done by Threefold connect

First: Let's check if the weblet and Threefold connect can communicate using libp2p and --Fill in project from Ahmed--

**Comment by xmonader** [comment]
Goal is having tf connect to include the libraries that we developed e.g to sign requests (or in this case will be deployments mainly)

We tested two flows in the twinactions repo https://github.com/freeflowuniverse/twinactions/

flow1:
https://github.com/freeflowuniverse/twinactions/blob/development/pocTS/server/flow1server.v
basically you go to a website e.g rob.com on http, you get a nice ui, this ui connects again to rob.com but on ws, there's a backend service running there will be awaiting client mnemonics, network configurations, you enter them in the ui they get sent over the websocket to initialize the client in the backend, and you can send specific messages from frontend e.g get balance of this address, call goes to the backend for the initialized client and executes and sends back to the ui via websockets


flow2:
https://github.com/freeflowuniverse/twinactions/blob/development/pocTS/server/flow2server.v

here you again connect to rob.com on http, the ui once it's loaded it initiates websocket connection to the backend, the main difference with the first flow, is the backend already has the credentials when it got started e.g using env variables, it passes the credentials to the frontend, the grid client is loaded in the frontend in the user browser

diagrams should follow
