### ISSUE TITLE
deployment of 3.8.1 in reproducible way

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1368]
specs see
https://docs.google.com/document/d/1OhWvW2uo3S-eYF4FIC0jaTtrl71gMo6hIx3zB_fKjYQ/edit#

purpose is to allow anyone to deploy quickly anything needed to deploy their own TFGrid

will also help us massively to deploy multiple testnets, ...

**Comment by robvanmieghem** [comment]
using https://github.com/despiegk/gridstarter ?

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tf_operations/issues/1334

**Comment by robvanmieghem** [comment]
@xmonader Should this be an operations issue? Anyone should be able to do this.

**Comment by xmonader** [comment]
> @xmonader Should this be an operations issue? Anyone should be able to do this.

There's another linked issue on operations, i'll assign both to @coesensbert :)

**Comment by xmonader** [comment]
After checking with Rob, he will own the story and Bert will be able to execute it

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/grid_deployment/issues/1

**Comment by robvanmieghem** [comment]
duplicate of #1384
