### ISSUE TITLE
define new version of 3.8.0 = release mgmt update

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1370]
## goal

- update this project to have clean stories of what is still open and what needs to be done

## to look at

- [x] project https://github.com/orgs/threefoldtech/projects/194/views/1
- [x] decide on the features/bugfixes needed without power mgmt / capacity planning 
  - [x] the graceperiod https://github.com/threefoldtech/zos/issues/1852
  - [x] qa environment stopped syncing https://github.com/threefoldtech/tfchain/issues/547
  - [x] https://github.com/threefoldtech/home/issues/1343
  - [x] graphql update https://github.com/threefoldtech/tfchain_graphql/issues/69
  - [x] yggdrasil fork? #1372 
- [ ] prepare versions
- [ ] deploy on qanet
- [x] deploy on testnet
- [ ] deploy on mainnet

**Comment by rkhamis** [comment]
project: https://github.com/orgs/threefoldtech/projects/194/views/1

**Comment by xmonader** [comment]
- graphql / subsquid issue been mitigated with the monitoring, to be fixed in 3.8.1
- qanet is syncing again 
- the new profile manager is actively being tested
