### ISSUE TITLE
find a workaround for network issues with planetary network

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1372]
## a possible solution

- re-introduce tcp-router from TFGrid 2.0
- introduce RMB proxy mode (means no more need for yggdrasil)
- keep yggdrasil best effort for community

> will check today (26 dec what needs to be done)

## remarks

- possibility is to fork underlying tech yggdrasil threefoldtech/test_feedback#367

**Comment by LeeSmet** [comment]
After deliberation, it was decided to improve RMB proxy support (#1373), such that we can run the full RMB infrastructure outside the planetary network. As for regular usage of planetary network, a networking toolbox will be created to alleviate this (story to be created), and if people want to continue the planetary network, they can do so as is for now
