### ISSUE TITLE
graphql indexer stability issue

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1381]
## indexer
https://github.com/threefoldtech/tfchain_graphql/issues/70
https://github.com/threefoldtech/tfchain_graphql/issues/75 

doesn't seem reliable at all 

## glibc
https://github.com/threefoldtech/zos/commit/10b31c096e75a87e7eaae952857fc919f8205fb3 seems to be resolved but happened again yesterday on devnet

## network stability in lochristi

**Comment by xmonader** [comment]
there's a plan to introduce firesquid, but that was never planned in 3.8, but I don't see a way out

**Comment by coesensbert** [comment]
https://graphql.dev.grid.tf/graphql is now serving new firesquid indexer with cockroach db

**Comment by coesensbert** [comment]
follow up here: https://github.com/threefoldtech/tfchain_graphql/issues/43

**Comment by Mahmoud-Emad** [comment]
verified on qanet:
all nodes are up for a while without any problems

![image](https://user-images.githubusercontent.com/57001890/214600996-bd0d28f7-41f4-4e9f-806a-194b3b3375d6.png)

also, the `createdAt`, `updatedAt`, and `uptime` fields work well as expected!
* Node 2 :
  - created 
 
      ![image](https://user-images.githubusercontent.com/57001890/214601734-a3443fd8-02b6-4937-b309-6f765a2f2693.png)
  - updated
      
      ![image](https://user-images.githubusercontent.com/57001890/214602019-5b313113-d796-4233-ba26-25f9655df266.png)

  - uptime
  
      ![image](https://user-images.githubusercontent.com/57001890/214602221-d4fc68ca-ee9e-4e38-b12a-f3fcc3321d5a.png)

**Comment by xmonader** [comment]
this happened today 

```
´{"level":5,"time":1674653913491,"ns":"sqd:processor","err":{"stack":"RangeError: The number 1656338040.002 cannot be converted to a BigInt because it is not an integer\n    at BigInt (<anonymous>)\n    at contractCreated (/squid/lib/mappings/contracts.js:70:37)\n    at handleEvents (/squid/lib/processor.js:75:92)\n    at /squid/lib/processor.js:116:19\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:165:17)´
```
reported by @coesensbert 

 https://github.com/threefoldtech/tfchain_graphql/pull/72/commits/2da1e4979224b79b8a85d11d960056865b9b0f79  should have fixed it, but will still keep the issue open

**Comment by DylanVerstraete** [comment]
This is fixed now for a couple of days

**Comment by A-Harby** [comment]
Verified on Devnet and Qanet, indexer were stable for the paste days now and no issue was reported.
