### ISSUE TITLE
update release notes

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1383]
https://github.com/threefoldtech/home/blob/master/wiki/products/v3/tfgrid_3.8.md

doesn’t really specify what we do and what is going to be delivered, its a low level most people wont understand, its great we have it though and we need it but please also write content which everyone understands

**Comment by xmonader** [comment]
https://github.com/threefoldtech/home/blob/master/wiki/products/v3/tfgrid_3.8.md linked documentation for major parts the monitoring and the 3rd party billing removed detailed bug fixes  from tfchain and zos and kept the links to the milestones for readers' interest. please close unless you still find it unclear

**Comment by A-Harby** [comment]
[Release note](https://github.com/threefoldtech/home/blob/master/wiki/products/v3/tfgrid_3.8.md) have more descriptive user-friendly info which is easier to understand.
If anything is unclear, please re-open the issue.
