### ISSUE TITLE
docker compose reproducible builds for TFGrid

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1384]
# purpose

Everyone with 2 physical computers can build & deploy a full TFGrid stack and deploy their local zeros-nodes & workloads. They have full control over which versions to use.

## why

- this will allow us to have many more tests going on in parallel and make it easy for everyone to have their own tfgrid deployment
 
## requirements

allow following process to work

### physical

- connect at least 2 computers with enough compute and storage capacity to a mikrotik switch
    - e.g. https://mikrotik.com/product/CRS109-8G-1S-2HnD-IN or https://mikrotik.com/product/RB260GS 
    - the smallest routers < 50 USD so is achievable for everyone
    - configure the switch with ssh and a login/passwd
    - connect the switch to the internet
- optionally deploy a supported PDU (power management device) connected to the nodes, we also support wake on lan

### install tfgrid management & boot infra

- on one of nodes: deploy ubuntu 22.04 with docker enabled
- on that node clone https://github.com/threefoldtech/builders
- source a versions file: has all releases defined as env variables e.g. version zos, version hub, ... 
- call the buildall script in the builders this creates all required docker images from code
    - the versions will specify which code gets checked out, all versions are linked to a release
    - a user can change one specific version to make a specialty build
- call  buildall script in tfgridbuilders (to be created)
    - build ubuntu 22.04 and push to hub so we have flist and files there so we can deploy ubuntu machine
    - build required zos and bootstrap components so they can be used behind hub
    - build hub/boot server
    - build tfchain
    - ...
- go to compose directory: start the docker compose
- now there should be a full blown single node install of TFGrid management and boot components with
    - the hub & bootstrap parts
    - tfchain single node
    - some fake money on tfchain so we can test all
    - web gateway
    - graphql indexing 
    - tfgrid proxy
    - 3bot which has example script which are configured to talk to single node
- execute a config script which will configure the switch and test network connectivity

### boot first zos

- boot the zos see it comes up and registers

### deploy an example workload

- go to the tfgrid management node, run a test script to deploy a ubuntu 22.04 vm on the grid

## implementation details

- use https://github.com/threefoldtech/builders
- ...

**Comment by robvanmieghem** [comment]
TODO ( non-exhaustive):
- [ ] [Create builders for grid components](https://github.com/threefoldtech/builders/issues/11)

**Comment by sabrinasadik** [comment]
Mikrotiks ordered, see #1385
