### ISSUE TITLE
better names for the concepts of solution provider and the 3rd party billing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1393]
Right now we introduced the ideas of
- solution provider that's allowing the creator of the solution to gain a percentage of the rewards 
- 3rd party billing allowing third party services to define their own custom billing implementation for the services they are providing

However that seems to have introduced lots of confusion https://forum.threefold.io/t/threefold-solution-provider-and-sales-channel/3746 and I believe it can be resolved by using different names

**Comment by xmonader** [comment]
@scottyeager do you have any input on this?

**Comment by rkhamis** [comment]
@scottyeager ?

**Comment by scottyeager** [comment]
I've been thinking about this. Part of the confusion comes from the fact that we have at least three different _roles_ that might take advantage of the two _mechanisms_ described above:

1. Solution Providers - create "solutions" which are essentially some software packaged in an flist that works on the grid
2. Sales Channels - market grid capacity and onboard users
3. Service Providers - provides some service that users pay for in TFT, separate from normal grid billing

Most of the confusion so far is around the difference between "solution providers" and "sales channels". These are both mentioned, but not defined, in the [wiki](https://library.threefold.me/info/threefold#/tokens/threefold__proof_of_utilization). The mechanism called "Solution Provider" currently covers both cases, and using a name that covers both could help. These are in essence people who do work to bring utilization to the grid and receive some rewards diverted from cost paid to use the grid. Something like...

* Proof of Utilization Beneficiary (okay that's a mouthful and I don't love it, but maybe it puts us on the right track)
* Utilization Facilitators

Now the mechanism we currently call "3rd party billing" is a way for two parties to enter a billing agreement in TFT. It's like an...

* External service contract (to make it clear this is about billing for something other than grid services)

**Comment by xmonader** [comment]
@weynandkuijpers can you also please look at this one too?
