### ISSUE TITLE
support umbrel on the grid

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1394]
- [x] image https://github.com/threefoldtech/tf-images/issues/126
- [x] weblet https://github.com/threefoldtech/grid_weblets/issues/1304

**Comment by 0oM4R** [comment]
weblet is ready, and I have some requested changes on the image pr, 
also faced a new issue that the apps installed inside umbrel are not accessible, working on this for the current time.

**Comment by 0oM4R** [comment]
## apps don't work with gw
it opens the gw:<app port> for example with bitcoin node in those screenshots,
### using ygg
when you access your app with its ygg it will appear as ready to open:
![image](https://user-images.githubusercontent.com/62248851/220147184-2289d2d7-2d5a-45b4-a538-4dd8ae59afaa.png)
and on click will open a new tab with URL: `http://[300:170b:469a:2ed8:1417:6b96:a29f:758d]:2100/`
### using gw
when accessing it with gw with this config:
    ![image](https://user-images.githubusercontent.com/62248851/220147918-c39bc88b-fc66-475c-9c5d-7f833c16de7a.png)
- it's stuck in starting ...
    ![image](https://user-images.githubusercontent.com/62248851/220148109-fb3fa8d3-e077-4711-a682-3fc384c531fd.png)

- and on click on the app icon will open a new tab with URL : https://umbrel2.gent01.qa.grid.tf:2100/
which can't be reached

### source code 
[this section on umbrel dashboard repo will make it more clear](https://github.com/getumbrel/umbrel-dashboard/blob/82ddf09d1ac723828a2717005d5fd96207277d9d/src/views/AppStore/AppStoreApp.vue#L431)

```` 
return `http://${window.location.hostname}:${this.app.port}${this.app.path}`;
````
