### ISSUE TITLE
community reward system

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1395]
as per @despiegk 's request for community contribution, the idea is having a simple DAO-like system that allows us to define a story with a specific set of tasks where we say the reward of having that story done 100% is X amount of tokens. The story may have subtasks that can also affect the reward e.g if 70% of the tasks were done we can release 70% of the tokens allocated for that story 

suggestion from Kristof is using lightning network (allowing small fees and faster transactions and invoices)  with a combination of or taiga (it has the project management features like stories, tasks built in) or gitea where maybe we can define a custom convention to define such thing

another note: signatures can be verified offline before sending the rewards

References:
- https://getalby.com
- https://lightning.network/
- https://btcpayserver.org/

**Comment by xmonader** [comment]
## The wallet (Alby)
 
I've been checking [Alby wallet](https://getalby.com/) what I found is 
1- it has a centralized identifier username@getalby.com that can be used as destination, but doesn't seem you can get the user public key using it .
2- Alby provides [oauth based system](https://guides.getalby.com/alby-wallet-api/reference/authorization) but seems only you can get the balance (user has many accounts https://github.dev/getAlby/lndhub.go/blob/7a01bf6d84061640ebd54845a436139294cb50ab/db/models/user.go#L1 but none seems exposed on the controllers?)  
3- I can't find any notation of multisig?
4- In Alby you can define a spending cap per a website (not a the way we are looking for per a story or locking in funds for a specific period or until signers approve in a way
5- There's no notation to store metadata using alby (btc has op_return of 80 or 40 bytes now)

## DAO metadata
Aside from the wallet on top (metadata, user identification and multisig)

we would have been linking against issue id in gitea or story id in taiga (but these are also mutable and subject to change (if we could provide metadata during payment)
one solution to the mutability in gitea is we can link to a commit id in a repo and come up with a structure as follows
```
stories/
	[story_id]
		metadata
		signed_metadata_signer1
		signed_metadata_signer2
		....
```
there will be a controlled directory about the story where meta has the specs of the story and signers public keys and each signer create a commit in that specific directory of signed metadata by their key so it can be verified offline (but then there's no need to use alby and maybe just a shared bitcoin wallet that gets created by one of the signers is enough?)


## Conclusion

I believe bitcoin may not be the right option for developing a DAO with its limited programmable capabilities (compared to ethereum) and we will be reinventing too many thing/workarounds to make it work in such ecosystem

**Comment by robvanmieghem** [comment]
>  believe bitcoin may not be the right option for developing a DAO with its limited programmable capabilities (compared to ethereum) and we will be reinventing too many thing/workarounds to make it work in such ecosystem

If it's just a m out of n multisig, bitcoin is perfectly suitable, the btc can be put on the account so everyone can see that it's available and reserved  for this story. How this can easily be integrated with the lightning network is something I still have to look in to.
