### ISSUE TITLE
Potential vulnerability stopping the P2P network altogether rather quickly

### ISSUE THREAD

**Issue by dumblob** [threefoldtech/home#1396]
The following is based on my (very) shallow understanding of ThreeFold. So bare with me.

It seems the bootstrap process depends on contacting a hardcoded list of existing "Gateway" servers in the P2P network (or worse some hardcoded public servers which are not even part of the P2P network). It doesn't seem to use any means to circumvent even the most basic ways of filtering and blocking (e.g. port blocking, DNS name blocking, ...) not even speaking about DPI /deep packet inspection/ (I don't know of any state nor big telco provider not having it on backbones!), etc. At least encrypted DHT over random ports would be nice as the initial step (see e.g. https://medium.com/unitychain/intro-to-dht-e98425fc05f1 and https://medium.com/unitychain/dht-attacks-and-defenses-e159b3d1bcf8 ).

What happens with the ThreeFold network if somehow these very few designated servers become unavailable (e.g. due to a DDoS or data center outage or DNS blocking or whatever) for more than a very short period during which the peers in the network will be forced to stop doing their job due to some timeouts or even perform a reboot (maybe by another attack - MITM or whatever).

I suppose the **whole network** will immediately stop working. And of course there won't be any way to resurrect the network because even if new nodes would want to join, they wouldn't have anyone to connect to because of all the few `rendezvous` servers unavailable.

Do you have any documentation about attack vectors on ThreeFold and how does the security profile look like?

**Comment by muhamadazmy** [comment]
This is rather a `grid` issue more than zos issue. I moved it here to properly discuss
