### ISSUE TITLE
Rewrite Playground/Weblets

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/home#1399]
The current playground has the following dev issues:
- incredibly long build time
- difficult to add solutions to 
- connects to external web sockets and makes API calls (polkadot and rmb) more times than necessary 
- difficult to debug

We propose rewriting the weblets such that:
- its build time is reduced
- it is easier to navigate
- it has a more user-friendly interface
- it is easier to integrate and debug profile manager more smoothly 
- it calls API and websockets once

**Comment by MohamedElmdary** [comment]
I had an old issue about rewriting playground more info in the issue
https://github.com/threefoldtech/grid_weblets/issues/557
