### ISSUE TITLE
digital.me Migrate Grid Capacity server to digital.me 

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/home#14]
Migrate https://github.com/threefoldtech/jumpscale_lib/tree/development/JumpscaleLib/servers/grid_capacity

to digital.me

**Comment by rkhamis** [comment]
@Hamdy I see no progress here?
I know you were done with this, can you please add documentation link so QA can verify? Also please put on verification when you do

**Comment by zaibon** [comment]
this seems to be stalled, I'll close, this work will be integrated in another story
