### ISSUE TITLE
Tfchain improvements Part 1

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/home#1401]
Features for 3.10

- Solve syncing issues https://github.com/threefoldtech/tfchain/issues/619
- Attaching solution provider id to contracts: https://github.com/threefoldtech/tfchain/issues/630
- Allow bonding a stash account to a twin: https://github.com/threefoldtech/tfchain/issues/636
- Billing storage cleanup: https://github.com/threefoldtech/tfchain/issues/665
- Various bugfixes (see release notes tfchain 2.4.0-rc1)

**Comment by DylanVerstraete** [comment]
Story updated and some thing moved to a new one to decouple from 3.10 release:

https://github.com/threefoldtech/home/issues/1433

**Comment by DylanVerstraete** [comment]
What's left to be done for tfchain is:

https://github.com/threefoldtech/tfchain/issues?q=is%3Aopen+is%3Aissue+project%3Athreefoldtech%2F192+

(looks like a lot but will all be addressed in a PR by Erwan)

**Comment by A-Harby** [comment]
Closing the issue since all the issue are solved and closed. https://github.com/threefoldtech/tfchain/issues?q=is%3Aopen+is%3Aissue+project%3Athreefoldtech%2F192+
