### ISSUE TITLE
bitcoin node: offload chain sync with zdbfs

### ISSUE THREAD

**Issue by maxux** [threefoldtech/home#1402]
See how to offload and speed up bitcoin node boot up time by using the same trick of NodePilot stuff with zdbfs and overlay. Checking using Umbrel base.

**Comment by maxux** [comment]
Won't be using zdbfs but will try with flist, zdbfs as read-only layer use way too much bandwidth (because local cache is never filled by write operations)

**Comment by maxux** [comment]
Got a node running with an flist and a snapshot, boot time in 4 min.

**Comment by sabrinasadik** [comment]
Status?
