### ISSUE TITLE
BTC deployment

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#1408]
A simple way to deploy a BTC lighting node
check the umbrel docker files to get started

See issues:
 - [x] https://github.com/freeflowuniverse/vbtc/issues/1
 - [ ] https://github.com/freeflowuniverse/vbtc/issues/2
 - [ ] https://github.com/freeflowuniverse/vbtc/issues/3

output:
 - auto build flist every month
 - scripts to deploy in a VM. should be deployed in 30 minutes

**Comment by amiraabouhadid** [comment]
BTC flist is complete with Tor and Lnd configs

**Comment by amiraabouhadid** [comment]
vlang script to start btc lightening node in progress

**Comment by DylanVerstraete** [comment]
Can we move this to web3proxy 1.1 ? Since BTC support will not be released in version 1.0

**Comment by amiraabouhadid** [comment]
On hold
