### ISSUE TITLE
BSC bridge multisig improvements

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1424]
- https://github.com/threefoldfoundation/tft/issues/117
- https://github.com/threefoldfoundation/tft/issues/170

**Comment by DylanVerstraete** [comment]
I would make this an issue to improve all bridges for TF at once. To rewrite the bridges for eth / tfchain in a single project (preferrably rust)

**Comment by robvanmieghem** [comment]
@DylanVerstraete That's a different story imo

**Comment by xmonader** [comment]
What is the status here, still feasible for 3.11? also should it still be linked to grid releases or can be in a separate project? @robvanmieghem

**Comment by despiegk** [comment]
lets just make sure its reliable for now, no need to rewrite, make sure we have it documented in our development docs (internal) / mdbook

**Comment by robvanmieghem** [comment]
Tested, small updates updated the docs to use the same code as the Ethereum bridge: https://github.com/threefoldfoundation/tft/releases/tag/v1.5.0
Deploying: https://github.com/threefoldtech/tf_operations/issues/1832
