### ISSUE TITLE
cleanup for specs 3script

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#1434]
# 3lang

Circles story: https://circles.threefold.me/project/tf_engineering_coordination/us/91?kanban-status=2521

Telegram chat :https://t.me/+nPZVC_napbBlNTU0

## purpose

Create intermediate language, see examples below.

## Requirements

- easy to use and well understood intermediate language
- make V-tool to read folder and execute the actions  (action parser already exists per dir) see actionsparser in crystallib
- document well in mdbook
- all primitives as needed to implement something like foldit should be part of web3gw, and the 3lang
- when info needs to requested, it will just return json formatted info

## Functionality

- [x] https://github.com/threefoldtech/web3_proxy/issues/94
- [ ] blockchain generic client for BTC, BTCLightning, Stellar, Ethereum multiple chains:
  - [ ] https://github.com/threefoldtech/web3_proxy/issues/119
  - [ ] https://github.com/threefoldtech/web3_proxy/issues/121
  - [ ] https://github.com/threefoldtech/web3_proxy/issues/122 
- [ ]  https://github.com/threefoldtech/web3_proxy/issues/137
- [ ] bridge TFT between networks

## example

```yaml

!!tfgrid.network_create
    name:private

!!tfgrid.tools_sshkey_create
    name:myssh
    key:'
            blabla
        '

!!tfgrid.vm.create
    name:kristof
    size:large
    network:private
    sshkey:myssh
    planet_net:true

!!tfgrid.vm.create
    name:kristof2
    size:small
    network:private
    sshkey:myssh
    planet_net:true

!!web3gw.money.send 
    channel:btclight
    from:mywallet
    to:'dfdfdfgdfdfdfdf'
    currency:btc
    amount:0.01

!!web3gw.money.send 
    channel:ethereum
    from:mywallet2
    to:'sdsdsd'
    currency:tft
    amount:0.01

```

**Comment by despiegk** [comment]
lets get all specs right first, then we define what we can do by when
