### ISSUE TITLE
threefold connect testsuite

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1440]

**Comment by xmonader** [comment]
Have to move this to 3.12, it won't be achieved in 3.11

**Comment by xmonader** [comment]
@ramezsaeed status? that was supposed to be finished 3 month ago

**Comment by ramezsaeed** [comment]
threfold connect testsuite on testlodge
https://app.testlodge.com/a/26076/projects/40893/suites/206114

latest run
https://app.testlodge.com/a/26076/projects/40893/runs/725092

https://app.testlodge.com/a/26076/projects/40893/runs/725164
