### ISSUE TITLE
update pricing 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#1442]
hi team, which cloud pricing calculator should we display on our manual?
me and @renauter found two links so far:

[PRICE CALCULATOR FOR V3.0.0 A4](https://threefold.docsend.com/view/7cjmy2kh94kpvdbb) 

or

[SUGGESTED PRICE LEVEL FOR V3.8](https://docs.google.com/spreadsheets/d/1E6MpGs15h1_flyT5AtyKp1TixH1ILuGo5tzHdmjeYdQ/edit#gid=2014089775)

?

at the moment we still refer to the first one, im double checking all the pricing contents on our manual

old manual:

https://library.threefold.me/info/threefold#/tfgrid/pricing/threefold__pricing

new manual:

https://manual.grid.tf/cloud/cloudunits_pricing.html

**Comment by sasha-astiadi** [comment]
@sabrinasadik maybe you could assist us finding the answer

**Comment by sabrinasadik** [comment]
?

**Comment by sabrinasadik** [comment]
Current prices for deployment (as per chain), values on chain are expressed as "units USD per hour" where "1 unit usd" == 10.000.000 (1e7). A month is considered as 30 days (720 hours):

CU: 0.01 USD/hour (7.20 USD/month)
SU: 0.005 USD/hour (3.60 USD/month)
NU: 0.0015 USD/GB (1.5 USD/TB)
IPU (IPv4 Address): 0.004 USD/hour (2.88 USD/month)
UniqueName: 0.00025 USD/hour (0.90 USD/month)
DomainName: 0.0005 USD/hour (1.80 USD/month)

On top of this, discounts are handed out if sufficient tokens are available on the account which pays for the deployment (defined in code here: https://github.com/threefoldtech/tfchain/blob/development/substrate-node/pallets/pallet-smart-contract/src/cost.rs#L296-L340):

Less than 1.5 months (45 days): No discount
1.5 months (45 days): Default (20% discount)
3 months (90 days): Bronze (30% discount)
6 months (180 days): Silver (40% discount)
18 months (540 days): Gold (60% discount)

Renting a node (i.e. dedicated node) gives a 50% discount for the entire node (but you always pay the entire node)

**Comment by sasha-astiadi** [comment]
@sabrinasadik CU: 0.01 USD/hour (7.20 USD/month)
SU: 0.005 USD/hour (3.60 USD/month)
NU: 0.0015 USD/GB (1.5 USD/TB)
IPU (IPv4 Address): 0.004 USD/hour (2.88 USD/month)
UniqueName: 0.00025 USD/hour (0.90 USD/month)
DomainName: 0.0005 USD/hour (1.80 USD/month)

is this mUSD / hour or usd per hour?

**Comment by sasha-astiadi** [comment]
how about dedicated server part:

## Dedicated Servers

Starting April 2022, the TFGrid 3.0/a5 has support for dedicated servers. You can reserve a full server and the server is only usable for you, a minimum of 70% discount is given for this usecase.

- Dedicated Node, 192 GB mem, 24 cores, 1000 GB SSD = 75 USD per month (max discount, 3Y staking)
- Dedicated Node, 32 GB mem, 8 cores, 1000 GB SSD = 31 USD per month (max discount, 3Y staking)

Above example was with generous 5TB of bandwidth used per node per month, which is huge.

These nodes are ideal to deploy blockchain nodes, or other high demanding workloads. Dedicated nodes leads to amazing pricing.

To use a dedicated node, you will have to reserve a 3node for yourself in your admin portal of TFGrid, only you can then deploy on this node and there is no additional cost.


---


any pricing change?

**Comment by renauter** [comment]
Made some updates on values based on what is in TFChain code:

https://github.com/threefoldtech/info_grid/pull/172

Also reworked a bit the content and structure.

Btw, 

> UniqueName: 0.00025 USD/hour (0.90 USD/month)
> DomainName: 0.0005 USD/hour (1.80 USD/month)

wasn't correct (unless I miss something) so I corrected:

UniqueName: 0.00025 USD/hour (0.18 USD/month)
DomainName: 0.0005 USD/hour (0.36 USD/month)

**Comment by sabrinasadik** [comment]
> @sabrinasadik CU: 0.01 USD/hour (7.20 USD/month) SU: 0.005 USD/hour (3.60 USD/month) NU: 0.0015 USD/GB (1.5 USD/TB) IPU (IPv4 Address): 0.004 USD/hour (2.88 USD/month) UniqueName: 0.00025 USD/hour (0.90 USD/month) DomainName: 0.0005 USD/hour (1.80 USD/month)
> 
> is this mUSD / hour or usd per hour?

USD / hour

**Comment by sabrinasadik** [comment]
> how about dedicated server part:
> 
> ## Dedicated Servers
> Starting April 2022, the TFGrid 3.0/a5 has support for dedicated servers. You can reserve a full server and the server is only usable for you, a minimum of 70% discount is given for this usecase.
> 
> * Dedicated Node, 192 GB mem, 24 cores, 1000 GB SSD = 75 USD per month (max discount, 3Y staking)
> * Dedicated Node, 32 GB mem, 8 cores, 1000 GB SSD = 31 USD per month (max discount, 3Y staking)
> 
> Above example was with generous 5TB of bandwidth used per node per month, which is huge.
> 
> These nodes are ideal to deploy blockchain nodes, or other high demanding workloads. Dedicated nodes leads to amazing pricing.
> 
> To use a dedicated node, you will have to reserve a 3node for yourself in your admin portal of TFGrid, only you can then deploy on this node and there is no additional cost.
> 
> any pricing change?

This is outdated. See message above for correct pricing.

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/home/issues/1442#issuecomment-1620738275 pr open just waiting for @Mik-TF @xmonader to review :) thanks @sabrinasadik @renauter

**Comment by Mik-TF** [comment]
The PR is merged. @sasha-astiadi I'll let you decide if this issue is OK to be closed just in case there's still stuff you want done.

Thanks!
