### ISSUE TITLE
KYC requirement for customers + strong verification

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1450]
- now that we are getting closer to commercial usage of the grid we need to fix our KYC requirements
- each customer who is using the grid for more than 1000 USD per month will have to do basic KYC
    - we will use an automatic KYC provider for this
- every customer will be verified using 2 levels
    - email
    - sms
- we should check if we can do an automatic physical mail for verification
   - e.g. https://www.postgrid.com/
   - how do we send to international destinations  
- we should check what other hosting providers do e.g. Digital Ocean
- customer should accept terms and conditions which allow us to share succesful KYC to our partners in our ecosystem
   - we cannot share info, but we can share that the KYC, email, sms, post check succeeded or not
   - the customer needs to agree that the private keys he uses (can be more than 1), to verify his identity are his

**Comment by ramezsaeed** [comment]
@adnansf 
whats is the status here ?
any docs we can follow to test ?

**Comment by xmonader** [comment]
this is no longer relevant, it was implemented in #1572 and in #1578
