### ISSUE TITLE
formalize TF Validators

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1451]
# why

- validators are run by members of the community, we need to make it more easy for the to install

# what are the components which need to be installed

- TFChain Node
- TFValidator 4.0 (soon)
- TFHub
- TFExplorer
- TFProxy (Access to TFChain and RMB Network)
- All the User Interfaces
- At least 1 WebGW giving access to all services
- TFDNS a DNS server which we run on behalf of our users (soon)
- others ?

# how to install

- they only need an Ubuntu 22.04 and at least a machine with a Public IP Address
- docker based install (using our 3script)
- they can build their own components (optional using 3script and our v crystallib)

# initial reward

- 500 USD per month in locked TFT (as provided by TFCloud)

**Comment by xmonader** [comment]
can you please update us here @sabrinasadik ?

**Comment by xmonader** [comment]
docker compose done, also documented
