### ISSUE TITLE
productize webgw in relation to deployed VM

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1452]
make sure there is a mechanism in the playground to after deployment of a VM

- attach one or more webgw to the VM, more more than 1 webgw with multiple DNS to same machine
- configure one or more DNS names to it (user has own DNS)
- ask for custom names, know which names can be asked on which webgw's (for fast testing)
- ability to delete the webgw entries
- ability to see which webgw are linked to which VM
- ability to do all of this using 3script and our GO API

see threefoldtech/home#1455 for documentation about webgw

**Comment by despiegk** [comment]
what is status ?

**Comment by khaledyoussef24** [comment]
tests made 
- attached more than one gate way to the same vm
- attached custom domains to the vm
![image](https://github.com/threefoldtech/home/assets/110984055/7477f3bd-9d5f-4213-a8f3-3f2eb27d4715)
- the ability to delete one or more gateway
![image](https://github.com/threefoldtech/home/assets/110984055/9bcc4b9f-d3b2-40a7-931a-51e617d6c939)
![image](https://github.com/threefoldtech/home/assets/110984055/a4ca8076-4d7a-450e-a7f2-2ea23939ff45)
- more than one domain name for the same vm
- you can show and edit the domian list for every deployment
- you can show the gateway contracts from the contract list
- 
![image](https://github.com/threefoldtech/home/assets/110984055/77345201-513d-4507-ab41-3e939ed9ad3c)
