### ISSUE TITLE
gather more info from 3nodes

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1453]
today its very hard to find which 3nodes are actually good enough to run workloads on

e.g. 

- are they connected enough
- what was their uptime
- utilization
- are they actually running
- available capacity

### a VM based on

- we need a VM workload which polls info from node and posts to central service
- use V for the information checking (do some pings, do a network perf test = download test, do a minimal cpu perf test)
- implementation will be done in https://github.com/freeflowuniverse/crystallib/issues/295

### a zos one

- see also https://github.com/threefoldtech/home/issues/1454
- the v client is in https://github.com/freeflowuniverse/crystallib/issues/296 (needed to fill in backend)

## requirements

- openrpc endpoints over mycelium (can be more than 1) see https://github.com/freeflowuniverse/crystallib/issues/295
- https://github.com/freeflowuniverse/crystallib/issues/297

**Comment by despiegk** [comment]
maybe it should be added to monitoring solution based on vector

**Comment by despiegk** [comment]
to be specked

**Comment by xmonader** [comment]
obsoleted by https://github.com/threefoldtech/home/issues/1535
