### ISSUE TITLE
webgateways productized

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1455]
- make sure there are at least 8 webgateways in major locations
- if needed take some OVH or DIGITAL ocean VM's
- make sure they are all usable
- make sure they are documented in our manual so its easy for people to use them

**Comment by muhamadazmy** [comment]
Why not just dedicated zos gateways, (has no storage only cache ssd) so they can only be used as public nodes AND gateways, this way they can integrate seamlessly with  wireguard,  contracts and billing mechanism already implemented in the grid.

**Comment by xmonader** [comment]
best course of action is deploying that on OVH

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/tf_operations/issues/1889

**Comment by despiegk** [comment]
what is status now?
