### ISSUE TITLE
explorer nodes UI needs to be better and more informative

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1457]
<img width="1254" alt="image" src="https://github.com/threefoldtech/test_feedback/assets/6021844/75a5a15e-c713-441a-be82-2d0bb891e1e1">

- should be a better grid
- should scale better with width of browser (maybe remove some info if it doesn't fit)
- suggest to use smaller font anyhow
- the filter criteria maybe need to be more dense and on top
- maybe its good we we can click out the filter screen (to new tab so we have all the screen)

remark: notice how we will have more fields to filter on see threefoldtech/home#1453

**Comment by ehab-hassan** [comment]
@samaradel 
Please use Figma as a guide (Click on filter to see animation)
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=551-1910&t=NDp4jo0SngU74DIU-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by samaradel** [comment]
> @samaradel Please use Figma as a guide (Click on filter to see animation) https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=551-1910&t=NDp4jo0SngU74DIU-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

[#1020](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1020)

**Comment by A-Harby** [comment]
Verified, Qanet 2.2.0-rc2.

![image](https://github.com/threefoldtech/home/assets/109473873/66452510-a8e1-4ff5-9400-4c3b216c0cc5)

![image](https://github.com/threefoldtech/home/assets/109473873/fc79fbec-f59b-4142-bc3b-b00cc5a52ea2)
