### ISSUE TITLE
threefold cloud website

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1459]
> specs see this [document](https://docs.google.com/document/d/10Ieu1D00vZdVNP9nQESk4WMszAM5vqi8XoWzSBy3xPU/edit?usp=sharing)

# why

- its time to go commercial
- TF Cloud= ThreeFold DMCC wants to offer commercial solutions on top of the TFGrid

## initial products

- Virtual Datacenter (VM's, Private Networks, Web Gateways)
- Private AI Clouds = feed your own AI network with private data
- Personal BTC and BTC Lightening Nodes
- Personal Chat Servers (based on matrix, redundant config possible)
- Personal 3Bot (with integrated file storage, web2 gw, web3 gw, ...)

## unique

- management through AI driven chat
- automation through 3script
- +30,000 GPU's available
- +40,000 v Cpu's on ThreeFold Grid
- each user has their own 3bot
- integrated DNS services

## website

- simple using our framework
- UI = MD book per VDC
    - each deployed solution is a VDC
- integrated with element chat (best decentralized chat interface)
- a safe cloud, strong governance (link to governance work), safe environment = we don't want criminals, we want to be the cloud for good people (needs to be stated) 
- link from threefold.io to this one

**Comment by samtaggart** [comment]
Being worked on here:

https://github.com/threefoldfoundation/www_tf_cloud

**Comment by samtaggart** [comment]
Staging environment live: https://www2.cloud.threefold.io/

**Comment by samtaggart** [comment]
I think each product will need its own page, which will need to have specs and key benefits.

Meeting with Adnan and Kristof shortly to discuss.

**Comment by samtaggart** [comment]
**Notes from Meeting with Kristof**

- Get interest through registration
- Early access for the first customers
- Don't promise any timing, create a bit of hype

- Add something about how the dashboard will be
- The analytics

- Interface of what gets deployed (each solution is a VDC)
- Each will be its own MD Book, will do monitoring on your behalf
- Chat interface ...

- Prop up the TF Grid and the benefits of running on a decentralized infrastructure
- Tech Page: Quantum Safe File System, Planetary Network, Compute, Blockchain ...

**Comment by xmonader** [comment]
@samtaggart what is the progress here?
