### ISSUE TITLE
FreeFlowPages to be production-ready

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#146]
Freeflow pages needs to be more streamlined for an end user with no technical background.
Signup/Sign in process needs to be very intuitive and easy for people to join.

In that respect, we need to explain better the process and improve the usability in the sign up page.

we also need freeflow logo to add to itsyouonline organization

![Untitled Diagram](https://user-images.githubusercontent.com/8425762/54528379-8279a900-4985-11e9-9ade-f5bd590b29e3.png)

**Text for signing up:**
 - Step 1: Register with ItsYouOnline
      SAFE. SECURE. PRIVATE.
 - Step 2: Fill in your data
 - Step 3: Confirm your identity
 - Step 4: Welcome to FreeFlowPages!

**Text for signing in:**
 - Log in with ItsYouOnline
 - (Temporary) Log in with Username/Password

**Comment by samaradel** [comment]
done & sent to @Hamdy

**Comment by rkhamis** [comment]
➤ Hamdy commented:

There's a pull request ( https://github.com/itsyouonline/identityserver/pull/743 ) now for IYO modifications to allow for skipping Phone Verification
It's being processed by GIG

On the other hand: We've a 3 Bot login Module ( https://github.com/freeflowpages/freeflow-threebot-login )
for integration with 3bot Login.

We're making Login with IYO deprecated

Please check 3bot login @staging Here ( https://github.com/freeflowpages/freeflow-threebot-login )
