### ISSUE TITLE
tools for TF Cloud Admin & Sign Up

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1461]
### Edit3Script Component

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1057
- a widget which allows easy editing of 3script (an just be a javascript widget use tailwindcss)
- this widget needs to be able to submit content signed by browser extension
- if we post we let the server know pubkey of who signed as well as the signature, so server can verify
- can we do autocomplete (maybe next phase)
- create example V webserver which accepts the posted content

e.g` <Edit3Script dest=.... />`

### PDFSigner component

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1056
- show pdf from a URL
- let user scroll all the way down
- get the md5 of the pdf
- sign with browser extension and post to a V webserver (pub key + signature + url from pdf)

e.g `<PDFSigner pdf-url= ...  dest=... />`

## KYC integration

- see how to integrate kyc best

## unified identity mgmt + login into our 2 websites

Use the browser extension everywhere

## Notifications API clients (email, sms)

- [x] https://github.com/freeflowuniverse/crystallib/issues/226
- [x] https://github.com/freeflowuniverse/crystallib/issues/227

**Comment by despiegk** [comment]
alternative we use polkadot widget if kepler not easy

**Comment by despiegk** [comment]
make sure it also works on mobile

**Comment by despiegk** [comment]
can you link to instructions how to use please

**Comment by A-Harby** [comment]
You can find the UI package [here](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/UI) and docs over [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/UI/README.md).

Main two feature are [PDF Viewer](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/UI/docs/pdf_viewer.md) and [Script Editor](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/UI/docs/script_editor.md), and there main issues are [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1057) and [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1056).




Other issues related just to fix some minor errors, docs and examples are [1](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1127) [2](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1173) [3](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1186) [4](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1181).

**Comment by xmonader** [comment]
@despiegk if you still missing anything from the docs please reopen the issue
