### ISSUE TITLE
fix publishing tools

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1463]
the publishing tools are written in V and kind of got lost in the noise

they are used for https://library.threefold.me/

## we need the following to happen

- find the software (see master branch on crystallib), or more recent
- copy the code itself to publishing tools repo (freeflow universe)
    - copy the macro's as well
- make sure it builds
- make sure we have a vbuilder for building the publishing tools
- run them in development mode, check them against library.threefold me, is it all working
- create a v script starting docker with the publishing tools, checkout info_legal and info_... load them all show the result in webserver from publishing server
- check the export function of publishing server
- make sure all docu is on publishing tool server

## training

- make sure Peter and other members of team know how to compile (through docker ok)
- deploy
- fix errors on the wiki itself (errors page)

## cleanup

- archive current info_threefold_pub and other info_... not used
- create a new info_threefold_pub only copy the latest relevant info there
- check the errors file, fix broken links

**Comment by xmonader** [comment]
closed in favor of https://github.com/freeflowuniverse/crystallib/issues/230
