### ISSUE TITLE
story: mycelium v 0.9 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1465]
is an alpha release

## initial features

- networking (at least features like in yggdrasil)
- ability to get pub key from source ip address
- reliable message delivery (queue in mycelium node, timeout, ...)
    - rest or other way how to push/pull the message from the mycelium node 
- minimal website (tech oriented) + mdbook

## requirements

- get community to play with it (not just our community)
- get exposure, on +1000 nodes asap

**Comment by despiegk** [comment]
all should be very easy to consume

- simple rest calls
- optional websockets with jsonrpc both way for the ABCI interface (simplify as much as possible)

**Comment by LeeSmet** [comment]
After some research, it turns out that the rust tendermint version only supports light clienst.

As such, it has been decided to drop this functionality for now.

**Comment by xmonader** [comment]
@LeeSmet what is the status here?

**Comment by xmonader** [comment]
@LeeSmet safe to close? is there any continuation to the story if not done yet?

**Comment by LeeSmet** [comment]
Features are done, to my knowledge website is as well. Only thing left is exposure, though I'm not sure how relevant that is to the story at hand

**Comment by ramezsaeed** [comment]
Testing requirements:
    - Need to know minimum number of nodes needed to test.
    - how to setup a test env.
