### ISSUE TITLE
Rework POBS protocol so it is no longer required to respent a blockstake output

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#147]
Deprecates #35 

- [x] Add block creation transaction type
- [x] Modify POBS algorithm to be able to use the explicit block creation tx instead of respending the blockstake

- [ ] Support for a delegation of one or more blockstakes, by referencing the output
- [x] Add delegation transaction

To be done in tfchain once the above is done and merged (and tfchain vendor is updated to include these)
- [ ] Explorer support for block creation transactions
- [ ] Explorer support for delegation transactions

**Comment by LeeSmet** [comment]
In the initial implementation of the block creation tx the following issue is encountered:
The reference to the block stake which will be used to create the block needs a signature (fulfillment) to prove ownership. However in the current system there is no way to retrieve the condition, since the code which does the actual signing only gets a parent ID, but it does not have the context of the consensus set. To solve this, we will need to rework part of the transaction signing architecture to somehow inject the consensus db

**Comment by LeeSmet** [comment]
Above issue could potentially be solved by forgoing the implementation of the extensionSigner interface, and manually signing in the blockcreator where we do have access to the used outputs to derive the right fulfillment. Though the same problem now arises for the validation, since we don't have an input to verify the fulfillment in the extension when checknig the transaction

**Comment by LeeSmet** [comment]
Another thing to note is that the transaction as it stands has no form of entropy, meaning all fulfillments of the same blockstake outputs have the same signature, and the transactions have the same ID

**Comment by LeeSmet** [comment]
Can now create blocks with the block creation transaction and the signature should be validated, checking if any other validation needs to happen.

**Comment by LeeSmet** [comment]
Opened draft PR for the block creation tx, still looking if we need to add additional checks for the blockstake aging (and if so, how)

**Comment by sabrinasadik** [comment]
@robvanmieghem Is this a prio for May?
