### ISSUE TITLE
3.12 testplan

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1470]
#### Test plan for v 3.12.x should cover:
- development project: https://github.com/orgs/threefoldtech/projects/203
- Testlodge Run: 
     - QAnet:
         - iteration 1: https://app.testlodge.com/a/26076/projects/40893/runs/721107
         - iteration 2: https://app.testlodge.com/a/26076/projects/40893/runs/725034
     - Testnet:
         - iteration 1: https://app.testlodge.com/a/26076/projects/40893/runs/722799
         - iteration 2: https://app.testlodge.com/a/26076/projects/40893/runs/725177
     - Mainnet:
         - https://app.testlodge.com/a/26076/projects/40893/runs/727876

- Known Issues: https://github.com/threefoldtech/home/issues/1471

### Schedule
- 3.12.x expected to be on QAnet OCT 1st
- All tests and verification should be within one week maximum.

#### Main Features:
- https://github.com/threefoldtech/zos/issues/2034
- https://github.com/threefoldtech/home/issues/1457
- https://github.com/threefoldtech/home/issues/1461
- https://github.com/threefoldtech/home/issues/1454
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1055

#### Quick verification:
- [x] https://github.com/threefoldtech/zos/issues/2034
- [x] https://github.com/threefoldtech/zos/issues/2071
- [x] https://github.com/threefoldtech/home/issues/1458
- [x] https://github.com/threefoldtech/zos/issues/2036
- [x] https://github.com/threefoldtech/zos/issues/2050
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1127
- [x] https://github.com/threefoldtech/home/issues/1449
- [x] https://github.com/threefoldtech/home/issues/1457
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1041
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1034
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1066

#### Validation and Add new testcases to testlodge:
- [x] https://github.com/threefoldtech/home/issues/1457
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1055
- [x] https://github.com/threefoldtech/home/issues/1452
- [x] https://github.com/threefoldtech/home/issues/1461
- [x] https://github.com/threefoldtech/zos/issues/2037
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1055
- [x] https://github.com/threefoldtech/zos/issues/2056
- [x] https://github.com/threefoldtech/tf-images/issues/163
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1057
- [x] https://github.com/threefoldtech/tfchain/issues/864

### PerfTest Reference Docs:
- https://github.com/threefoldtech/zos/tree/main/docs/tasks

Testlodge coverage:
- https://app.testlodge.com/a/26076/projects/40893/suites/234919

verify basic perf  test and node performance in ZOS

- [x] https://github.com/threefoldtech/home/issues/1454
- [x] https://github.com/threefoldtech/zos/issues/2033

Need to be tested
- [x] https://github.com/threefoldtech/zos/issues/2111
- [x] https://github.com/threefoldtech/zos/issues/2113
- [x] https://github.com/threefoldtech/zos/issues/2112
- [x] https://github.com/threefoldtech/zos/issues/2114

**Comment by ramezsaeed** [comment]
QAnet Test run:
https://app.testlodge.com/a/26076/projects/40893/runs/721107

![Screenshot from 2023-11-12 10-10-42](https://github.com/threefoldtech/home/assets/16083592/9f705c4e-0eb9-49db-9579-354b06b01c35)

**Comment by ramezsaeed** [comment]
TestNet run:

https://app.testlodge.com/a/26076/projects/40893/runs/722799?tab=0
![image](https://github.com/threefoldtech/home/assets/16083592/6af4e480-1c1d-4191-a965-99b26ed4a079)

**Comment by xmonader** [comment]
https://github.com/threefoldtech/home/issues/1454 this needs to be tracked

**Comment by xmonader** [comment]
While this is part of 3.12 project, it's purely bizdev https://github.com/threefoldtech/home/issues/1459 , please make sure that's not tracked

**Comment by ramezsaeed** [comment]
Done with fixing and verifying all add domains feature issues.

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1055

**Comment by ramezsaeed** [comment]
Work In Progress (WIP):
Testnet run iterration two is in progress:

![Screenshot from 2023-12-05 16-21-55](https://github.com/threefoldtech/home/assets/16083592/4183e116-7042-4cdc-8791-e4f3d47c948b)

**Comment by ramezsaeed** [comment]
Testnet run Done here
https://app.testlodge.com/a/26076/projects/40893/runs/725177


![Screenshot from 2023-12-06 14-19-54](https://github.com/threefoldtech/home/assets/16083592/f9e7b0e9-2a6f-4776-98ae-80c1667a2337)

**Comment by ramezsaeed** [comment]
waiting for 3.12 to be deployed on Mainnet

**Comment by ramezsaeed** [comment]
Test run for all the grid solutions can be followed here:
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1763

**Comment by xmonader** [comment]
@ramezsaeed please remove what's irrelevant to 3.12 from the story

**Comment by ramezsaeed** [comment]
https://app.testlodge.com/a/26076/projects/40893/runs/727876

![Screenshot from 2024-01-16 09-22-37](https://github.com/threefoldtech/home/assets/16083592/7bd32b89-6bdb-490b-b0f9-c0996892da96)
