### ISSUE TITLE
3bot reorg

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1474]
meta issue

- https://github.com/threefoldtech/3bot/issues/209
- https://github.com/freeflowuniverse/crystallib/issues/256
- https://github.com/freeflowuniverse/crystallib/issues/243
- https://github.com/freeflowuniverse/crystallib/issues/245
- https://github.com/freeflowuniverse/crystallib/issues/242
- https://github.com/freeflowuniverse/crystallib/issues/241

**Comment by despiegk** [comment]
- farmerbot can be moved to 3.13
- https://github.com/freeflowuniverse/crystallib/issues/249
- also: https://github.com/freeflowuniverse/crystallib/issues/244
