### ISSUE TITLE
Improved observability for stellar-tfchain bridge

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/home#1476]
We require improved observability for our bridges. This can be achieved by implementing a REST endpoint that provides health metrics or by enabling the services to output structured logs/events that help monitor real-time abnormalities and evaluate system health.

To achieve better observability into the bridges, we need to expose data such as bridge wallet balances and processed height in both chains.

- [x]  tfchain - stellar bridge - [issue](https://github.com/threefoldtech/tfchain/issues/874)

**Comment by renauter** [comment]
Update:

As we talked with @sameh-farouk on last meeting, we are waiting for feed back and validation for `TFChain <=> EVM` bridge logging (which is already live) to replicate the same patterns and adapt it to `Stellar <=> EVM` bridge.
