### ISSUE TITLE
Grid launch

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#148]
This story describe what needs to be done for us to be ready for the launch.

The launch consist of having everything ready for user to be able to reserve 4 workloads on the grid:
- virtual 0-os
- s3 archive
- 0-db namespace
- reverse proxy

Next to the reservation, user needs to be able to deploy container on their virtual 0-OS.

![architecture](https://user-images.githubusercontent.com/303164/55721714-5d1c1000-5a04-11e9-9824-dffc522d2bef.png)

- [x] 0-db [namespaces]
- [x] web reverse proxy
- [x] Update grid broker to use the new templates
- [x] Fix gedis usage in tfchain client
- [x] Ensure JSX 0-OS client is working
- [x] [refund sometimes fails to be send](https://github.com/threefoldtech/grid_broker/issues/10)
- [x] [Document how to create container on virtual 0-OS using JSX 0-OS client](https://github.com/threefoldtech/home/issues/168)
  - [x] validate jsx installation with docker works properly, user will use this technich to get JSX
  - [x] review documentation about tfchain client in JSX
  - [x] review documentation how to reserve capacity: https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation

**Comment by rkhamis** [comment]
@zaibon we'll need flists, then. I'll take care of the 3bot one

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscaleX/pull/284
https://github.com/threefoldtech/grid_broker/pull/9
Both PR for the code required to reserve the new workloads are ready.
Once this is merged, I'll have to update the grid broker with the new templates

**Comment by zaibon** [comment]
Documentation can be found at: https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation
