### ISSUE TITLE
ZOS mycelium v1

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#1480]
- [x] https://github.com/threefoldtech/zos/issues/2073
- [x] https://github.com/threefoldtech/tfgrid-sdk-go/issues/677
- [x] https://github.com/threefoldtech/zos/pull/2208#pullrequestreview-1900546737
- [x] https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2251

**Comment by muhamadazmy** [comment]
- [ ] https://github.com/threefoldtech/zos/issues/2073
- [ ] https://github.com/threefoldtech/tfgrid-sdk-go/issues/677
