### ISSUE TITLE
Problem with bridge

### ISSUE THREAD

**Issue by Zachem11** [threefoldtech/home#1496]
Hello.
You did and do an enormous volume of work, but can you briefly address the problem with the bridge? My money stucked somewhere in BSC-TFT and without them life is sad. Especially considering that the exchange rate has already fallen by 14 percent.
Sincerely

**Comment by renauter** [comment]
Hi @Zachem11 
Is it solved ?
If not we will need some more information to be able to see what is happening

**Comment by Zachem11** [comment]
> Hi @Zachem11 Is it solved ?

The bridge is functional, yes, i done tens of bridgings. But in one case txn stucked already sixth day.
https://bscscan.com/tx/0xa73695c4a19ce528ab0f4a00119cda06c4c92b1fd6839f39df80c809378dcff4
I checked five or more time, everything correct. Then i speak with suppport and, as i understood, problem is on your side. Can you push it through? Token already fall almost 20%...

**Comment by Zachem11** [comment]
No, the problem is not solved, unfortunately. What details do you need?

чт, 14 дек. 2023 г. в 05:12, Erwan Renaut ***@***.***>:

**Comment by Zachem11** [comment]
Yes, i received, thank you.
