### ISSUE TITLE
Communication project on git.ourworld

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/home#1511]
# Situation

With the new gitea: https://git.ourworld.tf/, we could add a repository to complement info_grid (tf manual), where we would track progress of communication projects based on the TF Manual.

# New Repo on git.ourworld.tf

The new repository:
`tftech/info_grid_communication`

We can then create a project and set issues to track progress. If in github, threefoldtech/info_grid_communication.

For more information on the communication project, refer to [this doc](https://docs.google.com/spreadsheets/d/1UTEHfAgJzz0FrC5_eNYu6fE6SgmkmpSKH9ZkkZOziZU/edit#gid=190440487).

# GH and git.ourworld

It can also be done on Github, but it might be a good opportunity to work on the new git.ourworld.tf

EDIT: git.ourworld.tf version [here](https://git.ourworld.tf/home/home/issues/1)

**Comment by xmonader** [comment]
@despiegk can you check, I'm not sure what should be done. for me I'd plan that communication project on the same repo of info_grid not on a separate repo, but that's just me. It's better to put as much as we can in one system, specially if related to the same repo.

**Comment by Mik-TF** [comment]
We started to set it on the git.ourworld.tf: https://git.ourworld.tf/threefold_coop/circle_comms_community/projects/11

We can transfer if needed.

You can see that it generates a lot of issues, since we want to publish 36 articles on 7 platforms (more or less).

This might be too much "issues" on info_grid.

Personally, I am open to all options.

**Comment by xmonader** [comment]
As long as it works it should be fine. Thanks Mik
