### ISSUE TITLE
Review/Update All testsuites in Testlodge 3.13

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1516]
We need to review all these testsuite; some of them even needs update or obsolete we can archive them.

- [x] [Profile Manager](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#suite_section_422331)
- [x] [TFGrid](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#suite_section_426660)
- [x] [Deploy](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#suite_section_426661)
- [x] [Deploy: Virtual Machines and Orchestrators](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#suite_section_422333)
- [x] [Deploy: Applications](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#suite_section_422332)
- [x] [Virtual Machine Deployment](https://app.testlodge.com/a/26076/projects/40893/suites/194664)
- [x] [perf testing](https://app.testlodge.com/a/26076/projects/40893/suites/234919)
- [x] [Billing](https://app.testlodge.com/a/26076/projects/40893/suites/229658)
- [x] [Grace Period](https://app.testlodge.com/a/26076/projects/40893/suites/217782)
- [x] [tf-grid-cli](https://app.testlodge.com/a/26076/projects/40893/suites/224178)
- [x] [Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/204782)
- [x] [Grid3_Client_TS](https://app.testlodge.com/a/26076/projects/40893/suites/194096)
- [x] [New Dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/234374)
- [x] [Farmer bot](https://app.testlodge.com/a/26076/projects/40893/suites/221831)
- [x] [TFRobot](https://app.testlodge.com/a/26076/projects/40893/suites/236972)

**Comment by A-Harby** [comment]
WIP:
- [tf-grid-cli](https://app.testlodge.com/a/26076/projects/40893/suites/224178)
- [Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/204782)

**Comment by khaledyoussef24** [comment]
WIP :
https://app.testlodge.com/a/26076/projects/40893/suites/234919

**Comment by khaledyoussef24** [comment]
work done: seperated every task because every taks has it's own docs and added test cases to shows that the results are clear 
WIP : VMS and k8s

**Comment by ramezsaeed** [comment]
WIP:
- [TFRobot](https://app.testlodge.com/a/26076/projects/40893/suites/236972)

**Comment by khaledyoussef24** [comment]
WIP : 
- [Deploy](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#suite_section_426661)
- [Deploy Applications](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#suite_section_422332)

**Comment by khaledyoussef24** [comment]
work done : 
went through the deploy section to make it look exactly similar to the Dashboard
![Screenshot 2024-02-19 at 4 55 45 PM](https://github.com/threefoldtech/home/assets/110984055/6d843e1d-aa67-4360-81f5-81877e0339cc)

![Screenshot 2024-02-19 at 4 54 41 PM](https://github.com/threefoldtech/home/assets/110984055/8c10e086-a7d7-4498-bbad-acea435fae22)
filtered some of the duplicated test cases as well.

working on the calculator section and will cover the vms test suite after to close this issue

**Comment by khaledyoussef24** [comment]
work done : test suite upgrade and virtual machines
https://app.testlodge.com/a/26076/projects/40893/suites/217765

**Comment by xmonader** [comment]
@ramezsaeed can we close now?
