### ISSUE TITLE
Review/Update All testsuites in Testlodge 3.14

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1517]
We need to review all these testsuite; some of them even needs update or obsolete we can archive them.

- [x] [TFChain](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#suite_section_422339)
- [x] [Farms](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#suite_section_426668)
- [x] [pulumi-threefold](https://app.testlodge.com/a/26076/projects/40893/suites/234258)
- [x] [QBD](https://app.testlodge.com/a/26076/projects/40893/suites/234925)
- [x] [Caprover](https://app.testlodge.com/a/26076/projects/40893/suites/194660)
- [x] [Kubernetes](https://app.testlodge.com/a/26076/projects/40893/suites/195277)
- [x] [Grid Upgrade](https://app.testlodge.com/a/26076/projects/40893/suites/217765)
- [x] [TF Grid Monitoring Bot](https://app.testlodge.com/a/26076/projects/40893/suites/218162)
- [x] [TF Grid Proxy](https://app.testlodge.com/a/26076/projects/40893/suites/211680)
- [x] [TF Grid Stats](https://app.testlodge.com/a/26076/projects/40893/suites/211395)
- [x] [tf-connector](https://app.testlodge.com/a/26076/projects/40893/suites/233085)
- [x] [Terraform](https://app.testlodge.com/a/26076/projects/40893/suites/193850)
- [x] [SFTPGO](https://app.testlodge.com/a/26076/projects/40893/suites/228220)
- [ ] [Jmeter](https://app.testlodge.com/a/26076/projects/40893/suites/227111)
- [x] [web3_proxy](https://app.testlodge.com/a/26076/projects/40893/suites/226812)
- [x] [Power Management](https://app.testlodge.com/a/26076/projects/40893/suites/217969)
- [x] [Node Restart](https://app.testlodge.com/a/26076/projects/40893/suites/217775)
- [x] [Get TFT test suite](https://app.testlodge.com/a/26076/projects/40893/suites/193825)
- [x] [Storage](https://app.testlodge.com/a/26076/projects/40893/suites/195671)
- [x] [Validator](https://app.testlodge.com/a/26076/projects/40893/suites/206106)
- [x] [Planetary network](https://app.testlodge.com/a/26076/projects/40893/suites/195345)
- [x] [WebGateway](https://app.testlodge.com/a/26076/projects/40893/suites/193856)
- [x] [QSFS](https://app.testlodge.com/a/26076/projects/40893/suites/193855)

**Comment by khaledyoussef24** [comment]
WIP 
- Pulimi
- monitoring bot

**Comment by khaledyoussef24** [comment]
@AhmedHanafy725 is web3_proxy and get tft still supported or shall we archive these test suites ?

**Comment by khaledyoussef24** [comment]
work done : 
[pulumi-threefold](https://app.testlodge.com/a/26076/projects/40893/suites/234258) 
[TF Grid Monitoring Bot](https://app.testlodge.com/a/26076/projects/40893/suites/218162)[tf-connector](https://app.testlodge.com/a/26076/projects/40893/suites/233085)

WIP
[TF Grid Proxy](https://app.testlodge.com/a/26076/projects/40893/suites/211680)
 [TF Grid Stats](https://app.testlodge.com/a/26076/projects/40893/suites/211395)
[Terraform](https://app.testlodge.com/a/26076/projects/40893/suites/193850)

**Comment by A-Harby** [comment]
Work done:
- [TFChain](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#suite_section_422339)
- [Farms](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#suite_section_426668)
- [Caprover](https://app.testlodge.com/a/26076/projects/40893/suites/194660)


Archived or not?
- [QBD](https://app.testlodge.com/a/26076/projects/40893/suites/234925)
- [SFTPGO](https://app.testlodge.com/a/26076/projects/40893/suites/228220)
- [Power Management](https://app.testlodge.com/a/26076/projects/40893/suites/217969)
- [Get TFT test suite](https://app.testlodge.com/a/26076/projects/40893/suites/193825)
- [WebGateway](https://app.testlodge.com/a/26076/projects/40893/suites/193856)
- [Validator](https://app.testlodge.com/a/26076/projects/40893/suites/206106)

**Comment by ramezsaeed** [comment]
Archived:
- [WebGateway](https://app.testlodge.com/a/26076/projects/40893/suites/193856)
- [Get TFT test suite](https://app.testlodge.com/a/26076/projects/40893/suites/193825)
- [Validator](https://app.testlodge.com/a/26076/projects/40893/suites/206106)

**Comment by khaledyoussef24** [comment]
Running the remaining tests to check if any updates is needed 
[testrun](https://app.testlodge.com/a/26076/projects/40893/runs/753728?tab=0)

**Comment by khaledyoussef24** [comment]
done for today 
- QBD
WIP : [#3258](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3258)

**Comment by khaledyoussef24** [comment]
[Planetary network](https://app.testlodge.com/a/26076/projects/40893/suites/195345)
should be archived outdated since we started to use 0.5 yggdrasil instead of 0.4

**Comment by ramezsaeed** [comment]
Jmeter: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3258
