### ISSUE TITLE
QAnet 3.13 TestRun V1

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#1521]
Testlodge run for 3.13 on QAnet

https://app.testlodge.com/a/26076/projects/40893/runs

**Comment by khaledyoussef24** [comment]
added to grid client :
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4221239
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4221253

**Comment by A-Harby** [comment]
WIP:
I started with the new dashboard test suite.
I found 6 failed cases, some of which had issues, and others were created:
- https://github.com/threefoldtech/tf_operations/issues/2337
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2266
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2275
- https://github.com/threefoldtech/tf_operations/issues/2342

**Comment by A-Harby** [comment]
WIP:
Reached 12 failed, and new issues created:
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2280
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2282
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2283
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2284
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2286
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2287

**Comment by khaledyoussef24** [comment]
finished test suite of grid_client : 
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2289

finished test suite of perf testing

**Comment by khaledyoussef24** [comment]
[health check task in perf tests ](https://github.com/threefoldtech/zos/issues/2209)

**Comment by A-Harby** [comment]
WIP:
Reached [21](https://app.testlodge.com/a/26076/projects/40893/runs/733116?result=0&tab=2) failed, and new issues were created:
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2291
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2292
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2293
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2294

Test suite finished:
- [Node Restart](https://app.testlodge.com/a/26076/projects/40893/runs/733116?expand_config=1200470#run_suite_1200470)
- [Grid Upgrade](https://app.testlodge.com/a/26076/projects/40893/runs/733116?expand_config=1200469#run_suite_1200469)
- [TF Grid Stats](https://app.testlodge.com/a/26076/projects/40893/runs/733116?expand_config=1200468#run_suite_1200468)
- [Grid3_Client_TS](https://app.testlodge.com/a/26076/projects/40893/runs/733116?expand_config=1200451#run_suite_1200451)
- [perf testing](https://app.testlodge.com/a/26076/projects/40893/runs/733116?expand_config=1200393#run_suite_1200393)

**Comment by ramezsaeed** [comment]
Work Complete.
Will create new testrun for TestNet 3.13-rc2
