### ISSUE TITLE
GetTFT: Market Price

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/home#1527]
# Situation

There has been a lot of feedback from the community on gettft.com being an OTC and not following market price. Right now the service seems also unavailable.

As discussed with @samtaggart and @scottyeager, to name a few.

# Suggestion

- Have gettft.com present current market price, maybe add 1 cent as a revenue for the service
- In the meantime, we suggest to have a redirect of gettft.com to the manual quick buy section: https://manual.grid.tf/documentation/threefold_token/buy_sell_tft/tft_lobstr/tft_lobstr_short_guide.html

**Comment by Mik-TF** [comment]
# Situation

- GetTFT price is not current market
- This looks bad and unprofessional

# Todo

- Unpublish it from the online web
- on website, have the get tft button leading to manual get TFT article

@sabrinasadik

**Comment by sabrinasadik** [comment]
Does gettft.com need to be redirected to the wiki?

**Comment by Mik-TF** [comment]
We could do this. To link the buy tft section of the manual
