### ISSUE TITLE
Mycelium desktop and mobile clients

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1544]
Tracking the efforts to provide clients for 

- [x] Desktop
  - [x] Windows
  - [x] Linux (enough as a CLI)
  - [x] Mac
- [x] Mobile
  - [x]  IOS
  - [x] Android

**Comment by khaledyoussef24** [comment]
test suites covering is mobile versions is created and tested
[test suite](https://app.testlodge.com/a/26076/projects/40893/suites/244166)

**Comment by khaledyoussef24** [comment]
Tested Desktop version but only version available for now 
- Macos
- Winodws
- IOS
- Android

the progress and steps made to verify the desktop version can be found [here](https://github.com/threefoldtech/myceliumflut/issues/66) 

test suite including test cases covering all of the versions can be found [here](https://app.testlodge.com/a/26076/projects/40893/suites/244166)

**Comment by khaledyoussef24** [comment]
while testing on windows faced this [issue](https://github.com/threefoldtech/mycelium/issues/474)

the mycelium network works fine but could not connect on the grids machine but could ping any mycelium ip and connect to any server has mycelium installed

**Comment by khaledyoussef24** [comment]
Worked on windows fine now also
![telegram-cloud-photo-size-4-5819062692281960362-y](https://github.com/user-attachments/assets/832a5270-ead5-40a3-a02f-de1f5417d58c)
