### ISSUE TITLE
TFGrid Full Stack Deployment: Procedures and Documentation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1546]
- [x] Bootstrap https://github.com/threefoldtech/grid_deployment/issues/50
- [x] Hub https://github.com/threefoldtech/grid_deployment/issues/49
- [x] Validator https://github.com/threefoldtech/grid_deployment/issues/52

**Comment by Mik-TF** [comment]
@coesensbert is stuck on some issues for the grid stack:

https://github.com/threefoldtech/tfchain/issues/981
https://github.com/threefoldtech/grid_deployment/issues/52
https://github.com/threefoldtech/grid_deployment/issues/63
https://github.com/threefoldtech/grid_deployment/issues/62
https://github.com/threefoldtech/grid_deployment/issues/61

@xmonader can you check with the dev team how to best help him out here? Thanks!

**Comment by Mik-TF** [comment]
# Status

- Bootstrap and hub completed: #49, #50
- Validator WIP

**Comment by Mik-TF** [comment]
# Status

- @coesensbert is finalizing the validator part
- Once this is 100% completed, we will make sure docs are up to date, and add the docs to the manual.grid.tf
