### ISSUE TITLE
Support multiple stacks per network in ZOS, sdk-go and sdk-ts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1550]
update ZOS,  SDK-go and SDK-ts to support fallback to alternative stacks when the primary stack fails. This feature will improve reliability and resilience of applications using these SDKs.

## Requirements:
1. Configuration:
   - Allow users to specify multiple stacks in configuration

2. Fallback Mechanism:
   - Attempt to connect to the primary stack first
   - On failure, automatically try the next stack in the priority list
   - Continue until a successful connection is made or all options are exhausted

3. Error Handling:
   - Provide detailed error information for each failed attempt
   - Log each fallback attempt with relevant details (stack info, error message)

4. Documentation:
   - Provide code examples demonstrating how to configure and use multiple stacks

## Tasks
- [x] threefoldtech/zos#2372
- [x] threefoldtech/tfgrid-sdk-go#1113
- [x] threefoldtech/tfgrid-sdk-ts#3078

**Comment by 0oM4R** [comment]
Where can i find the stacks urls ?

**Comment by AhmedHanafy725** [comment]
> Where can i find the stacks urls ?

@hossnys @PeterNashaat

**Comment by PeterNashaat** [comment]
all 4 nets stack urls can be found [here](https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/grid_operations/grid_backend)

**Comment by hossnys** [comment]
I already provided @ashraffouda and @AbdelrahmanElawady with all that info and here are the urls again : 
https://dashboard.dev.grid.tf
https://dashboard.02.dev.grid.tf
https://dashborard.dev.ninja.tf

https://dashboard.qa.grid.tf
https://dashboard.02.qa.grid.tf

https://dashboard.test.grid.tf
https://dashboard.02.test.grid.tf
https://dashborard.test.ninja.tf

https://dashboard.grid.tf
https://dashboard.02.grid.tf
https://dashborard.ninja.tf

Note:
any stack with domain ninja.tf is just for testing purposes.

**Comment by xmonader** [comment]
All of the subtasks are closed
