### ISSUE TITLE
Sentry integration: Typescript and Dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#1554]
Use Sentry for error tracking and monitoring in sdk-ts, and the Dashboard, and even the mobile apps check also #1487 to provide more insights. This will enhance our ability to identify, track, and resolve issues quickly across our entire stack.

##  Error Tracking:
   - Capture and report unhandled exceptions/errors
   - Ensure sensitive data is not sent to Sentry (implement proper redaction)

##  Environment Separation:
   - Configure separate projects or environments in Sentry per network
   - Allow option to enable the data to be sent to our servers  e.g TF_SENTRY_ENABLE

##  Dashboard Integration:
 Implement Sentry error handling for Vue/Vuetify components (requires some research)

##  Documentation
   - Update documentation for all projects to include information about Sentry integration
   - Provide guidelines for developers on how to use Sentry effectively

##  Testing
   - Implement tests to ensure Sentry is capturing errors correctly
   - Create a test suite for verifying Sentry integration in CI

## performance tracking (extra)
no idea yet

## Deployment (Operations)
https://github.com/threefoldtech/tf_operations/issues/2641

## Alerting (Operations)
   - Set up alert rules in Sentry for critical issues
   - Configure notification channels (e.g., Slack, email)

**Comment by khaledyoussef24** [comment]
how shall we test the sentry integration ?

is making a new branch with files which contains errors and vulnerabilities and then run the work flows on them to check the issue creation is the best practice ?

**Comment by xmonader** [comment]
Let's talk about this

**Comment by xmonader** [comment]
the typescript ticket was verified.
