### ISSUE TITLE
Ubuntu JSX/DigitalMe Sandbox Usable 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#156]
Sandbox =  Python/jumpscale & Lua/openresty

## repo's

-  [Base Sandbox](https://github.com/threefoldtech/sandbox_base) contains only pure python&lua libs. It doesn't contain any platform specific libs `*.so` files so scripts in it, can run in any platform, be it  MacOsX or Ubuntu.
-  [Ubuntu Sandbox ](https://github.com/threefoldtech/sandbox_ubuntu) contains native libs that are linux/ubuntu specific 

## implement the builder

- use instructions on https://github.com/threefoldtech/jumpscaleX/blob/development_types/docs/Internals/Builders.md
- 

## To build 

```python3
j.builder.apps.digitalme.build()
flist = j.builder.apps.digitalme.sandbox(zhub_instance=...)
```

only do starting from Ubuntu 1804

## To Test

```
j.builder.apps.digitalme.test(zos_client)
```

- script to start from ZOS client connection
- start container, see kosmos shell & openresty wiki is working

/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/builder/apps/BuilderDigitalME.py

**Comment by andrewayoub** [comment]
`j.builder.apps.digitalme.build()` now works but it uses other builders which still need refactoring to follow the new instructions

**Comment by Dina-Abd-Elrahman** [comment]
- verified here https://github.com/threefoldtech/home/issues/160
