### ISSUE TITLE
zos to work on cloud providers

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/home#1561]
for zos to work on cloud providers we need to only support mycelium and do some more modification to how things works regarding namespaces and all network setup more info about the specs are here https://github.com/threefoldtech/zos/tree/fecd21a5f475e5c6680f00f800700dc4a64f4704/docs/internals/network-light

**Comment by xmonader** [comment]
can this go to verification @ashraffouda ?

**Comment by xmonader** [comment]
That has been verified by devs and ops
