### ISSUE TITLE
Create a testsuite to cover the three primitives' of SAL

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#16]
# Description
Need to create testcases to cover SAL three primitives: VM, GW, and Zero-db.

# Goal
- Test cases to cover VM
- Test cases to cover GW
- Test cases to cover ZD

# Stakeholders
Dina Magdy

**Comment by despiegk** [comment]
why  the code there?
which repo does this belong too?
cirical for more than 11 days??? critical means, resolve today.

**Comment by despiegk** [comment]
code is in old repo?
can we put it in right repo please

**Comment by ramezsaeed** [comment]
code is here now:
https://github.com/threefoldtech/jumpscale_lib/tree/sal_testcases/tests/integration_tests/testcases

**Comment by Dinaamagdy** [comment]
We covered sal-primitives for : 
- Gateway
- Vms
- Zdbs 
and can find code of testcases here 
https://github.com/threefoldtech/jumpscale_lib/tree/sal_testcases

**Comment by ramezsaeed** [comment]
Test cases on travis:
https://travis-ci.org/threefoldtech/jumpscale_lib
