### ISSUE TITLE
digitalme on zos

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#160]
-  create j.builders.apps.digitalme
- follow /sandbox/code/github/threefoldtech/jumpscaleX/docs/Internals/Builders.md

**Comment by rkhamis** [comment]
Already finished. @Dina-Abd-Elrahman please close when verified

**Comment by Dina-Abd-Elrahman** [comment]
- I got an error when trying to use DigitalMe build method https://github.com/threefoldtech/jumpscaleX/issues/335

**Comment by Dina-Abd-Elrahman** [comment]
- the error still exists when trying to use build method

**Comment by Dina-Abd-Elrahman** [comment]
estimate time ```3 hours```

**Comment by Dina-Abd-Elrahman** [comment]
error while trying to build digital me sandbox 

![error](https://user-images.githubusercontent.com/21218053/56301343-ea174580-6137-11e9-8131-aa23671d5457.png)

**Comment by Dina-Abd-Elrahman** [comment]
still have the same problem. @ranatrk

**Comment by Dina-Abd-Elrahman** [comment]
- after the last fix i got another error

![error](https://user-images.githubusercontent.com/21218053/56468743-d79b5580-6430-11e9-90d3-8fec04e0d082.png)

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/907703ec25262345592b39e2ac021e24f8fe9d7f
https://github.com/threefoldtech/jumpscaleX/commit/7a09eca63894bbd38bf45ca810e9b5cb478a43d1

**Comment by Dina-Abd-Elrahman** [comment]
### Verification steps:
- create  ```zhubclient```

```
iyo = j.clients.itsyouonline.get("",baseurl="https://itsyou.online/api",application_id="",secret="")  
token = iyo.jwt_get().jwt
zhub_client = j.clients.zhub.get("hub_instance",token_=token,username="") 
zhub_client.authenticate()```

- create digitalme flist 

```
j.builder.apps.digitalme.sandbox(reset=True, zhub_client=zhub_client, flist_create=True) 
```

- merge the flist with jsx base flist.

**Comment by Dina-Abd-Elrahman** [comment]
- create a container with new merged flist (using zos)

- test if openresty , lua , python is running in this container.
