### ISSUE TITLE
gdrive gateway for 3bot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#165]
The idea here is to be able to link from google docs into our wiki/websites/FFP easily

requires https://github.com/threefoldtech/jumpscaleX/issues/12

We'll do this by exposing these endpoints:
 - [x] http://$IPADDR/gdrive/slide/$gpresentation_guid/$gslide_slide_guid.png
 - [x] http://$IPADDR/gdrive/slide/$gpresentation_guid/$slidename.png
 - [x] http://$IPADDR/gdrive/doc/$gdoc_guid.pdf
 - [ ] http://$IPADDR/gdrive/spreadsheet/$sheet_guid.pdf 
 - [ ]  http://$IPADDR/gdrive/doc/$gdoc_guid.md

More information is on the breakdown of the tasks below.

this story card tracks the progress on:
 - parent of threefoldtech/digitalmeX#45
 - parent of threefoldtech/digitalmeX#46
 - parent of threefoldtech/digitalmeX#47
 - parent of threefoldtech/digitalmeX#48

Child of #162

**Comment by rkhamis** [comment]
Estimation: 4 working days + 3 working days for QA

**Comment by AhmedHanafy725** [comment]
I will start today

**Comment by AhmedHanafy725** [comment]
test for png and pdf is made

**Comment by xmonader** [comment]
Gdrive client is refactored and supports the export to PDF functionality

**Comment by xmonader** [comment]
we have gdrive actor that supports exporting doc to pdf and it needs some changes to support slides (prioritizing these tasks of the story)

**Comment by xmonader** [comment]
pattern for slides should be `presentation_guid/slide_guid.png` 

using slides names/titles while not being unique doesn't sound right.

**Comment by rkhamis** [comment]
Let's leave it as an option. First hit in the presentation will be the slide chosen.

**Comment by andrewayoub** [comment]
but we can either store the slides with the slide title or the guid we should choose only one approach

**Comment by rkhamis** [comment]
@andrewayoub can we add the name to the metadata and find from there? or if the slide has a name it can be part of the stored path

for instance `<presentation.id>/<slide.id>.<name>.png`?

**Comment by andrewayoub** [comment]
now I'm generating a file called presentation.meta stored beside the slides which can be used to get a slide guid from it's title and I added get_presentation_meta to gdrive client to return this file a python dict, and I updated the actor to use it and it's working

**Comment by AhmedHanafy725** [comment]
Tests has been added here [test_location](https://github.com/threefoldtech/digitalmeX/tree/development/packages/gdrive/tests)

**Comment by xmonader** [comment]
please export sheets to pdf

**Comment by andrewayoub** [comment]
Will work on converting sheets to pdf now

**Comment by rkhamis** [comment]
Moved issues of current sprint there. Please add docs and put on verification @andrewayoub @xmonader

**Comment by AhmedHanafy725** [comment]
setUp method in tests need to be refactored by using open publish.
Waiting for doc for open publish and how to use it with this actor.

**Comment by andrewayoub** [comment]
docs exists in open publish

**Comment by AhmedHanafy725** [comment]
Tests has been moved to https://github.com/threefoldtech/digitalmeX/tree/development/tests/gdrive

**Comment by AhmedHanafy725** [comment]
**Verified on**
jumpscaleX: https://github.com/threefoldtech/jumpscaleX/commit/060ed8f93c3d28ea2a9bc256d03b9cc359640bf1
digiralmeX: https://github.com/threefoldtech/digitalmeX/commit/7d1915d982385320e7c1e88ccf78722e02d4cad0
