### ISSUE TITLE
OpenWiki FrontEnd Improvements

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#166]
Child of #162 

Is our wiki system done with docsify.
Need some new plugins into the docsify

This storycard is a placeholder to track progress on the following
 - parent of threefoldtech/digitalmeX#49
 - parent of threefoldtech/digitalmeX#50
 - parent of threefoldtech/digitalmeX#51
 - parent of threefoldtech/digitalmeX#52
 - parent of threefoldtech/digitalmeX#53

**Comment by rkhamis** [comment]
Estimation: 3 working days + 4 days for QA

**Comment by abom** [comment]
Only https://github.com/threefoldtech/digitalmeX/issues/53 still open, @andrewayoub  will continue start working on it soon.

**Comment by abom** [comment]
Now https://github.com/threefoldtech/digitalmeX/issues/53 is still in verification.

**Comment by Dinaamagdy** [comment]
## Status 
- Issues #49 #50 #51 #52 verified 
- issue threefoldtech/digitalmeX#53 doesn't work yet 
- there is problem in loading mages without domain 
-  create  testcases for wikis macros

**Comment by Dinaamagdy** [comment]
all issues verified and docs here
https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform
