### ISSUE TITLE
SMTP forwarder

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#167]
child of #162 

Email server which accepts all our configured domains (wildcard) and forwards to other domain e.g. incubaid.com.

This allows us not having to create all aliases on google domain which is a pain.

So e.g. kristof@openwiki.com would automatically get to kristof@incubaid.com

In python there are quite some libraries doing SMTP, let's put in gevent loop and use nginx as the proxy (forwarded).

**Comment by ahussein** [comment]
I was looking into [lamson](https://github.com/zedshaw/lamson)
I think its better to just implement a simpler application to do the forwarding using the standard library instead (doing this now)

**Comment by ahussein** [comment]
PR is open [here](https://github.com/threefoldtech/jumpscaleX/pull/448) 
Still working on documentation
