### ISSUE TITLE
Create documentation for containerized application on virtual 0-OS

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#168]
The idea is we choose a fun application we would like to run on the grid. 
And document the full flow how to deploy it on a virtual 0-OS reserved using the tfchain client.

Please explain what you choose so we don't work on the same kind of app.
- [x] @xmonader  : 
  - [x] pastebin server
- [x] @zaibon :
  - [x] [PeerTube](https://github.com/Chocobozzz/PeerTube) instance
- [x] @GlenDC :
  - [x] Quake 3 Server
- [x] @maxux:
  - [x] Icecast2 server
- [ ] @muhamadazmy :
- [x] @DylanVerstraete :
  - [x] Ethereum full node
- [x] @LeeSmet : 
  - [x] minecraft server

You can create PR for your documentation to this repo : https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation

**Comment by DylanVerstraete** [comment]
I will deploy an Ethereum full node

**Comment by maxux** [comment]
I'll deploy multiple things, but first one will be an icecast server (audio streaming) :)

**Comment by muhamadazmy** [comment]
What about we redo this https://www.cryptokitties.co/

**Comment by xmonader** [comment]
I'll start with deploying a pastebin server

**Comment by GlenDC** [comment]
I was able to deploy a quake3 game server on the grid with the help of @zaibon. Documented example has been created and opened a PR for it https://github.com/threefoldfoundation/info_grid/pull/83.
