### ISSUE TITLE
Capacity website: Add freeflow page for each farmer when he creates his farm

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/home#169]
Auto create a freeflow page when a farmer sets up his farm or ask to add freeflow page url if freeflowpage already exists

**Comment by weynandkuijpers** [comment]
Need to record the freeflowpages in the JSON structure: Can we add a parameter:

  {
    "farmer_id": "threefoldfarmer", 
    "location": {
      "city": "Hulshout", 
      "continent": "Europe", 
      "country": "Belgium", 
      "latitude": 51.060386316691016, 
     "longitude": 4.82351303100586,
      **"freeflowpage":"https://freeflowpages.com/s/green-edge-cloud/"** 
   }, 
    "node_id": "ecf4bbd9ea2c", 
    "os_version": "master 584ba6fe3b2891eb62c233f0c606315c97595ff9", 
    "parameters": [
      "support"
    ], 
    "reserved_resources": {
      "cru": 0.0, 
      "hru": 0.0, 
      "mru": 0.0, 
      "sru": 0.0
    }, 
    "robot_address": "http://10.102.18.17:6600", 
    "total_resources": {
      "cru": 40.0, 
      "hru": 61477.23, 
      "mru": 251.91, 
      "sru": 9313.5
    }, 
    "updated": "Mon, 15 Apr 2019 15:20:59 GMT", 
    "uptime": 2695868, 
    "used_resources": {
      "cru": 20.23, 
      "hru": 0.0, 
      "mru": 3.01, 
      "sru": 0.0
    }
  }

**Comment by zaibon** [comment]
Can we have a bit of history of why this is required ?

**Comment by jdelrue** [comment]
@andhartl is this still needed? Can you provide info requested by @zaibon ?

**Comment by andhartl** [comment]
would give the farmer the option to create. not auto as this will create a lot of empty ff pages
