### ISSUE TITLE
scripts for basic performance tests v1.0

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#17]
# Description
Performance testing on ZOS 

# Goal
Test should:
    - Deploy 100 S3 services
    - that results in 100 gateways + 100 vms running S3
They make use of the ZDB's that are available on all physical nodes in the dc.
Test upload & download speed & verify that files uploaded & downloaded are binary correct

# Stakeholders
John Kheir

**Comment by ramezsaeed** [comment]
https://github.com/zero-os/autotests/tree/master/bancadati_performance_testing/scripts

**Comment by ramezsaeed** [comment]
https://docs.grid.tf/threefold/proj_bancadati/src/branch/master/testing/performance_stability/scripts

**Comment by john-kheir** [comment]
@fastgeert already did this test on 88 minios and here are the results https://docs.google.com/spreadsheets/d/1nrdcLKxllt-WBLGoI8UOxRTTl40rTy1vjt2OJOpJA-Y/edit#gid=1656237392 .. But we still need to do it on 100 minios .. for this we need to be running upload and download script from more than one machine and Geert want it to be done through the webgateway  .. he is asking Riaan from where we can do that ? .. Also @fastgeert please let us know here if u want the deployment through 3bot or it is not mandatory?
