### ISSUE TITLE
Verify threefold nodes kernel upgrade

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#172]
The threefold chain nodes are running a kernel which is now 1.5 years old. Upgrading from this version might cause issues (i.e. data loss), which we definitely need to avoid. To see what steps are needed to take eventually, we can simulate the upgrade in a vm.

Steps:
- Create a vm with the specific zero os version run by the threefold nodes
- Create a container in the vm, preferably a tfchain to be as close to reality as possible
- After the container has been run for a while, kill the os, and start it again using a new kernel version
- Ensure the container is started again (should happen automatically with zrobot), and ensure its data is still intact.

If the above fails, find out where the container data went and how we can recover it, document and possibly script this in case we want to upgrade the tfchain nodes

**Comment by zaibon** [comment]
> Create a container in the vm, preferably a tfchain to be as close to reality as possible

definitely need to be the exact same workload as what you have in prod.
