### ISSUE TITLE
scripts for ZOS stability auto tests

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#18]
# Description
- test on Bancadati nodes
- only stability test for the ZOS nodes, not performance testing

# Goal
### Default setup within one zeroos:
![zeroos](https://user-images.githubusercontent.com/15011431/44149018-d63b3638-a09a-11e8-8761-c9056858de8b.png)

- We will be having some vms or containers running apps (need to be determined). Those apps will be loaded from different machines in which certain number of users will do certain requests against these apps with certain frequency (locust can be used here to load these apps)
- Also I think we can make apps on different containers (or vms) talk to each other and measure how responsive they are.

- During running the test for a long time.. we will  monitor the system and collect the data for analysis and check for failures if exist:
#### Application measurements:
 - Average, min and max response times. 
 - Total request per second.
 - Number of failed requests.
 

#### ZERO-OS measurements: 
  This can be done using rtinfo .. we can measure memory and cpu usage, average load, disks iops and speed..etc 

### Questions:
- How many zeroos node is needed? how many vm or container that need to be up and running?
  and how many 0-db?
- What is the kind of applications that need to be running on the vms or containers?
- We have components like gateways, 0-db, vms, ..etc .. so what kind of Design is needed (near to what is provided in the figure?)
- I'm giving a very general default setup.. so What else need to be tested? Any disk tests (using fio)  other than locust loads?
 

# Stakeholders
John Kheir

**Comment by ramezsaeed** [comment]
https://docs.grid.tf/threefold/proj_bancadati/src/branch/master/testing/performance_stability/scripts

**Comment by john-kheir** [comment]
Script is done but not tested on 100 minios
