### ISSUE TITLE
Predictable Network Interface Names on flist 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/home#19]
### Steps:
 Create VM on ZOS using 0-core Client:
```
name = 'ahmed'
flist = 'https://hub.grid.tf/tf-bootable/ubuntu:latest.flist'
nics = [{'type': 'default'}]
port = {24:22}
config = {'/root/.ssh/authorized_keys': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDrxj7aUpIFrrmMoKqf07z0k6GY5mt/42ND8cBU1h1PED2L3pZAEWaViQPhHsP77XKQo2W9+TD4BIai65m9Ib4jZy5zbCSIDMlL9ukRaWKuC4QcFl2+Ge2nH1imrn9ZYy2pPMwNvES17Fo9xZIWI8R5KFyZpAsrL5Je1AWFi3aTbtHqPwAKDzyiyqekh8yyMehmRsi3wm17F6M0PJ4r5mlfkCycIMRR3W62UoQM2eQjYKVa1gqN3ZeLrRClmBrF7mIXOzJywdX1tfh+ayZ36F2fFUcm6G8X/xpfQpFbEDds/ohcwvMbYR6JYxC/Ugn4KSeTXk4534wAVtS9xpXDX9oR ahmed@ahmed-HP-ProBook-450-G1'}
mount = [{'source': '/ahmed', 'target': 'share', 'readonly': False}]
client.kvm.create(name=name, flist=flist, nics=nics, port=port, config=config, mount=mount)
```
### Issue:
The VM created with default network but I couldn't access the VM using (ssh).

#### Predictable Network Interface Names 
when I used 'mount', it added new PCI interface and took name (ensX) which result in the default network interface name changed.
If I don't use mount, I can access it using (ssh).

#### To solve:
This problem should be handled on flist of Ubuntu 16.04 and higher versions or disable it and go back to unpredictable kernel-native (ethX) naming.

**Comment by despiegk** [comment]
don't understand issue, is it really an issue, and if yes, should not be here but on a component repo.

**Comment by AhmedHanafy725** [comment]
I edited the issue

**Comment by AhmedHanafy725** [comment]
moved to https://github.com/threefoldtech/jumpscale_prefab/issues/31
