### ISSUE TITLE
S3 server Redundancy Features

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#21]
parent of threefoldtech/minio#15
parent of threefoldtech/minio#12
parent of threefoldtech/0-templates#148
parent of threefoldtech/0-templates#149
parent of threefoldtech/0-templates#152
parent of threefoldtech/0-templates#153
parent of threefoldtech/0-templates#154
parent of threefoldtech/0-templates#155
parent of https://github.com/threefoldtech/minio/issues/16

**Comment by zaibon** [comment]
I will write a document explaining how redundancy will work, and then create the issue for it and link them here.

**Comment by zaibon** [comment]
Created issues regarding redundancy features and updated the first post to link them
