### ISSUE TITLE
all in 1 testsuite for all archive features on top of ZOS

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#22]
See Trello issue [here](https://trello.com/c/5DAbSMfo/42-all-in-1-functionality-testsuite-for-all-features-of-the-archive-solution)

**Comment by 0xIslamTaha** [comment]
https://github.com/threefoldtech/minio/tree/failures_testsuite/test/failures_testsuite

here are the covered scenarios:

```
        - upload 2M
        - Stop n zdb, n <= parity
        - Downlaod 10M file, should succeed
        - assert md5 checksum is matching
        - Start n zdb
```

        """
        - Stop n zdb, n <= parity
        - upload file, should pass
        - download file, should pass
        - assert md5 checksum is matching
        - start n zdb, should pass
        """

        """
        - Stop n zdb, n <= parity
        - upload file, should pass
        - start n zdb, should pass
        - download file, should pass
        - assert md5 checksum is matching
        """

        """
        - Stop n+ zdb, n = parity, should succeed
        - Upload file, should fail
        - Start n+ zdb
        """

**Comment by 0xIslamTaha** [comment]
Didnt work on it 6 days ago as we can't deploy a minio on banchadati cause of nw issue

**Comment by 0xIslamTaha** [comment]
As our setup now has only one tlog all the metadata scenarios will be deployed later on
```
except this spec is written so it still corrects the day we decide we will deploy 2 tlog namespace or more
```

**Comment by zaibon** [comment]
> As our setup now has only one tlog all the metadata scenarios will be deployed later on

Why ? the fact that we only have one tlog doesn't mean we don't have to test the self-healing of the metadata.

**Comment by zaibon** [comment]
> As our setup now has only one tlog all the metadata scenarios will be deployed later on

Why ? the fact that we only have one tlog doesn't mean we don't have to test the self-healing of the metadata. Also, I don't see any relation between what you say, and the quote underneath, can you explain

**Comment by 0xIslamTaha** [comment]
I misunderstood it, so for the record, Our setup has only one tlog and we need to kill it and test the self-healing is working well. 

I'm gonna implement this scenario

**Comment by rkhamis** [comment]
@islam, please map these tests to the above description, make a checklist of the tests that still need to be done. This is a nice progress, but doesn't really show how much work is still left to be done.

**Comment by 0xIslamTaha** [comment]
# 0-db level:
## data 0-db temporary unavailable
```
    def test001_upload_stop_parity_zdb_download(self):
        """
        - upload 2M, should succeed.
        - Download file, should succeed
        - Deleted the downloaded file
        - assert md5 checksum is matching
        - Stop n zdb, n <= parity
        - Download file, should succeed
        - assert md5 checksum is matching
        - Start n zdb
        """

    def test002_stop_parity_zdb_upload_download_start(self):
        """
        - Stop n zdb, n <= parity
        - upload file, should pass
        - download file, should pass
        - assert md5 checksum is matching
        - start n zdb, should pass
        """

    def test003_stop_parity_zdb_upload_start_download(self):
        """
        - Stop n zdb, n <= parity
        - upload file, should pass
        - start n zdb, should pass
        - download file, should pass
        - assert md5 checksum is matching
        """

    def test004_stop_greater_parity_zdb_upload(self):
        """
        - Upload file, should succeed
        - Stop n+ zdb, n = parity, should succeed
        - Upload file, should fail
        - Download the uploaded file, should succeed
        - Start n+ zdb
        """
```

## Metadata 0-db temporary unavailable
```
    def test001_upload_stop_tlog_start_download(self):
        """
         - Upload file
         - stop tlog
         - Try to download, should fail
         - Start tlog
         - Download file, should succeed
        """

    def test002_stop_tlog_upload_download(self):
        """
         - Stop tlog
         - Upload file, should fail
         - Start tlog
         - Download file, should succeed
        """

```

**Comment by 0xIslamTaha** [comment]
# Metadata 0-db dies forever
```
    @skip('https://github.com/threefoldtech/0-templates/issues/186')
    def test005_upload_tlog_die_forever_download(self):
        """

        test005_upload_tlog_die_forever_download
         - Upload file
         - Make tlog die forever
         - Wait for 60 sec.
         - Download file, should succeed
        """


    @skip('https://github.com/threefoldtech/0-templates/issues/186')
    def test006_tlog_die_forever_upload_download(self):
        """

         - Make tlog die forever
         - Wait for 60 sec.
         - Upload file, should succeed
         - Download file, should succeed
        """

```

**Comment by 0xIslamTaha** [comment]
Our test cases now in the development branch
