### ISSUE TITLE
3bot capacity planner

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#24]
- Reserve any primitive through the 3bot
- Find/filter nodes through 3bot
- overview of farm 
- Flist of deployable 3bot

Parent of #25 
parent of threefoldtech/digital_me#43
parent of threefoldtech/jumpscale_lib#156
parent of threefoldtech/digital_me#49
parent of threefoldtech/digital_me#48
parent of threefoldtech/digital_me#47
parent of threefoldtech/digital_me#45
parent of threefoldtech/digital_me#46

**Comment by zaibon** [comment]
most of this is done. The rest will be reworded in another story to match the proper design of 100% distributed 3bots
