### ISSUE TITLE
Live grid

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#25]
- Deployed webgateway (@delandtj , @BolaNasr )
- 3bot to add/delete domains and reverse proxies ( ?)
- Grid networks in place

Parent of threefoldtech/digital_me#18
Parent of threefoldtech/digital_me#40
Parent of threefoldtech/jumpscale_lib#184

**Comment by rkhamis** [comment]
@zaibon please define grid networks

**Comment by zaibon** [comment]
> @zaibon please define grid networks

documentation about grid networks is there: https://github.com/threefoldtech/home/blob/master/docs/threefold_grid/networks.md

**Comment by rkhamis** [comment]
This storycard is no longer relevant
