### ISSUE TITLE
Archive Data Tests

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#28]
- Data Integrity test:
   Tamper with some of the data blocks written in the ZDB by overwriting them with a bad value.
Force the bitrot protection to run.
Then check if the tempered block was repaired with a valid value. Then download the file after stopping all parity shards and binary compare the file with the one that was uploaded originally.

- Bitrot protection Test:
 Tamper with some of the data blocks written in the ZDB by overwriting them with a bad value.
Force the bitrot protection to run.
Then check if the tempered block was repaired with a valid value. Then download the file after stopping all parity shards and binary compare the file with the one that was uploaded originally.

Child of #23 
Depends on threefoldtech/minio#15

**Comment by john-kheir** [comment]
bitrot testcase: https://github.com/threefoldtech/minio/blob/failures_testsuite/test/failures_testsuite/testcases.py#L98
Data Integrity test: https://docs.grid.tf/threefold/proj_bancadati/src/branch/master/testing/performance_stability/scripts

**Comment by ramezsaeed** [comment]
blocked on this task to be merged
https://github.com/threefoldtech/minio/issues/15

**Comment by rkhamis** [comment]
Since threefoltech/minio#15 is closed, this no longer needs to be blocked.
@ramezsaeed @john-kheir I'll put this back to backlog until you're ready to close it

**Comment by john-kheir** [comment]
this test is done .. please check it here: https://github.com/threefoldtech/minio/blob/master/test/failures_testsuite/testcases/s3/test05_bitrot.py#L38

**Comment by rkhamis** [comment]
@john-kheir please link to results as well
