### ISSUE TITLE
Self-healing Tests

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#29]
Child of #23 
child or #21 

Test | Expected result | Requires | Finished
-- | -- | -- | -- 
 Kill a node robot process | Node robot process gets restarted | requires threefoldtech/demo#2 | <ul><li>[ ✔ ]</li></ul>
Kill a ZDB process | ZDB process gets restarted | requires threefoldtech/demo#3 |  <ul><li>[ ✔ ]</li></ul>
Simulate a hdd failure | All deployed shards on this hdd are reassigned to other hdd’s and the new shards get filled by the erasure coding healing process. Even with no parity shards running we can still download files that existed on the shard, and they are still binary exact copies of the originally uploaded files.| requires threefoldtech/0-templates#152 and requires threefoldtech/demo#4 |  <ul><li>[ ✔ ] </li></ul>
Simulate an ssd failure with a vdisk namespace of the active Minio VM | The reverse proxy stops serving requests to the broken minio VM and starts forwarding requests to the passive minio VM which then becomes the active minio VM. A new minio VM gets deployed, and metadata gets rebuild from the tlog and starts acting as the passive minio VM.| requires threefoldtech/home#21 and requires threefoldtech/demo#4 |  <ul><li>[ ✔ ] </li></ul>
Simulate an ssd failure with a vdisk namespace of the passive Minio VM | A new minio VM gets deployed, and metadata gets rebuild from the tlog and starts acting as the passive minio VM.  | requires threefoldtech/home#21 and requires threefoldtech/demo#4  |  <ul><li>[ ✔ ] </li></ul>
Simulate an ssd failure with the active meta data tlog namespace | The reverse proxy stops serving requests to the broken minio VM and starts forwarding requests to the passive minio VM which then becomes the active minio VM. A new ssd namespace is reserved and the tlog gets populated from the tlog of the new active minio vm | requires threefoldtech/home#21 and requires threefoldtech/demo#4  |  <ul><li> [ ✔ ] </li></ul>
Simulate an ssd failure with the passive meta data tlog namespace | A new ssd namespace is reserved and the tlog gets populated from the tlog of the new active minio vm | requires threefoldtech/home#21 and requires threefoldtech/demo#4  |  <ul><li>[ ✔ ] </li></ul>
Kill the minio process | It gets restarted automatically |   |  <ul><li>[ ✔ ] </li></ul>
Kill the active minio vm | The reverse proxy stops serving requests to the broken minio VM and starts forwarding requests to the passive minio VM which then becomes the active minio VM. The killed VM is started and starts acting as the passive minio VM | requires threefoldtech/home#21 and requires threefoldtech/demo#5  |  <ul><li>[ ✔ ] </li></ul>
Kill the passive minio vm | The killed VM is started and starts acting as the passive minio VM | requires threefoldtech/demo#5  |  <ul><li>[ ✔ ] </li></ul>
Reboot a node with data shards | After the node comes back, all impacted S3 appliances start healing their stored erasure coded data. | requires threefoldtech/home#21  |  <ul><li>[ ✔ ] </li></ul>

**Comment by Dinaamagdy** [comment]
```
https://github.com/threefoldtech/demo/issues/2 : 
````
https://github.com/threefoldtech/minio/blob/zrobot_restart/test/failures_testsuite/testcases.py#L212

```
https://github.com/threefoldtech/demo/issues/3:
````
https://github.com/threefoldtech/minio/blob/zrobot_restart/test/failures_testsuite/testcases.py#L204

**Comment by john-kheir** [comment]
Kill the active and passive minios vms are done, but I'm not sure yet how to ```wait till passive minio configuration is updated```  and till  ```passive minio vm is created```  .. so will wait till this feature is implemented

**Comment by john-kheir** [comment]
Also simulating ssd failure for a vdisk of a (active/passive) minios vm is done.. but same stuff related to ```Kill the active and passive minios vms``` are not implemented yet as in the above comment.. Also we have this issue that need to be fixed before running this test https://github.com/threefoldtech/0-core/issues/72

**Comment by john-kheir** [comment]
1- kill the active and passive minios are done ..  the expected behaviour is that the vms will restart 
2- For the ssd failures for the vdisks and tlogs (finished partially): we are blocked on this https://github.com/threefoldtech/minio/issues/49
3- @dinaamagdy please update us on ```Simulate a hdd failure``` and ```Reboot a node with data shards```

**Comment by 0xIslamTaha** [comment]
we need to create test cases to cover this flow chart

![image](https://user-images.githubusercontent.com/17981089/48772353-d1138100-eccc-11e8-83aa-2f712c1746b3.png)

**Comment by Dinaamagdy** [comment]
reboot node with data shards selfhealinf doesn't work  
https://github.com/threefoldtech/0-templates/issues/239

**Comment by ramezsaeed** [comment]
All done
