### ISSUE TITLE
Ethereum erc-20 tft tokens and bridge: Research

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#31]
[ERC-20](https://theethereum.wiki/w/index.php/ERC20_Token_Standard) is a technical standard used for smart contracts on the Ethereum blockchain for implementing tokens.

# General idea
A lot of the bigger exchanges support erc20 tokens but it would require some  effort to support tftokens directly. By creating an erc20 token to represent tft, these exchanges can support an and transfer tft  amongst each other without any effort. 
We propose to be able to send tft to an ethereum address, the bridge would create the tfterc20's and add them to the target ethereum address. Maybe multisign is required to  secure this. 
The reverse depends if we can encode a tft adress in an eth adress, if not, a receiving adress needs to be published on the tft chain first. A user can withdraw from an exchange to an eth adress generated by a tft wallet and a blockcreator node would include the coin creation transaction to a block. Every full node can run a validator to only accept valid eth to tft transactions.
This would allow user to easily convert tft to tft erc20 and back, making the process to transfer tft to an exchange that supports tfterc20  and back almost seamless.

**Comment by robvanmieghem** [comment]
related issues:
- [ ] [Investigate how to monitor erc20 tokens for a erc20](bridgehttps://github.com/threefoldtech/rivine/issues/458)

**Comment by LeeSmet** [comment]
![img_20181116_115333](https://user-images.githubusercontent.com/22023708/48617721-84ac0680-e997-11e8-8449-5339bb28f125.jpg)

**Comment by sabrinasadik** [comment]
We haven’t approached any exchanges yet, we are planning on doing some initial communication this month. Some of our exchange relationships will take 2/3weeks and others 1 month for listing. Before we list we need to clean up on our docs wiki, token accounting, web content and so on ...just to make sure we are ready for traffic.
