### ISSUE TITLE
Research Tarantool for Rivine

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/home#320]
Currently we are using BoltDB for Rivine, we might want to switch to Tarantool.

**Comment by LeeSmet** [comment]
@DylanVerstraete please add your findings, e.g. can we indeed embed it in our chain like we can with BoltDB, are there ACID transactions, (No)SQL, etc...

**Comment by DylanVerstraete** [comment]
Findings:

* Tarantool cannot be embedded into Rivine binary, its a seperate server which you can use Docker for.
* You must create `spaces` upfront by executing Lua based statements.
* You must create `indexes` on `spaces` upfront by executing Lua based statements. Indexes are required in order to store data, so you must know upfront how each record is going to look like..
* Credentials need to be provided for connecting to Tarantool

**Comment by DylanVerstraete** [comment]
Encountered following issue:

https://github.com/tarantool/tarantool/issues/4196

**Comment by DylanVerstraete** [comment]
Blocked by: https://github.com/tarantool/go-tarantool/issues/80

For parsing data returned from the `go-client`.
