### ISSUE TITLE
investigate UX of Rivine multi-sig

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#324]
- [ ] See if our current recipient approach (where one targets a MultiSig address) is the most UX approach we can take. It would be for example a lot easier if a user could target a single address;
- [ ] Lay out a plan for a quick&dirty Desktop Wallet App, so we at least have one GUI wallet that supports all features that we offer (e.g. MultiSig);

**Comment by GlenDC** [comment]
> See if our current recipient approach (where one targets a MultiSig address) is the most UX approach we can take. It would be for example a lot easier if a user could target a single address;

I think a more sane approach (also following what chains like bitcoin and ethereum have been doing for a longer time already), would be to turn Multisig wallets into a "smart contract":

- Has to be deployed only once;
- Contains the information of the owners and the amount of owners that have to sign;
- The actual address would be the same, and could be used as a regular address;
- When tokens are transferred to a MultiSig wallet they are actually transferred to this contract;
- The spending of these tokens happens very similar (work done offline);
- Light wallets could still look up what wallet they are attached as the explorer can still easily index it this way;

(*) Need to look into how a Nonce is important here as a protection against replay-attacks;
(**) Need to look if this would be possible to integrate in an existing Rivine-based ecosystem, without breaking everything;

**Comment by DylanVerstraete** [comment]
In progress at: https://github.com/threefoldfoundation/tfchain-wallet-electron
