### ISSUE TITLE
core-x 2.0

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#327]
# CoreX 1.0.0

0-OS container process manager. 

Projects : https://github.com/orgs/threefoldtech/projects/32

Is the tmux code from Maxim which gets renamed to core-x.

## Deliverables

- make sure we have builder which creates flist
- tests implemented in python which demonstrate scalability, performance, reliability, functionality

## definitions

- session = a process running in the process manager

## manager requirements

- can start any process in a session
- can read std error/out
- logging for last X lines per session
- kill session
- check if process is active in the session
- upto 256 sessions
- each process started has unique pid = process id
- allow access over https over web (remote console access over web) (is optional parameter when starting process)
- < 20Mb mem overhead
- < 100kb mem overhead per session

## RPC at python client (implemented in JSX)

- session_start(...)
- session_kill(pid)
- session_info(pid)             #return basic info e.g. CPU info, meminfo...
- session_read(pid,nrlines)
- session_children_get(pid)     #which pid's are children

- sessions_list()               #return all pids

- web_access_allow(pid)         #only works for pid's which are top in a session
- manager_info()                #generic information from the process manager e.g. total CPU used, ...

**Comment by maxux** [comment]
Current version of https://github.com/threefoldtech/corex

- [x] Can start any process in a session
- [x] Can read std error/out
- [x] Logging for last X lines per session
- [x] Kill session
- [x] Check if process is active in the session
- [x] Up to 256 sessions: there is actually no limits
- [x] Each process started has unique pid = process id
- [x] Allow access over https over web (remote console access over web) (is optional parameter when starting process)
- [x] < 20Mb mem overhead: idle at 1.97 MB
- [ ] < 100kb mem overhead per session
