### ISSUE TITLE
TFGrid: ability to inform a 3bot about the life state of primitive which came life

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#358]

**Comment by zaibon** [comment]
For this to be possible, we fist need to know what do we mean by `3bot` here.
What is going to be the interface we need to use to "talk" to the 3bot ?

**Comment by despiegk** [comment]
this will happen by means informing the BCDB.
so e.g. the ZOS brings something life and the the updates BCDB object gets registered on the BCDB blockchain.

there will be subscription possibilities on BCDB

will need JSX 10.0.2
