### ISSUE TITLE
Tfchain testnet faucet 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#36]
A web page  where people can just  request some tfchain testnet tokens

**Comment by GlenDC** [comment]
Minimalistic web server, that hooks to a local unlock (Go tfchain) daemon, is implemented in PR https://github.com/threefoldfoundation/tfchain/pull/207.

Next: prepare the tooling to being able to deploy it and hook it up to our testnet block creators, and have them as links available. Not sure if we want seperate subdomains, or if we just add it as `/faucet`.

**Comment by LeeSmet** [comment]
I think its best to deploy this on something like a `faucet.testnet.threefoldtoken.com` domain so we don't have to modify the current explorer scripts.

**Comment by sabrinasadik** [comment]
To Do: 
- Create a deployment template: 4h
- Create Flist: 2h
- Deploy node: 2h

**Comment by LeeSmet** [comment]
Flist with  a faucet + caddy binary: https://hub.grid.tf/tfchain/caddy-faucet.flist.md

**Comment by LeeSmet** [comment]
Initial template: https://github.com/threefoldfoundation/tfchain-templates/tree/master/faucet

Meanwhile a mac address has been added to the `dhcp` , and the `faucet.testnet.threefoldtoken.com` dns record has been added and points to the correct IP

**Comment by LeeSmet** [comment]
Deployment (and verification of the template) blocked on https://github.com/threefoldtech/0-core/issues/84

**Comment by LeeSmet** [comment]
After a node reboot, the service is now running. However, while the container indeed has the correct mac address (as was the case in the initial deployment attempt), it does not get the assigned ipv4 address from the dhcp server for some reason

**Comment by LeeSmet** [comment]
Blocking issue: https://github.com/threefoldfoundation/tfchain/issues/216

**Comment by LeeSmet** [comment]
Faucet running on faucet.testnet.threefoldtoken.com

For now this is funded with 900TFT,  will add more once everyone is happy with the current setup

**Comment by GlenDC** [comment]
@LeeSmet are all the required Makefile/scripts also checked into the repo? so others can build the flists and deploy?

**Comment by GlenDC** [comment]
I just tested it, using one of my testnet wallets, and all seem to work fine :) Will already add documentation about it on the main README. Can you please make sure it is funded with plenty of tokens tomorrow morning first thing?

**Comment by GlenDC** [comment]
Still to do:

* [ ] fund 300k TFT into that wallet (time: 5 minutes)
* [ ] enable https on the faucet and make it the default (time: 3h)

**Comment by LeeSmet** [comment]
- [ ] Debug ipv6 connection issues (which cause caddy to fail to start)

**Comment by LeeSmet** [comment]
>@LeeSmet are all the required Makefile/scripts also checked into the repo? so others can build the flists and deploy?

Makefile targets have been added in the tfchain repo to build the faucet and create/upload an flist for it

> Ah by the way unrelated @LeeSmet, but could you also please deploy the web explorers of testnet again? My last fixes from last week are not yet deployed, making some pages fail due to an error.

Done

300.3K TFT have been funded to the faucet, but I removed the old one and created a new one while I was messing with the https (and trying to figure out why it would not work). Turns out caddy couldn't start due to a bad router advertisement setup, causing ipv6 connections to letsencrypt to have issues when pulling the certs.

As a result of installing a new faucet, it will take an hour or 2 before it is completely synced and realizes it has the funds
