### ISSUE TITLE
TFGrid: security on deployment of vzos

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#360]
the redis backend for commands needs secret

**Comment by zaibon** [comment]
Now that we can use the notary BCDB to put more information about the reservation we can add a password to the [VZOS reservation schema](https://github.com/threefoldtech/jumpscaleX/blob/master/Jumpscale/clients/blockchain/tfchain/schemas/reservation_vm.schema) Using this new info the grid broker can set the password [when creating the VM](https://github.com/threefoldtech/grid_broker/blob/master/templates/reservation/reservation.py#L76)

**Comment by serboctor** [comment]
@robvanmieghem you're talking about the zos client, right?

I've extended the reservation part to pass around a password, however, 0-os doesn't really support setting a password for the redis access. What is currently supported is setting the organization in the kernel args and in this case the user needs to supply a valid jwt as a password while accessing the client via redis. Am I correct @muhamadazmy?

@robvanmieghem @zaibon so do you want the user to be able to specify an organization while reserving, or do you just want him to be able to set any random password and in this case make changes to 0-os to support this? @muhamadazmy are there any limitations on being able to extend it to support this?

**Comment by zaibon** [comment]
> What is currently supported is setting the organization in the kernel args and in this case the user needs to supply a valid jwt as a password while accessing the client via redis. Am I correct @muhamadazmy?

correct

> @robvanmieghem @zaibon so do you want the user to be able to specify an organization while reserving, 

yes, exactly.
