### ISSUE TITLE
TFGrid Directory Actors working

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#365]
## link to other issues

- [ ] [tfgrid_directory FR](https://github.com/threefoldtech/jumpscaleX_threebot/issues/23)  : 23

## steps

- [ ] specs (schemas, actors) reviewed by kristof
- [x] all code merged inside the right actor location
- [x] actors done
- [x] tests done in package test factory
- [x] import feature, to import from older directory into the local one

**Comment by zaibon** [comment]
Threebot actors and 0-OS client are done. 
We still miss job to pull information from old directory to BCDB.

**Comment by zaibon** [comment]
Regarding the import feature from the old directory. There are 2 types of data we need import:
- farms detail
- nodes detail

Currently new farmer can still register on the old directory and 0-OS v1 nodes are still pushing data to it.
So we cannot just have an import once feature. We need to have a background job running every X minutes that pulls information from the old directory and update the BCDB.

the BCDB model for [farm](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/models/farm.toml) and [node](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/models/node.toml) have all the field present in the old directory. 
If something is missing feel free to open a PR to adapt the models.

To achieve that I think we could use the myjobs tools to start background job when the [threeebot directory package](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_directory/package.py) starts.
