### ISSUE TITLE
TFGrid Provisioning Actors

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#366]
## checks

- [ ] actors reviewed kristof
- [ ] get all code in package: https://github.com/threefoldtech/jumpscaleX_threebot/issues/26
- [x] make sure ZOS team understand how to use this actor:
  - actor has been reviewed by zos team, need to discuss extra functionality to be used by zero os. Right now the implementation seems good for threebot, but zos is missing some required functionality. For this we also need to know/decide how the node will get informed about reservations and reservation actions
- [x] link the required FR/Bugs to this story
- [ ] ... tbd

## links 

- ~~PR for work we currently have: https://github.com/threefoldtech/jumpscaleX_threebot/pull/16~~
- docs for reservation: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/tfgrid_workloads/docs/reservation.md
-Development issue:  https://github.com/threefoldtech/jumpscaleX_threebot/issues/26

**Comment by LeeSmet** [comment]
PR for actor implementation: https://github.com/threefoldtech/jumpscaleX_threebot/pull/16

**Comment by zaibon** [comment]
was blocked today on: https://github.com/threefoldtech/jumpscaleX_threebot/issues/32
