### ISSUE TITLE
prepare ZOS so it has all primitives done for connection to threebot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#367]
in couple of days we connect to threebot we need to make sure all on ZOS level is done

- [x] support to delete workloads:
    - workloads are automatically deleted when the reservation is finished
    - Support for manual deletion of workloads needs to first decide/know how a node would get informed that it needs to preemptively delete the workload, tracking issue: threefoldtech/zosv2#234
- [x] check all primitives are implemented in line with actor:
  - Primitives are ok, need to work out the integration path now (how is a node informed of new workloads / workloads to be deleted)
- [x] ZOS team review the specs
- [x] check the gedis : redis client compatibility implementation/specs
  - Tracking issue for implementation: https://github.com/threefoldtech/zosv2/issues/224
  - WIP PR: https://github.com/threefoldtech/zosv2/pull/226
  - gedis spec/doc: https://github.com/threefoldtech/digitalmeX/tree/master/docs/Gedis

**Comment by LeeSmet** [comment]
Support for delete workloads is being added, tracking issue: https://github.com/threefoldtech/zosv2/issues/234

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zosv2/pull/241 has been merged

**Comment by zaibon** [comment]
Everything on 0-OS side has been merged. 0-OS is now capable of talking to 3bot tf_directory actors.
