### ISSUE TITLE
TFMobile APP 1.0.x

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#368]
## features for this release

- [ ] authenticator for
    - [ ] any website
    - [ ] bottle website in 3bot (need example), need to see 3botlogin & email
- do we need something else now?

## steps

- [ ] what is x
- [ ] document features/issues on the right repo's
- [ ] where are the repo's
- [ ] define roadmap

**Comment by jdelrue** [comment]
All code + flow overview can be found at:

https://github.com/3botlogin/3botlogin

We have integration examples for PHP/Python/Javascript:

https://github.com/3botlogin/integration_examples

Although some are outdated, will fix it this week (and close this issue when I'm done).

Releases:
1.2 (Production now) - includes recover account, settings, FFP in app, ...
1.3 (Staging now) - includes wallet, security fixes, fingerprint, ..

Roadmap:
- Multi accounts
- Improvements in URL sizes
- Better mobile flow experience (less going back & forth - no entering name in browser - ...)
- Auto sign in from same PC which makes embedding easy
- Multiple emails per account

**Comment by jdelrue** [comment]
All updated https://github.com/3botlogin/integration_examples

**Comment by zaibon** [comment]
@jdelrue can we close this one then ?

**Comment by jdelrue** [comment]
Done
