### ISSUE TITLE
cleanup repo's

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#369]
- there are still issues left on https://github.com/orgs/threefoldtech/projects/36: jumpscale 10.0.1 & 10.0.2 -> put on right milestone now,later,... and on project if needed
- some projects have no owners yet
- the 10.0.1 project has lots of issues not closed https://github.com/orgs/threefoldtech/projects/15

## remarks

- stories only defined on home repo
-

**Comment by rkhamis** [comment]
done
