### ISSUE TITLE
Automated Tfchain shop with bitcoin 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#37]
A webpage where people can buy threefoldtokens with bitcoin 
preliminary spec:https://github.com/threefoldtech/rivine/blob/master/specs/webshop.md

**Comment by sabrinasadik** [comment]
- [ ] Define specs & possibilities @robvanmieghem: 8h 
- [ ] Implementation 42h

**Comment by robvanmieghem** [comment]
Related but not part of this story( not required for launch):
- [ ][ Check and document other bitcoin wallets compatible with electrum Master Public Key restore](https://github.com/threefoldtech/rivine/issues/471)

**Comment by xmonader** [comment]
DigitalMe application is a flask blueprint defines the APIs to serve staticfiles or communicate with gedis server via websockets using capnp messages.

Currently, Jumpscale team replacing the flask layer with lua and [openresty](https://openresty.org/en) and adding support for json payloads with gedis server so it'll be more like [JSONRPCServer](https://json-rpc.readthedocs.io/en/latest/quickstart.html) 

So the application would be 
- Frontend: defined in Lua/Openresty will be responsible for routing and static files
- Backend: Gedis RPCServer (python)  will be responsbile application logic

**Comment by robvanmieghem** [comment]
repository: https://github.com/threefoldfoundation/tftshop

**Comment by robvanmieghem** [comment]
blocked until the digital me vue integration and rest api exposure is defined
