### ISSUE TITLE
web integration part 2

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#373]
- [x] [blog](https://github.com/threefoldtech/jumpscaleX_threebot/issues/22)
- [x] alerta
   -  [x] [alerta](https://github.com/threefoldtech/jumpscaleX_threebot/issues/20)
   -  [x] improve ui and use jsx alertahandler (https://github.com/threefoldtech/jumpscaleX_core/issues/55)

**Comment by xmonader** [comment]
alerta awaits PR review https://github.com/threefoldtech/jumpscaleX_core/pull/89

**Comment by rkhamis** [comment]
Done!
