### ISSUE TITLE
Taiga Rebranding 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/home#376]
TO_DO:

- Taiga to ThreeFold Circles
- put some threefold logo's in
- do mention somewhere though that this wonderful tool has been created by the Taiga guys.
- e.g. in telegram we see:

Taiga is a project management platform for startups and agile developers & designers who want a simple, beautiful tool that makes work truly enjoyable.

Needs to become

``` ThreeFold Circles Collaboration Tool```

installation dos are [here](https://taigaio.github.io/taiga-doc/dist/setup-development.html)
repos are here : 
https://github.com/threefoldtech/taiga-events
https://github.com/threefoldtech/taiga-front
https://github.com/threefoldtech/taiga-back

**Comment by despiegk** [comment]
suggest to use gitlab as a first test on gitlab for the forks
please fork to https://gitlab.com/threefoldforks
is that possible?

**Comment by xmonader** [comment]
@despiegk if you wanna do this it's better to use the importer instead of manually doing so https://docs.gitlab.com/ee/user/project/import/github.html

**Comment by hossnys** [comment]
verified , Threefold Circles is running now here https://projects.threefold.me
![Screenshot from 2019-10-17 09-25-28](https://user-images.githubusercontent.com/26298009/66986806-df764280-f0bf-11e9-9961-2105e5a05556.png)
