### ISSUE TITLE
circles.threefold.me improvements

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#378]
- [x] 3bot login
- [x] disable mail login
   - [x]  to check whether admins have authorisation to change all e-mail addresses, and then check if 3bot login is possible after change
   - [x] preliminary message to be sent to all tf_org_internal before push production to check that people have a Threebot with the same e-mail as the e-mail used in circles
- [x] Change in the member roles: 
  - [x] product owner => Owner (= who owns the circle)
  - [x] stakeholder => stakeholder (stays)
  - [x] member (= who is part of the circle, the default, normally people should only belong to 1 circle per organisation)
  - [x]external (anyone not part of a circle)
  - [x]  contributor : can see items in the circle but not update them (often helping from out of his circle)
  - [x]  UX, design, front, back : to be deleted not relevant for circles)

**Comment by zaibon** [comment]
> should be possible to not see the closed ones by default now overwhelming see 

For this you can create a custom filter that exclude all the closed issue. That gives something like: https://projects.threefold.me/project/despiegk-threefold-community-organization/issues?exclude_status=95


![2019-10-30_468x1302_scrot](https://user-images.githubusercontent.com/303164/67896825-6fef6100-fb5d-11e9-80f8-c1af8677c8d1.png)

**Comment by hossnys** [comment]
for integrate 3bot login there are two scenarios :

1- add feature in the front end and back end to link your profile with your 3bot account as done with freeflow,  this will go for UI Team first.
 
2-let all people make sure or change there accounts email to be the same one they use for 3bot login and let the both links for login for some time tell people do that.

**Comment by Hamdy** [comment]
@hossnys  my opinion about this is, 
3 bot login philosophy shouldn't promote users to have multiple accounts of 3bot login
just against the philosophy of 3 bot.
Also making so, promotes doing the same thing we did in freeflowpages and will not prevent this from happening in future, every system we need to build we'll have to put effort into doing same feature
A more realistic and better approach is to support multiple email addresses in 3bot login, 
they can all be rerturned or user can choose each one to be returned per application from phone
that way, we'll have solved this issue forever, and everyone is happy 
no effort will be spent on solving same issue over and over and over!

**Comment by ramezsaeed** [comment]
@Hamdy totally agree but I don't think that this can happen in the near future.
So I prefer to go with the first solution in Samir's comment.
@rkhamis please add your feedback and priorities so Samar and Hamdy can start in this asap ;)

**Comment by Hamdy** [comment]
@ramezsaeed @rkhamis 
After a discussion with @jdelrue we agreed to support migration in taiga itself
that will require some time and UI changes

**Comment by hossnys** [comment]
@rkhamis  Can you please define the priority for this story so we can organize when to start with it and get UI team to do changes related to them.

**Comment by rkhamis** [comment]
As discussed with @Hamdy, it's of high priority

**Comment by despiegk** [comment]
lets discuss what we want to get out of this, what is needed now what can wait
what is easy to do what not

**Comment by hossnys** [comment]
3bot login now is done by @Hamdy  and @samaradel  and deployed on [staging](https://staging-circles.threefold.me) @rkhamis  please check it and when we can push it to production , also is the rest requirements will be developed soon or what is it's priority ?

**Comment by gmachtel** [comment]
A few remarks to be implemented on staging first, agreed with KDS: 
- Disable mail login method, only 3bot login if possible, but then 
-- to check whether admins have authorisation to change all e-mail addresses, and then check if 3bot login is possible after change
-- preliminary message to be sent to all tf_org_internal before push production to check that people have a Threebot with the same e-mail as the e-mail used in circles
- Change in the member roles: 
-- product owner => Owner (= who owns the circle)
-- stakeholder => stakeholder (stays)
-- member (= who is part of the circle, the default, normally people should only belong to 1 circle per organisation)
-- external (anyone not part of a circle)
-- contributor : can see items in the circle but not update them (often helping from out of his circle)
-- UX, design, front, back : to be deleted not relevant for circles)

**Comment by Hamdy** [comment]
@gmachtel we now support migration from normal login using email/pass to 3bot login
we recommend that users can login using this old way and in their user settings they can link their 3bot login account!
we can leave this kind of process for 2 weeks or so, then we can disable old way of logging
this is the easiest way for now!

**Comment by gmachtel** [comment]
OK but then it needs to be limited in time, and best to have a manual for guidance.

**Comment by hossnys** [comment]
most of requirement up in the issue body is done and updated , tested on staging , email and message over telegram chat sent to all users to check their accounts .
the remaining requirements is going to be released later.
