### ISSUE TITLE
requirements for v10.1.0

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#383]
# tests
- installation
- tests should cover basic functionality & high-level scenarios (e.g essential threebot functionality)

# process
- branches per features (story)
- PR essential checks (e.g enable precommit, codacy)
- all code should have comments on the internals and usable documentation (if not documented it's broken)
 
### Deliverables:
Topics to be covered by tests + documentation:

 - [x] [installation](https://github.com/threefoldtech/jumpscaleX_core/tree/development/install/installation_tests)
 - [x] [BCDB](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/data/bcdb/tests) 
 - [x] [schema](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/data/schema/tests)
 - [x] clients:
    - [x] [ssh](https://github.com/threefoldtech/home/issues/388)
    - [x] [gedis](https://github.com/threefoldtech/jumpscaleX_core/issues/212)
    - [x] [zdb](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/clients/stor_zdb/tests)
    - <strike>[ ] threebot [Blocked](https://github.com/threefoldtech/home/issues/390) MOVED TO THE NEXT MILESTONE</strike> 
    - [x] [registery](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/registry/ThreeFoldRegistryFactory.py#L19)
 - [x] servers
    - [x] [openresty](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/servers/openresty/tests)
    - [x] [threebot (zbot)](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/tests/test_threebot.py)
    - [x] [gedis](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/tests/test_gedis.py)
    - <strike>[ ] oauth</strike>
 - [x] packages
    - [x] [package manager](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/servers/threebot/tests)
    - <strike>[ ] community [Blocked](https://github.com/threefoldtech/jumpscaleX_threebot/pull/199)</strike>
    - [x] [registry](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/clients/tfgrid_registry/tests)

**Comment by john-kheir** [comment]
After investing some time to automate a test for oauth, found out that it has been decided to use 3bot login instead .. so stopped working on it.

**Comment by 0xIslamTaha** [comment]
Related bugs: 

- https://github.com/threefoldtech/jumpscaleX_core/issues/171

**Comment by john-kheir** [comment]
**Threebot client** is not ready for testing yet, please check this: https://github.com/threefoldtech/home/issues/390

**Comment by Dinaamagdy** [comment]
- **threebot**

https://github.com/threefoldtech/jumpscaleX_core/issues/209
https://github.com/threefoldtech/jumpscaleX_core/issues/208
https://github.com/threefoldtech/jumpscaleX_core/issues/211

**Comment by john-kheir** [comment]
Registry client bugs:
* https://github.com/threefoldtech/jumpscaleX_core/issues/217
* https://github.com/threefoldtech/jumpscaleX_core/issues/221

**Comment by AhmedHanafy725** [comment]
zdb client bug: 
- https://github.com/threefoldtech/jumpscaleX_core/issues/179
- https://github.com/threefoldtech/jumpscaleX_core/issues/213

package managrer:
- https://github.com/threefoldtech/jumpscaleX_core/issues/149

schema: 
- https://github.com/threefoldtech/jumpscaleX_core/issues/162

**Comment by xmonader** [comment]
Thank you all for the hard work :)
