### ISSUE TITLE
Testing: BCDB 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/home#385]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to test all the bcdb components.

**Deliverables**
- Test cases in TestQuality linked to the testing sheet
- Automation test cases 
- Integrated with ZeroCI

**Estimation Time**
- As we need to discover in deeps before starting on designing the test cases, It would be better to spend 4H to do exploratory testing then update this estimation time.

**Exploratory Testing goals:**
- Which components are under testing?
- What are the testing techniques should we follow to test it?
- What are the requirements to setup the testing environment?

**Comment by john-kheir** [comment]
For this Phase, just checked if all tests pass .. so all tests implemented [here](https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/data/bcdb/tests) passed except [unique_data test](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/data/bcdb/tests/9_unique_data.py), for this test a [bug](https://github.com/threefoldtech/jumpscaleX_core/issues/171) has been opened to get more input .

**Comment by john-kheir** [comment]
Also @BolaNasr will update [BCDB Docs](https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/BCDB)

**Comment by john-kheir** [comment]
docs updates: https://github.com/threefoldtech/jumpscaleX_core/pull/192

**Comment by john-kheir** [comment]
This ticket is done, just blocked on this bug:https://github.com/threefoldtech/jumpscaleX_core/issues/171

**Comment by 0xIslamTaha** [comment]
As there is nothing to be done from our side, I'm gonna close it for now.
