### ISSUE TITLE
Testing: The installation

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/home#386]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to update our installation test cases to match the new changes.

**Deliverables**
- Update all test cases in TestQuality linked to the testing sheet
- Update all the automation test cases 
- Integrated with ZeroCI

**Estimation Time**
- 1 working day

**Comment by Dinaamagdy** [comment]
code : https://github.com/threefoldtech/jumpscaleX_core/tree/development/install/installation_tests
last running results : https://zeroci.grid.tf/projects/jumpscaleX%20Installation/5dc226aca724b2bb3c5fbcff
updated Traceability Matrix with new features should be added :
https://docs.google.com/spreadsheets/d/1-VjAoOtl4rasbbTdu1KK_th-lvWeAU_lpRqC0KhoPAs/edit#gid=746161841

**Comment by Dinaamagdy** [comment]
working in 
container-install : --no-interactive --reinstall

**Comment by Dinaamagdy** [comment]
scratrch: finished 
start working in --threebot,  --port options

**Comment by Dinaamagdy** [comment]
finished today:
 -- scratrch
-- threebot
 --port options
-- images 
- containers
-- branch
