### ISSUE TITLE
Testing: SSH client

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/home#388]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to finalize our SSH client test cases.

**Deliverables**
- Update all test cases in TestQuality linked to the testing sheet
- Update all the automation test cases 
- Integrated with ZeroCI

**Estimation Time**
- 4H

**Comment by Dina-Abd-Elrahman** [comment]
- error in ssh client
https://github.com/threefoldtech/jumpscaleX_core/issues/160

- update the latest code,  https://github.com/threefoldtech/jumpscaleX_libs/blob/client_testing/JumpscaleLibs/clients/test/test_ssh_client.py

- update tractability matrix https://jsx.testquality.com/project/7543/plan/13826/test/206806

**Comment by Dina-Abd-Elrahman** [comment]
- the latest updated tractability matrix:

https://docs.google.com/spreadsheets/d/1-VjAoOtl4rasbbTdu1KK_th-lvWeAU_lpRqC0KhoPAs/edit#gid=916159529

- the latest updated code:
https://github.com/threefoldtech/jumpscaleX_libs/blob/client_testing/JumpscaleLibs/clients/test/test_ssh_client.py

- this issue still unsolved so i skipped almost all test cases

https://github.com/threefoldtech/jumpscaleX_core/issues/160

**Comment by 0xIslamTaha** [comment]
@Dina-Abd-Elrahman ssh code is in jsx_core but the test cases are in jsx_libs repo. Is that for purpose? 

I looked at the code and I can find that there r missing test case, here is my list.

**List of methods to test**
- `execute_jumpscale` 
- `shell`
- `mosh`
- `syncer` 
- portforward+tp_local
- portforward_kill
- `execute` with specific script not only one command

**List of properites to test:**
- addr_variabile
- port_varaible
- is_connected

**Comment by Dina-Abd-Elrahman** [comment]
issue for ssh client documentation, 

https://github.com/threefoldtech/jumpscaleX_core/issues/174

**Comment by Dina-Abd-Elrahman** [comment]
issue for shell method in ssh client 

https://github.com/threefoldtech/jumpscaleX_core/issues/176

**Comment by 0xIslamTaha** [comment]
I reviewed the existing code and it is 29 test cases till now. Here are my comments: 
- `test017_execute_for_non_valid_command_line` and `test018_execute_for_none` should be parametrized. 
- `test024_kill_port_forwarding` needs to check that u can't access the running nginx after killing the port forwarding.
- `test025_try_killportforwarding_doesnt_exists`, add another test case as a parametrized here to test that u can't do port forward for an existing port
-

**Comment by Dina-Abd-Elrahman** [comment]
- test quality:
https://jsx.testquality.com/project/7543/plan/13826/test/206806

- Requirement Traceability Matrix:
https://docs.google.com/spreadsheets/d/1-VjAoOtl4rasbbTdu1KK_th-lvWeAU_lpRqC0KhoPAs/edit#gid=916159529

- test cases code:
https://github.com/threefoldtech/jumpscaleX_libs/blob/client_testing/JumpscaleLibs/clients/test/test_ssh_client.py

- created bugs:
https://github.com/threefoldtech/jumpscaleX_core/issues/206
https://github.com/threefoldtech/jumpscaleX_core/issues/176
https://github.com/threefoldtech/jumpscaleX_core/issues/160
https://github.com/threefoldtech/jumpscaleX_core/issues/174

**Comment by Dina-Abd-Elrahman** [comment]
- **Report**

2019-11-13 11:30:41.766 | INFO     | base_test:info:13 - create ssh client
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.digitalocean.client
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.digitalocean.vm
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.server
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.itsyouonline.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.itsyouonline.jwt.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sshclient.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sshkey.client
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.syncer.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.client
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot_server.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.client.1
Wed 13 11:30:41 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zerohub.client
Wed 13 11:30:41 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
Wed 13 11:30:41 4068f65729750a9fc.py -  31 - 1_eac736a0bc53d514068f65729750a9fc : init index:jumpscale.sshclient.1
TC 509 ... 2019-11-13 11:30:42.054 | INFO     | base_test:info:13 - check addr variable property
ok
TC 510 ... 2019-11-13 11:30:42.054 | INFO     | base_test:info:13 - check port variable property
ok
TC 511 ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/206
TC 485 ... 2019-11-13 11:30:42.054 | INFO     | base_test:info:13 - create file locally
2019-11-13 11:30:42.054 | INFO     | base_test:info:13 - use copy_file to copy ssh_test04.txt from local machine to remote one
Wed 13 11:30:42 SSHClientParamiko.py - 145 - sshclientparamiko_SSH_395          : connect to:192.168.21.144
/root/.local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/root/.local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/root/.local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
Wed 13 11:30:42 SSHClientParamiko.py - 164 - sshclientparamiko_SSH_395          : connection ok
Wed 13 11:30:42 SSHClientParamiko.py -  82 - sshclientparamiko_SSH_395          : Copied local file /tmp/ssh_test04.txt to remote destination /tmp/ssh_test04.txt for SSHCLIENT ssh: 192.168.21.144 (22)
2019-11-13 11:30:42.507 | INFO     | base_test:info:13 - check that file is copy in the remote machine or not
ok
TC 486 ... 2019-11-13 11:30:42.807 | INFO     | base_test:info:13 - try to copy non valid local file to remote valid file
ok
TC 487 ... 2019-11-13 11:30:42.808 | INFO     | base_test:info:13 - create a directory in local machine 
2019-11-13 11:30:42.813 | INFO     | base_test:info:13 - try to copy the directory to remote file it should fail.
ok
TC 488 ... 2019-11-13 11:30:42.814 | INFO     | base_test:info:13 - create a directory in remote machine with name ssh_test07 in /tmp/
2019-11-13 11:30:43.083 | INFO     | base_test:info:13 - create a file with name ssh_test_DIR in local machine
2019-11-13 11:30:43.087 | INFO     | base_test:info:13 - try to use copy_file to copy this file from local machine to remote one, should fail.
ok
TC 491 ... 2019-11-13 11:30:43.088 | INFO     | base_test:info:13 - create a file in a directory in remote machine, with certain file name.
2019-11-13 11:30:43.623 | INFO     | base_test:info:13 - use download method to copy this directory in my local machine in /tmp/ssh_test08/
root@192.168.21.144's password: 
2019-11-13 11:30:47.215 | INFO     | base_test:info:13 - check if files is downloaded or not
ok
TC 502 ... 2019-11-13 11:30:47.222 | INFO     | base_test:info:13 - create a file in a directory in remote machine, with certain file name.
2019-11-13 11:30:47.754 | INFO     | base_test:info:13 - use download method to copy this directory in my local machine in /tmp/ssh_test09/
root@192.168.21.144's password: 
2019-11-13 11:30:50.729 | INFO     | base_test:info:13 - check if files is downloaded or not
ok
TC 503 ... 2019-11-13 11:30:50.743 | INFO     | base_test:info:13 - create a file in remote directory in remote machine, with certain file name.
2019-11-13 11:30:51.299 | INFO     | base_test:info:13 - use download method to copy this directory in my local machine in /tmp/ssh_test10/
root@192.168.21.144's password: 
2019-11-13 11:30:54.296 | INFO     | base_test:info:13 - check if files is downloaded or not
ok
TC 503 ... 2019-11-13 11:30:54.304 | INFO     | base_test:info:13 - try to use download method with non valid source should fail
ok
TC 491 ... 2019-11-13 11:30:54.446 | INFO     | base_test:info:13 - create a file in a directory in local machine, with certain file name.
2019-11-13 11:30:54.477 | INFO     | base_test:info:13 - use upload method to copy this directory in my local machine in /tmp/test_ssh/
root@192.168.21.144's password: 
sending incremental file list
test1
test2

sent 161 bytes  received 54 bytes  61.43 bytes/sec
total size is 0  speedup is 0.00
2019-11-13 11:30:57.401 | INFO     | base_test:info:13 - check if files is downloaded or not
ok
TC 506 ... 2019-11-13 11:30:57.672 | INFO     | base_test:info:13 - create a file in a directory in local machine, with certain file name.
2019-11-13 11:30:57.682 | INFO     | base_test:info:13 - use upload method to copy this directory from my local machine in /tmp/ssh_test13/
root@192.168.21.144's password: 
sending incremental file list
test13_1

sent 112 bytes  received 35 bytes  42.00 bytes/sec
total size is 0  speedup is 0.00
2019-11-13 11:31:00.937 | INFO     | base_test:info:13 - check if files is uploaded or not
ok
TC 507 ... 2019-11-13 11:31:01.193 | INFO     | base_test:info:13 - create a file in a directory in remote machine, with certain file name.
2019-11-13 11:31:01.207 | INFO     | base_test:info:13 - use upload method to copy this directory in my local machine in /tmp/ssh_test14/
root@192.168.21.144's password: 
sending incremental file list
test14_1

sent 135 bytes  received 36 bytes  48.86 bytes/sec
total size is 0  speedup is 0.00
2019-11-13 11:31:04.115 | INFO     | base_test:info:13 - check if files is uploaded or not
ok
TC 508 ... 2019-11-13 11:31:04.384 | INFO     | base_test:info:13 - try to use upload method with non valid source should fail
ok
TC 492 ... ok
TC 493, 494 [with command='NON_VALID'] ... Wed 13 11:31:04 SSHClientParamiko.py - 243 - sshclientparamiko_SSH_395          : bash: NON_VALID: command not found
ok
TC 493, 494 [with command=None] ... ok
TC 512 ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/160
TC 495 ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/160
TC 496 ... 2019-11-13 11:31:04.542 | INFO     | base_test:info:13 - use ssh_authorize without pubkeys specified, and homedir option
ok
TC 501 ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/160
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/204
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/204
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/204
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/204
TC ... 2019-11-13 11:31:04.543 | INFO     | base_test:info:13 - create a instance from syncer method
Wed 13 11:31:04 5a1af4adeca20bc01.py -  31 - 1_b2c1e13b9dc70a55a1af4adeca20bc01 : init index:jumpscale.syncer.1
Wed 13 11:31:04 Syncer.py            -  82 - syncer_SSH_395                     : syncer started
2019-11-13 11:31:04.597 | INFO     | base_test:info:13 - try to list ssh_clients in this method, should return our ssh_client
ok
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/160
TC ... SKIP: https://github.com/threefoldtech/jumpscaleX_core/issues/160
2019-11-13 11:31:04.598 | INFO     | base_test:info:13 - delete ssh client

----------------------------------------------------------------------
Ran 29 tests in 22.837s

OK (SKIP=10)
Wed 13 11:31:05 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
