### ISSUE TITLE
Testing: Threebot Client

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/home#390]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to design and automate test cases for the ThreeBot client.

**Deliverables**
- Design test cases in TestQuality linked to the testing sheet
- Automate the test case 
- Integrated with ZeroCI

**Estimation Time**
- Do the exploratory testing and set the estimation time.

**Comment by john-kheir** [comment]
@xmonader Let us know when this client is ready to test 
PR: https://github.com/threefoldtech/jumpscaleX_core/pull/157
