### ISSUE TITLE
web publishing environment production for threefold [development_web]

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/home#392]
- the final image of the new tf-gateway should be like this 
![ovh3](https://user-images.githubusercontent.com/13523434/68669385-0a36a800-0553-11ea-9d65-fe6441135a6a.jpg)

- every nodes of ovh will have CoreDNS, tcp router and redis slave container
![ovh1](https://user-images.githubusercontent.com/13523434/68669752-f63f7600-0553-11ea-839c-b855310ec696.jpg)

- redis master will only be reachable from private network connected with redis slaves
![ovh2](https://user-images.githubusercontent.com/13523434/68669730-e7f15a00-0553-11ea-8a63-0bb54793311f.jpg)

## website deployments

- create packages on threebot repo (is ok for now) for the websites & wiki's
- websites github repo's need to be checked out out using the git tools in JSX to a right location

# specs docs

make sure next is understood

https://docs.google.com/document/d/13HKlf1qQb8ZU8fIFKWtnpAVgYOf53RLMwBJ4BN5WlYM/edit#heading=h.uojrdejjn06y

# steps

prepare script for 
### step 1
- [X] 2 OVH or DO machines

### step 2
- [X] 2 threebot containers (staging, production)
- [X] 1 redis container

### step 3
- [X] build tcprouter, coredns and copy it to the host

### step 4
- [X] configure coredns to use redis container
- [X] configure tcprouter to use redis container

### step 5 
- [X] start tcprouter
- [X] start coredns

### step 6 (later):

requires:
- ovh client to be usable otherwise use digital ocean
- well defined packages for websites in threebot repo
- builders for taiga/postgresql/gitea/ffp . (NO NEED FOR DOCKER IMAGES)

# location of the configuration

 https://docs.grid.tf/threefold/itenv_web_v2/src/branch/master

**Comment by PeterNashaat** [comment]
@zaibon and @muhamadazmy  can you guys put your insights about using 0-os v2 on our production environment

**Comment by muhamadazmy** [comment]
This is a tiny document that you need to read regarding migration: https://github.com/threefoldtech/zos/tree/master/docs/migration

**Comment by PeterNashaat** [comment]
- is 0-os V2 available for production ?
- how can we create containers with persistent data ?

**Comment by zaibon** [comment]
This design is impossible to in place with how the tech is today.

While the first version of the networking stack of 0-OS v2 could have been adapted to allow running container with public internet access it has been refused and asked to be change to only support fully private network. Reason was the tf_gateway was supposed to be the entry point of any traffic into the grid. So it is impossible to run any workload with public IP today in 0-OS

0-OS needs tf_gateway. So tf_gateway cannot depend on 0-OS. This is basic circular dependencies.

**Comment by xmonader** [comment]
I doubled checked with @despiegk  he meant V2 of the web publishing not V2 of zero-os :) I'll reopen and sorry for the ambiguity and the confusion @zaibon @muhamadazmy

**Comment by despiegk** [comment]
@xmonader where is the work already done?

**Comment by PeterNashaat** [comment]
finalizing script and testing it 
https://docs.grid.tf/threefold/3bot_connect/src/branch/master/itenv_web_v2.py

issues : 

- do client sometime create the vm in the default project instead of the given project name

**Comment by PeterNashaat** [comment]
new issue while building coredns : 
![image](https://user-images.githubusercontent.com/13523434/69140204-b7b53880-0aca-11ea-86a9-1389e258b8fd.png)

**Comment by PeterNashaat** [comment]
- issue while building Coredns  
![coredns](https://user-images.githubusercontent.com/13523434/69161446-dc71d600-0af3-11ea-86cb-0efbe5c64e8d.jpg)

**Comment by PeterNashaat** [comment]
- script is ready (hashed coredns building)

https://docs.grid.tf/threefold/3bot_connect/src/branch/master/itenv_web_v2.py

**Comment by despiegk** [comment]
despiegk to review with team, I see quite some issues
