### ISSUE TITLE
new wiki + first early 3git in python [development_3git]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#393]
see https://github.com/threefoldtech/home/issues/426

**Comment by abom** [comment]
Theebot `start()` should return a client, right?

I know it's not yet complete, but just need to understand the context behind [this](https://github.com/threefoldtech/jumpscaleX_core/compare/development_3git#diff-aef10fab995e741e3dfbbc90db742259R298) and [this](https://github.com/threefoldtech/jumpscaleX_core/compare/development_3git#diff-aef10fab995e741e3dfbbc90db742259R309).

**Comment by xmonader** [comment]
> Theebot `start()` should return a client, right?
> 
> I know it's not yet complete, but just need to understand the context behind [this](https://github.com/threefoldtech/jumpscaleX_core/blob/7d45ad78206e1fd1aa0db90545c4bf2e153b3f23/JumpscaleCore/servers/threebot/ThreebotServer.py#L298-L306).

the idea is to provide a limited j for packages without servers for instance so they won't mess with the gevent loop afterwards

**Comment by abom** [comment]
Thanks @xmonader 

Another question, now `start()` does not have `timeout` parameter, how should we wait for the gedis server to start like here:

```python
        if not j.sal.nettools.waitConnectionTest("127.0.0.1", 8901, timeout=timeout):
            raise j.exceptions.Timeout("Could not start threebot server")
```

**Comment by abom** [comment]
For limiting `j` object by removing references to builders, servers...etc, it can reach other code paths where j.servers and j.builders...etc are used, for example this error which happens when accessing bcdbfs from wiki package via `/wiki/....`

```
127.0.0.1 - - [2019-11-17 19:03:06] "GET /wiki/chat HTTP/1.1" 200 3202 0.019190                                                           [147/11666]
system__system                                                                                                                                       
system__system                                                                                                                                       
Traceback (most recent call last):                                                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 862, in _handle                                                                      
    return route.call(**args)                                                                                                                        
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 1742, in wrapper                                                                     
    rv = callback(*a, **ka)                                                                                                                          
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/wiki/BottleWebServerWiki.py", line 29, in _enable_cors                                      
    return fn(*args, **kwargs)                                                                                                                       
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/wiki/BottleWebServerWiki.py", line 132, in docsite_handler                                  
    content = j.sal.bcdbfs.file_read(full_path)                                                                                                      
  File "/sandbox/lib/jumpscale/Jumpscale/sal/bcdbfs/BCDBFS.py", line 289, in file_read                                                               
    return self._file_model.file_read(path)                                                                                                          
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/models_threebot/FILE.py", line 154, in file_read                                                  
    file = self.get_by_name(name=path)                                                                                                               
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 300, in get_by_name                                                           
    list_obj = self.find(nid=nid, **args)                                                                                                            
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 629, in find                                                                  
    for id in self.find_ids(nid=nid, **kwargs):                                                                                                      
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 602, in find_ids                                                              
    cursor = self._find_query(nid, **kwargs)                                                                                                         
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 584, in _find_query                                                           
    return self.query_model([field], whereclause, values)                                                                                            
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 588, in query_model                                                           
    query = f"select {fieldstring} FROM {self.index.sql_table_name} "                                                                                
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 98, in index                                                                  
    self._index_ = indexklass(model=self, reset=False)                                                                                               
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 63, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModelIndex.py", line 64, in _init
    self.sonic  # sonic needs to be started and needs to exist !
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModelIndex.py", line 147, in sonic
    self._sonic = j.clients.sonic.get_client_bcdb()
  File "/sandbox/lib/jumpscale/Jumpscale/clients/sonic/SonicFactory.py", line 21, in get_client_bcdb
    j.builders.apps.sonic.install()
AttributeError: 'Jumpscale' object has no attribute 'builders'
```
```

**Comment by despiegk** [comment]
> Thanks @xmonader
> 
> Another question, now `start()` does not have `timeout` parameter, how should we wait for the gedis server to start like here:
> 
> ```python
>         if not j.sal.nettools.waitConnectionTest("127.0.0.1", 8901, timeout=timeout):
>             raise j.exceptions.Timeout("Could not start threebot server")
> ```

take a default timeout value

**Comment by despiegk** [comment]
there should be no automatic building, this will not be supported anyhow in the future
you can do building before starting 3bot server but not at the level where we do it now

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/69013619-7fa2de00-0982-11ea-8f46-9e3ca6e3665f.png)
super bad, installing a server bcause you need a client

**Comment by despiegk** [comment]
we need to harden the sonic, zdb, redis security
now its really bad
and NO auto install

**Comment by waleedhammam** [comment]
Walked into markdown docs, macros parsing mechanisms and how it works, wikis load/reload. starting writing `j.tools.wiki` tool to integrate it with 3git.

**Comment by waleedhammam** [comment]
updates:
- fix logChanges at: https://github.com/threefoldtech/jumpscaleX_core/commit/1502760ee4d815f8e0e4f444a30c51b242e8b365 [needs to handle other files states]

- migrate from bcdbfs to normal file system to get changes from last process

In Progress

-  getting markdown docs running by git changes instead of taking all files

**Comment by waleedhammam** [comment]
Changelog:

at commit: **https://github.com/threefoldtech/jumpscaleX_core/commit/998ed161d7e5709c4b12026dc47680efa954341e**
- Started filling in threegit tool to reuse markdown docs code with filesystem instead of bcdb.
- Redirected macros to serve to filesystem
- Threegit tool process docsite with macros now.

TODO:
- Integrate with git 3git tools
- verify macros are working well
- tests

**Comment by waleedhammam** [comment]
**Commit** https://github.com/threefoldtech/jumpscaleX_core/commit/9c72fc339cb2b5322c7590a9af7db015c302b6b8

**Changes**
- 3git can process markdown documents with macro's
- integrate 3git to load only changed files

**How to use**
```python
j.tools.threegit.process("test_wikis", path_source="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/docs/wikis/examples/docs/", path_dest="/test/test2/", check=True, reset=False)
```

:param **path_source**: source of gitrepo / docsite files
:param **path_dest**: destination to save docsites files in it
:param **check**: reload changed files in docsite since last revision
:param **force**: Reload all docsites files and reparse them

**Comment by waleedhammam** [comment]
some fixes in the tool and make it use bcdb configs at: https://github.com/threefoldtech/jumpscaleX_core/commit/4b5f136d8b2017dde516037b62e54e4cb6adc0e0

usage now changed to 
first take a config first using name and path_source and path_dest 
then process

**Comment by waleedhammam** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_core/commit/ac0ecf93373dbfc0f2c34dca1adbf78181bf3822
updated some docs, test for the usage at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_3git/JumpscaleCore/tools/threegit/README.md
