### ISSUE TITLE
3bot upgrade

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#397]
We need to agree on a process regarding 3bot upgrades.
3Bot has many different component all have their own version and installed differently. First let's try to list them all:
- jumpscale
- packages
- core servers (sonic, nginx, 0-db, ... )
- weblibs (is this separate from jumpscale ?)

Now the question is, how do we version and upgrade all of those things. We need to keep in mind that a 3bot is own by its owner. There is no way for us (developers) to "go" to the 3bot of someone and manually do anything. 
So I see 2 possibities:
-  the upgrade is presented to the user and he needs to accept it. Could be a pop up on his 3bot telling him something new is available, and he can click upgrade or not.
-  The 3bot is have a built int system that will make it upgrade itself whenever a new version is available.

Both systems have they pro and cons.

**Comment by despiegk** [comment]
for now we just will have flist based approach
