### ISSUE TITLE
threebot security [development_security]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#399]
## features

- [x] actor security
- [x] acl security
<strike>- [ ] crud actors integration with security 
- [ ] integration with threebot_connect - for next release see #497
- [ ] revisit weblayer for websites - for next release 
- [ ] revisit weblayer for gedis for using JSX gedis client (gedis using https) </strike>

## actor security

- admin user = threebot user, only he can go to actors by default
- need to use the session object to make sure only admin (own user) can access
- you can have multiple admin (so suggest to use the circle:admin for that purpose)

### remark for actor methods

- or method is 100% public (need to specify, maybe a decorator?)
- or default is method only accessible by admins
- or in actor method we deal with checking the circles membership
<strike>
- [ ] update base crud actor to check for the required right in each method:
  - [ ] new > w
  - [ ] set > w
  - [ ] get > r
  - [ ] delete > d
</strike>

### phase 2

- [x] update actors to use usersession threefoldtech/jumpscaleX_core#329

**Comment by xmonader** [comment]
- actor security is done here https://github.com/threefoldtech/jumpscaleX_core/pull/205
- more work on the integration with threebot client is actively being done as part of threebot client story https://github.com/threefoldtech/jumpscaleX_core/pull/187
- crud actors already been merged (https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/zerobot/models_crud) 
- acl security is done here https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/data/bcdb/models_system/ACL.md

**Comment by despiegk** [comment]
make sure all further work done around security on this branch and this branch only

**Comment by xmonader** [comment]
@andrewayoub already started working on this

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/home/issues/492

**Comment by rkhamis** [comment]
we should open a new one when approach is clearer
