### ISSUE TITLE
Threefold registration web-page [development_registration]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/home#400]
# Goal allow anyone to register today, until the 3bot connect app is done on mobile

## To connect:

`https://threefold.io/register`

or 

`https://threefold.io/join?kristof`

### Step 0:

- No arguments
    - Go to step 1
- referral given:
    - Go to step 2, because referral name known
- Secret given:
    - Go to step S

### Step 1:

- Give the 3bot name of the person who referred you, if you don’t have leave empty
If not empty
- Do lower case, remove special chars 
- check +5chars if not right format tell what format needs to be, check is unique
- Check if it exists, if not ask again, until ok
- If empty
    - Go to step X
- Go to step 2

### Step 2:
- Ask name
- Ask email
- Ask company
- Ask country
- Generate a secret : used to let user change his info
- Go to step 3

### Step 3:

- Say
	Please mention which topics of ThreeFold you would like to be informed off.
- List
	- ThreeFold Network User
	- ThreeFold Network Farmer
	- ThreeFold Network Developer
	- Tokens Initial Exchange Offering Jan 2020
	- ThreeFold Technology
	- ThreeFold Investor
	- ThreeFold Events
	- 3Bot your Digital Self
- Go to step 4

### Step 4:

- Please confirm it's ok we inform you about news in the chosen topics. 
You can always unsubscribe later. If not you will not receive email notifications.
- Go to step 5

### Step 5:

- Say
	- Choose your own 3bot name.
	- A 3bot name consists out of minimum 5 characters.
- Ask for the 3bot double name & validate if unique
- Go to Step6

### Step 6

- Say:
    Congrats you have registered your unique 3bot name.
- Do:
    - Send an email
- Email:
    - TO BE DONE
    - We need to put in there the referral link & the secret link
    - The referral link is to let them invite others.
    - The secret link is to let them change their information

### Step S:

Ask the info again… modify the info of the user

### Step X:

- Ask
	- Ask name
	- Ask email
	- Ask company
	- Ask country
- Say
	We will find you the right ThreeFold Ambassador to help you further, stay tuned, 
	instructions will follow over email.
- Do
    Register in DB the state

**Comment by rkhamis** [comment]
@despiegk @jdelrue i feel we're going round in circles. we don't need this page as its main point was to have people with no 3bots sign up with their emails to later on register their 3bots. we already have 3bot registeration flows: https://github.com/threefoldtech/home/issues/415, which can be linked in our website to deploy a new 3bot.


Please confirm or let me know if we're keeping this

**Comment by despiegk** [comment]
its still needed, but the starting step is different, people have to authenticate with a 3bot connect

**Comment by gmachtel** [comment]
If we have 3bot connect, then why sign with e-mail ? This is what the issue is about. Should it not be done through https://github.com/threefoldtech/home/issues/407 ?

**Comment by rkhamis** [comment]
we indeed don't need this anymore. will be done through the community builder (see: #407)
