### ISSUE TITLE
move all threebot code to tftech

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#404]
### why

to make project management easier

### todo

- [ ] move all
- [ ] license 
    - author: to ThreeFold Foundation NV Belgium (only in root of repo)
    - apache2
- [ ] make sure new repo;s are added in right projects

**Comment by jdelrue** [comment]
@despiegk Should we also move FFP? Would be easier for the issues but now its nicely separated in differen organisations

**Comment by sasha-astiadi** [comment]
@ken-de-moor have we completed this?
