### ISSUE TITLE
tcprouter/coredns needs to be moved to threefoldtech

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#405]
- [x] choose license (bsd 3)
- [x] add feature requests for tcprouter client
- [x] make sure they have right labels
- [x] [create FR for tcprouter client](https://github.com/threefoldtech/home/issues/406)

- coredns plugin exists at https://github.com/threefoldtech/coredns-redis
- tcprouter https://github.com/threefoldtech/tcprouter

**Comment by xmonader** [comment]
I licensed the tcprouter project originally as BSD v3, now I think it's more appropriate to have it as AGPL v3
