### ISSUE TITLE
tfgrid_solutions [development_tfgridsolutions]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#409]
Implement chatflows to deploy the following from flists

- [ ] gitea
- [ ] odoo 
- [ ] taiga 
- [ ] ubuntu 
- [ ] wordpress 
- [ ] Minecraft 

Each solution should have its wiki and chatflow implemented

 - [ ] flists to be promotes to tf-solutions

Development branch: development_3git_solutions

**Comment by despiegk** [comment]
needs cleanup

**Comment by Pishoy** [comment]
faveo flist is https://hub.grid.tf/mikhaieb/bishoyabdo-faveo-latest.flist
and repo under https://github.com/xmonader/tf-images/tree/master/faveo

**Comment by sasha-astiadi** [comment]
@xmonader can we close this or not?
