### ISSUE TITLE
blog based on gedis and svelte [development_web]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#411]
Create a blog package based on gedis/svelte

- [x] actors
   - [x] get meta data, blog title, author, author photo,... etc (get_blog_metadata)
   - [x] get posts list (get_blog_posts)
   - [x] get single post (get_blog_post with id)
   - [x] get tag's posts (get_blog_posts_by_tag)
   - [x] search posts/pages

- [x] UI based on svelte
  - [x] simple interface
  - [x] searchable
  - [x] Taiga like theme
  - [x] tags

- [x] Deployment
  - [x] package.py
  - [x] package factory
  - [x] start paramaterized in blog repo url

- [x] Documentation
  - [x] Repo format
  - [x] Metadata format
  - [x] Actors usage
  - [x] Svelte components
  - [x] Communication over gedis (gedis http client)
  - [x] Deployment related info

**Comment by VonSub** [comment]
General Changes

- [ ] Set Favicon (see docs folder)
- [ ] Remove navbar, as this pionts back to blog overview
- [ ] Change social icons (see docs folder)
- [ ] Remove Disquss (I think already did but verify please)
- [ ] Set post count to even number (pagination looks like disaster now)

**Comment by VonSub** [comment]
Post overview Changes:

- [ ] Make image as wide as the text in the column
- [ ] Move authorimage underneath image
- [ ] Move date and put in european order
- [ ] apply same style to tags as seen in side bar and move below post snippet.

Left post = new
Right post = current
![Screenshot 2019-11-19 at 14 50 35](https://user-images.githubusercontent.com/29431263/69157430-2f905c80-0ae5-11ea-8576-557b36fd5945.png)

**Comment by VonSub** [comment]
Post Detail page changes:
- [ ] Align image with sidebar box
- [ ] Move Author + date underneath image + date european style
- [ ] Move tags underneath image and apply sidebar style
- [ ] Repeat same tags at bottom of post

**Comment by despiegk** [comment]
need to decide which features to do and what not
before we can do so we need to know how much work @xmonader

**Comment by xmonader** [comment]
@VonSub for UI changes please follow up on this story https://github.com/threefoldtech/home/issues/487
