### ISSUE TITLE
move code & update bugs & start using the people projects

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#412]
- make sure all code as needed for threebot & tfgrid is in threefold tech repo
- make sure your team is complete
- recommend that every member of team has photo on profile
- make sure every member is in FFP & circles...
- make sure all labels set on all repo's
- remove bugs too old
- make sure stories are all in home

make sure to read the gdoc
- https://docs.google.com/document/d/1mCdAuQ38E5WnwGk2y0N0bTGmRMpNuDPvYA2BYKXiM7Q/edit

**Comment by zaibon** [comment]
- [x] make sure all code as needed for threebot & tfgrid is in threefold tech repo
- [x] make sure your team is complete
- [ ] make sure every member of team has photo on profile
- [x] make sure every member is in FFP & circles...
- [x] make sure all labels set on all repo's
- [x] remove bugs too old
- [x] make sure stories are all in home

**Comment by rkhamis** [comment]
regarding my team:
- [x] make sure all code as needed for threebot & tfgrid is in threefold tech repo
- [x] make sure your team is complete
- [ ] make sure every member of team has photo on profile
- [x] make sure every member is in FFP & circles...
- [x] make sure all labels set on all repo's
- [x] remove bugs too old
- [x] make sure stories are all in home

**Comment by despiegk** [comment]
lets skip the photo's on github, but photos need to be on FFP

**Comment by xmonader** [comment]
regarding my team:
- [x] make sure all code as needed for threebot & tfgrid is in threefold tech repo
- [x] make sure your team is complete
- [x] make sure every member of team has photo on profile
- [x] make sure every member is in FFP & circles...
- [x] make sure all labels set on all repo's (only new repo was added tcprouter)
- [x] remove bugs too old
- [x] make sure stories are all in home

**Comment by rkhamis** [comment]
regarding my team:
- [x] make sure all code as needed for threebot & tfgrid is in threefold tech repo
- [x] make sure your team is complete
- [x] make sure every member of team has photo on profile
- [x] make sure every member is in FFP & circles...
- [x] make sure all labels set on all repo's (only new repo was added tcprouter)
- [x] remove bugs too old
- [x] make sure stories are all in home

**Comment by zaibon** [comment]
seems we're done here @despiegk
