### ISSUE TITLE
As a person, register your 3bot

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#415]
Assumptions:

- Registration of a 3bot is located on a ‘centralized bootstrap 3bot’ that has access to the threefold network to launch 3bots and send emails
- Will be added to interface package 

Location is a list of regions to get a 3bot close to your location
After clicking deploy, user is redirected to their 3bot for initialization

**Flow**

![Registration3Bot](https://github.com/threefoldtech/jumpscaleX_threebot/raw/development/docs/images/3Bot%20Registration.png)
- User logs in to a centralized bootstrap 3bot, using a chosen doublename 
- This doublename is checked both on the TfPhonebook (master info) as on the currently used list (temporary master)
- A 3bot boot is created and deployed with a randomly generated keypair, as the definitive ones can't be defined yet
- Doublename is registered, with temporary public key on TfPhonebook
- 3bot is reachable through {double.name}.3bot.grid.tf
- User completes info in the 3bot with seed info
- Full identity is verified
- Public key is adapted to hold the final version in TfPhonebook (3 entries to be rewritten using new encryption keys)
- 3bot initialization page is shown

**Linked tasks**
- [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/144
- [x] [improve login button for 3bot app in registration chat flow](https://github.com/threefoldtech/jumpscaleX_threebot/pull/244)
- [x] harden deployment flow, some random error still happens
- [x] write documentation how to deploy a 3bot

**Comment by serboctor** [comment]
Added end user docs here https://github.com/threefoldfoundation/info_grid/blob/development_v2_migration/docs/faq/threebot_server.md 

And also hardened the chat flow a bit for the part where it checks if a  container exists https://github.com/threefoldtech/jumpscaleX_threebot/commit/d99101723c70c593c664a2d1af9ae44113587da3 and  https://github.com/threefoldtech/jumpscaleX_threebot/commit/d06d076fc80a78238ccd52b5fc0ce864ae041aa8

**Comment by despiegk** [comment]
shouldn't we create a new story, this one is getting so big and hard to understand
should specs not be part of the package which is needed to execute this or elsewhere,
personally I do not like specs in stories because once story closed spec is gone

**Comment by zaibon** [comment]
This story was in verification for quite some time already. I'll just close it nothing seems to happen here anymore.
