### ISSUE TITLE
ZeroCI brainstorming

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/home#418]
As we are planning to make our ZeroCI as a separate product, We gonna list all the features of it in this ticket.

### Components
- Login.
- Dashboard (lots of reports will be displayed here)
- Repo landing page
- Test Case Management system
        - Test suites for each repo
        - Test cases under each test suites
        - Test steps under each test case
        - Mapping technique to map each test suite with the specific component and it is related testing code.
- Execuoters
- Reports
- Paying with TFT

## 1- Login:
- user can login with his github account
- after configuring the github, user can list all his repos
- username, avatar, ssh key should be gripped from the github
- user can create an account and link it with a github account

## 2- Dashboard:
It is the landing page of the user and the main feature of it is showing an overall status of all repos and test cases. Here is a list of ideas for the dashboard
- Total number of repos
- Total number of test cases
- A specific card for each repo having:
    - Total number of test cases
    - Total number of passed/failed/skipped test cases 
    - summer of bugs related to skipped test cases
    - Last running date 
    - who triggered this run? (user, commit id, pr id, branch)
- Filter to order these cards (By date, By name)
- User can pin specific cards 
- List of repos to access the repo landing page
- List of test suites to access it as a short link

## 3- Repo landing page: 
When the user selects a specific repo from the dashboard, he will go to the repo landing page which has these features:
- Repo details
    - Repo name 
    - Repos github link
   - Repo components map (component <-> test suite <-> testing code)
    - Repo test suites, each test suite should have the following features:
           - Execution of the code
           - Map to a specific component in the repo
           - Related test cases description and steps
           - History 
                     - Execution time
                     - Execution date
                     - Execution results (pass, fail, still executing, stopped)
                     - How many test case 
 
.. To be continue

**Comment by AhmedHanafy725** [comment]
All needed features from this issue are specified on #543
