### ISSUE TITLE
As a user deploy a 3bot on a 0-OS node [development_3botdeployement]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#419]
Followup of https://github.com/threefoldtech/home/issues/415
Since #415 we can allow any user to deploy a 3bot, but the current deployment strategy as a few flaws:
- centralized
- 3bot owned and accessible by us
- not using grid capacity (0-OS)

We want to fix these issue by updating the deployment flow to use 0-OS containers.
The user story for this would be the following:

As a user that have a identity though the 3bot login app, I can deploy a personal 3bot server on any 0-OS node. 
To do so an flist containing all the code of the 3bot should exist.
With this flist, I can then create a reservation schema that contains a network definition, a volume and a container. Once this reservation sent to BCDB, I should be able to connect to my 3bot at `{double.name}.3bot.testnet.grid.tf`

Tasks :
- [x] Have a builder for 3bot flist https://github.com/threefoldtech/home/issues/465
- [x] [Adapt the chat flow so it generate the reservation schema and send it to BCDB](https://github.com/threefoldtech/jumpscaleX_threebot/issues/369)
  - [x] a chat flow to create a network will most probably

**Comment by despiegk** [comment]
part of this is already of another story card

**Comment by zaibon** [comment]
Can you link which one please ?

**Comment by despiegk** [comment]
threefoldtech/jumpscaleX_core#262 
was not story is fr

**Comment by despiegk** [comment]
revise content
