### ISSUE TITLE
fix auto upgrade of BCDB record when fetch [development_bcdbautoupdate]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#421]
fix auto upgrade of BCDB schema's in simple form : threefoldtech/jumpscaleX_core#261

meant as quick fix for what we need now

**Comment by despiegk** [comment]
done see https://github.com/threefoldtech/jumpscaleX_core/pull/282/files

**Comment by gmachtel** [comment]
Fixed partly, scheme object only checked for root object.

**Comment by despiegk** [comment]
I did it for subobj
