### ISSUE TITLE
filemanager / office solution on tfgrid & 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#427]
# goal

Have a solution which allows us to start using our TFGrid and personal 3bots for certain of our office/filemanagement requirements no longer having to use gdrive, right now its weird we do everything there seen our decentralized goal

## ideas

- install X onlyoffice instances who can work with multiple 3bots as backend
- filemanager is on 3bot directly, if click on office file go to a onlyoffice server which can do the editing, onlyoffice server is central not per user
- person authenticates by means of 3botconnect to the onlyoffice, the onlyoffice server knows because of that authentication the 3bot to go to, on that 3bot the filemanagement interface is used (webdav or ?)
- support pdf, slides, spreadsheet, docs
- if possible collaboration between users on 1 doc
- a GUID link which allows people to see the files/docs in a folder on the filemanager, read only, so the only thing needed is the GUID link which is unique and it gives them RO rights
- user can define circles in 3bot (groups of 3bot users)
- ACL on dir/file based on circles, in other words remote user can see dir or file based on ACL

**Comment by ken-de-moor** [comment]
This was finished and followup in deployment is done in other issues ( Flist & Helm )
