### ISSUE TITLE
tfgrid tfprimitive provisioning usable by all phase 1 [development_provisining]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#429]
## goal

- make sure everyone knows how to provision ZDB/container/network
- goal is to have the low levels understood & documented
- this is only phase 1, look at other story for phase 2

### deploy container ubuntu + wireguard :

- can start from example script below
- query directory on explorer to find node
- deploy ubuntu on that node
- deploy SSH key on that node
- create wireguard server config
- create client wireguard config
- connect wireguard, see we can ping the ubuntu server & login using SSH
- only requirement: is a locally deployed JSX env

### multi container + private network + wireguard

- same as above, only deploy 3 ubuntu's on 2 locations
- make private network between the 3 ubuntu's
- create wireguard connection from local machine
- ping/ssh to the 3 ubuntu's
- let the ubuntu's ping to each other

### container with corex

- start container with corex
- show how to start something in corex using JSX coreX client

### multi zdb

- deploy 2 ZDB
- test connection to the ZDB

### threebot basic

- deploy flist for threebot based on development branch
- do wireguard connection from local machine
- use rsync (exists in syncer tool) to push code over from local machine over wireguard connection
- start 3bot client to do a ping 

## deliverables

- put in a package on threebot repo
- documentation in wiki in that package
- create a factory where the scripts can be called (can do as test script in test/ dir)

## not to do

- no need for high level actors on 3bot centrally

## questions

- how do we know that the install succeeded?
- is something went wrong how can we see what went wrong
- has the aggregation of monitoring info been done to redis on core0 level?

## Examples:
- [x] [ubuntu containers](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_provisining/ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh.py)
- [x] [0-DBs](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_provisining/ThreeBotPackages/tfgrid/provision_examples/zdb.py)
- [x] Corex usage
- [ ] 3bot

**Comment by despiegk** [comment]
https://cockpit.testnet.grid.tf/web/gedis/http/nodes/list

**Comment by zaibon** [comment]
>  how do we know that the install succeeded?

The reservation schema contains a result object for each workload
> Is something went wrong how can we see what went wrong

The reservation schema contains a result object for each workload

> has the aggregation of monitoring info been done to redis on core0 level?

no

**Comment by zaibon** [comment]
As of today the testnet explorer is broken and there is no way to test the scripts nor to deploy any workloads.

Also there is not yet a working 3bot flist, so this part is not done. But there is nothing special about deploying a 3bot compare to deploy any other container so the documentation/example present already covers it.

**Comment by zaibon** [comment]
Yesterday I managed to restart the testnet explorer.

All the example script except the one for 3bot are done and available at : https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/tfgrid/provision_examples

3bot is not done cause https://github.com/threefoldtech/jumpscaleX_core/issues/262 is still in progress so there is no 3bot flist yet. But would anyone want to write the reservation for it, that is exactly the same as any other container and there are already example for that. So I'll move this task to verification
