### ISSUE TITLE
tfgrid tfprimitive provisioning usable by all phase 2 [development]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#430]
## goal

- make sure everyone knows how to provision ZDB/container/network/tcprouter/coredns
- goal is to have the low levels understood & documented

### deploy container ubuntu + wireguard + http(s) entry point

see #429 
but add

- deploy webserver on the ubuntu (hello world ok)
- configure TCPRouter + CoreDNS to expose https://mywebsite.something.com
- point local resolver to coreds so we get that dns back
- check we can get to the webserver

### basic S3 server

- deploy 10x ZDB
- deploy our S3 server
- configure it to use the 10x ZDB over zero-stor
- check the S3 server is working
- configure a login/password on the S3 server
- make connection through wireguard and use S3 client to push / download a file
- kill 2 ZDBs, show S3 server still works

### basic 3bot server

- same as in #429  but add https access to it

## deliverables

see #429 
can be in same package

**Comment by zaibon** [comment]
All these example requires tcp router client to be available. So this is blocked until https://github.com/threefoldtech/jumpscaleX_threebot/issues/277 is done.
