### ISSUE TITLE
namespace is in read only mode (when starting threebotserver)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#433]
StackTrace:

**Comment by andrewayoub** [comment]
![image](https://user-images.githubusercontent.com/5163693/69552413-184ee480-0fa7-11ea-88e3-071473089b66.png)
in zdb logs
![image](https://user-images.githubusercontent.com/5163693/69552503-3b799400-0fa7-11ea-91d7-fa7f5e9181fb.png)

**Comment by andrewayoub** [comment]
![image](https://user-images.githubusercontent.com/5163693/69552980-07eb3980-0fa8-11ea-8d58-2c0c8c10ea85.png)

**Comment by andrewayoub** [comment]
the problem was that zdb client doesn't select the correct namespace, I added the following line to zdbclientbase 
![image](https://user-images.githubusercontent.com/5163693/69554585-ac6e7b00-0faa-11ea-9163-3705874946de.png)

**Comment by Pishoy** [comment]
@andrewayoub is it merged to development ?

**Comment by andrewayoub** [comment]
@Pishoy No, it's still on development_actorsimprovements
