### ISSUE TITLE
As a user, login from trusted device without entering pin

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#435]
If a user logs in from a trusted device, on a known service (so scope settings are known), the user should be auto logged in. The device will sign the request because a token (could be time based) is known/agreed between the browser and the device.

A token can be created on the trusted device (cookie / local storage). This token can be time based or fixed. The token can be sent to the mobile device for each login attempt.

- [x] Token creation
- [x] User accepts trusted device (token is accepted)
- [x] Auto login
- [ ] Testing

**Comment by DylanVerstraete** [comment]
Question: Where is the user accepting the device as a `trusted device` ? 
In the frontend I suppose, but on which page ? 

I suggest we prompt the user with this question after his first successful login with his mobile device and right before routing to the callback. There should also be an option somewhere to remove a trusted device, any suggestions on that ?

**Comment by jdelrue** [comment]
- Trusted device should be accepted in the "scopes screen". We can treat it as a scope, so applications can allow it if they pass the scope

- For the second one we probably need an entry in settings? Maybe @KristofVanstappen can help with how and where?

**Comment by DylanVerstraete** [comment]
Currently added 
- Token creation
 - User accepts trusted device (token is accepted)
- Auto login

Needs testing, and I propose we create a screen to remove these trusted devices from the app. This would be in the settings screen ?

**Comment by sasha-astiadi** [comment]
@ken-de-moor please take a look and clean up if its still valid or not
