### ISSUE TITLE
Technical: Convert backend to zerobot

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#438]
Backend is a normal flask applicaiton right now, next version should be running in a zerobot.

// More information needed!

**Comment by zaibon** [comment]
So the current code used to manages the identity of the 3bot connect app is currently https://github.com/threefoldtech/3Bot_connect/blob/release/v1.5.6/backend

This developed as a temporary solution and we should be able to now migrate to a more permanent system.
At the moment on the grid ecosystem the component that host the identities of the 3bot is the [explorer](https://explorer.grid.tf/)

These 2 must be merged into one. I see 2 possible path:
- 3bot connect keeps its API and just change its implementation to grab the identity data from the explorer
- the explorer implements the missing API endpoint to fully replace the current backend

**Comment by jdelrue** [comment]
I guess number 2 is the best way to go, however, we must be sure that we can support the backend in a very stable way. So maybe using number 1 as a first step would be better. In both cases we need to plan a migration. Also, when do we have the resources to properly do this.

**Comment by zaibon** [comment]
Implementing the code from the current backend into the explorer takes half a day.
I can get cracking on this and give you access on a version for you to test by tomorrow.

Then we indeed need a plan to migrate the data itself. We have identify that there are already some conflicts between the 2 databases.

**Comment by zaibon** [comment]
Had another look at this issue. And I don't think we should implement the full 3bot connect API on the explorer itself. This would bring too much thing on the explorer that cannot be the right approach.

I think the explorer already exposes the required API for the 3bot connect to be able to use it as source for the identities.

Now we still need to merge the databases and for this there are things to decide:
- which db has dominance in case of conflict ?
- how do we resolve these conflict with the user ?
- explorer makes the names and email unique. I don't think that was a requirements in 3bot connect.

**Comment by despiegk** [comment]
I would like to be part of this discussion, lets resolve for 2.1
