### ISSUE TITLE
Technical: Convert wallet to non-webpack build + JSX package [development_jsxwallet]

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#439]
The wallet should be converted to a non-webpack build and have support to be loaded as a JSX package.

- [ ] Add package.py
- [ ] Remove webpack, use weblibs
- [x] Add Vuetify 2.0
- [ ] Add stellar SDK instead of Rivine

Testing
- [ ] Use from app (auto login)
- [ ] Check key compatibility
- [ ] Send tokens
- [ ] Receive tokens
-> List to be extended

**Comment by coeneivan** [comment]
Vuetify 2.0 is now being used :)
https://github.com/JimberSoftware/3bot_wallet/pull/4
