### ISSUE TITLE
Testing Some Clients [development_testing_clients]

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/home#451]
This story will include testing the following clients:

- [x] Currency Layer: https://github.com/threefoldtech/jumpscaleX_core/issues/291
- [x]  ssh agent: https://github.com/threefoldtech/jumpscaleX_core/issues/292
- [x] Fix sshkey_client tests
- [x] Fixing registry client tests 

## related issues

- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/292
- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/293
- [x] https://github.com/threefoldtech/jumpscaleX_core/issues/291

**Comment by despiegk** [comment]
is that really for now or for future?

**Comment by ramezsaeed** [comment]
yes its for now, its already almost done
