### ISSUE TITLE
threebot/tfgrid packages cleanup [development_cleanup]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#455]
continuation of https://github.com/threefoldtech/home/issues/377

- all indexed fields aren't optional
- actors should be decorated with `@j.baseclasses.actor_method`
- actors should have schema_out
- package documentation should go into PKG_NAME/wiki directory
- reusable servers should go into jumpscale repos
- need to make sure we only use j.threebot... (no longer the self.... on packages)
- no need for factories in the packages
- no more meta.toml -> package.toml. frontend flag in package.toml now under `source` section
- SPA directory should be `frontend` not `html`
- Static website directory should be `html`
- no static assets to be distributed when you can use weblibs for it (weblibs exposed on `/weblibs` location)

**Comment by xmonader** [comment]
remarks from @Dinaamagdy on zerobot packages/docs

> ## Docs
> * package.toml missing here
>   https://github.com/threefoldtech/jumpscaleX_threebot#creating-a-new-package
> * wrong url in almost pacakge ex:myjobs
>   https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/myjobs_ui/wiki/README.md#running
>   instead of `https://172.17.0.2/myjobs` should  be  `https://172.17.0.2/zerobot/myjobs_ui` same for alerta and package manager ,etc
>   -- should add that alerta added by default too here https://github.com/threefoldtech/jumpscaleX_threebot#starting-the-server

**Comment by despiegk** [comment]
@jdelrue is this one done for you?

**Comment by tobiaschielens** [comment]
We are working on this.
We removed the static assets from webplatform and we are fixing issues in order to make the front-end work again.

**Comment by xmonader** [comment]
@tobiaschielens webplatform needs to be moved out of zerobot directory as well https://github.com/threefoldtech/jumpscaleX_threebot/issues/278
