### ISSUE TITLE
Explorer 2.0.1 [development_explorer]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#456]
## requirements

- [x] actors tested:
    - [x] farms
    - [x] nodes
    - [x] workloads manager (some further tests)
- [x] deploy new version (erase db)
    - [x] waiting actors (thursday 12, 14h) thabet
- [x] 3bot init
- [x] 3bot server started with correct packages 
- [x] modify zos to use new cmds to add farms, nodes, deal with workloads. https://github.com/threefoldtech/zos/issues/443

## remarks

- [x] make sure branch is used !!!

**Comment by serboctor** [comment]
farms, nodes, and workloads were tested on Sunday. I believe we need to do another round of testing when we're done with all changes in this release before updating the explorer.

**Comment by gmachtel** [comment]
As agreed during call, nothing blocking this one (no 3bot registration in first step), and critical for launch of the grid. So changed to prio_critical.
