### ISSUE TITLE
threebot flist builder & tester part 1 [development_threebot_builder]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#465]
## requirements

- [x] use ```jsx threebotbuilder``` to build a threebot
- [x] add a feature to the threebotbuilder to create flist from this container & upload to hub
    - [x] zflist = cli on top of libflist, use this tool to create a chroot dir which get's uploaded to hub
- [x] launch 3bot on the tfgrid
    - [x] launch the flist on a ZOS in TFGrid see the threebot starts
         - [x] create a JSX script to start a 3bot on tfgrid
    - [x] corex gets started with a secret
    - [x] configure wireguard interface while launching the threebot container
    - [x] use wireguard client in jumpscale to connect to the configure network
- [x] use corex to further configure the 3bot
    - [x] use defined SSH pub key to allow remote connection to the threebot container
    - [x] test SSH access over the wireguard
    - [x] test client to threebot

## checklist

- [x] coreX used to expose the threebot itself (the shell is visible)
- [x] passwd set on the coreX
- [x] wireguard to access the network on zero-os which is connected to the 3bot container
- [x] only jsx tool used to create the flist

Deliverable by first week of Feb

**Comment by BolaNasr** [comment]
# launch 3bot on the tfgrid using flist

### create your own threebot flist and upload it to hub
- ***Applicationid*** of itsyou.online
- ***SECRET*** of itsyou.online
- ***USER_NAME*** of hub.grid.tf

```python3
/tmp/jsx threebot-flist --app_id Applicationid --secret SECRET --username USER_NAME
```

###  launch the flist on a ZOS in TFGrid
- passing two env variables for coreX :
    ```buildoutcfg
    corex_user = COREX_USER_LOGIN
    corex_password = COREX_PASSWORD_LOGIN
    ```
- create port forward to 1500 ( default port) to see coreX page in web browser

**Comment by BolaNasr** [comment]
![image](https://user-images.githubusercontent.com/10259267/73466176-298ee580-438a-11ea-9a5f-8841d271cc84.png)
## After login 

![image](https://user-images.githubusercontent.com/10259267/73466217-3b708880-438a-11ea-92c4-c88ef4566ef8.png)

## check my job
![image](https://user-images.githubusercontent.com/10259267/73466269-4d522b80-438a-11ea-85a0-6575bd04a95c.png)

**Comment by BolaNasr** [comment]
**still in progress**

To create container of Threebot in zos v2: 

first should build ```tfuser``` tool from 
https://github.com/threefoldtech/zos/tree/master/docs/tfuser
**create your user id**
``` tfuser id```
**Then create your network and your wireguard configure** 
``` tfuser generate --schema network.json network create --name network --cidr 172.20.0.0/16```

```tfuser generate --schema schema.json network add-node --node qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3 --subnet 172.20.1.0/24 ```

```./tfuser generate --schema network.json network add-access --node qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3 --subnet 10.1.0.0/24 --ip4```

**Then copy the config of wireguard and up your wireguard using your config**

then craeate extra amount of your container 
``` tfuser generate storage volume --size 10 --type SSD > amount.json```

``` tfuser provision --schema amount.json --duration 5h --seed user.seed --node qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3 ```

**Then create your schema of container like that** 

``` tfuser generate --schema ubuntu.json container --flist https://hub.grid.tf/bola_nasr_1/threefoldtech-3bot-corex.flist --ip 172.20.1.42 --network YOUR_NETWORK_NAME  --entrypoint "/usr/bin/zinit init"  --envs corex_user=root --envs  corex_password=root  --mounts STORAGEID:/sandbox/code --mounts STORAGEID:/sandbox/var > ubuntu.json```

``` tfuser provision --schema ubuntu.json --duration 5h --seed user.seed --node qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3 ```


then can see your corex in ```172.20.1.42:1500```  -> **Still in progress  to autostart using our entrypoint**

**Comment by BolaNasr** [comment]
# launch 3bot on the tfgrid using flist

### create your own threebot flist and upload it to hub
- ***Applicationid*** of itsyou.online
- ***SECRET*** of itsyou.online
- ***USER_NAME*** of hub.grid.tf

```python3
/tmp/jsx threebot-flist --app_id Applicationid --secret SECRET --username USER_NAME
```

###  launch the flist on a ZOS V2 in TFGrid:

- first should build ```tfuser``` tool from 
https://github.com/threefoldtech/zos/tree/master/docs/tfuser

- **create your user id**:

    
  ```  tfuser id```
- **Then create your network and your wireguard configure** :
    - get Node_ID from https://cockpit.devnet.grid.tf/
    
    
    ```tfuser generate --schema network.json network create --name NETWORK_NAME --cidr 172.20.0.0/16

    tfuser generate --schema network.json network add-node --node NODE_ID --subnet 172.20.1.0/24 

    tfuser generate --schema network.json network add-access --node NODE_ID --subnet 10.1.0.0/24 --ip4```


- **Then copy the config of wireguard and up your wireguard using your config**
    
    
    sudo wg-quick up /etc/wireguard/demo.conf 

- **provision your network to your node**:


   ``` tfuser provision --schema network.json --duration 60 --seed user.seed --node NODE_ID```

- **create extra mount for directory that contain bcdb and logs files**:
    
    

    ```
    tfuser generate storage volume --size 10 --type SSD > amount.json
    
    tfuser provision --schema amount.json --duration 8h --seed user.seed --node NODE_ID```
    
- **create container of threebot**:
    - passing two env variables for coreX :
        ```buildoutcfg
        corex_user = COREX_USER_LOGIN
        corex_password = COREX_PASSWORD_LOGIN
        ```

```
tfuser generate --schema ubuntu.json container --flist  https://hub.grid.tf/bola_nasr_1/threefoldtech-3bot-corex.flist --ip 172.20.1.20 --network NETWORK_NAME  --entrypoint "/usr/bin/zinit init -d"  --envs corex_user=COREX_USER_LOGIN --envs  corex_password=COREX_PASSWORD_LOGIN  --mounts STORAGEID:/sandbox/var > ubuntu.json

tfuser provision --schema ubuntu.json --duration 5h --seed user.seed --node NODE_ID
```


- coreX page in web browser  ```172.20.1.20:1500```

**Comment by BolaNasr** [comment]
you can connect to your threebot container using our client 

![image](https://user-images.githubusercontent.com/10259267/74231167-9da48400-4cce-11ea-93aa-a50ed6bc252b.png)

**Comment by PeterNashaat** [comment]
- i tried many times the container gets created but i can't reach the container ?, will try again tomorrow.


https://explorer.devnet.grid.tf/reservations/3170-1

https://explorer.devnet.grid.tf/reservations/3174-1

**Comment by PeterNashaat** [comment]
- Verified the steps above and from chat bot both working and can reach the container.
