### ISSUE TITLE
postgresql docker test for 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#474]
## to do

- [ ] create docker image on our docker hub which is built with latest postgresql 
    - [ ] create docker build script for it so its easy to redo
- [ ] make sure postgresql has been built using https://github.com/pllua/pllua
- [ ] check can use lua stored procedure to go to redis server
- [ ] test the docker with max of 100MB and NO SWAP !!!, see its stable
    - see jumpscaleX_core/JumpscaleCore/clients/peewee/PeeweeFactory.py
- [ ] test the docker with max of 50MB and NO SWAP !!!, see its stable
- [ ] make sure postgresql client works in  j.clients.postgresql.get() (is it there)
- [ ] create function on psql client jsx for checking how much mem used
- [ ] create function on psql client jsx for checking how much storage used
- [ ] create function on psql client jsx for changing master passwd
- [ ] create function on psql client jsx for create/delete DB (set login/passwd)
- [ ] create function on psql client jsx to save lua stored procedure (trigger or so)
- [ ] create tests in psql client for lua trigger to go to a redis
- [ ] if all of this ok create an flist for this postgresql for ZOS
- [ ] create a test for master/slave replication between 2 containers (script in postgresql client in jsx)
    - [ ] question: can this be configured per table or is it per DB?

## remarks

- postgres/tf007 as default passwd

## the test for stability

- put 1m records in there see  jumpscaleX_core/JumpscaleCore/clients/peewee/PeeweeFactory.py
- do some random queries 

## to read

- https://docs.docker.com/config/containers/resource_constraints/

**Comment by rkhamis** [comment]
obsolete
