### ISSUE TITLE
jumpscale 10.2 repos mgmt

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#479]
## to do

- [x] sort issues with no milestone on core [see here](https://github.com/threefoldtech/jumpscaleX_core/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)
- [x] go over issues on lib & libextra & builders & threebot 
    - [x] make sure all "no milestone" issues processed, or on next/later or linked to story
    - [x] make sure all now issues are linked to story and relevant, if not cleanup, move to next/later remove labels/assignment/...
    - [x] remove old issues, better to delete then to keep dragging along
   - if question use coordinators group

**Comment by rkhamis** [comment]
Done with my issues.
