### ISSUE TITLE
Provide ability for the Js client to see transaction descriptions

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#48]
Initial Implementation (1st iteration):
- [x] List wallet transactions: 4h
- [x] Get transaction details: 4h

Improved Implementation (2nd iteration):
- [x] Define layout (design): 1h
- [x] Implement improved List Wallet transactions: 6h

**Comment by GlenDC** [comment]
Closed by 
https://github.com/threefoldtech/jumpscale_lib/commit/14d9895781cd117cd7cedf053466cb27cb82d510.

**Comment by GlenDC** [comment]
@robvanmieghem can you please verify, read the docs and play with it when you can. Let me know if it is more or less what you would expect of this feature.

**Comment by robvanmieghem** [comment]
reopened for verification: todo: 1h

**Comment by robvanmieghem** [comment]
list_transactions is a very detailed view of the transactions and it is hard to get the actual -/+ amounts since you have to refilter the coinoutputs with all your addresses. Having by default  a simpler version with id, blockheight, confirmed, sending addresses, receiving addresses, multisig( yes/no) and amount( +/-)  and a human readable default printing in js_shell would be nice.

**Comment by GlenDC** [comment]
@robvanmieghem please provide feedback or let's have a chat. Here is how the 2nd iteration version looks like:

* <https://github.com/threefoldtech/jumpscale_lib/tree/development_960/JumpscaleLib/clients/blockchain/tfchain#listing-all-incoming-transactions-of-a-wallet>:
   * shows how to list incoming transactions (renamed it, as it really does just show incoming transactions, ignoring outgoing ones as well as transactions from the same address to itself (refunds);
   * the format of the printing is: `height - txid :\n from_addresses -> to_address : amount`;
* <https://github.com/threefoldtech/jumpscale_lib/tree/development_960/JumpscaleLib/clients/blockchain/tfchain#get-a-transaction>:
   * I think the get_transaction function is pretty good as it is, UX wise. It is the only (of the 3) functions that I think I got 100% right, so I don't think we need to change something more here;
   * this functions returns a different type of transactions (python class-wise) than the other 2 functions;
* <https://github.com/threefoldtech/jumpscale_lib/tree/development_960/JumpscaleLib/clients/blockchain/tfchain#get-all-transactions-for-one-or-multiple-wallet-addresses>:
   * again it lists all incoming transactions for one or multiple addresses given;
   * format is the same as the same output, as it uses the same types under the hood as the first;

**Comment by robvanmieghem** [comment]
@GlenDC  Looks really good  and I think this is enough for 3bot.
Let's create a follow up issue to include the outgoing transactions which we can schedule in a later sprint.

**Comment by GlenDC** [comment]
OK, in that case will make sure to:

- [ ] double-check the current code,
- [ ] ensure my test coverage is OK,
- [ ] create a follow-up issue,
- [ ] and close this issue.
