### ISSUE TITLE
Make green run for jumpscalex  tests [development_green_run]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#480]
## deliverables

- [ ] REDO THIS STORY

## tests to be done for Jumpscale_core :
- [ ] servers
     - [ ]  imap server(https://github.com/threefoldtech/jumpscaleX_core/issues/445)
     - [ ]  threebot server (https://github.com/threefoldtech/jumpscaleX_threebot/issues/351)
- [ ] Installation 
     - [x] insystem 
     - [x] docker
- [ ] SAL(https://github.com/threefoldtech/jumpscaleX_core/issues/451)
- [x] clients 
   - [x] sonic : threefoldtech/jumpscaleX_core#250 
   - [x] redis_config : https://github.com/threefoldtech/jumpscaleX_core/issues/453
- [x] BCDB https://github.com/threefoldtech/jumpscaleX_core/issues/455

### Libs
- [x] github client

### Libs_extra
- [ ] radicale server 
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/197
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/193
    - [ ] https://github.com/threefoldtech/jumpscaleX_threebot/issues/198
### Threebot
- [x] wikis (high) 
- [x] threefold registry (high)
- [x] package token 
- [x] workloadmanager (high)
- [x] directory (high)
- [x] bottle_web (high)
- [ ] phonebook (high)
 threefoldtech/jumpscaleX_core#326

**Comment by rkhamis** [comment]
Closing this story in favor of the new testrunner #516
