### ISSUE TITLE
Create taiga flist

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#482]
Create taiga flist and automate all changes to be as container environment variable and test it .

### related Issues:
- [ ] https://github.com/threefoldtech/Threefold-Circles-Flist/issues/1

**Comment by Pishoy** [comment]
taiga flist created has been deployed bu autobuilder and tested in container in our zos 
https://hub.grid.tf/tf-autobuilder/threefoldtech-Threefold-Circles-Flist-autostart-master.flist
