### ISSUE TITLE
As a user, get feeds in the app

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#486]
Story is 2 parts:
- Changes in FFP
- Changes in app
# Changes in FFP

We need an extra screen for spaces so they are shown as feeds, particularly for these groups:

![image](https://user-images.githubusercontent.com/1687505/70899215-76934400-1ff6-11ea-949a-6c0d59f67966.png)

- [ ] Menu on top
- [ ] Choose between pages
- [ ] Remove obsolete parts
- [ ] Remove crisp button

![image](https://user-images.githubusercontent.com/1687505/70899835-d1796b00-1ff7-11ea-95a1-86b38f420677.png)

# Changes in App

Home button should say "feeds" and load the FFP view as webview

**Comment by sasha-astiadi** [comment]
this feature no longer exists so i close it
