### ISSUE TITLE
Threebot Blog UI changes [development_web]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#487]
General Changes
https://drive.google.com/drive/u/1/folders/1ibfvOJkBb6yAQGzGJro-wWbTj94cAMX-

**backend**

- [x] update package & blog loader to align with threebot packages
- [x] restore _api files and use it in components
- [x] make it able to run in development server
- [x] update api calls to new gedis end points
- [x] update docs, make sure it's running without server

**frontend**

- [x] Set Favicon (see docs folder)
- [x] Remove navbar / footer, as these point back to blog overview (options added to remove the navbar/footer)
- [x] Change social icons (see docs folder)
- [x] Remove Disquss (I think already did but verify please)
- [x] Set post count to even number (pagination looks like disaster now)
- [x] See how we can use different images for different authors

Post overview Changes:
- [x] Make image as wide as the text in the column
- [x] Move authorimage underneath image
- [x] Move date and put in european order
- [x] apply same style to tags as seen in side bar and move below post snippet.

Left post = new
Right post = current

![Screenshot 2019-11-19 at 14 50 35](https://user-images.githubusercontent.com/29431263/69157430-2f905c80-0ae5-11ea-8576-557b36fd5945.png)

Post Detail page changes:
- [x] Align image with sidebar box
- [x] Move Author + date underneath image + date european style
- [x] Move tags underneath image and apply sidebar style
- [x] Repeat same tags at bottom of post

![Screenshot 2019-11-19 at 16 02 12](https://user-images.githubusercontent.com/29431263/69158108-32d81800-0ae6-11ea-85ac-579b151963f8.png)

![Screenshot 2019-11-19 at 16 02 18](https://user-images.githubusercontent.com/29431263/69158109-32d81800-0ae6-11ea-826b-3a63815a9203.png)

**Comment by xmonader** [comment]
@VonSub I created this issue to track blog UI change requests

**Comment by waleedhammam** [comment]
Blog package loaded ok and actors loaded & works at commit: `https://github.com/threefoldtech/jumpscaleX_threebot/commit/96378c90b8606332cf003187ee2a2dad4de9ea63`

**Comment by waleedhammam** [comment]
- Development server now works at commit: **https://github.com/threefoldtech/jumpscaleX_threebot/commit/dc5242e9b0ba0919f363db38b413eb44b51cfe3d**

To run it use:

```bash
cd sapper-blog
export DEV=1
npm install
npm run build
node __sapper__/build
```
then go to `YOUR-CONTAINER-IP:3000/blog`

**Comment by abom** [comment]
Pagination bar now is always at the bottom (fixed at https://github.com/threefoldtech/jumpscaleX_threebot/commit/7a20934a246fa32c13d7f2fa8d9f36e6dcdead4a).

Also, fixed jsx blog loader at https://github.com/threefoldtech/jumpscaleX_threebot/commit/962846d41707ca5719734435618bf6bba4426c1e.

**Comment by abom** [comment]
Fixed passing metadata to `Nav` component at https://github.com/threefoldtech/jumpscaleX_threebot/commit/ecae737bc137b45928df536f4a5b681984063e99.

**Comment by xmonader** [comment]
@VonSub  I consider all of the features done are we good to go or not?

**Comment by VonSub** [comment]
@xmonader as discussed just now in chat we still need the button to return to the post overview when the navbar is hidden. (like the taiga blog) but that is out of scope for this issue I think.
