### ISSUE TITLE
jumpscale 10.2 hotfixes [development_hotfixes] 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#488]
Here link all of hotfixes that needs to go into development

- [x] fix bcdb rebuild index https://github.com/threefoldtech/jumpscaleX_core/pull/373/files 
- [x] fix imap server start https://github.com/threefoldtech/jumpscaleX_libs/commit/d96a83013d6d156903c39fa3fb4343191b8f55c4
- [x] import fixes https://github.com/threefoldtech/jumpscaleX_core/pull/372/commits/52a505bd9b2315535e6025f75cdcd9909604aa0b

- [x] zdb admin client not authenticated anymore after creating a new namespace with a new name https://github.com/threefoldtech/jumpscaleX_core/issues/361

**Comment by Pishoy** [comment]
verified
```
bcdb rebuild
``` 
```
kosmos -p 
j.servers.imap.start()
```
```
j.data.bcdb.test(name="export")'
```
```
kosmos -p 'j.clients.zdb.test()'
```
