### ISSUE TITLE
wiki fixes [development_wiki_fixes]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#489]
- [x] make sure basic loading works
- [x] macros
  - [x] include
  - [x] gpdf
  - [x] gallery
  - [x] dot macro
  - [x] slideshow 
  - [x] slideshow vs2
  - [x] check links and docsite loading

**Comment by abom** [comment]
There's a problem with `logChanges()` of git client, it returns some paths in the format of `/path/to/file\t/path/to/file` which is invalid.

**Comment by abom** [comment]
Fixed links and loading, files referenced in links was copied and replaced processed files.

Also fixed dot and include macros, and custom link format.

**Comment by abom** [comment]
@waleedhammam Fixed slideshow macros.

**Comment by abom** [comment]
Note that slideshow uses `reveal.js`, only a single reveal container should be included in a single page, so, only one slideshow macro per page is recommended.

**Comment by abom** [comment]
To run wikis, you can add `zerobot.wiki_examples` package and wait until it's loaded in background, then access it at `http://<container ip>/zerobot/wiki_examples/wiki`.

Also, to manually force reload, you can do something like:

```
JSX> p = j.tools.threebot_packages.get("tfgrid.registry")
LOAD CONFIG BCDB
JSX> p.load_wiki(reset=True)
```

**Comment by Pishoy** [comment]
all test are okay except first tab on left called Test not working, give below picture while i installed graphviz

![image](https://user-images.githubusercontent.com/21987477/71192883-c80b2f80-2291-11ea-8b67-c68ea6343631.png)
- jsx version
```
3BOTDEVEL:3bot:jumpscaleX_core: git log -1
commit 7cb4bda879ea1fd7902c438e51bca6fd4bf5d959 (HEAD -> development_wiki_fixes, origin/development_wiki_fixes)
Merge: 273a80c f98a049
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Thu Dec 19 15:45:53 2019 +0200

    Merge branch 'development' into development_wiki_fixes
3BOTDEVEL:3bot:jumpscaleX_core: cd /sandbox/code/github/threefoldtech/jumpscaleX_threebot/
3BOTDEVEL:3bot:jumpscaleX_threebot: git log -1
commit 6044e9a7a37427d103a58a489c8023b11449ab48 (HEAD -> development_wiki_fixes, origin/development_wiki_fixes)
Merge: fb33f73e 93f5d7ff
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Thu Dec 19 15:46:08 2019 +0200

    Merge branch 'development' into development_wiki_fixes
3BOTDEVEL:3bot:jumpscaleX_threebot: 

```

**Comment by abom** [comment]
@Pishoy If you installed `graphviz` after loading this wiki, you need to reload it with `reset=True`
