### ISSUE TITLE
Unskip jumpscale tests [development_green_unskip]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/home#491]
due to  latest milestone , go through jumpscale tests  and unskip tests  which its bugs fixed and make suitable changes to make it green run  
- [x] clients
     - [x] git
     - [x] mail 
     - [x] redis 
     - [x] sonic 
     - [x]  ssh client
     - [x] sshkey
     - [x] tfgrid 

       
- [x] servers 
    -  [x]  test_servers 
    -  [x]  smtp_imap servers
    -  [x] threebot
    -  [x] tmux
    -  [x] zdb
     - [x] gedis  
     - [x] odoo

- [x] installation
  - [x] insystem 
  - [x]  container
- [x] SAL 
  - [x] fs
  - [x] process

**Comment by Dinaamagdy** [comment]
@Dina-Abd-Elrahman  please takecare of clients pleaese

**Comment by Dinaamagdy** [comment]
@AhmedHanafy725  tak care of sal , please

**Comment by Dinaamagdy** [comment]
I will pickup installtion and servers

**Comment by Dina-Abd-Elrahman** [comment]
- no skip test cases was needed to be removed.

**Comment by Dina-Abd-Elrahman** [comment]
- working on smtp_imap server.

**Comment by AhmedHanafy725** [comment]
SAL is done on https://github.com/threefoldtech/jumpscaleX_core/commit/b8d39cd855b62d105ac331dc38c10547786c52cf

**Comment by AhmedHanafy725** [comment]
#### Installation
- in system done on https://github.com/threefoldtech/jumpscaleX_core/commit/75891a615a4cb28c893775071bdf0cbd8063cbdd
- `wiki-load`, `wiki-reload` options are no longer used, as `3git` is used now

**Comment by Dinaamagdy** [comment]
all done
