### ISSUE TITLE
3bot authentication [development_gedisauth]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#492]
- [ ] [restore gedis authentication](https://github.com/threefoldtech/jumpscaleX_core/issues/326)
- [ ] [threebot client over http](https://github.com/threefoldtech/home/issues/431)

**Comment by gmachtel** [comment]
Ongoing, centralized setup for this release.

**Comment by zaibon** [comment]
closed in favor of https://github.com/threefoldtech/zos/pull/602
