### ISSUE TITLE
rework executors/sshclient to work good enough for our 10.2 [development_executor]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#494]
los of issues found, rather than patching it, its better to rework some of it,

needs to be reviewed/documented

**Comment by waleedhammam** [comment]
- Commit: https://github.com/threefoldtech/jumpscaleX_core/commit/22b0df45a6a62f75f8ee0f9d3ca9d83f339d318d, https://github.com/threefoldtech/jumpscaleX_core/commit/51d9348728343756df09542ea6e0f5c2ff180983

- Added some fixes for ssh client and executors

- Main functions work now (execute, download, upload)

- README at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_executor/JumpscaleCore/clients/ssh/README.md

**Comment by waleedhammam** [comment]
**Commits** https://github.com/threefoldtech/jumpscaleX_core/commit/ee6fc2125be7556f42768e678a4ff01a1c6ec238, https://github.com/threefoldtech/jumpscaleX_core/commit/15b34e75c3ed3d96ca9830f100cc9eec1fda51c7

**Changelog**
- Fixed some old bugs.
- port forwarding to local works ok
- port forwarding to remote works ok
- update readme

**Comment by waleedhammam** [comment]
docs are updated at: https://github.com/threefoldtech/jumpscaleX_core/blob/development_executor/JumpscaleCore/clients/ssh/README.md

**Comment by xmonader** [comment]
branch verified by @despiegk
