### ISSUE TITLE
3Bot Connect 1.4.0 [development_webplugin]

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#498]
# 1.4.0
1.4.0 will include new webview widget and a full refactor.

## NOW

Following issues are still open to finish 1.4.0:

## NEXT (NICE TO HAVE)
- [ ] Recover account screen Error messages should be more consistent. Name / Name, Email / email phrase / Seedphrase ....
- [ ] When going through the registration, we should auto focus the input fields so that users don't need to re-click them when typing in their information. 
![image](https://user-images.githubusercontent.com/7256303/71716303-8becd880-2e14-11ea-8beb-780dd3733464.png)
- [ ] When registering and clicking the next button without entering a name, we get the same exception as before during the recovery screen. **This seems to be happening on all input fields.**  (Could be caused by: Async onpressed or Navigator.pop(context);)
- [ ] Try to 'fix' the "Finishing" step in registration, this looks weird when the email is cut off.
![image](https://user-images.githubusercontent.com/7256303/71716008-a4a8be80-2e13-11ea-9f5a-ebc2027c484a.png)
- [ ] Another exception happens when trying to click the recover account button without any data. (Could be caused by: Async onpressed or Navigator.pop(context);)

## LATER
- [ ] When confirming the seed phrase, we could trim the input field and make sure people can't re-use the same word three times.
- [ ] Pincode screen looks a bit empty, this could use a small re-design. 
- [ ] Fingerprint layout is not pretty since fix on cheap phones

## FIXED

- [x] version 
- [x] Remove account from device 
- [x] Notifications sometimes dont work ( ie email verified)
- [x] FFP when no valid email bug
- [x] Initscreen images not working
- [x] "Enter Valid Email" has too much capitalization and could be a bit more friendly.
- [x] Can't verify email or the UI doesn't update? (Needs to be checked) 
- [x] Switch to FFP and open correct page when clicking circle 
- [x] Change name to Circles like version that wouldve been released 
- [x] Main logo doesn't contain text "connect".
- [x] 'Register Now!' button doesn't need an exclamation mark and "Now" doesn't need to capitalized. 
- [x] Clicking the button triggered an exception, due to the fact that their is still a "logger.log" there.
![image](https://user-images.githubusercontent.com/7256303/71715914-4f6cad00-2e13-11ea-9448-1f8582d469a2.png)
- [x] The extra error above the button seems to be redundant in this scenario
![image](https://user-images.githubusercontent.com/7256303/71716210-3c0e1180-2e14-11ea-8913-5e5dff3fa5d5.png)
- [x] This information means nothing to the user and should be adjusted. 
- [x] Fingerprint test [not working on cheap phones]
- [x] Recover account not working
- [x] Click in and out of window before login is finished
- [x] Autologin some vuex problem
- [x] Mobile login
- [x] QR code without FB

- [x] More testing with wallet (maybe change login procedure to just inject PK in localstorage instead of dancing around) 
- [x] Email verification is not queued: Close app, verify mail, open app, mail is not verified 
- [x] Link TO ffp ON ffp -> no inappbrowser
- [x] Design of open 3bot app button + text
- [x] Mobile login not working when app is NOT started
--
- [x] Go back to browser after mobile login attempt
- [x] Socket security

**Comment by MathiasDeWeerdt** [comment]
Added more bugs/enhancements.

**Comment by azertyalex** [comment]
# Remarks:
- Opening app shows white screen too long, add spinner?

# Bugs:
## Opening the app without internet connection gives user unfriendly error

<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/9082988/71773276-d1b3b900-2f5a-11ea-9391-c3245ff0f2a4.png)
</details>

**Comment by azertyalex** [comment]
Tested on android 8.1

# Bugs
## Resend notification is buggy
It doesn't always work
