### ISSUE TITLE
threebot simple mail server [development_simplemail]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#499]
A simple mail server to receive, save, search  and send emails with html, txt and md content.

**Comment by waleedhammam** [comment]
Working on this approach:

- Simple SMTP server like: https://github.com/abunsen/inbox.py will be used as our mail server. It will receive all the emails from a specific domain or host, filter and store them, also will store attachments in a specific location.

**Package actors**:
- send -> will be used to send emails using sendgrid api
- search -> will search into the stored inbox

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
