### ISSUE TITLE
integrate available jumpscale tests in zeroCI [development_jstests]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#501]
Make sure all of the tests bundled with jumpscale in general, are integrated in zeroCI 

e.g base types https://github.com/threefoldtech/jumpscaleX_core/blob/d8ab86c405144f7b6811827991f2b97f7a933ccc/JumpscaleCore/data/types/tests/3_dict.py#L14 tests weren't integrated

**Comment by AhmedHanafy725** [comment]
JSX tests are added here
https://github.com/threefoldtech/jumpscaleX_core/commit/8164e1ee01c914693948791a27063388a670c118
https://github.com/threefoldtech/jumpscaleX_core/commit/109c9d184970e4828636be9a7243861686ef12d5
And result on zeroCI [here](https://zeroci.grid.tf/repos/threefoldtech%2FjumpscaleX_core/development_jstests/5e1b15fc75a7fa06db86a218)

**Comment by xmonader** [comment]
all merged in

**Comment by Dinaamagdy** [comment]
verified on dev
