### ISSUE TITLE
Test environment for 3bot infrastructure [development_deploy_infrasturcture]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#502]
replicate the 3bot infrastructure for testing

- prev story https://github.com/threefoldtech/jumpscaleX_threebot/issues/50

- [x] [update script ](https://github.com/threefoldtech/jumpscaleX_threebot/issues/333)
- [x] deploy testing infrastructure

Deliverable by first week of February

**Comment by ranatrk** [comment]
**[development_deploy_infrasturcture]**
After script is complete, there were a couple of issues in testing how the infrastructure actually works and the packages and actors used in the flow. Still WIP, but the following fixes were done :

https://github.com/threefoldtech/jumpscaleX_core/commit/fadf6592dc4235be6a12b255e981e4c6cd1f27d4
https://github.com/threefoldtech/jumpscaleX_threebot/commit/23c7b9f00910f5bc6c1435d39c8931abda1bc9cd

The flow in https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_deploy_infrasturcture/ThreeBotPackages/tfgrid/registration/actors/registration.py is being followed and reached domain registration using namemanager

**Comment by ranatrk** [comment]
After re installing and deploying the infrastructure, the steps worked well until reaching the use of the actor of the namemanager again where after adding and installing the package the actor is not loaded for the package. Looking into it.
https://github.com/threefoldtech/jumpscaleX_threebot/commit/c0dfe8b10bbb171ff879eb75bfa1d54c01549174

**Comment by ranatrk** [comment]
Fix actors used in registration script : https://github.com/threefoldtech/jumpscaleX_threebot/commit/504e1f389ab878ad2653ab8f77aa9b1c3b6c1fe9

**Comment by ranatrk** [comment]
To be able to test using the domains created, and to avoid conflicts with `testnet.grid.tf`, added to the configurations to use `archive.tf` instead where the 3bot record will be `3BOT_NAME.archive.tf` . After adding the records to redis and trying to use `dig 3BOT_NAME.3bot.archive.tf` to see if correct results are returned but so far still 0 answers from the dig query. Still investigating the configurations and will look into coredns logs

**Comment by ranatrk** [comment]
- Fixes done in setupinfra_new script, and gateway,registration,and namemanager actors.
- Deployed initial infrastructure with one tcprouter(+coredns) where a new 3bot can register with the following `....tfgrid.registration.actors.registration.register(threebot_name=THREEBOT_NAME,email=EMAIL,description=DESCRIPTION) 
`
- The registered 3bot will have the following domain : THREEBOT_NAME.threebot.gateway.tf

https://github.com/threefoldtech/jumpscaleX_threebot/commit/60a68a7eb4cdbaf0ef3747eda066e0b94dbc7a55

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/effd39fecafb16606234b9a960db88074d02130c
Explorer IP: 128.199.32.174
DNS Machine 1 IP: 142.93.158.221

**Comment by ranatrk** [comment]
Both flows now work, fix in using tcprouter and service : https://github.com/threefoldtech/jumpscaleX_threebot/commit/2d3b6964ea356c32a046cdd8329e69d1bccf0162

docs: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_deploy_infrasturcture/docs/explorer/infrastructure.md

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
