### ISSUE TITLE
rework jsx installer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#504]
when we have time installer has many scenarios and options resulting many problems and complexities beyond the normal use case of using bunch of python code :) 

installer should 
- allow in system installation
- allow in container installation
- be boostrapped from a docker image 
- based on ssh-agent

**Comment by despiegk** [comment]
this is not a story,

amazing amount of time has been put in the installer
instead of re-working which will result in much more time loss I would like to see where issues are and I am sure its easy to resolve.

if we feel something needs to be done then create a good story
