### ISSUE TITLE
JumpScale New Test Framework[development_testrunner]

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/home#505]
## Goals:
- Doing a test runner engine that define all helpers that is needed to write tests
- Adapting all  tests cases and making sure they all are using the new test runner.

## Requirements:
- Please find all test runner engine requirements here: https://github.com/threefoldtech/jumpscaleX_core/issues/190
- Make sure everything is running as a part of `j` and can be exposed as collection of tests or only one test.

## Related tasks
- coding: https://github.com/threefoldtech/jumpscaleX_core/issues/190 
  - [x] before, after (setupClass, teardownClass)
  - [x] before, after each function  (setup, teardown)
  - [x] skip: use a custom Skip Exception
  - [x] able to run test suites
  - [x] reporting
  - [x] docs 
- updating existing tests: https://github.com/threefoldtech/home/issues/516

**Comment by xmonader** [comment]
if too big we can split that into another story, docs can be minimal at this point

**Comment by john-kheir** [comment]
Done
