### ISSUE TITLE
As a user I want to change the order of my wallets.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#507]
# What
It should be possible to change the order of the wallets. Currently they are displayed in the order they are created and this can not be changed.

# How
The user should be able to drag a wallet card to any position by holding down their finger and dragging the wallet to another position. This should re-order all the wallets.

Don't forget to store the order of the wallets in PKID so the user will always see the same, even after recovery.

**Comment by JonasWijne** [comment]
doe to the complecity of differentiating between imported and app wallets this is a lower priority
