### ISSUE TITLE
As a user, I should be able to mark wallets as public and send TFT to other public wallets based on 3bot name.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#508]
# What
Currently it is not user friendly to always require a wallet address to be able to send TFT.

We could get all the public wallets from a specific user using PKID.

# How
This User Story exists of 2 parts. The create/edit wallet where a user can set/change the name and/or make the wallet public/private and the create transaction where a user can find public wallets of users.
## Create / edit
In the details of a wallet it should be possible to set a wallet as public. When the user attempts to set this wallet as public the following warning should pop up.  
> Setting a wallet as public will allow other users to find your wallet. 
> Are you sure you want to continue? 
> Yes/Cancel
### Mock up
![creaete wallet](https://user-images.githubusercontent.com/22675385/72797018-a1e60000-3c40-11ea-9167-87db9633127f.png)

![options](https://user-images.githubusercontent.com/22675385/72796836-52073900-3c40-11ea-805b-74810d03bcba.png)
When updating or creating a wallet, a user can choose/change the name and/or set this wallet to private/public.

![dialog](https://user-images.githubusercontent.com/22675385/72797029-a7434a80-3c40-11ea-9666-26c3b1608466.png)
![op](https://user-images.githubusercontent.com/22675385/72796945-87138b80-3c40-11ea-950f-b0d4656a81d9.png)
By default the wallets are private, if a user makes them public the following dialog will be shown.
- [ ] Check technical design with Jonas
## Transaction
During a transaction it should be possible to search for other wallets based on 3bot name. This should show ONLY the public wallets for that user.
For this the Contact button should be expanded. Under Others this should show a search dialogue based on 3bot name. When a match is found the user can be selected and all public wallets are shown in a dropdown. These can be used in the transaction.

![creaete transaction](https://user-images.githubusercontent.com/22675385/72800642-1bcdb780-3c48-11ea-8156-a95fe2cc81eb.png)
![search contact](https://user-images.githubusercontent.com/22675385/72800658-2720e300-3c48-11ea-802e-bea5e887ce88.png)

**Comment by jdelrue** [comment]
We need ticket on 3bot connect to implement public key sharing

**Comment by ken-de-moor** [comment]
Was shelved
