### ISSUE TITLE
TECHNICAL: Switch wallet storage to pkid

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#509]
# What
Currently a user can create a wallet and give it a name.
When they open the app again, it is possible that the name of the wallet is forgotten. We can prevent this by saving important info in PKID.

Following things will be stored in PKID:
- [x] Imported wallets
- [x] Created wallets

# How
By passing the name of the wallet to PKID when created, this data can be stored in a safe way.

# Extra
Don't forget about this:
- [x] [When Pkid is unavailable, the wallet stops on an exception #22
](https://github.com/threefoldtech/3bot_wallet/issues/22)

**Comment by JonasWijne** [comment]
basic pkid feature is implemented on feature/pkid 
current status:
- all wallets are stored/synced with pkid
- imported wallets can be deleted (created not yet)
