### ISSUE TITLE
As a user I want to be able to remove and rename my imported wallets.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#511]
# What
Currently it is not possible to change the name of a wallet or delete the wallet. This is functionality that should be added.

# How
1) When selecting a wallet the user is currently redirected to the details page, this page should be extended with two new options. Remove wallet and rename wallet.
2) Removing a wallet is only possible when it has 0.1 or less TFT remaining.
> "Removing a wallet is only possible when it has 0.1 or less TFT remaining, please first transfer your remaining TFT to another wallet"
3) When renaming a wallet we should take care to include the same validations as on the create wallet. 
4) Deleting a wallet should have a clear confirmation message.
> "Are you sure you want to delete the wallet? This action can not be reversed."
 > Yes or Cancel

## Extra
Don't forget to delete it on PKID.

# Mock ups
![options](https://user-images.githubusercontent.com/22675385/72803200-c694a480-3c4d-11ea-8082-b762116f6124.png)
![op](https://user-images.githubusercontent.com/22675385/72803212-cc8a8580-3c4d-11ea-89d9-459140edbc18.png)

**Comment by JonasWijne** [comment]
implemented but only for imported right now

**Comment by JonasWijne** [comment]
todo: change text

**Comment by ken-de-moor** [comment]
Moved back to in progress as it was only partially implemented so far.

Delete for non-imported wallets and redesign ( see mockups ) are not included.
