### ISSUE TITLE
Update all the tests using new jumpscale test runner [development_testrunner]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/home#516]
## Jumpscale tests
- Update all tests to use the new jumpscale runner 
- Any tests that exist in python file need to be under `tests` directory beside factory module.
- Any tests that exist in factory, should not be changed.

## JumpscaleCore
jumpscaleCore/JumpscaleCore/
### Data
/data
- [x] BCDB : /bcdb/tests
- [x] schema  : /schema/tests
- [x] Capnp :  /capnp/Capnp.py 
- [x] NACL:  /nacl/NACLFactory.py 
- [x] types  : /types/tests
- [x] /encryption/EncryptionFactory.py
- [x] /regex/RegexTools.py
- [x] /peewee/PeeweeFactory.py

### clients
/clients
- [x] sshkey : /sshkey/SSHKeys.py 
- [x] sshagent :/sshagent/SSHAgent.py  
- [x] ssh :/ssh/SSHClientFactory.py  
- [x] redis : /redis/tests
- [x] currencylayer: /currencylayer/CurrencyLayerFactory.py
- [x] /sonic/SonicFactory.py 
- [x] rdb : /stor_rdb/RDBFactory.py
- [x] /redisconfig/RedisConfigFactory.py
- [x]  /threebot/ThreebotClientFactory.py
- [x] /tcp_router/TCPRouterFactory.py 
- [x] zdb :/stor_zdb/tests

### Sal
/sal
- [x] bcdbfs  :/bcdbfs/BCDBFS.py 
- [x] fs:  /fs/tests
- [x] hostfile: /hostfile/tests
- [x] ssl : /ssl/tests
- [x] tls : /tls/tests

### tools
/tools
- [x] /threebot_package/ThreeBotPackageFactory.py
- [x] /syncer/SyncerFactory.py 
- [x] /executor/ExecutorFactory.py 
- [x] /threegit/ThreeGitFactory.py 
- [x] /wireguard/WGFactory.py
- [x] /time/Time.py 
- [x] /formatters/FormattersFactory.py 
- [x] /logger/tests
- [x] /jinja2/Jinja2.py
- [x] /restic/ResticFactory.py
- [x] /alerthandler/RedisAlertHandler.py
- [x] /bash/BashFactory.py
- [x] /dnstools/DNSTools.py
- [x] /threebot/tests
- [x] /mail/EmailFactory.py
### servers
/servers
- [x] /myjobs/tests
- [x] /openresty/tests
- [x] /corex/CorexFactory.py
- [x] /startupcmd/tests
- [x] /threebot/tests
- [x] /dns/DNSServerFactory.py
- [x] gedis : /gedis/pytests
- [x] gedis : /gedis/tests
- [x] /gedis_websocket/GedisWebsocketFactory.py
- [x] /gipc/GIPCFactory.py
- [x] /graphql/GraphQLFactory.py
- [x] /gundb/GunsbFactory.py
- [x] /sockexec/SockExec.py
- [x] /sonic/SonicFactory.py
- [x] /tmux/Tmux.py
- [x] /zdb/ZDBServers.py
- [x] rack: /gevent_rack/ServerRackFactory.py

## jumpscale_libs
/JumpscaleLibs
### SAL
/sal/
- [x] /sshd/tests
- [x] /ubuntu/tests
- [x] /nfs/tests
- [x] /dnsmasq/tests

### Data
/data/
- [x] /markdown/tests
- [x] /rivine/tests
- [x] /dicteditor/DictEditor.py

### clients
/client/
- [x] /goldchain/tests
- [x] /logger/tests
- [x] /tfchain/tests

## jumpscale_threebot
- [x]  /ThreeeBotPackages/tfgrid/directory/tests
- [x]  /ThreeeBotPackages/tfgrid/workloads/tests

### Clients
/clients 
- [x] traefik
### data
/data
- [x] latex/Latex.py 
- [x] nltk/NLTK.py
### Servers
/servers
- [x] OdooFactory.py
- [x] mail/smtp
- [x] mail/imap
### tools
/tools
- [x] storybot/tests

# QA tests 
## Jumpscale_core
- [x] Installation  (JumpscaleCore/install/installtion_tests/test_installtion.py)
     - [x] insystem 
     - [x] docker
-  [x]  Servers (/JumpscaleCore/servers/tests)
      - [x] gedis
      - [x] odoo
      - [x] servers
      - [x] smtp/imap
      - [x] startcmd
      - [x] threebot
      - [x] tmux
      - [x] zdb
-  [x] Clients (/JumpscaleCore/clients/tests)
      - [x] git 
      - [x] mail
      - [x] redis_config
      - [x] sonic
      - [x] sshagent/sshkey
      - [x] tfgrid_registry
      - [x] manual/test_ssh_client
-  [x] Sal 
      - [x] fs (/JumpscaleCore/sal/fs/tests)
      - [x] process (JumpscaleCore/sal/process/tests)

## jumpscale_libs
-  [x] Sal 
      - [x] ubuntu (/JumpscaleLibs/sal/ubuntu/tests)

## jumpscale_builder
jumpscaleX_builders/tests/builder
- [x] web ,apps
- [x] network
- [x] virtualization
- [x] blockchain
- [x] runtimes
- [x] db, storage
- [ ] builder_base
## Jumpscale_threebot
- [x] ThreeBotPackages/tests
     - [x] myjobs
     - [ ] alerta
     - [ ] blogs
     - [ ] pastebin
 - [x] ThreeBotPackages/tests/zerobot/webinterface/tests/test_wiki

**Comment by john-kheir** [comment]
working on: types : /types/tests

**Comment by john-kheir** [comment]
working on ssl : /ssl/tests

**Comment by john-kheir** [comment]
working on hostfile: /hostfile/tests

**Comment by john-kheir** [comment]
working on redis : /redis/tests

**Comment by Dinaamagdy** [comment]
working on : /bcdb/tests

**Comment by Dina-Abd-Elrahman** [comment]
working on: /sshkey/SSHKeys.py

**Comment by Dina-Abd-Elrahman** [comment]
working on: /sonic/SonicFactory.py

**Comment by Dina-Abd-Elrahman** [comment]
working on: git

**Comment by Dina-Abd-Elrahman** [comment]
working on: sshagent

**Comment by Dina-Abd-Elrahman** [comment]
working on: mail

**Comment by Dina-Abd-Elrahman** [comment]
working on: redis_config
Done: https://github.com/threefoldtech/jumpscaleX_core/commit/71db8c9ea8c369d3cc6847d3277550cce15955dc

**Comment by Dina-Abd-Elrahman** [comment]
working on: odoo server

**Comment by john-kheir** [comment]
working on: /currencylayer/CurrencyLayerFactory.py

**Comment by Dinaamagdy** [comment]
working in Capnp : /capnp/Capnp.py

**Comment by Dina-Abd-Elrahman** [comment]
working on: gedis server

**Comment by Dinaamagdy** [comment]
working on 
 /encryption/EncryptionFactory.py

**Comment by Dina-Abd-Elrahman** [comment]
- working on: Installation (docker)

**Comment by john-kheir** [comment]
working on /encryption/EncryptionFactory.py

**Comment by Dinaamagdy** [comment]
working on process (JumpscaleCore/sal/process/tests)

**Comment by Dinaamagdy** [comment]
working on 
bcdbfs :/bcdbfs/BCDBFS.py
 tls : /tls/tests

**Comment by Dinaamagdy** [comment]
working on /myjobs/tests

**Comment by john-kheir** [comment]
working on: /tools/threegit/ThreeGitFactory.py

**Comment by Dina-Abd-Elrahman** [comment]
working on: /tmux/Tmux.py

**Comment by Dina-Abd-Elrahman** [comment]
working on: 
/clients/testsmanual/test_ssh_client

**Comment by Dinaamagdy** [comment]
working on 
 servers/startupcmd/tests
servers/threebot/tests

**Comment by Dina-Abd-Elrahman** [comment]
working on:
-  rdb : /clients/stor_rdb/RDBFactory.py

**Comment by Dina-Abd-Elrahman** [comment]
working on :

- /sal/sshd/tests

**Comment by Dina-Abd-Elrahman** [comment]
working on:

- /sal/ubuntu/tests

**Comment by john-kheir** [comment]
working on: 
-  /clients/ssh/SSHClientFactory.py

**Comment by Dina-Abd-Elrahman** [comment]
working on:
/tools/threebot/tests

**Comment by Dina-Abd-Elrahman** [comment]
working on: 
 gedis : /server/gedis/pytests

**Comment by Dinaamagdy** [comment]
working on QA tests:

Servers (/JumpscaleCore/servers/tests)
 - odoo
 - servers
 - startcmd
 - zdb
- gedis

**Comment by Dina-Abd-Elrahman** [comment]
working on: 

Clients (/JumpscaleCore/clients/tests): manual/test_ssh_client

**Comment by john-kheir** [comment]
working on: 
- core: servers/smtp/imap
- libs: servers/mail/imap

**Comment by Dina-Abd-Elrahman** [comment]
working on:
libs/sal/nfs/tests

**Comment by john-kheir** [comment]
working on: /dicteditor/DictEditor.py

**Comment by john-kheir** [comment]
working on libs_extra
-  /clients/traefik --> not found
- /data/ latex/Latex.py

**Comment by Dina-Abd-Elrahman** [comment]
working on jumpscaleX_builders/tests/builder:

- web, app

**Comment by john-kheir** [comment]
working on:
- jumscaleX_threebot/ThreeeBotPackages/tfgrid/workloads/tests

**Comment by john-kheir** [comment]
Working on:
- jumpscaleX_builders/tests/builder/runtimes

**Comment by Dina-Abd-Elrahman** [comment]
working on:
 - /jumpscaleX_builders/tests/builder/db
- /jumpscaleX_builders/tests/builder/storage

**Comment by Dina-Abd-Elrahman** [comment]
For builders: 
As per Thabet we will change a lot of them so better not to waste a time on changing test cases related to it, so we will pause working on them now.

**Comment by john-kheir** [comment]
fixes:
 - https://github.com/threefoldtech/jumpscaleX_core/commit/a23901db86a1a4e8aeb53e16514ac127d96deac9
- https://github.com/threefoldtech/jumpscaleX_libs/commit/5c43765fbb2453e3a38451916d7f2fbe577df4e3

**Comment by Dinaamagdy** [comment]
fixes in schema and change to j.sal.process.execute instead of os_command method :
https://github.com/threefoldtech/jumpscaleX_core/commit/e0784e4d7d9b02a0323073a6f9ebc5833807025e
 
refactor schema test_suit :
https://github.com/threefoldtech/jumpscaleX_core/commit/f9639147ef5d9b32f586dfe2391f51f5e015f7c0

**Comment by Dinaamagdy** [comment]
working on 
ThreeBotPackages/tests:
 myjobs
 alerta
 blogs
 pastebin

**Comment by john-kheir** [comment]
libs clients skips: https://github.com/threefoldtech/jumpscaleX_libs/commit/7158e30d9f6bf22da42b11acebd434e28d110326

**Comment by Dina-Abd-Elrahman** [comment]
- working on:

libs: /clients/l/DigitalOcoan

**Comment by Dinaamagdy** [comment]
fixs and skips  on data so all green
https://github.com/threefoldtech/jumpscaleX_core/commit/420b5db2ea29273faa3f640eb2d431d0e67bb5b0
0 Failed, 0 Errored, 85 Passed, 34 Skipped

**Comment by Dinaamagdy** [comment]
jumpscale_core:https://github.com/threefoldtech/jumpscaleX_core/commit/7090e18f1ef525137c2df9ae5acd418b5b6192f4
jumpscale_libs:https://github.com/threefoldtech/jumpscaleX_libs/commit/faeb2f45dabd3b5ab52a4a9fadd93b931475aa49
jumpscale_libs_extra:https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/4af4594b435e478b195d33cff62278726f4bf5c2

all tools green except one as explorer is down now
```
ERROR: j.tools.threebot.test
----------------------------
EXCEPTION: 
    Redis on explorer.testnet.grid.tf:8901 did not answer: Error 111 connecting to explorer.testnet.grid.tf:8901. Connection
        refused.
--TRACEBACK------------------
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _execute_test
    203    test()
/sandbox/lib/jumpscale/Jumpscale/tools/threebot/ThreebotToolsFactory.py in test
    417    self.actor_phonebook = e.actors_get("tfgrid.phonebook").phonebook
/sandbox/lib/jumpscale/Jumpscale/clients/threebot/ThreebotClient.py in actors_get
    71    return self._gedis_connections[package_name].actors
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in actors
    155    self.reload()
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in reload
    89    assert self.ping()
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in ping
    63    test = self._redis.execute_command("ping")
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in _redis
    174    self._redis_ = j.clients.redis.get(addr=addr, port=port, secret=secret, ping=True, fromcache=False)
/sandbox/lib/jumpscale/Jumpscale/clients/redis/RedisFactory.py in get
    140    raise j.exceptions.Base("Redis on %s:%s did not answer: %s" % (addr, port, str(e)))
-----------------------------

----------------------------------------------------------------------
Ran 27 tests in 107.66417980194092


0 Failed, 1 Errored, 11 Passed, 15 Skipped 
```
