### ISSUE TITLE
update jumpscale docs [development_docs]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#517]
because of the recent changes in 10.2, and major breaking changes in jumpscale lots of documentation is now obsoleted.

for a proper release we needs docs on 
- [x] baseclasses @ranatrk (done)
- [x] logging/alerts @abom @waleedhammam [logger](https://github.com/threefoldtech/jumpscaleX_core/blob/development_logalert/docs/logger/README.md), [alerts](https://github.com/threefoldtech/jumpscaleX_core/tree/development_logalert/docs/alerts)
- [x] types @BolaNasr  @RafyAmgadBenjamin 
- [x] schema @andrewayoub 
- [x] bcdb @Hamdy @BolaNasr 
- [x] gedis @andrewayoub 
- [x] 3bot @xmonader @abom 
- [x] zdb client @serboctor https://github.com/threefoldtech/jumpscaleX_core/commit/cfa7b27fb3dbe993ebcc45c4508b082f525e8289 https://github.com/threefoldtech/jumpscaleX_core/commit/299789ed8d2990bab856e4dcdad487c0d8781f0c
- [x] wikis  @abom @ranatrk 

note: would be great if we can add more docs on the internals as well

More about wikis and threebot docs:

- [x] Wiki docs to re-add `jsx wiki-load` and `jsx wiki-reload` commands, as the docs [has been removed before](https://github.com/threefoldtech/jumpscaleX_threebot/commit/0448d8c1ae4e1e051faadade1ed7d8158b2bf0a0#diff-401cfb3b441bd71b2f65ffd6854762c3) because the commands were removed, also add more docs to wiki related packages (including `zerobot/wiki_examples` and `threefold/wikis`).
- [x] Remove old examples of wikis located at /docs/wiki/examples and replace references and links to them by `zerobot/wiki_examples` ones.
- [x] Updating threebot obsolete docs for how to add a package.
- [x] Trying to re-structure the docs in threebot repository:
     - [x] to make it more easy to be navigated
     - [x] update or remove the confusing duplication of top-level read me file and the one inside `docs` 
            directory (maybe just add a small intro and a link to docs directory instead).
     - [x] update dead links

**Comment by abom** [comment]
Working on updating:
* Wiki docs to re-add `jsx wiki-load` and `jsx wiki-reload` commands, and add more docs to wiki related packages (including `zerobot/wiki_examples` and `threefold/wikis`).
* Update threebot obsolete docs for how to add a package.
* Trying to re-structure the docs in threebot repository to make it more easy to be navigated.

**Comment by ranatrk** [comment]
- baseclasses: https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/Internals/baseclasses
- wikis: https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/zerobot/webinterface/wiki/wikis

**Comment by abom** [comment]
Updated references of examples directory to wiki_examples at https://github.com/threefoldtech/jumpscaleX_core/commit/f5a36e6c44aeeac74d22be35a4a32c18784c4cd7 and https://github.com/threefoldtech/jumpscaleX_threebot/commit/67ab8528c9c64e3cc1596b19a390958b9301892e.

**Comment by abom** [comment]
@ranatrk Reviewed wiki docs, all seems to be up-to-date, marked it done.

**Comment by abom** [comment]
Updated obsolete `gedis` client usage at https://github.com/threefoldtech/jumpscaleX_threebot/commit/33e36a0aae0d36b725d3c091acf302ddee6cbc1b.

**Comment by abom** [comment]
> Trying to re-structure the docs in threebot repository to make it more easy to be navigated (also, update dead links).

@xmonader Need to discuss this point with others too.

**Comment by abom** [comment]
Now 3bot docs are re-structured with more fixed dead and obsolete links (https://github.com/threefoldtech/jumpscaleX_threebot/commit/af8088dff7eafc01a7db8a73df73b47697bbcd97 and https://github.com/threefoldtech/jumpscaleX_threebot/commit/0f964906a07d352a0d8d9d9243f63c5818c0f47d).

**Comment by Dinaamagdy** [comment]
[ ] wikis
install part in wikis docs here  not updates 
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/zerobot/webinterface/wiki/wikis#install
![image](https://user-images.githubusercontent.com/24386802/76232772-db45ef80-622f-11ea-984d-c9d7d42667b7.png)

**Comment by rkhamis** [comment]
@Dinaamagdy please verify on unstable, not development

**Comment by Dinaamagdy** [comment]
in unstable branch 
- [ ] wikis https://github.com/threefoldtech/jumpscaleX_threebot/tree/unstable/ThreeBotPackages/zerobot/webinterface/wiki/wikis#install
![image](https://user-images.githubusercontent.com/24386802/76305285-8d7fc480-62cd-11ea-93f1-c8ec076dff24.png)
- [ ] logging
https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/logger/README.md#js_logs

![image](https://user-images.githubusercontent.com/24386802/76305981-ca988680-62ce-11ea-9992-28b882bc598e.png)
 - [ ]package_manager
https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/docs/packages.md#registering-package
![image](https://user-images.githubusercontent.com/24386802/76306772-2c0d2500-62d0-11ea-9d89-df81b0759f85.png)

examples here need to be updated 
https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/README.md#complete-examples

**Comment by RafyAmgadBenjamin** [comment]
Updated the docs on ```development_docs```

commit Id:
https://github.com/threefoldtech/jumpscaleX_threebot/commit/929b7f537bd6c02b48c5c611580d2fcef18b3d7b

It is working on ```developement```:
![image](https://user-images.githubusercontent.com/46320202/76746569-6408e200-6780-11ea-824d-40682a0e26bf.png)

![image](https://user-images.githubusercontent.com/46320202/76746581-6a975980-6780-11ea-98f2-18900b475b27.png)

PR:
https://github.com/threefoldtech/jumpscaleX_threebot/pull/425

**Comment by hossnys** [comment]
verified on development but still the complete examples not updated yet.
![Screenshot from 2020-03-17 13-55-13](https://user-images.githubusercontent.com/26298009/76855192-49566c00-6859-11ea-902f-f9bfedd52785.png)
