### ISSUE TITLE
Last preparations for first grid usage (farmers and grid consumers)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#518]
Components are ready to be used by early adopter farms, with some shortcuts yet: 
- Kosmos only, not yet using 3Bot
- No UI
- No KYC yet
- User needs Linux machine to run it

## To do
- [x] Create [documentation](https://github.com/threefoldfoundation/info_grid/blob/development/docs/tf_farming/setup_farm_using_jsx.md) that explains farmers how to make first usage of the grid to: 
    - install JSX
    - Kosmos instruction overview
    - Farm mgmt app
- [x] Retest farmer mgmt app (reigster farm, see nodes, set price)
- [x] Re-enable payment flows
  - [x] https://github.com/threefoldtech/jumpscaleX_threebot/pull/375
  - [x] https://github.com/threefoldtech/zos/issues/605
  - [x] Test full flow on devnet
  - [x] Deploy on testnet
  - [x] Deploy on mainnet
- [x] [Deploy production explorer](https://github.com/threefoldtech/home/issues/555)
~~- [ ] [ Secure explorers environments #609 ](https://github.com/threefoldtech/home/issues/609)~~

**Comment by zaibon** [comment]
Payment flow is deployed on devnet and being tested.
Some more work needs to be done in jsx to have all the required feature for farmer to update their wallet address with the new tokens (TFT, FreeTFT, ...)
