### ISSUE TITLE
threefold wiki & web package [development_web103]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#522]
- [x] package to install all wiki's for threefold
- [x] package to install all websites related to us 
- [x] readme's in both packages to define how to get to website (use wireguard on container, which url , link to google security...)
- [x] client for gdrive
- [x] tool to allow easy reload of wiki/website
- [x] make sure macro's work (ppt, pdf, ...)
- [x] make sure indexing / search works

# goal

- allow people to use jsx tool to deploy container & develop on all websites/wiki
- needs to be fast, so easy reload of any changes (FAST), uses the git marker
- run on OSX (in container with jsx)
- easy to navigate in own browser for debug purposes e.g. http://x.x.x.x/threefold/www_3bot_org

Deliverable by first week of Feb

**Comment by andrewayoub** [comment]
Added a new package to load the four main websites:
www.3bot.org
www.incubaid.com
www.threefold.love
www.threefold.tech

to load the package:
```
cl = j.clients.gedis.get("packagemanager", package_name="zerobot.packagemanager")
cl.actors.package_manager.package_add(path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/websites/")
```

![image](https://user-images.githubusercontent.com/5163693/73468310-437df780-438d-11ea-9597-ebe3c522a36f.png)

**Comment by waleedhammam** [comment]
**Commit**

https://github.com/threefoldtech/jumpscaleX_threebot/commit/641d45faf045544073aaf5ac1b1ac45836cf77f9

Readme at: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_web103/ThreeBotPackages/threefold/wikis/wiki/README.md

### How to run:

### configure gdrive
`j.clients.gdrive.get_from_file("main", "/sandbox/code/cred.json")`

- start threebotserver: j.servers.threebot.start()
- start wiki package: j.threebot.packages.threefold.wikis.start()

### Examples

grid -> https://172.17.0.2/wiki/grid
foundation -> https://172.17.0.2/wiki/foundation
tokens -> https://172.17.0.2/wiki/tokens#/
tokens -> https://172.17.0.2/wiki/examples

![Screenshot from 2020-01-30 18-22-24](https://user-images.githubusercontent.com/10658229/73468446-7cb66780-438d-11ea-9453-0307b7c5f343.png)


![Screenshot from 2020-01-30 18-08-31](https://user-images.githubusercontent.com/10658229/73468403-68726a80-438d-11ea-8255-4455c967fe0a.png)


![Screenshot from 2020-01-30 18-11-23](https://user-images.githubusercontent.com/10658229/73468385-5e506c00-438d-11ea-8fac-0a58917d237a.png)

![Screenshot from 2020-01-30 18-22-46](https://user-images.githubusercontent.com/10658229/73468496-8b9d1a00-438d-11ea-9eef-286ce87ccecd.png)

![Screenshot from 2020-01-30 18-23-09](https://user-images.githubusercontent.com/10658229/73468524-9657af00-438d-11ea-95e4-5a4aa696b7ef.png)

**Comment by waleedhammam** [comment]
Todo
- update / remove duplicate wiki examples (in jumpscaleX_threebot/docs)
- wikis auto update

**Comment by waleedhammam** [comment]
updated wiki docs for load / reload at: https://github.com/threefoldtech/jumpscaleX_threebot/commit/e1f29e1335e9516f52004361d3fa111696ded013

- to load wik [jsx wiki load]: https://github.com/threefoldtech/jumpscaleX_threebot/blob/e1f29e1335e9516f52004361d3fa111696ded013/docs/wikis/tech/README.md#Loading-wikis-using-jsx-wiki-load

- to reload wiki [jsx wiki reload]: https://github.com/threefoldtech/jumpscaleX_threebot/blob/e1f29e1335e9516f52004361d3fa111696ded013/docs/wikis/tech/README.md#reloading-wikis-using-jsx-wiki-reload

**Comment by Dina-Abd-Elrahman** [comment]
-verified.
