### ISSUE TITLE
tcprouter delivery [development_tcprouter]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#524]
- [x] lets change tcprouter client to be able to connect to multiple servers
- [x] test behaviour
- [x] make easy for user to connect auto to the 3 we have
- [x] doc about how to use the tcprouter as part of provisioning a workload

Delivered by mid Feb

**Comment by rkhamis** [comment]
relates to: https://github.com/threefoldtech/home/issues/520

**Comment by zaibon** [comment]
PR to allow client to connect to multiple server: https://github.com/threefoldtech/tcprouter/pull/19

**Comment by zaibon** [comment]
Coding wise we are done now.
I'll  see to produce a documentation showing how we can use the gatway actor to configure the tcprouter client and server
