### ISSUE TITLE
chatflows for primitive workloads on tfgrid [development_tfchatflows]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#525]
see https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/tfgrid/provision_examples

## flows

- [x] ubuntu (@BolaNasr)
- [x] threebot -> threebot_reservation (@BolaNasr)
- [x] Generic flist (@BolaNasr)
- [x] Minio/S3 (@ranatrk)
- [x] K8S cluster (@ranatrk) 

## to improve

- check all returns on the questions and ask again if not ok (defensive programming)

**Comment by rkhamis** [comment]
basic workload chatflow is done here: https://github.com/threefoldtech/jumpscaleX_threebot/pull/370/commits/6c5765f183e3ec4633b68224fa45287cb21cb027


needs to be adapted for each primitive

**Comment by ranatrk** [comment]
Currently blocked on testing as [chatflows sal tool](https://github.com/threefoldtech/jumpscaleX_libs/blob/development_tfchatflows/JumpscaleLibs/sal/chatflow/Chatflow.py) being used in the chatflows needs to be updated to handle reservations for both ipv4 and ipv6 nodes as some machines cannot access nodes with deployments that use ipv6

**Comment by despiegk** [comment]
kristof wants to verify and give feedback

**Comment by gmachtel** [comment]
chatflows are code complete but we can't deploy minio right now and trying to get help from zos team to trace.
