### ISSUE TITLE
Minio/s3 working on top of 0-OS v2

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#526]
We need to do some work regarding 0-Stor and Minio/S3 to ensure everything still work on top of 0-OS v2.

Tasks :
- [x] [ Allow to have different namespace name per shard](https://github.com/threefoldtech/0-stor/issues/31)
- [x] ensure 0-Stor daemon mode is working
- [x] ensure 0-Stor python client for daemon is working
- [x] Review Minio implementation and try to be up to date with upstream
- [x] [0-db provisioning doesn't take in account the 0-db mode](https://github.com/threefoldtech/zos/issues/499)
- [x] Performance tests
  - [x] plain performance of minio running in 0-OS container on top of N 0-db spread over different nodes. We just check write/read speed between minio and the 0-db
  - [x]  performance of tcprouter proxy client. Goal is to see how fast we can write/read from minio when using a TFGateway as public entry-point

**Comment by muhamadazmy** [comment]
Regarding testing 0-stor daemon mode.

- I configured 0-stor daemon to use 3 zdb namespaces running on the grid. I was able to download/upload files normally with no issues. But during testing I realized that the python client actually send the file path to the daemon then the daemon opens and reads the file and upload the chunks to the zdbs. Hence this means daemons must be running on local systems where u want to upload files. 
Another option is to put you full data in one grpc call. This can work for small files, but for large files it's gonna be really really heavy.

**Comment by zaibon** [comment]
> But during testing I realized that the python client actually send the file path to the daemon then the daemon opens and reads the file and upload the chunks to the zdbs. Hence this means daemons must be running on local systems where u want to upload files.

Yes this is the intended use case. The idea is that if you want/need, you can run a daemon locally on your node, and any application can talk to it. 
So this solve 2 problems:
- any language can integrate with it, there is no hard dependency with go
- if you have a lot of application that needs to user 0-stor, running a single daemon will save some memory while still enabling 0-stor for all apps

**Comment by muhamadazmy** [comment]
We have this https://github.com/threefoldtech/minio-perf now to IC test minio on the development grid. It also show a problem with download performance as reported in this issue [here](https://github.com/threefoldtech/minio/issues/84)

**Comment by muhamadazmy** [comment]
After doing some tests with tcprouter as a proxy, we noticed a drop of around 35% of upload speed. Download speed was not affected that much (almost not) which makes us think that the bad download performance experienced is actually coming from minio itself, not the network.
