### ISSUE TITLE
TECHNICAL: The wallet should be moved to stellar

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#527]
# What
The blockchain should be converted to stellar

# How
- [x] make wallet compatible with stellar api
- [x] convert tokens
- [x] import accounts

# Extra
Keep in mind the following use cases.

1) Ensure the user does not lose any tokens
2) Ensure the conversion will keep working, even if a user does not open the app for 3 years and then later tries to access his wallets. Many users just store tokens and don't access them until a lot later.
3) Ensure that tokens sent to old addresses from before the conversion are not lost.
4) Make sure the user is correctly informed about this conversion, and has all the information and tools needed to continue using TFT with no problems.

**Comment by JonasWijne** [comment]
wallet basics are moved to stellar including migration
