### ISSUE TITLE
Deploy websites using 3bot websites package

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#529]
currently 
- www production (branch master)
- ww2 staging (branch development) uses auto pulling every 5 mins.
for migration of staging ww2 we need to make sure the websites package is good enough to be deployed in staging `ww2`.

Please start deploying all websites using the 3bot websites package and make sure all of them are hosted with `ww3` and check if all works so we can promote them in ww2

**Comment by PeterNashaat** [comment]
- tested multiple websites in the same [package.py](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/websites/package.py)
- https is working fine

![image](https://user-images.githubusercontent.com/13523434/75622386-1e58f080-5ba8-11ea-8b90-2a5cb040f077.png)

![image](https://user-images.githubusercontent.com/13523434/75622396-4183a000-5ba8-11ea-9ac3-9350701268a4.png)

- Steps : -

```
j.servers.threebot.start(background=True) 
cl = j.clients.gedis.get("packagemanager", package_name="zerobot.packagemanager")
cl.actors.package_manager.package_add(path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/websites/")
```
