### ISSUE TITLE
Address subscription using the electrum protocol 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#53]
- [x] [support a 'notificator' module which allows you to subscribe to certain events](https://github.com/threefoldtech/rivine/issues/408)
- [x] [Verify electrum address subsciption with the electrum spec](https://github.com/threefoldtech/rivine/issues/474)
- [ ] Enable the electrum module in the explorer templates

**Comment by GlenDC** [comment]
Now that you verified it @robvanmieghem, does it mean that you do receive the information about the actual transactions that are new for your address, such that you can request those directly?

**Comment by robvanmieghem** [comment]
@GlenDC No, according to the spec, it's a hash of the state, if it changes, you have the fetch the history again.

**Comment by GlenDC** [comment]
That's what I thought. How would you fetch the history and what would you be fetching?

**Comment by robvanmieghem** [comment]
@GlenDC Btw, the electrum spec does specify a minimum height for the history so it makes sense to add that parameter to our list_transactions

**Comment by GlenDC** [comment]
For our static `/explorer/hashes/:hash` call there is already a PR open, https://github.com/threefoldtech/rivine/pull/476, please review and merge when you can.

**Comment by LeeSmet** [comment]
To enable the electrum module:
- Update the flags passed to the explorer in the jumpscale_lib.
- Reboot the node so it pulls the latest version of jumpscale (need to check if this is the proper procedure)
- Update the caddy config template to proxy websockets (proxy /wsendpoint wshost { websocket } )
- Update caddy startup command line to disable http2 (-http2=false)
- Update the service to store the port on which we want to expose the websocket (actually this might not be needed as we can use a fixed port for the deamon and then proxy some endpoint )

Given the requirements, and the lack of apparent documentation on the caddy website that this will indeed work as expected so we have secure websockets, I think it might be best to first try this on a standalone machine with regular ssh access, with a manual setup. Once we then confirm it works we can indeed do the necessary changes.

**Comment by LeeSmet** [comment]
After talking with Zaibon, the correct way to update the jumpscale code on the node is to add our commit to master ( using a PR), and after that the 0-robot flists needs to be updated. Then the nodes can be rebooted

**Comment by sabrinasadik** [comment]
Follow-up story for deployment: https://github.com/threefoldtech/home/issues/57
