### ISSUE TITLE
There should be monitoring on disk space and backups on the server where pkid is hosted.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#533]
# What
For safety reasons and to ensure the solution keeps being accesible, there should be daily backups. There should also be better monitoring of the volume to ensure that we never have the disk space run out, as this would cause major issues.

# How
 - [x] make sure disk space is monitored and notifications are sent at several intervals of disk space remaining.
 - [x] make sure the data is backed up daily in a location that's not on the same server

# Extra
The monitoring should also check that the back ups actually succeeded. So they don't error for months in a row without us realizing !

**Comment by jdelrue** [comment]
Backups are ready, done by Jasper,  but need to be checked. Monitoring not ready yet. @tobiaschielens can check it out and add pkid to monitoring

**Comment by tobiaschielens** [comment]
A cronjob is executing /home/jimber/diskmonitoringPKID.py on the server where pkid is hosted. The python file notifies jdelrue, jonaswijne and tchielens on telegram when the disk space is less than 1GB.
