### ISSUE TITLE
reporting tool to create rich output [development_reportlab]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#534]
Mainly to be used with the simulator @despiegk created

Points to check
- [x] open source
- [x] ease of use
- [x] friendly dsl integrated in jumpscale
- [x] markdown content easily allowed
- [x] allow basic graphs

# example of expected usage:
```
doc = j.tools.pdfreport.get_doc()
doc.header_add..
doc.footer_add
doc.image_add..
doc.leftMargin = 1 * cm
doc.rightMargin = 1 * cm
doc.bottomMargin = 1.5 * cm
doc.topMargin = 1.5 * cm
doc.table_add...
doc.list_add..
doc.save(filepath...)
```

check:  
- https://www.reportlab.com
- [prev tool](https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/6b70929fec4e765ac057a30249a139bf5cba5fab/JumpscaleLibsExtra/tools/reportlab/ReportlabFactory.py)

**Comment by andrewayoub** [comment]
I spent the last hours reading [reportlab user guid](https://www.reportlab.com/docs/reportlab-userguide.pdf)

then I started refactoring the existing tool in libs extra :
* created a new tool called reportlab2 to keep the old one until we finish refactoring
* separated the default template code to be able to start a document in different templates
* re organized styling to be able to pass custom styles for each flowable 

TODO:
* implement flowables (text, images, ..)
* creating a refined dsl to customize styles easier 
* handle multipage docs

**Comment by despiegk** [comment]
please make sure markdown elements can be inserted to make it easy for someone to add content.
also basic graphs

**Comment by andrewayoub** [comment]
* added support for tables 
* added support for md but still can't add images inside md
* will investigate how to implement graphs 

check the test here for usage examples 
https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/76849f856e78c9ee79b51a67229f714672b238d4/JumpscaleLibsExtra/tools/reportlab2/ReportlabFactory.py#L14

**Comment by andrewayoub** [comment]
* added support for graphs using dot
