### ISSUE TITLE
TECHNICAL: 29 word wallet seeds should be converted.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#536]
# What
Some early TFT buyers have 29 word phrases, we should see what we can do to ensure this doesn't break, and convert them to 24 word phrases.

# How
To be decided by R&D team.

# Extra
See following links.

1) https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/conversion/locking.md#distinction-between-locked-and-unlocked-addresses
2) https://github.com/threefoldfoundation/tft-stellar/blob/master/specs/conversion/addressdistinction.md

**Comment by JonasWijne** [comment]
https://www.npmjs.com/package/mnemonicconversion2924 was made to handle this exact situation.

**Comment by JonasWijne** [comment]
testing with 29 words, i can transfer tokens to the 29 words in the threefold app and import those 29 words in the 3bot_wallet

test concludes with seeing tokens on our 3bot_wallet

**Comment by tobiaschielens** [comment]
The 29 words feature has been implemented and is available on production. However poeple are getting the following error message: "can’t find variable :biglnt"

**Comment by JonasWijne** [comment]
test phrase :
`fully mobile shyness pixels sapling match yacht shipped aisle angled olive awful volcano dented knuckle jostle aching yodel austere peeled fowls punch cedar owls lumber ascend noted oyster acumen`

**Comment by JonasWijne** [comment]
New implementation seems not to work on iOS, probably because BigInt isn't supported by safari

**Comment by tobiaschielens** [comment]
Received confirmation that the new implementation is working on iOS. This can be closed
