### ISSUE TITLE
simulation for threefold [development_simulator]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#537]
# Goal
- allow 3e parties to easily collaborate on our simulator

## token simulation

- [x] simulator tools using jupyter to let others help us with our tokenomics
- [x] voila option
- [ ] package on https://github.com/threefoldfoundation/token_simulator
- [x] basic tutorial on how to use
- [x] documentation (includes setup, starting of the package)

**Comment by rkhamis** [comment]
verified that package runs and starts. still missing docs

**Comment by Hamdy** [comment]
@rkhamis 
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_simulator/ThreeBotPackages/threefold/simulator

**Comment by hossnys** [comment]
verified on these branches :
jumpscaleX_libs : development_simulator
jumpscaleX_libs_extra : development_simulator
jumpscaleX_threebot : development_simulator

steps :
- start komos and then start threebot server
``` j.servers.threebot.start(background)```
- add simulator package :
```j.threebot.packages.zerobot.packagemanager.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/simulator')```
- access the simulator from this link :
https://172.17.0.2/simulator/threefold/notebook/
![Screenshot from 2020-03-08 16-06-25](https://user-images.githubusercontent.com/26298009/76164383-2cce7b80-6157-11ea-8d9b-49492c1c0cc9.png)

or for voila
https://172.17.0.2/simulator/threefold/show/

![Screenshot from 2020-03-08 16-07-27](https://user-images.githubusercontent.com/26298009/76164384-36f07a00-6157-11ea-8565-fef0b51e1eba.png)

**Comment by Hamdy** [comment]
added simple docs 
https://github.com/threefoldtech/jumpscaleX_threebot/tree/unstable/ThreeBotPackages/threefold/simulator

**Comment by hossnys** [comment]
verified

**Comment by hossnys** [comment]
verified
