### ISSUE TITLE
3bot user should be able to host their own private git repos

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#544]
3bot user should be able to host their own private git repos using a solution like gitea

- [x] docker image ready for gitea (https://github.com/threefoldtech/tf-images/tree/master/gitea)
- [x] chatflows ready for gitea setup? or maybe we do relative user configurations?
- [x] add manual for usage
- [x] create deployed solution tab for gitea

**Comment by BolaNasr** [comment]
Now we have gitea chatflow
branch : development_gitea ( libs and threebot)

this after deployed container
![image](https://user-images.githubusercontent.com/10259267/81168591-92908580-8f97-11ea-867a-5b3b75d548db.png)

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/wiki/gitea/README.md

**Comment by BolaNasr** [comment]
deployed solution tab for gitea at ```development_deployed_solutions``` branch

**Comment by Pishoy** [comment]
verifed

- jsx version 

```
root@test105_testnet:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 35454a9d7800eb7dd478a12c2820d383eb83ad9c (HEAD -> development, origin/development, origin/HEAD)
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Mon May 18 18:28:00 2020 +0200

    fix passing of hru instead of mru in flist deploy
    
    See: #709
    
    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

```
