### ISSUE TITLE
namemanager actor: allow to register tcp router client connection [development_infradeployment]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#549]
the [namemanager actor](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/tfgrid_dns/actors/namemanager.py) currently only support to map a domain to an IP. 
With the new feature of the [tcprouter](https://github.com/threefoldtech/tcprouter) that allow to proxy a TCP stream from a domain to a connection open from a TCP router client, we should update the namemanager actor to expose this feature.

This will also involve adding this feature to the [TFGateway tool first](https://github.com/threefoldtech/jumpscaleX_libs_extra/tree/master/JumpscaleLibsExtra/tools/tf_gateway) since this is was the namemanager actor uses.
(I'm not sure why this TFGateway tools live in libs extra... maybe need to be moved ? )

- [x] move tfgateway tool into libs
- [x] update tfgateway to register clients
~- [ ] update namemanager actor~
- [x] create gaetway package
- [x] make the wireguard configuration persistant in infrastructure deployment scrip : https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/scripts/setupinfra_new.py
- [x] delete the duplicate deployment script
- [x] Add some methods to the gateway actor to be able to list what is currently configured
- [x] Add some method to the gateway actor to be able to remove any domain or proxy
~- [ ] Figure out how to secure the actor.~

**Comment by zaibon** [comment]
So I did a full review on what is available today.

### Deployment script
- location: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/scripts/setupinfra_new.py
This mostly works ok. There are some hardcoded value inside that needs to be made configurable (SSH key to put in the droplets, DO project names).
I would also be nice to be able to make this script a real CLI tool instead of a plain script that needs to be manually modified before running it.

The biggest issue with it is regarding the wireguard configuration on the 3 gateway server. The way how its done doesn't survive a reboot. It seems the wireguard is interface is brought up once but there is no configuration written on disk nor. This needs to be fixed.

### Gateway actor
- location: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/gateway/actors/gateway.py

The method currently implemented in the actor seems to work. But the actor is not complete.
There is no way for a user to delete a domain or a proxy configuration.
There is no way for a user to see the configuration of a proxy 
Found some small bugs.
https://github.com/threefoldtech/jumpscaleX_threebot/blob/39c12beb0532fcacc045ab446249b3e324a72528/ThreeBotPackages/tfgrid/gateway/actors/gateway.py#L33-L39

The there is also the question of how do we secure this ? At the moment anyone can just overwrite the configuration of someone else...

**Comment by xmonader** [comment]
- removed old setup script threefoldtech/jumpscaleX_threebot@5cff454cd5f77fcf8c356bc74432273ba12ef811
- updated the domain_dump endpoint threefoldtech/jumpscaleX_threebot@e7340f843dbf447b7c61ca6ea59ac9feafde2a52

- persistence of wireguard config should be fixed in [WireGuard Tool](https://github.com/threefoldtech/jumpscaleX_core/blob/88abc8729f1b843aade164fd6141350d13732919/JumpscaleCore/tools/wireguard/WireGuard.py#L133)

- deleting domain
first make sure to configure a prefix to be used e.g _dns or anything because the redis is used for multiple services. coredns-redis https://github.com/threefoldtech/coredns-redis allows `prefix` param to be defined
the subdomains are configured within a hash (key is the root domain)

e.g for domain `ahmed.3bot.grid.tf` you will find the root domain is `3bot.grid.tf.` and is a hash with domains as keys to another hash of record_type to list of records

e.g
```

# redis-cli> hgetall example.net.
#  1) "_ssh._tcp.host1"
#  2) "{\"srv\":[{\"ttl\":300, \"target\":\"tcp.example.com.\",\"port\":123,\"priority\":10,\"weight\":100}]}"
#  3) "*"
#  4) "{\"txt\":[{\"ttl\":300, \"text\":\"this is a wildcard\"}],\"mx\":[{\"ttl\":300, \"host\":\"host1.example.net.\",\"preference\": 10}]}"
#  5) "host1"
#  6) "{\"a\":[{\"ttl\":300, \"ip\":\"5.5.5.5\"}]}"
#  7) "sub.*"
#  8) "{\"txt\":[{\"ttl\":300, \"text\":\"this is not a wildcard\"}]}"
#  9) "_ssh._tcp.host2"
# 10) "{\"srv\":[{\"ttl\":300, \"target\":\"tcp.example.com.\",\"port\":123,\"priority\":10,\"weight\":100}]}"
# 11) "subdel"
# 12) "{\"ns\":[{\"ttl\":300, \"host\":\"ns1.subdel.example.net.\"},{\"ttl\":300, \"host\":\"ns2.subdel.example.net.\"}]}"
# 13) "@"
# 14) "{\"soa\":{\"ttl\":300, \"minttl\":100, \"mbox\":\"hostmaster.example.net.\",\"ns\":\"ns1.example.net.\",\"refresh\":44,\"retry\":55,\"expire\":66},\"ns\":[{\"ttl\":300, \"host\":\"ns1.example.net.\"},{\"ttl\":300, \"host\":\"ns2.example.net.\"}]}"
# redis-cli>
```
- deleting router configurations
keys are formatted within redis `/tcprouter/service/$DOMAIN_NAME`

- to inspect the router configuration it's in the format of 

key is $DOMAIN_NAME
value is [base64encoded json](https://github.com/threefoldtech/jumpscaleX_libs/blob/473fe2efc741b7ac0c791055a14b9a683719637f/JumpscaleLibs/tools/tf_gateway/TFGateway.py#L247)  it's how [valkeyrie](https://github.com/abronan/valkeyrie ) serializes its data)


on the security part the idea in the previous iteration only namemanager could manipulate the redis maybe using a chatflow to reserve a subdomain or configuring a service or we can add also add info about the issuer (to allow modifying/deleting the records) within the services

**Comment by ranatrk** [comment]
> The biggest issue with it is regarding the wireguard configuration on the 3 gateway server. The way how its done doesn't survive a reboot. It seems the wireguard is interface is brought up once but there is no configuration written on disk nor. This needs to be fixed.

@zaibon  When using the wireguard tool, the configuration is written on disk and then interface started using the path of that file. Is this what you mean and will be started manually? or do you mean it should be brought up again on its own when reboot occurs (by adding wireguard service to systemd)

**Comment by ranatrk** [comment]
- Wireguard configurable by adding to schema `config_path` and changing its value in the script to be `/root/cfg/INTERFACE_NAME.conf`.
- **to be done:** need to make sure /root/cfg directory exists 

https://github.com/threefoldtech/jumpscaleX_core/commit/1ab4f199879c1161f60bd8eea6e52c5470f6e726
https://github.com/threefoldtech/jumpscaleX_threebot/commit/db7961a74ed940d58ae31e8e34b2dfa377300610

**Comment by m-motawea** [comment]
* Unregistering domain and TCPRouter services:
https://github.com/threefoldtech/jumpscaleX_threebot/commit/dd6d3e8905e5ce77ec40eb4c5d2fe244edcdf805
https://github.com/threefoldtech/jumpscaleX_libs/commit/562ee25145c00e3acf38c79c36e6e2c50ea4e46a
https://github.com/threefoldtech/jumpscaleX_libs/commit/23b6fa0cab8fab898df637eac38af085807425e3
https://github.com/threefoldtech/jumpscaleX_threebot/commit/7007b427aa30ba76ddb58e33f75b03c495c36ff4

* Support prefix for domain operations:
https://github.com/threefoldtech/jumpscaleX_libs/commit/801f791654bb469262f51cf363bed525390cc5a1

* Allow users to list and view TCPRouter services configuration:
https://github.com/threefoldtech/jumpscaleX_libs/commit/a04e8543e507cf22e91cb3c86c99ca7a2868f16d
https://github.com/threefoldtech/jumpscaleX_libs/commit/bd52a9311711961bbdf06602d702e9a93109c3f7

**Comment by rkhamis** [comment]
I think we should split the security to a separate storycard. development of features is done.
But to have proper security, only the original author should be able to modify and delete their records. in that case, we will have to keep track of the author of each record. 

This needs more thought and be approached carefully

**Comment by zaibon** [comment]
I'm going to give another review on the newly added code. But I wonder why is this not been done in a PR? this is 10 time harder to comment on now...

> But to have proper security, only the original author should be able to modify and delete their records. in that case, we will have to keep track of the author of each record.

Indeed and if this is not the case today, then we need to review the data structure used...

**Comment by rkhamis** [comment]
all the information needed is there, after review. blocked on #492

**Comment by xmonader** [comment]
@m-motawea Please make sure to continue on the wg guard configuration is saved and restored on restart.

**Comment by m-motawea** [comment]
make wireguard config presistent and make droplet name and key used configurable from myenv
- droplet name format: ```{DROPLET_PREFIX}{x+1}{DROPLET_POSTFIX} ``` where DROPLET_PREFIX and DROPLET_POSTFIX are read from myenv. 
- key name: ```SSH_KEY_NAME``` as read from myenv.

https://github.com/threefoldtech/jumpscaleX_threebot/commit/0bdc18419f661e14513bc8fac6ba055110545bd3


PR: https://github.com/threefoldtech/jumpscaleX_threebot/pull/426

**Comment by gmachtel** [comment]
removed securing the actor from here (which will be in 10.4), we'll go live without it after testing
