### ISSUE TITLE
Create a testing environment for jumpscale and threebot [development_myjobs]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#552]
This will involve:
 - [x] running tmux in a separate testing context
 - [ ] running testing workers
 - [x] running separate redis queues so we can ensure workload being tested

**Comment by RafyAmgadBenjamin** [comment]
* I have separated the tmux session and the Redis queue 
* working on issue related to database separation

**Comment by RafyAmgadBenjamin** [comment]
I am blocked on an issue related to starting  the ```myjobs``` database as master and ```myjobs_test``` database as slave and reading and writing through Redis
