### ISSUE TITLE
Admin Dashboard for threebots [development_dashboard]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#553]
A default package `zerobot.admin` that will be installed on all 3bots with a dashboard landing page

it should:
 - [x] run on `/admin`
 - [x] be a single page with intuitive navigation and encompasses:
   - [x] alerta overview
     - [x] alerts to be searchable, fliterable and orderable (https://github.com/threefoldtech/jumpscaleX_threebot/issues/367)
     - [x] each alert is clickable to view more details about logs
   - [x]  Logs overview
      - [x] added actor for count, list, find, list_apps
   - [x]  package overview (rafy)
      - [x] details about each package to stop/start/reload/install/uninstall
   - [x]  3bot health overview (landing page)
       - [x] we can show here each of the servers running for how long, consumption
  - [x] wiki and websites overview
     - [x] reload of wikis
 - [x] codeserver
 - [x]  MyJobs overview (Ghanem)
 - [x] Juptyer
 - [x] In codeserver show a message when the package is not installed and don't show 404 error message 

---
details

Now:

- [x] redundant ports, and change its name to ports only not running ports  (rafy)
- [x]  Running processes, add info. (usage in mb), also change colors (waleed)
- [x]  add more tests beside bcdb (running codeserver, .. etc)
- [x] we can make information in same line in widgets
- [x] We need to add total memory usage (waleed)
- [x] installed by default
- [x] logs in alerts
- [ ] responsive design

---
Later
- [x] templates in webinterface should be enhanced, remove duplicate code
- [x] color logs message according to level

**Comment by john-kheir** [comment]
Verified
