### ISSUE TITLE
Create and add new tests to  wikis tests to cover new changes [development_testing_wikis]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/home#556]
- Create tests to cover the new changes here https://github.com/threefoldtech/home/issues/546
- Edit the tests here 
https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/zerobot/webinterface/tests

**Comment by Dina-Abd-Elrahman** [comment]
- we need to add one test case to test that full reset doesn't clean the output docsify directory. 
**Test scenario** 

- create test.md file in any of docsite directory sub-folders `/sandbox/var/docsites/`, e.g info_grid.
- then do `jsx wiki-load -r` 
- and check that the new created file is deleted.

**Comment by Dina-Abd-Elrahman** [comment]
- we need to add test case to check the existence of `info_grid and grid` after installing threefold.wikis package and both are referenced to correct end point.
