### ISSUE TITLE
Taiga package [unstable_taiga]

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/home#559]
# Step 1
as 3bot package 
- [x]  Import all info from taiga use their api python client (?)
- [x] Cache in mem (functools, LRU cache?)
- [x] Maybe taiga is fast enough
- [x] Create actor to expose CSV format with all info
- [x] So can import in google sheet as first solution to our reporting problem

# Step 2
- [ ] Import in datastructure using the jumpscale baseclasses (see Kristof)
- [x] Coordinate creation of datagrid to give people overview of (Waleed)
  - [x] Their stories
  - [x] Their tasks (checklists)
  - [x] Circles they own (need to see how we will do this)

**Comment by despiegk** [comment]
is taiga fast enough?

**Comment by despiegk** [comment]
can you make an actormethod to move a story from one circle to another?
usecase: relocate stories between projects

**Comment by alichaddad** [comment]
Moving user stories is not supported in taiga https://tree.taiga.io/project/taiga/issue/2776 @despiegk

**Comment by alichaddad** [comment]
Work done so far is on `unstable` branch.
Commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/849df7fcfd353121fc6896367e147dffb722d8ca

**Comment by despiegk** [comment]
can you mark what is done above?

**Comment by despiegk** [comment]
about moving stories, I know taigo does not do
but we can do
take the content from one story, create a new one
delete the source one if all succeeded and only then

**Comment by alichaddad** [comment]
Required actor actions are implemented. And added LRU caching.

**Comment by alichaddad** [comment]
Package is done and implemented a dynamic way to add views to packages.
Progress is reflected above.
