### ISSUE TITLE
tf_simulator playground [unstable_deploytfsimulator]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#560]
The idea is to make it easy for us to deploy new instances for tfsimulator and enhance the user experience for deploying new instances 

# Requirements
- [x] Deployment script on https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/scripts/play.grid.tf/play_with_simylator.py
- [x] Deploy on TF Grid  
  - [x] Use container (big enough)
  - [x] Webgateway for access simulator-RANDOMID.play.threefold.io (need to recheck)
- [x] Host chatflow to deploy directly on https://play.grid.tf
  - Chatflow informs user what will be deployed
  - Chatflow tell user deployed url
  - Chatflow redirects user to deployed url

# Enhancements
- [x] Make sure notebooks work

**Comment by ahelsayd** [comment]
can't work on branch development_baseclasses because of this issue
https://github.com/threefoldtech/jumpscaleX_threebot/issues/406
to unblock myself i will work on unstable for now

**Comment by ahelsayd** [comment]
block on https://github.com/threefoldtech/jumpscaleX_threebot/issues/470

**Comment by ahelsayd** [comment]
commit  https://github.com/threefoldtech/jumpscaleX_threebot/commit/d9ee58599fd2a2157a3409e3952adf451e69d94a

**Comment by ahelsayd** [comment]
converted this script https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/scripts/play.grid.tf/play_with_simylator.py into a 3bot package, and testing it now

**Comment by AhmedHanafy725** [comment]
## Verified

### Verification steps:
#### 1- Go to http://play.grid.tf/
![image](https://user-images.githubusercontent.com/41957921/78020428-bc7bda00-7351-11ea-9daf-73d4be6edf38.png)

#### 2- Continue and wait for the container link.
#### 3- Go to this container link.

![image](https://user-images.githubusercontent.com/41957921/78020832-707d6500-7352-11ea-9f5b-127d83923f35.png)

#### 4- Try notebooks
![notebooks](https://user-images.githubusercontent.com/41957921/78021071-d964dd00-7352-11ea-8b0f-724f7af6c249.png)

#### 5- Try terminal
![terminal](https://user-images.githubusercontent.com/41957921/78021164-0b763f00-7353-11ea-8d8b-ec6649e07b98.png)
