### ISSUE TITLE
Create tests for jumpscalex_10.5[development_testing]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/home#561]
The idea is to make it  new tests for new jumpscale components , and edit exist test to track the new changes in exist jumpscale components 

## Requirements 

- [ ] Create tests for threebot_dashboard 
- [ ] Create tests for codeserver https://github.com/threefoldtech/jumpscaleX_threebot/issues/418

**Comment by zaibon** [comment]
Not relevant anymore.
