### ISSUE TITLE
BCDB rest interface [development_bcdbrest]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#563]
- [x] Create bottle server as package in threebot
- [x] CRUD: post/get/delete on /bcdb/$packageurl/$schemaurl

# hints
- Check which BCDB in package url and get that bcdb and then get the model
- do set/and get 
- for find `GET` with params on /bcdb/$packageurl/$schemaurl?name=...&color=...`

note: protected behind 3bot connect (only admin allowed)

**Comment by xmonader** [comment]
@abom make sure to rename the branch to be `development_bcdbrest` instead of `development_bcdb_rest`

**Comment by abom** [comment]
Now it's a part of webinterface (loaded by default).

Two PRs, https://github.com/threefoldtech/jumpscaleX_core/pull/613 and https://github.com/threefoldtech/jumpscaleX_core/pull/613.

docs: https://github.com/threefoldtech/jumpscaleX_threebot/blob/c17e0608b646c35ed1d6940e6dc7117ced1894f0/ThreeBotPackages/zerobot/webinterface/wiki/bcdb_rest.md

**Comment by abom** [comment]
@Hamdy Can you verify this? as @Dina-Abd-Elrahman won't be able to do this from now on.

**Comment by Hamdy** [comment]
added j.tools.packages.bcdbrest.test()
