### ISSUE TITLE
research schema replacement

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#567]
See if we can come up with a static structure definition (as in defined at compile time), in contrast to the user defined schemas (at runtime). 

Ideally, the long term goal would be a framework (for 3bot) with the following features:
 - Every root object is owned by exactly 1 3bot.
 - Object serialization, preferably so we only serialize data which has actually changed and communicate that back to the 3bot, which checks ACL to see if this is allowed.
 - Local object caching?
 - Strict typing so we are sure about the input/output of a field

This should then be exposed in JS/WASM, python, ...?

**Comment by zaibon** [comment]
closed in favor of: https://github.com/threefoldtech/home/issues/567
