### ISSUE TITLE
wiki basic functionality [development_basicwiki]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#569]
- links (basic use cases)
  - [x] link to a file in the repo (first file in the repo that matches)
  - [x] whatever available working linking schemas  and document them

- includes (basic use cases)
  - [x] include to a file in the repo (first file in the repo that matches)
  - [x] whatever available working including schemas  and document them

- [x] macros: all of the current macros (google slides, pdf, gallery, teams..)
- [x] pull button for the wikis

**Comment by abom** [comment]
All is working on unstable, need to configure gdrive client (main instance)

```python
cl = j.clients.gdrive.get_from_file(name="main", path="/sandbox/var/cred.json")
cl.save()
```

Had some problems not related to wikis, but all of them should be fixed now, and i could load examples wiki using:

```
jsx wiki-load -n examples -u https://github.com/threefoldtech/jumpscaleX_threebot/tree/unstable/ThreeBotPackages/zerobot/wiki_examples/wiki -f -r
```

Going to `https://172.17.0.2/wiki/examples` to verify includes, macros...etc

**Comment by abom** [comment]
For documentation, all of wiki macros and link formats are still documented here

https://github.com/threefoldtech/jumpscaleX_threebot/tree/unstable/docs/wikis

**Comment by abom** [comment]
For links, it resolves the link if it's a custom one, otherwise we cannot do it with a single file name, yields lots of problems that has been discussed before.

**Comment by xmonader** [comment]
using links with just the filename is supported now  using custom link `:` before the filename 
https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/docs/wikis/links.md#a-custom-link-with-only-paths

same for includes

**Comment by abom** [comment]
Will test `:filename` links with includes

Also, will add a `pull` button (https://github.com/threefoldtech/jumpscaleX_threebot/issues/473)

**Comment by abom** [comment]
Includes work with file names (even without a colon)

All macros are documented https://github.com/threefoldtech/jumpscaleX_threebot/tree/unstable/docs/wikis/macro

**Comment by abom** [comment]
Added reload button at https://github.com/threefoldtech/jumpscaleX_threebot/commit/252b6beb73c52ed866a3fe7c94795916911b5198.

**Comment by abom** [comment]
Added more examples to `test_include` of `wiki_examples` too at https://github.com/threefoldtech/jumpscaleX_threebot/blob/252b6beb73c52ed866a3fe7c94795916911b5198/ThreeBotPackages/zerobot/wiki_examples/wiki/test_include.md#only-filenames.

**Comment by john-kheir** [comment]
Verified
