### ISSUE TITLE
basic grid usecases using own 3bot on jumpscale 10.4

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#570]
## goal

- anyone can play with threefold environment using locally install 3bot (in docker)

## starting point

process as followed by user

- install jsx tool (see website from branch unstable)
- use 'jsx threebot_test -w' to get an up and running threebot environment
    - if on osx, wireguard connection made
- test the admin webinterface, should get access no need for 3bot connect

### kubernetes

- deploy kubernetes using wizards on own 3bot
- deploy some chosen solution using the deployed kubernetes
- deploy monitoring (grafana/...) to visualize something from chosen solution
- use webgateway through additional step to expose the chosen solution

### S3

- deploy S3 solution using wizards on own 3bot
- use webgateway to access the S3 solution
- test S3 connection

### 3bot

- deploy 3bot using wizards on own 3bot
- access the 3bot show it works

### scripts

- same as above but with scripts

### TF main wiki

- if needed show how to install wiki (but think is part of std threebot install)
- show access to main TF Wiki
- show how to edit wiki and reload

## deliverables

- [ ] all documentation on main tf wiki
    - [ ] user can find all there on the wiki to do everything as described above

**Comment by despiegk** [comment]
dont start because kristof declares the install process with docker table working on it right now

**Comment by rkhamis** [comment]
threebot_init will have to be done first. otherwise workloads would not be accepted

**Comment by RafyAmgadBenjamin** [comment]
The  command ```threebot_test``` is not there yet
![image](https://user-images.githubusercontent.com/46320202/78470972-cfb1ef80-772d-11ea-8831-a792a0668c76.png)
