### ISSUE TITLE
Need to improve documentation for capacity reservation [development_reservationmanual]

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#572]
Story for improving documentation for capacity reservation: 

[] Reserve capacity [see doc](https://github.com/threefoldtech/jumpscaleX_libs#JumpscaleLibs/sal/zosv2/readme.md)

**Comment by xmonader** [comment]
docs merged into development/unstable, will leave this story open for enhancements

**Comment by gmachtel** [comment]
Branch development_reservationmanual reopened (added payment example, more explanation)
