### ISSUE TITLE
It should be possible to share your screen [development_sharescreen]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#576]
- [x] There should be an option to share your screen with the other users in the room
- [x] Frontend has to BC ID to backend
- [x] Other users can join
- [x] When a user is sharing their screen, it should be possible to enlarge this screen share to full screen size
- [x] It should be possible to pick which screen to share when the user has multiple displays

**Comment by jdelrue** [comment]
Still buggy, mostly happy path
