### ISSUE TITLE
get 3Bot support in tfchain production-ready

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#58]
Goals:

- [ ] prevent double registration of names and public keys;
- [x] register 3Bot fee payments in parent block;

Work will involve tfchain and the blockchain libs in JumpScale.
For now we go for a quick solutions that fits within the current codebase,
keeping the mindset of the perhaps duck-and-tape solutions.
Next year we can then work on a new version of the consensus and block creator modules.

Specific tasks of this story yet to be defined. (2w)
Related issues: 
- https://github.com/threefoldfoundation/tfchain/issues/195

**Comment by GlenDC** [comment]
> register 3Bot fee payments in parent block;

done, see: https://github.com/threefoldfoundation/tfchain/issues/237

**Comment by Sacha96** [comment]
close#58
