### ISSUE TITLE
The application should be mobile compliant[dev_mobile]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#583]
- [x] Scale layout on mobile
   - [x] Mobile user controls
   - [x] Mobile chat
   - [x] Mobile stream view
   - [x] Mobile UserList toggleable
   - [x] Mobile main user view selection
- [ ] ~Support touch events and motions~
- [x] Implement mobile login flow for 3bot connect

**Comment by jdelrue** [comment]
@DeanVerjans updates?

**Comment by DeanVerjans** [comment]
@jdelrue Converted the old mobile design to a working one with CSS-Grid
