### ISSUE TITLE
revise/enhance jsx dockers [unstable_jsxcontainer] 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#585]
test and harden:
- [x] container-install 
- [x] container-start
- [x] container-kosmos
- [x] container-import
- [x] container-export
- [x] container-stop
- [x] container builder 

# issues
- [x] redo argument https://github.com/threefoldtech/jumpscaleX_core/issues/642
- [x] DockerContainer has no attribute sshshell https://github.com/threefoldtech/jumpscaleX_core/issues/643
- [x] long time to start https://github.com/threefoldtech/jumpscaleX_core/issues/648

**Comment by m-motawea** [comment]
container-stop & container-start commit https://github.com/threefoldtech/jumpscaleX_core/commit/ee26335fdc7483178e9e02e992c8fc8455e79d4c

- preserve container on ```jsx container-stop```
- check for container in docker in ```jsx container-start``` and start it if it exists

**Comment by ahelsayd** [comment]
fixing import commits
https://github.com/threefoldtech/jumpscaleX_core/commit/244a4bf8fe8f7719b151295b3589c4b7fe01b7fd
https://github.com/threefoldtech/jumpscaleX_core/commit/b4232e1f38000e8e291d930a4eb8492113e5250a

**Comment by ashraffouda** [comment]
basebuilder fixed 
threebot builder almost done

**Comment by ashraffouda** [comment]
threebotbuilder is working without errors now,
but the image itself is corrupted still fixing that

**Comment by ashraffouda** [comment]
threebotbuilder done

**Comment by Dina-Abd-Elrahman** [comment]
- threebotbuilder doesn't work, it took very long time in ` failing in installing pycapnp` then terminate with this error

![ff](https://user-images.githubusercontent.com/21218053/77533379-6dd8c680-6e9f-11ea-85e0-bfc47771aefb.jpg)

**Comment by ashraffouda** [comment]
Verified on many machines it works
on ur machine it has 1G memory
can u plz verify on a machine with at least 3G memory

**Comment by Dina-Abd-Elrahman** [comment]
- verified on 3G memory machine and it's working correctly.
