### ISSUE TITLE
authentication review [unstable_authentication] 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#587]
check authentication on:
   - [ ] gedis
   - [ ] http bcdb rest interface
   - [ ] http actors
   - [ ] http webserver

if admin/local, should be authenticated by default and set in session

**Comment by grimpy** [comment]
So far I've rebased https://github.com/threefoldtech/jumpscaleX_core/tree/development_secrethandshake into unstable_authentication will start testing

**Comment by grimpy** [comment]
the branch is working again. if we decide to merge this we will have a closed system

**Comment by grimpy** [comment]
Blocked on: https://github.com/threefoldtech/zos/issues/627
