### ISSUE TITLE
Fix issues for chatflows and validate [unstable]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#588]
Fix:
 - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/459
 - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/455
 - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/454
 - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/452
 - [x] https://github.com/threefoldtech/jumpscaleX_threebot/issues/451

and validate these chatflows:
  - [x] deploy 3bot
  - [x] deploy ubuntu
  - [x] deploy your own flist
  - [x] deploy k8s
  - [x] deploy minio

**Comment by BolaNasr** [comment]
ubuntu deploy works good: 
![image](https://user-images.githubusercontent.com/10259267/77251538-89ea2700-6c57-11ea-86b6-95c16242ad73.png)

**Comment by BolaNasr** [comment]
3bot deploy works good: 
![image](https://user-images.githubusercontent.com/10259267/77251611-f9601680-6c57-11ea-85da-badd7927195b.png)

![image](https://user-images.githubusercontent.com/10259267/77251620-0977f600-6c58-11ea-893d-e0f034a0ba2f.png)

**Comment by BolaNasr** [comment]
k8s deploy works good :

![image](https://user-images.githubusercontent.com/10259267/77252415-607fca00-6c5c-11ea-8c54-fa0dacb1075a.png)

**Comment by ranatrk** [comment]
**Minio** 
- successfully deployed
- logs in using accesskey and secret created with
- files uploaded
![Screenshot from 2020-03-22 16-04-02](https://user-images.githubusercontent.com/17128393/77251463-29f38080-6c57-11ea-8ee1-63eaff8f5edd.png)

**Comment by BolaNasr** [comment]
Tested creating flist with `https://hub.grid.tf/tf-bootable/ubuntu:18.04` and worked:
![Screenshot from 2020-03-22 17-59-38](https://user-images.githubusercontent.com/17128393/77254214-67143e80-6c68-11ea-9f81-b52494eb4664.png)
