### ISSUE TITLE
chatflow docs update [unstable]

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/home#589]
# Solutions chatflows
Create docs for the deployment of the chatflows:

- [x]  How to deploy the chatflows themselves (deployer)
- [x] chatflow sal
- [x] MinIO package
- [x] Threebot reservation package 
- [x] Ubuntu reservation package
- [x] your flist reservation package
- [x] k8s reservation package

**Comment by BolaNasr** [comment]
Threebot reservation doc: https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/tfgrid/threebot_provisioning/wiki/threebot.md

Ubuntu reservation doc: https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/tfgrid_solutions/ubuntu/wiki/ubuntu.md 

your flist reservation doc:  https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/tfgrid_solutions/any_flist/wiki/your_flist.md

**Comment by ranatrk** [comment]
Minio reservation doc: https://github.com/threefoldtech/jumpscaleX_threebot/blob/unstable/ThreeBotPackages/tfgrid_solutions/minio/wiki/README.md

**Comment by ranatrk** [comment]
chatflow sal : https://github.com/threefoldtech/jumpscaleX_libs/blob/e1bfadf2b75a2322be2730e60efcb17a88a94a0b/JumpscaleLibs/sal/chatflow/readme.md
