### ISSUE TITLE
Upgdrade 0-Core without reboot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#59]
parent of threefoldtech/0-core#75
parent of threefoldtech/0-core#88
parent of threefoldtech/0-core#90
parent of threefoldtech/0-core#89
parent of threefoldtech/0-core#91

hot update, over the wire, of zero-os.
The goal is to be able to upgrade running zero-os's in the field without any downtime.

To do this, operational logic of zero-os needs to be separated from the init process which can be separately updated.

- [ ] New zero-os protocol https://github.com/threefoldtech/0-core/issues/75
- [x] Stripping down init to the bare minimal, and implement plugin support
- [x] Move all different modules to separate modules/plugins
- [ ] Support hot load and reload of modules
- [x] implement `kexec` for fast full image restart

**Comment by muhamadazmy** [comment]
This issue is now obsolete, and can't be delivered with the current version of zos. I will close it.
