### ISSUE TITLE
farm mgmt integration in the dashboard [unstable_farmmanagementStandalone]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#592]
- [x] [convert to standalone package](https://github.com/threefoldtech/jumpscaleX_threebot/issues/467) @tobiaschielens 

in the admin panel @ahelsayd 
- [x] integrate in the admin panel
  - [x] only install the farm mgmt if needed (check the code for codeserver, notebooks packages) for lazy loading
  - [x]  use an iframe to include it in the UI
- [x] if there's any dependency in webplatform needed and can be reduced take it out, the "webplatform" is discontinued
- [x] documentation in the wiki dir

**Comment by ahelsayd** [comment]
dashboard integration is done 
commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/5fa94c860a5388a405cffc792750d1a514dfc86d
