### ISSUE TITLE
chatflows improvements part 2 [unstable_chatflows]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#593]
- [x]  [chatflow for network deployment ](https://github.com/threefoldtech/jumpscaleX_threebot/issues/495)(the user should be able to reuse their network across their solutions
- [x]  when reservation fails make sure to `cancel it` and resend it again as this will create a new reservation with the same content (should be implemented in chatflow sal probably instead of doing that for every deployment) https://github.com/threefoldtech/jumpscaleX_threebot/issues/495

Note: when reservation fails, explorer will refund automatically so no need to worry about that

**Comment by ranatrk** [comment]
**WIP** added check on reservation network for port in use issue, so that it is canceled and a new reservation is done with a new port is created instead
https://github.com/threefoldtech/jumpscaleX_libs/commit/d87f015bdaec6e7d55cc0b31940d7af3f65594f3

**Comment by BolaNasr** [comment]
The user can be able to reuse their network across their solutions
Feature commit : 
https://github.com/threefoldtech/jumpscaleX_libs/pull/138/commits/2982cbe315c2f3d8fcda958de369d6566b4ef374
