### ISSUE TITLE
Review and refactor SSL logic for openresty [unstable_ssl]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#595]
- move ssl configs in websites conflgs
- resolve ssl conflicts
- unify default website names

# issues
- [x] [too many certs issued for wiki]( https://github.com/threefoldtech/jumpscaleX_threebot/issues/469)
- [x] [openresty auto ssl: failback to default cert for localhost](https://github.com/threefoldtech/jumpscaleX_core/issues/650)

**Comment by hossnys** [comment]
both child issues verified on branch unstable
