### ISSUE TITLE
make bcdb tests green [unstable_bcdbtests]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#596]
Run all bcdb tests with no skips.

**Comment by RafyAmgadBenjamin** [comment]
### Working on tear down bcdb tests to be able to run them all together
**commit**
9c965f006b0dca55ae27324cf9cd38c2549ccd23
### Update 18_schema_update test to avoid confustion while using its schema with other tests
4694b8b7ee1eac923d315419cb306a2943ace7b4
### Code cleaning 
c1e08c2d2d4ecc6ce61b439eca0e069c3dfcba66

![image](https://user-images.githubusercontent.com/46320202/77557041-f10b1400-6ec1-11ea-8f9d-1d653a23ea08.png)

## Tests can run now but
* export test
* webdav test
* schema_update test
* models test 
**need more tear down to work effectively and many times**

**Comment by RafyAmgadBenjamin** [comment]
### Refactor BCDB export test to use a single database during exporting  so it can run now many times safely and keeping the system database separated. 
**commit**
https://github.com/threefoldtech/jumpscaleX_core/commit/503958afd1ef65c135d298e845491f29bb1091ae

**Comment by RafyAmgadBenjamin** [comment]
### I can not remove the schema that already loaded, it prevents some tests from rerunning again and cause it to crash (example schema update test)
**Issues**
https://github.com/threefoldtech/jumpscaleX_core/issues/679
https://github.com/threefoldtech/jumpscaleX_core/issues/680
one of the previous needs to be solved to make this test run more than one-time successfully

**Comment by RafyAmgadBenjamin** [comment]
### All the tests can run multiple times except :
* schema_update test
* models test

**Comment by rkhamis** [comment]
obsolete
