### ISSUE TITLE
Research best options for a decentralized chat solutions

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#597]
Compare between:
 - [ ] rocketchat
 - [ ] mattermost
 - [ ] nextcloud/talk
 - [ ] zulip
 - [ ] keybase
 - [ ] berty

points of comparison:
 - API
- how to build bots for it
- functionality
- how easy to integrate 3bot connect (we don't want people to maintain their identity on separate services)
- rebrandable
- mobile clients (are these rebrandable or integratable with 3bot connect)
- can we integrate FreeFlow Connect? how easy ?
- how compatible with our circle idea
- how fast
- how easy to maintain/monitor
- integration with onlyoffice

Solution should be deployed on the grid (scripted)

**Comment by hossnys** [comment]
after some research i reached  out to these info [there](https://docs.google.com/document/d/1FTZ6-TYgGe70qyrvMKUJbaIlGvuUzRNqWX0bdmmorrg/edit?usp=sharing) 
file to be updated with the founded information.

**Comment by hossnys** [comment]
| Rocket chat(JavaScript) | Mattermost(Golang and React) | nextcloud/talk(PHP -javascript) | Zulip(python -javascript) | Keybase(Go) | Berty(typescript)
-- | -- | -- | -- | -- | -- | --
API | REST-full APIs | REST-full APIs | REST APIs | REST APIs |   |  
Build bots | Yes , Here | Only built in ones ,here | not currently supported | Yes , Here | Still under development |  
Functionality |   |   |   |   |   |  
3bot connectintegration |   |   |   |   |   |  
Rebrandable | Yes | Yes ,already done before. | yes | yes |   |  
Mobile clientsRebrandable-Integratable with 3bot |   |   |   |   |   |  
integrate FreeFlow Connect |   |   |   |   |   |  
compatible with our circle idea |   |   |   |   |   |  
How fast | Super | Super |   |   |   |  
easy to maintain/monitor | yes | yes |   | yes |   |  
integration with onlyoffice |   |   |   |   |   |  
Demo | https://threefold.rocket.chat | Demo , admin_consolesamir@incubaid.com / tft007tft | https://try.nextcloud.com/ |   |   | https://berty.tech/docs/berty/#development-status

**Comment by hossnys** [comment]
@xmonader will check this comparison and see with development team which solution is better to go with it .
