### ISSUE TITLE
Manual for wiki editors [development]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#598]
Create a manual from scratch covering
- [x] Installation (JSX and how to spawn a threebot)
- [x] Wiki loading info_threefold / any wiki
- [x] Code editing in codeserver
- [x] Viewing/Reloading/Pulling wikis
- [x] Wiki syntax
- [x] manual testing

https://github.com/threefoldfoundation/info_threefold

**Comment by xmonader** [comment]
initial manual https://github.com/threefoldfoundation/info_threefold/blob/2ac18c2843ebb11e90431d33991113f72ecc5104/docs/wikieditors/_sidebar.md

**Comment by Dina-Abd-Elrahman** [comment]
- the wiki link here is unreachable https://github.com/threefoldfoundation/info_threefold/blob/2ac18c2843ebb11e90431d33991113f72ecc5104/docs/wikieditors/editing.md#wiki-syntax

and here also https://github.com/threefoldfoundation/info_threefold/blob/2ac18c2843ebb11e90431d33991113f72ecc5104/docs/wikieditors/editing.md#committing-changes

**Comment by xmonader** [comment]
@Dina-Abd-Elrahman please verify on development branch

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
