### ISSUE TITLE
Zero-Robot DM Integration part 1

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#60]
- [x] [migrate 0-robot to support jumpscale 960](https://github.com/threefoldtech/0-robot/issues/60)
- [x] [Add gedis interface](https://github.com/threefoldtech/0-robot/issues/58) (8h)

**Comment by zaibon** [comment]
Code complete and test written. But some recent change in gedis code broke my code. I will park this until gedis is stable again. No point running after something that is still moving that much
