### ISSUE TITLE
windows support for TFGrid SDK

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#600]
tfgrid sdk = JSX in container with optional 3bot server

### how on windows

- [x] use docker-compose to deploy 3bot container in local docker (use 3bot2 docker image)
- [x] deploy ssh key chosen from user or even login/passwd
- [x] checkout over HTTP or git if sshkey used the required repo's

### requirements

- [x] no mounts on host system
- [x] portforward for 3bot & TFGrid Notebook (Jupiter lab notebook)
- [x] hide irrelevant logs
- [x] codeserver needs to work, otherwise user cannot edit local files there
- [x] admin panel works

continue on: https://github.com/threefoldtech/home/issues/606

**Comment by waleedhammam** [comment]
untill now: https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Installation/windows_installation/jsx_windows.md

- installation ok, admin board, codeserver can be accessed
![image](https://user-images.githubusercontent.com/10658229/77657090-77d0f700-6f7d-11ea-9458-11292da99c34.png)

- ALso container works and doesn't mount on local filesystem
![image](https://user-images.githubusercontent.com/10658229/77657166-9505c580-6f7d-11ea-879b-cb00918c9606.png)

Still needs more work and test more than 1 container

**Comment by waleedhammam** [comment]
continue on: https://github.com/threefoldtech/home/issues/606
