### ISSUE TITLE
TFGrid SDK final touches & tests

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#601]
TFGrid SDK = JSX/3bot in local container

needs to be good enough

- [x] <20 sec up & running after first docker image download
- [x] local 3bot server with admin panel
- [x] codeserver good enough working
- [x] TFGrid notebook working
- [x] first example deployment scripts in TFGrid notebook done
- [x] wiki working for TF foundation
- [x] wizards for deploying capacity on TFGrid working
- [ ] no ugly logs

**Comment by alichaddad** [comment]
There are some bugs on simulator that I am working on fixing.
Code server works as expected.

**Comment by rkhamis** [comment]
I'm not sure what ugly logs are
