### ISSUE TITLE
Improvements on windows support for TFGrid SDK

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#606]
Continuation of #600 

 - [x] user can go in the container with any SSH client
 - [x] add documentation
 - [x] <20 sec once docker image loaded [blocked on https://github.com/threefoldtech/jumpscaleX_core/issues/648]
 - [ ] make more user-friendly

**Comment by waleedhammam** [comment]
not valid anymore, continues on https://github.com/threefoldtech/jumpscaleX_core/issues/722 with 3sdk
