### ISSUE TITLE
update kosmos to use prompt toolkit 3.x [development_kosmos]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#610]
currently, we use 2.0.9 and accidental upgrading to 2.10 doesn't work and yielding errors like 
![image](https://user-images.githubusercontent.com/64129/77817809-9565a400-70d6-11ea-84b5-b75e8847744f.png)

- [ ] review kosmos code and upgrade it to 3.x version of ipython

check if there're more items to be added to the story

**Comment by sasha-astiadi** [comment]
@rkhamis is it done / planned to be done? please assign someone @rkhamis
