### ISSUE TITLE
3bot test users

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#611]
can we do something on explorer for phonebook
that any user who is created in test domain

despiegk.test

gets removed after 1 month

and that everyone can overwrite the one from a user before

e.g. if despiegk.test already exists, I can overwrite it

I realize there is a risk here but we need something to allow people to create many 3bot id's without poluting our environment

we need to think about charging for it soon

**Comment by zaibon** [comment]
I think what you are trying to express is the need of a test environment. Lucky you testnet is there for that. 

Regarding auto remove and overwrite I don't think this is a good idea. This just push wrong habit to the users. It also will force us to have weird logic in the code that inevitably will become messy.

Any user can already create any number of identities he wants. The only constraints are name and email address have to be unique throughout the all phonebook. But nothing prevent a single physical person to "own" multiple identity in the phonebook.

A user can already overwrite any of the data in its own phonebook user as long as he can proof he own the private key link to the public key registered in the phonebook  (signature).

**Comment by gmachtel** [comment]
Many projects do a reset of their testnet on a regular base. If we communicate that well, I don’t see an issue. Agree with zaibon not to make the logic in the code too complex, with individual removes and overwrites, it’s going to become a mess.
