### ISSUE TITLE
admin dashboard improvements [development_admin]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#613]
- [x] start/stop did not work on packages
- [x] same for install
- [x] packages like alerta and myjobs_ui are obsolete, we have our admin interface
- [ ] should there be no detail page of a package, job, ... it does not open to a detail widget
- [ ] bad formatting of message in alerts
- [x] cannot delete logs & alerts, should be possible
- [x] allow stop/start of codeserver (through package)
~- [ ] don't show health for codeserver or jupyter if not installed~ fixed in 10.4

**Comment by despiegk** [comment]
alert message bad
![image](https://user-images.githubusercontent.com/6021844/77842533-bb04b300-7193-11ea-86b4-1a409cf85f3a.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/77842708-d375cd00-7195-11ea-88cb-5a0dfa38a65d.png)

not good enough
if jupyter or codeserver not installed no need to show error

**Comment by xmonader** [comment]
I checked already done points on unstable.

**Comment by xmonader** [comment]
closed in favor of this https://github.com/threefoldtech/jumpscaleX_threebot/issues/563
