### ISSUE TITLE
jupyter integration in admin needs to be improved [development_jupyter]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#614]
- there needs to be easy way how to install multiple jupyter packages in admin panel
- when clicking on notebook part need to have following
    - [ ] grid of installed Jupyter packages
    - [ ] start or stop the Jupyter instance (need to use package stop/start)
    - [ ] see the status of the Jupyter instance
    - [ ] link to the url where the notebook is hosted, so people can go there seamless
- [ ] voila option review (need to make sure it renders correctly)
- [ ] Try to minimize the kernels used (would be great if all notebooks can share same kernel) (low prio) 

- need a stop all command, all notebooks stop

**Comment by sasha-astiadi** [comment]
is it done / planned to be done? @rkhamis
