### ISSUE TITLE
js-ng research evaluation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#618]
# background

The work been done last year in summer training on how we can use a more standard/modern solutions in the python ecosystem while staying as close as possible to the original intentions of @despiegk 

# repos
https://github.com/js-next
- [js-ng](https://github.com/js-next/js-ng): the core
- [ js-ext:](https://github.com/js-next/js-ext) example of an extension library
- [js-ext-template-cookiecutter](https://github.com/js-next/js-ext-template-cookiecutter) to bootstrap extension libraries easy as well
- [general design docs](https://github.com/js-next/js-ng/tree/development/docs/specs)
-  [API docs ](https://js-next.github.io/js-ng/api/jumpscale/)

# main check points
- pip installable 
- using poetry [specs and comparison with pipenv](https://github.com/js-next/js-ng/blob/development/docs/specs/poetry.md) and [pyproject format support](https://python-poetry.org/docs/pyproject/)
- [dsl based on facilities exposed under god object: j](https://github.com/js-next/js-ng/blob/development/docs/specs/god_object_namespaces_concepts.md)
- [API generated docs](https://js-next.github.io/js-ng/api/jumpscale/)
- [baseclasses support ](https://github.com/js-next/js-ng/blob/development/docs/specs/baseclasses.md) and [implementation](https://github.com/js-next/js-ng/tree/development/jumpscale/core/base)
- [pluggable](https://github.com/js-next/js-ng/blob/development/docs/specs/god_object_namespaces_concepts.md) 
- safe for host machines [works well with virtualenvs](https://github.com/js-next/js-ng/blob/development/docs/specs/poetry.md)
- [command distribution using entry points ](https://github.com/js-next/js-ng/tree/development/jumpscale/entry_points)
- configmgmt [(2 backends file and redis)](https://github.com/js-next/js-ng/blob/development/jumpscale/core/base/store.py) 
- [example client for redis](https://github.com/js-next/js-ng/blob/development/jumpscale/clients/redis/redis.py) with config mgmt 
- [gedis server ](https://github.com/js-next/js-ng/blob/development/jumpscale/servers/gedis/server.py) / [gedis client](https://github.com/js-next/js-ng/blob/development/jumpscale/clients/gedis/gedis.py) 
- modern [syncer](https://github.com/js-next/js-ng/blob/development/jumpscale/tools/syncer/__init__.py) tool
- [kosmos shell ](https://github.com/js-next/js-ng/blob/development/jumpscale/entry_points/jsng.py)
- very easy/familiar interface (lots of things ported (sals, clients in almost 0 time)
- jsx [schema](https://github.com/js-next/js-ng/blob/development/jumpscale/data/schema/schema.py) and [advanced types ](https://github.com/js-next/js-ng/blob/development/jumpscale/data/types/types.py) are supported 
- extensions are very easy to do (pip based) check [js-ext](https://github.com/js-next/js-ext)

**Comment by zaibon** [comment]
js-ng has been approved. closing
