### ISSUE TITLE
Testing stellar payment integration [unstable_payment_testing]

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/home#624]
### Scope: 
This story will focus on testing stellar payment integration

### Objective
Test all possible scenarios related to stellar payment where reservation does succeed or fail

### issues:
- [x] https://github.com/threefoldtech/jumpscaleX_libs/issues/158

**Comment by xmonader** [comment]
Regarding jumpscale, the 3bot will need to start with a stellar wallet to do the payments for 3bot owner.

**Comment by gmachtel** [comment]
already live
