### ISSUE TITLE
new identity manager integrated [unstable_identity]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#625]
the new identity manager needs to be tested/documented/...
all will operate from a shell only

**Comment by despiegk** [comment]
once first version ready & have the shell usable Kristof will handover

**Comment by m-motawea** [comment]
- Phonebook registeration is now working in `j.me` 
- Threebot server and solutions are now working with the new identity.
- `jsx kosmos` is using the new identity. (quickstart to initialize new 3bot with identity: https://github.com/threefoldtech/jumpscaleX_core/blob/unstable_identity2/docs/Identity.md)

**Comment by m-motawea** [comment]
TODO:
1- migrate j.tools.threebot to j.me
2- check if all usages of j.me and j.myidentites.(me, default, get) are correct

**Comment by waleedhammam** [comment]
using multiple identities: https://github.com/threefoldtech/jumpscaleX_core/blob/unstable_identity2/docs/Identity.md#creating-multiple-identities

**Comment by waleedhammam** [comment]
unstable_identity2 now up to data with unstable, 3bot server starts and can deploy solutions
![Screenshot from 2020-04-09 20-26-29](https://user-images.githubusercontent.com/10658229/78928157-6a992980-7aa0-11ea-8aee-4fcd8a868d86.png)

**Comment by waleedhammam** [comment]
TODO:

- More testing and verification

**Comment by xmonader** [comment]
verified. and merged into unstable already
