### ISSUE TITLE
3bot / packages cleanup / nacl removal [unstable_identity]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#626]
## packages

- [x]  go over all packages
- [x] make sure readme is ok
- [x] packages which don't belong in threebot repo move them to other relevant repo

## nacl cleanup

- [x] nacl still everywhere in code
- [x] everything should ONLY use:  ```jumpscaleX_core/JumpscaleCore/me```
- [x] the tools are underneath me....

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/78472952-3c80b600-773d-11ea-84df-aebc41d19129.png)
prob no longer needed

remove the things which are now implemented on new explorer

phonebook backend
workloads backend
tfgrid directory
...

**Comment by despiegk** [comment]
prob no longer relevant jumpscaleX_threebot/ThreeBotPackages/tfgrid/registrationthreebot

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/78493532-79eb4080-7749-11ea-8c7b-f18ad540c731.png)

**Comment by rkhamis** [comment]
packages are all cleaned up

**Comment by m-motawea** [comment]
moving to j.me and j.me.encryptor was done in https://github.com/threefoldtech/home/issues/625

**Comment by xmonader** [comment]
closing
