### ISSUE TITLE
info_threefold -> mdbook also for all package wikis

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#627]
rust mdbook

the tfgrid_compute_storage part can be skipped (because that we are already doing)

**Comment by despiegk** [comment]
work from development branch

**Comment by rkhamis** [comment]
blocked on https://github.com/threefoldtech/jumpscaleX_threebot/issues/553

**Comment by xmonader** [comment]
- wikis converted to mdbook format
- wiki packages in admin
- webhooks integrated
