### ISSUE TITLE
Freeflowconnect polishing

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#630]
- [x] Catch screenshare stopped
- [x] Show name of user who's sharing their screen instea of active speaker in left corner
- [x] Room in url
- [x] Re-enable video does not work  GRAY OUT
- [x] Pinning
- [x] @message.click => show time in corner
- [x] Add more snackbar messages (on mute/...)
- [x] On join -> Emit screenshare started to the new user and not everyone
- [x] Send screenshare_stopped signal
- [x] Fix margins in messages
- [x] Remove rounded border in sidepannel
- [x] Paste room ID in landing page
- [x] When joining a room, check if someone is sharing their screen
- [x] Scroll down in chat on refresh
- [x] If video is not working show nice error instead of white box
- [x] Show chat by default (no chatbutton needed I think? ) 
- [x] Upload file doesnt seem to work (fix or hide?)
- [x] Chat not always working
- [x] Show 3bot names on the videos 
- [x] Show first stream as big (or speaker if possible)
- [x] Click on link in chat
- [x] Resizing of frame makes part of video dissapear ( black borders up and own)
- [x] Layout, my video above others? 
- [x] Desktop shares (1 per group; in the main screen)
- [x] Disable fileshare for now since it is buggy

- [x] No users in the room -> black screen looks bad
- [x] Names switching

**Comment by coeneivan** [comment]
File upload works but not for files bigger then 1MB.
Should I hide it for now @jdelrue ?

**Comment by jdelrue** [comment]
Can we give an error to the user? Please use file below 1mb?
