### ISSUE TITLE
File manager with Backend in Crystal lang

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/home#634]
filemanager that is responsive with Crystal lang backend

- [x] Find a filemanager frontend that is responsive
- [ ] Implement Backend in crystal lang
- [ ] Threebot login support
- [ ] Integrate with new rust DB

**Comment by Hamdy** [comment]
**Frontend**  We are going to use the filebrowser : https://filebrowser.xyz/ it's responsive

**Comment by sasha-astiadi** [comment]
https://github.com/crystaluniverse/crystal_filebrowser

**Comment by sasha-astiadi** [comment]
@Hamdy please recreate one issue on crystaluniverse if still active
