### ISSUE TITLE
desktop testing environment for out SDK

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#635]
we need a solution to test our SDK on multiple versions of desktop, 
rather than doing this manually we need a generic usable solution

## preparation

- create virtual box images for the multiple desktops
- OSX: Catalina and the previous version
- windows 10, ...
- ubuntu 1604, 1804, 1904 

SSH login on all , enabled when booting
- VNC also installed on all, root:tester007
- root:tester007

store these images on a company S3 cloud on our grid, have copies locally !

desktops need to be empty

## scripts

- make scripts in jumpscale to start virtualbox
- set right parameters
- launch chosen desktop
- login over SSH remote install docker
- use 3sdk and over SSH pass right commands to it

**Comment by PeterNashaat** [comment]
trying to find a working mac os image.

![2020-04-19 18 17 34](https://user-images.githubusercontent.com/13523434/79693304-17766200-826a-11ea-856c-3fb15d175aef.jpg)

**Comment by Pishoy** [comment]
Win10 image is ready now as below
![IMG_20200419_182051_338](https://user-images.githubusercontent.com/21987477/79693375-8ce23280-826a-11ea-8708-e7e43c559d88.jpg)

**Comment by zaibon** [comment]
Why not just running the tests of the SDK on github action or any other testing platform that allows different OS ? It is way less work then trying to manage this all system manually. And it gives you report directly on the repo themself ?

**Comment by AhmedHanafy725** [comment]
I tried using github actions on (`Linux` and `Catalina`) and it worked fine on `Linux`, but it didn't work on `Catalina` as docker didn't start and I found opened issue on docker with this https://github.com/docker/for-mac/issues/4307 

![image](https://user-images.githubusercontent.com/41957921/79954929-5bda4b80-847e-11ea-847c-c9569afbe38e.png)

**Comment by PeterNashaat** [comment]
- Ubuntu 18.04 is uploaded in our s3 with the requested password , vnc and ssh enabled

**Comment by Pishoy** [comment]
- Win10 image is uploaded to s3 https://s3.grid.tf/minio/os-images/
With rquired services ssh, RDP 
- now am testing JSX installing in Windows 10 and prepare automated installation script

**Comment by AhmedHanafy725** [comment]
Also tried windows server on github actions and it didn't work.

![image](https://user-images.githubusercontent.com/41957921/80068367-c99a7c00-853f-11ea-8508-516f16a2c66b.png)

Experimental feature is disabled on windows runner os, so docker linux's images are won't work https://github.community/t5/GitHub-Actions/How-to-use-Linux-Docker-container-on-Windows-VM/td-p/38535
I think github actions can't be used.

**Comment by PeterNashaat** [comment]
tried macOS Sierra vmdk image, tried to fix it but didn't work.

<img width="1228" alt="Screen Shot 2020-04-23 at 11 38 54 AM" src="https://user-images.githubusercontent.com/13523434/80105626-236b6800-8579-11ea-82df-bf5b78f2ef4a.png">

**Comment by PeterNashaat** [comment]
Now trying this :-
https://github.com/myspaghetti/macos-guest-virtualbox
but i'm having some issues fixing them one at a time
<img width="1300" alt="Screen Shot 2020-04-23 at 3 35 29 PM" src="https://user-images.githubusercontent.com/13523434/80106367-0d11dc00-857a-11ea-9660-f6dad8c6a34c.png">

**Comment by Pishoy** [comment]
while testing installing jsx in windows10 , i got issue with nested virtualization as i am testing with ubuntu host  (droplet) in digital ocean installed on it a virtualbox and windows10 is a guest OS in ubuntu host as below 

![image](https://user-images.githubusercontent.com/21987477/80107023-e6a07080-857a-11ea-9ddb-ba3f6101d41f.png)
- now trying to test in my physical ubuntu laptop host with virtualbox guest os windows10

**Comment by PeterNashaat** [comment]
Almost done with Catalina installation
<img width="1219" alt="Screen Shot 2020-04-23 at 6 43 51 PM" src="https://user-images.githubusercontent.com/13523434/80125873-8d443b80-8592-11ea-85d4-3c3f446aeb60.png">

**Comment by PeterNashaat** [comment]
Getting disk is locked error, installation is not proceeding.
<img width="1206" alt="Screen Shot 2020-04-23 at 6 56 01 PM" src="https://user-images.githubusercontent.com/13523434/80127178-40616480-8594-11ea-9546-3c42082dab43.png">

**Comment by PeterNashaat** [comment]
Finally !
<img width="1226" alt="Screen Shot 2020-04-23 at 10 18 56 PM" src="https://user-images.githubusercontent.com/13523434/80145482-84faf900-85b0-11ea-82a3-ec3cff6994e2.png">

**Comment by PeterNashaat** [comment]
error in installation.

<img width="1224" alt="Screen Shot 2020-04-23 at 11 55 45 PM" src="https://user-images.githubusercontent.com/13523434/80153528-01480900-85be-11ea-8c74-9dc423ab1161.png">

**Comment by PeterNashaat** [comment]
- installation fixed, but it's not booting up!, will try to fix.

<img width="1224" alt="Screen Shot 2020-04-24 at 1 40 12 AM" src="https://user-images.githubusercontent.com/13523434/80159967-a9fd6500-85cc-11ea-886d-7a64554c0546.png">

**Comment by Pishoy** [comment]
- i tested to install jsx inside a windows guest os in virtualbox and host is Ubuntu 18.04 but it fail
![image](https://user-images.githubusercontent.com/21987477/80305452-0b842600-87bd-11ea-8f99-49b19b5c8b9b.png)

- can not test jsx in windows vm in a virtualbox, as it is requiring a docker desktop running in windows guest os which is requiring a hyper-v installed which is not supported by virtualbox to hyper-v and docker desktop inside the windows guest os 

-  to test jsx need another solution or run in physical server

**Comment by PeterNashaat** [comment]
trying on OVH node, getting this error while starting the vm : 

- vm log : 
```
00:00:01.740567 ERROR [COM]: aRC=NS_ERROR_INVALID_ARG (0x80070057) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={Argument aWidth is invalid (must be aWidth != 0 && aWidth <= 32767)}, preserve=false aResultDetail=0
00:00:03.295294 ERROR [COM]: aRC=NS_ERROR_INVALID_ARG (0x80070057) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={Argument aWidth is invalid (must be aWidth != 0 && aWidth <= 32767)}, preserve=false aResultDetail=0
``` 

- screenshot : 

<img width="1137" alt="Screen Shot 2020-05-05 at 5 41 30 PM" src="https://user-images.githubusercontent.com/13523434/81085617-bac8a780-8ef7-11ea-8995-62be42fd0783.png">

**Comment by PeterNashaat** [comment]
Can't create 3bot container as it need a working 3bot key every time.

![photo_2020-05-06 12 38 42](https://user-images.githubusercontent.com/13523434/81168100-a7b8e480-8f96-11ea-9d0b-58cd5cf8249c.jpeg)

**Comment by Pishoy** [comment]
- we could start a windows guest os in OVH node using KVM and we can create docker containers inside windows, seems OVH nodes support nested virtualization but where i test SDK installation, i got some errors , checking with waleed about that

**Comment by despiegk** [comment]
- why do you need nested virtualization, stay away from that please.
- you should use Virtualbox everywhere so it can run
- what is now the status of OSX, on the internet I see reports of people who do it, so why can't we?

**Comment by Pishoy** [comment]
- i tried to start docker in windows 10 guest os in virtualbox6.1 with Ubuntu 18.04 but does not started with me, i got same error as this below issue, ( seems it is buggy with Intel CPU) 
https://github.com/docker/for-win/issues/4470#issuecomment-567097907

**Comment by PeterNashaat** [comment]
- Docker installation on macOS is blocked, due to no kernel hypervisor support .
<img width="1371" alt="Screen Shot 2020-05-11 at 12 10 20 PM" src="https://user-images.githubusercontent.com/13523434/81793833-2ddea900-950a-11ea-9808-619789093297.png">

**Comment by PeterNashaat** [comment]
as kds requested i will close this issue as it is too complicated to do vm in a vm because of docker
