### ISSUE TITLE
Development Sandbox

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#64]
Development sandbox on linux and OSX

**Comment by Hamdy** [comment]
Finished by KDS


Task basic idea is to have A sandbox shipped with Pyhton/jumpscale & Lua/openresty

We have 3 Repos for this task (development_961 Branch)
==

1.  [Base Sandbox](https://github.com/threefoldtech/sandbox_base) contains only pure python&lua libs. It doesn't contain any platform specific libs `*.so` files so scripts in it, can run in any platform, be it  MacOsX or Ubuntu.
2.  [Ubuntu Sandbox ](https://github.com/threefoldtech/sandbox_ubuntu) contains native libs that are linux/ubuntu specific 
3.  [MacOsX Sandbox](https://github.com/threefoldtech/sandbox_osx/) contains native libs that are MacOsx specific

Combining [Base Sandbox](https://github.com/threefoldtech/sandbox_base) and one of the 2 other repos gives us the final sandbox we want

Testing Process
===

- Testing Build Ubuntu Sandbox : location by default `{j.dirs.BUILDDIR}/sandbox/tfbot/`
   - Python Sandbox `js_shell 'j.tools.sandboxer.python.build(reset=False)'`
  -  Lua/Openresty Sandbox `js_shell 'j.tools.prefab.local.web.openresty.build()`

- Test each Sandbox individually
  - clone each repo and test the sandbox working by activating sandbox and checking python installation
- Test jumpscale shipped with sandbox is working : [JS_INSTALL](https://github.com/threefoldtech/jumpscale_core/blob/development_961/docs/Installation/install.md) 

- Test openresty functionality
