### ISSUE TITLE
Integration payments

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/home#648]
# Make chatflows support payments

## Add wallets
- [x] add new chatflow to setup wallets
  - wallets can be created automaticly on testnet for tft and freetft
  - wallets on mainnet need registration

## Update solutions chatflows
- [x] Update chatflows

When escrow information is retrurned from the reservation we will enter a new screen in the chatflow that will show infromation about the payments.
We will list the available wallets to pay + give an option to pay with the 3bot connection app

When a preconfigured wallet is chosen payment will be done automaticly, when 3bot connect app is chosen we will show QR code to scan by 3bot connect so payment can be made

**Comment by zaibon** [comment]
> wallets can be created automaticly for freetft
   wallets for tft needs registration


This is not right. On stellar testnet, ALL wallet can be activated for free.
On mainnet, we need to use the activation service provided by Threefold: https://github.com/threefoldfoundation/tft-stellar/#tft-stellar-tooling

The fact that you need to pay or not doesn't depend on the asset, but on which network you are using.

**Comment by zaibon** [comment]
@grimpy Do we allow user to write down their wallet secret ? and are they able to import a wallet ?

**Comment by zaibon** [comment]
![2020-04-24_2207x393_scrot](https://user-images.githubusercontent.com/303164/80183400-11d1a100-8609-11ea-98de-624622336278.png)
Could we also maybe show the balance on the grid ?

**Comment by grimpy** [comment]
> @grimpy Do we allow user to write down their wallet secret ? and are they able to import a wallet ?

Not yet I'll add this to the requirements

**Comment by rkhamis** [comment]
verified

**Comment by Dinaamagdy** [comment]
verification steps 
- test import wallets created and found them in chat fllow with values
- use freetoken created wallet in chatflow payement
