### ISSUE TITLE
Migrations of primitives 0-robot template to Digital-Me actor

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#66]
Once the 0-robot will be migrated to digital-me, we will have to migrate the template used to deploy 0-OS primitives into Digital-Me actor. 

The node templates that needs migration are:
- [ ] node
- [ ] zdb
- [ ] namespace
- [ ] network
- [ ] node_ip
- [ ] vm
- [ ] gateway
- [ ] container

Some clean up in the template will also need to be done to make sure we don't only deal with capacity deployment on the primitives templates and nothing else.
https://github.com/threefoldtech/0-templates/issues/274 is a good example of some clean up that needs to happens during this effort

Requires #60

**Comment by muhamadazmy** [comment]
The node robot will ONLY have these templates. They need to be cleaned up and have a defined and stable interface. Also they need to be rock solid. 

Once this is accomplished, other templates can run on local robot and it will be much easier to debug and develop.

**Comment by rkhamis** [comment]
With kosmos, this storycard becomes irrelevant
