### ISSUE TITLE
pricing improvements

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#663]
## issues

- today minimum fixed to 1 month, needs to become more variable

## change pricing to be

- CU = 15 USD/month
- SU = 10 USD/month
- NU = free for now 

- when < 1 week: price X 2
- when < 1 day: price X 4 (1h is smallest)

- more than 1 month, no discounts yet
- remark: 1.5 months is same as 2 months

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/tfexplorer/pull/43
