### ISSUE TITLE
Elements missing to make the release a success

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#666]
Releases JSX 10.5 done and grid 2.0.4 as well. 
As perception of these release to be not successful, here is inventory of elements to consider to improve. 

### Improve UX during installation of SDK

SDK was conceived for being used by developers. hence, it is now used by non-developers telling they are not able to do installation.
Checked with support team, that mention people are struggling with the **shell / command line interface**. But this shouldn't be a problem for developers. 
So we should find the right **target audience** to first deploy our Threebot SDK. 

Possible options: 
- A nice GUI also for the first steps of the installation, before the admin panel is shown ?
- Deployer of 3Bot on the grid ? But there is issue around payment there. Possible solution: explore using FreeTFTs ? 

### Blocking factors in capacity reservation
- [x] Reserving capacity with a node that does not have a Stellar wallet yet is impossible. See [issue](https://github.com/threefoldtech/jumpscaleX_threebot/issues/654)

### More Documentation

- mention Docker installation as a prerequisite in wiki/doc
- refine SDK setup on Windows 

### Bugfixing 
- ...

#### To be included
- ...

#### Excluded

- IPv4 support (not feasible to realise in the short term, is for future release)

**Comment by zaibon** [comment]
> Possible solution: explore using FreeTFTs ?

Keep in mind that at the moment, you can only pay reservation with free TFT on node that have been marked as free to use BY THE FARMER. At the moment I don't think there is a lot of hardware free except provided by the foundation.

**Comment by gmachtel** [comment]
Isn't the reason that we set FreeTFT = 'No' as default ? Can't we inverse, being FreeTFT accepted by all nodes unless changed by the farmer ? I think there wouldn't be any objection to that by farmers, it's even to their own interest in a startup phase. And in any case, they can change it if they do object.

**Comment by zaibon** [comment]
Ask them what they think. But if that was me. I would be pissed with such a change without me knowing it. It's how they make money.

**Comment by gmachtel** [comment]
They can always change, so no reason to be pissed about it. And it's not like there will be masses of FreeTFTs available, for the moment it's hidden behind an application form. 
Anyway, I will ask Andreas.
