### ISSUE TITLE
Changing and and adding information from existing farms results in no changes stored

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#668]

**Comment by joefoxton** [comment]
Update:

- Editing wallet address/es, email, and country all seem to work fine
- You can't edit the farm name

**Comment by AhmedSa-mir** [comment]
Can't reproduce

![Screenshot from 2020-05-11 13-24-14](https://user-images.githubusercontent.com/18093386/81556623-f0074680-938a-11ea-9f8f-99ae4012f19f.png)

![Screenshot from 2020-05-11 13-24-57](https://user-images.githubusercontent.com/18093386/81556621-ef6eb000-938a-11ea-8b8c-7027c0b9ec37.png)


![Screenshot from 2020-05-11 13-25-10](https://user-images.githubusercontent.com/18093386/81556616-eda4ec80-938a-11ea-8199-6b625e4975c2.png)

**Comment by zaibon** [comment]
The root cause of this issue is probably the same as https://github.com/threefoldtech/jumpscaleX_threebot/issues/673

**Comment by joefoxton** [comment]
As of today, changing the farm name works fine.

**Comment by Dinaamagdy** [comment]
verified
