### ISSUE TITLE
GE: the secret of the wallet is stored in clear text and shown 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#677]
why is the secret stored and shown in clear text?
in the GUI it is an extra click
in JSX you see it immediately

JSX> j.clients.stellar.ht1                                                                                                                                                                          

## jumpscale.stellar.client
ID: 59
 - name                : ht1
 - network             : STD
 - address             : GBKVJL52QU3OIKVPNCPP62B4MLJ5HRAOJ6X3S6KUJ6PVBIDVRKELZQ2B
 - secret              : SBK5 < I removed it > 6RW
 - sequence            : 126,651,765,150,973,954
 - sequencedate        : 2020/05/11 09:28:30

having the secret I can mount the wallet and use it!

**Comment by zaibon** [comment]
The data is stored encrypted on the filesystem. But it is shown in clear text both in the in the shell and in the UI cause you are authenticated in the system and the decryption happens transparently so you can see the actual value.
It is good practice to always copy the secret of any wallet you create so make sure you can restore it if that would be needed
