### ISSUE TITLE
Extension of capacity reservation 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#682]
Capacity can be reserved, but not extended. 
So currently, nothing can be done for the moment to leave the solution up and running if a user wants that. 

Some ideas : 
- new workflow and chatflow to be created that implement following workflow (image shows first part, after this workflow is the same as with reservation of new capacity: success or fail)
![image](https://user-images.githubusercontent.com/30384423/81565499-ba1d8e80-9399-11ea-8388-674446117c10.png)
- implement a signing_request_extend service

**Comment by joefoxton** [comment]
It would be ideal if there was an auto-extend setting, so you could make a reservation for one month, and it auto-extends every month if the user has paid, with a one month grace period for late payment.

**Comment by joefoxton** [comment]
Also... when you extend the reservation, you should also be able to grow the reservation. I imagine that this would be done manually in the short term, but automated via elastic reservations in the longer term.

**Comment by zaibon** [comment]
closed in favor of : https://github.com/threefoldtech/tfexplorer/pull/64
