### ISSUE TITLE
GE: 3sdk ubuntu deployment failed

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#683]
ubuntu deployment failed after 15min waiting
but reservation exists:
https://explorer.grid.tf/explorer/reservations/9273

![image](https://user-images.githubusercontent.com/24313736/81566813-b25ee980-939b-11ea-8713-5ebbc4ba7568.png)
![image](https://user-images.githubusercontent.com/24313736/81566832-b8ed6100-939b-11ea-8ba4-bd2132535184.png)

**Comment by hteibler** [comment]
where can I find logs and the root cause?

**Comment by zaibon** [comment]
The error message means the node didn't deploy the workloads in time and the provision timeout has been reached. I suspect this is a duplicate of https://github.com/threefoldtech/tfexplorer/issues/62

**Comment by joefoxton** [comment]
@zaibon What's the fix?
