### ISSUE TITLE
GE: Elastically grow reservations

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#684]
Currently, you can only reserve a fixed amount of storage/compute for a fixed amount of time. It would be idea to allow reservations to be "elastic":
- When the reservation ends, it auto-extends for one month until the reservation is closed/removed
- When the storage reaches a certain configurable threshold (let's say 90%), then the storage grows in configurable increments
- Haven't thought through how this would work on the compute side, but let's think about how to make this elastic also.

I imagine these would all be parameters on the original reservation, with an ability to edit these parameters.

**Comment by zaibon** [comment]
We are currently working on something that would allow something similar, if you are interested head to: https://github.com/threefoldtech/tfexplorer/pull/64

**Comment by joefoxton** [comment]
Not exactly. You are working on manual extension of a reservation. We are asking for auto-elasticity. 

However, the manual extension would work for us in the short term if we are able to script/automate it.

**Comment by joefoxton** [comment]
@zaibon I've read the staking & polling doc #749, and it seems like a very smart solution. However, I'm still not sure whether it gives us truly elastic reservations, which we'll need for some deals we're currently working on. Let me ask this a simpler way:

1. Will we be able to extend reservations in time, many times over the course of many years, without a cap?
2. Will we be able to grow reservations in size, many times over many years, without a cap?
3. Will this be possible starting this year?

**Comment by zaibon** [comment]
> Will we be able to extend reservations in time, many times over the course of many years, without a cap?

The reservation are not bound to time anymore. They are just linked to the capacity pool. So as long as your pool is provisioned, all the workloads attached to it continue to live.

> Will we be able to grow reservations in size, many times over many years, without a cap?

Workloads remains immutable. Anything different would break the IT contract and thus this is not allowed. But nothing prevent you from having your final application designed in a way that allows you to extend it. Minio and k8s cluster already works like this today.

> Will this be possible starting this year?

Yes, all this will be release in TFGrid 2.2 which is on testnet right now. It would be cool if you could play a bit on testnet to see if everything there works for you and is understood. 
You will also probably need to adapt a bit your eventual code/scripts you use to manages your services.

**Comment by joefoxton** [comment]
@zaibon Some further questions below:

> > Will we be able to extend reservations in time, many times over the course of many years, without a cap?
> 
> The reservation are not bound to time anymore. They are just linked to the capacity pool. So as long as your pool is provisioned, all the workloads attached to it continue to live.

Just to get this clear, does this mean we'll need to follow something like the following workflow?

1. Reserve capacity for one year.
2. Before the end of the year, load up another years worth of tokens to the "pool".
3. Extend the reservation for a year? 

Or is it more automatic than that? 

> 
> > Will we be able to grow reservations in size, many times over many years, without a cap?
> 
> Workloads remains immutable. Anything different would break the IT contract and thus this is not allowed. But nothing prevent you from having your final application designed in a way that allows you to extend it. Minio and k8s cluster already works like this today.

Just so I'm clear...

If I have a reservation for 1PB, and the customer ends up using the capacity, then their only option is to create a new separate 1PB reservation?

Or is it possible to create a new 1PB reservation, and connect it with the original minio server reservation?

> 
> > Will this be possible starting this year?
> 
> Yes, all this will be release in TFGrid 2.2 which is on testnet right now. It would be cool if you could play a bit on testnet to see if everything there works for you and is understood.
> You will also probably need to adapt a bit your eventual code/scripts you use to manages your services.

@zaibon Indeed, we'll start testing staking/pooling as soon as our new Lead Architect starts on October 5, if not before.

**Comment by zaibon** [comment]
> - Reserve capacity for one year.
>  - Before the end of the year, load up another years worth of tokens to the "pool".
>  - Extend the reservation for a year?

The last step is not required. Just topping up the pool is enough. Of course this could be automated since everything is available from the explorer API. So you can make your 3bot always keep a pool with enough token to run the worklaods attach for a predefined period of time.

> Or is it possible to create a new 1PB reservation, and connect it with the original minio server reservation?

This. Our minio implementation has a API where you can update it's config. So you can indeed reserve more 0-DB namespaces and update the minio config to make it aware of the new 0-DB namespace.

**Comment by joefoxton** [comment]
This is all fantastic news, and works well for us. Thank you Zaibon.

We may needs a bit of guidance on the “how”. I’ve suggested an in person workshop at TF Tech headquarters with myself and our new lead architect, Phillip Oldham. Would be nice to just to have lunch too :)

**Comment by zaibon** [comment]
these features are now live on the grid, I'm closing this.
