### ISSUE TITLE
GE: Installing threefold.wikis fails

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#686]
When I click "Install required packages" I get the following error

![Screenshot 2020-05-11 at 16 19 54](https://user-images.githubusercontent.com/1249806/81573246-81cf7d80-93a4-11ea-972e-bf632f6f219e.png)

**Comment by grimpy** [comment]
This has already been resolved in 10.5.3
These links now show the hosted sites: https://wiki.threefold.io/ and https://sdk.threefold.io/
