### ISSUE TITLE
GE: JSX error

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#687]
after been away 4 hrs from my computer
the same command ( which was working before) got an error:
see: https://github.com/threefoldtech/home/issues/677

j.clients.stellar.ht1                                                                                                                                                                          
Mon 11 19:18:22 /BASECLASSES/Attr.py -  39 - __getattr__                        : EXCEPTION: 
    try to get attribute: 'ht1', instance did not exist, was also not a method or property, was on 'stellarfactory'
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py in __getattr__
    39    % (name, self._key)
-----------------------------

Mon 11 19:18:22 /BASECLASSES/Attr.py -  39 - __getattr__                        : EXCEPTION: 
    try to get attribute: 'ht1', instance did not exist, was also not a method or property, was on 'stellarfactory'
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py in __getattr__
    39    % (name, self._key)
-----------------------------

try to get attribute: 'ht1', instance did not exist, was also not a method or property, was on 'stellarfactory'

**Comment by abdulgig** [comment]
If the wallet is there, you can still retrieve it using the ```get``` method. Try this,

```wallet = j.clients.stellar.get('ht1')```

**Comment by hteibler** [comment]
OK :  
JSX>j.clients.stellar.get('ht1')   is working
and JSX> j.clients.stellar.ht1    is now working again

very unstable behavior !

**Comment by rkhamis** [comment]
reopened because this should be fixed

**Comment by waleedhammam** [comment]
.get() actually creates a new instance if it's not exists that's why it doesn't fail.
was it in another kosmos shell ?

**Comment by hteibler** [comment]
sorry , but this is more than 1 week ago
it was all in the same shell
