### ISSUE TITLE
GE: documentation wrong, so hard to build code

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#688]
like:
JSX> j.tools.threebot.me                                                                                                                                                                            

error...

**Comment by abdulgig** [comment]
Thanks for pointing that out. This is now changed to,

```j.me```

You can use something like,

```me = j.me```

Could you please share the link to the document?

**Comment by hteibler** [comment]
everywhere in 
https://sdk.threefold.io/#/code

**Comment by zaibon** [comment]
Opened a issue so we make sure to update all example with latest version: https://github.com/threefoldfoundation/info_tfgridsdk/issues/98
