### ISSUE TITLE
GE: Maintenance Mode for Nodes/Farm

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/home#689]
Farmer should be able to perform planned Maintenance on there Nodes/Farms

**Why?**
Servers running for 5 Years might need 
- Firmware upgrades 
- Cleaning 
- Reapplying of Thermal compound 
- Have to be moved inside the DC
- Planned Maintenance in the DC on Network or Power
- Shut Down for RCM Testing (once per Year required by Law)
- Shut Down for insulation measurement (once per Year required by Law)

Compared to just switching the node off the Maintenance Mode does not impact the Uptime requirements and pauses the Cultivation Token (and of course) the Tokens earnings from Capacity sold.

**Considerations:**
- **Farmer sets a Maintenance for a whole Farm or single nodes**
   Farmer enters Start time, Date and Duration
   From that time on the Node is (from view of the Grid) in Maintenance Mode
   A Flag should be set in the Block-chain to record this, it would basically be a smart contract

- **Capacity Users should be informed**
   To give the Capacity User a chance to react to it if needed

- **Maintenance has to be announced at least 24-72 hours before start**
  To give the Capacity User a chance to react to it if needed 
  To prevent to just switch a failed Node in Maintenance mode to prevent Token loss

- **Max Maintenance duration 1-72 hours (to be discussed)**
  Repairing a Node can be done in 6 hours
  Moving or re-configuring a Farm in a DC can be done in 72 Hours
  To prevent Nodes staying in Maintenance Mode for extended periods of time

- **Max Maintenance duration per Year**
  to ensure Nodes are reliable and not down to much

**Comment by zaibon** [comment]
Pertinent remark. Let's try to come up with a scheme properly define for these kind of things.

@andhartl @weynandkuijpers @despiegk @LeeSmet

**Comment by zaibon** [comment]
https://forum.threefold.io/t/allowed-downtime-for-maintenance-windows/536?u=zaibon
