### ISSUE TITLE
statefull chatflows

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#694]
[development_chatflows_steps]
rework the current chatflows to have steps to go backwards.

chatflow:
 - [x] gitea
 - [x] s3
 - [x] k8
 - [x] ubuntu
 - [x] any flist
 - [x] gw
 - [x] network
 - [x] domain delegation
 - [x] solution expose

docs:
 - [x] gitea
 - [x] s3
 - [x] k8
 - [x] ubuntu
 - [x] any flist
 - [x] network

**Comment by BolaNasr** [comment]
All updates of chatflows at https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_chatflows_steps

**Comment by Pishoy** [comment]
verified
