### ISSUE TITLE
Ubuntu disk size to be configurable 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#695]
seams that the ubuntu container has a 10G diskqouta
which limits me installing tools in the container.

dpkg: error: unable to open/create status database lockfile: Disk quota exceeded

**Comment by rkhamis** [comment]
we currently set it as a default value to keep the chatflow short and simple


I'll change this to a feature request

**Comment by zaibon** [comment]
There are 2 thing to take in account here. 

When you reserve a container, the root filesystem of the container gets allocated 250MB only. If you need more storage, you must reserve a volume and attach it to the container.

Container are meant to be start with a proper flist containing all the file required by your application. In a container world you do not install things at runtime. everything comes with the image/flist.
Any file that is part of the flist doesn't count in the storage quota.

**Comment by zaibon** [comment]
in 0-OS v0.3.3 you can now specify the size of the root filesystem of a container. The chat flow also ask you the size and type when you deploy a container.
