### ISSUE TITLE
GE: Question: payment via Escrow

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#697]
payment flow is
user Wallet -> Escrow Wallet -> Farmer Wallet

this means as a farmer I only see the Escrow ID and never the user ID?
so I can't mach payments to user?

**Comment by zaibon** [comment]
In each transaction made to pay a reservation you will find the reservation ID in the memo text of the transaction. So you can build accounting system that links a transaction on stellar to a reservation on the grid.

Example this reservation 9229: https://explorer.grid.tf/explorer/reservations/9229
is linked to this transactions: https://stellar.expert/explorer/public/tx/126849483970756608#126849483970756609
