### ISSUE TITLE
orderbook v1

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#7]
## OrderBook

# Description
- An order book is a ledger containing all pending orders [buy/sell]
- these orders are paired up as soon as their requirements are fulfilled.

## Needed APIs

- Create order  
- Read orders ( with some filters)   
- Delete orders
- Matching

# Tasks

- implement an orderbook server(on top of gedis2 server)
- Orders are saved in memory and committed to db for history only
 
# Deliverables
- Order book server using gedis2 with SSL support
- Python client for orderbook
- Create a matcher to match selling with buying orders
- Create a trader to actually do the transactions to user wallets

# Design

- API layer accessible through gedis2 server
- SAL layer for handling logic (called by API)
- Matcher

# Code

- TODO

# Stakeholders
@despiegk

# Issues

- TODO: link issues

**Comment by despiegk** [comment]
needs
- https://github.com/threefoldtech/jumpscale_lib/issues/92
- https://github.com/threefoldtech/digital_me/issues/16

**Comment by rkhamis** [comment]
This storycard is obsolete
