### ISSUE TITLE
0-templates Automated testsuite coverage

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#70]
- Integration tests to cover all the templates in 0-temlates repo
    - https://github.com/threefoldtech/0-templates/tree/development/templates
- Add travis Job

**Comment by AhmedHanafy725** [comment]
#### location: [testsuite](https://github.com/threefoldtech/0-templates/tree/development/tests)
#### covered:
[vm](https://github.com/threefoldtech/0-templates/tree/development/templates/vm)
[bridge](https://github.com/threefoldtech/0-templates/tree/development/templates/bridge)
[container](https://github.com/threefoldtech/0-templates/tree/development/templates/container)
[namespace](https://github.com/threefoldtech/0-templates/tree/development/templates/namespace)
[zerodb](https://github.com/threefoldtech/0-templates/tree/development/templates/zerodb)
[vdisk](https://github.com/threefoldtech/0-templates/tree/development/templates/vdisk)
[zerotier_client](https://github.com/threefoldtech/0-templates/tree/development/templates/zerotier_client)

#### to be covered:
parent of threefoldtech/0-templates/issues/278
parent of threefoldtech/0-templates/issues/268
parent of threefoldtech/0-templates/issues/267
parent of threefoldtech/0-templates/issues/284
parent of threefoldtech/0-templates/issues/283
parent of threefoldtech/0-templates/issues/282
parent of threefoldtech/0-templates/issues/280
