### ISSUE TITLE
GE:  S3 solution information 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#701]
## please provide CPU , Mem , and storage requirements for
*  minio-container
*  volume
*  each zdb

## and..
* what is the largest zdb size
* how to prometheus, grafana
* ssh access to minio container ( with my pub-key )

**Comment by zaibon** [comment]
Everything will be documented and explain as part of https://github.com/threefoldtech/home/issues/720

**Comment by joefoxton** [comment]
If this is handled by #720, then this can be closed.
