### ISSUE TITLE
Ge: after reboot of the nodes resources are not reachable anymore

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#703]
## can't reach resources anymore :
* ubuntu: 9463
* S3:  9461,9462

via network 9457

```
[Interface]
Address = 100.64.129.1/32
PrivateKey = GVg6mShmDgKSL3Z7RgGK8RN2hw+WhOLrscmVI/JgzUU=
[Peer]
PublicKey = gKFejlmJWJ8QYQxUkWncXfiFfXYFaI1gzCsno4ze8xw=
AllowedIPs = 10.129.0.0/16, 100.64.129.0/32
PersistentKeepalive = 25
Endpoint = 185.69.166.242:5086
```

**Comment by zaibon** [comment]
The network define in reservation [9457](https://explorer.grid.tf/explorer/reservations/9457) only contains one node: CBDY1Fu4CuxGpdU3zLL9QT5DGaRkxjpuJmzV6V5CBWg4

While the ubuntu from [9463](https://explorer.grid.tf/explorer/reservations/9463) is deployed on node: 9KAbX21NGbZYupBJ6EeeWx3ZTKDx7ADevr8qtmEa5WkC.

I think we are missing some pieces here cause with these info the ubuntu should not be accessible on the network indeed.

**Comment by hteibler** [comment]
minio 
https://explorer.grid.tf/explorer/reservations/9462

should be on: 
https://explorer.grid.tf/explorer/nodes/9KAbX21NGbZYupBJ6EeeWx3ZTKDx7ADevr8qtmEa5WkC

**Comment by hteibler** [comment]
tried a ubuntu now, on the same network
Sorry your reservation 9476 has failed :
CONTAINER: COULDN'T LOAD NETWORK WITH ID (YQ73TV1CDCGDF): OPEN /VAR/RUN/CACHE/NETWORKD/NETWORKS/YQ73TV1CDCGDF: NO SUCH FILE OR DIRECTORY

**Comment by zaibon** [comment]
both 9462 and 9476 doesn't define any network workloads and the error you get from 9476 also shows that the network you are trying to join is not define on this node.

So first thing to do it to double check on which node exactly is your network define. 
From what you shared here. the network `htnet31` defined in 9457 only contains one single node `CBDY1Fu4CuxGpdU3zLL9QT5DGaRkxjpuJmzV6V5CBWg4`.

**Comment by hteibler** [comment]
it was working until
* I tried to deploy a k8s, which failed, because of 
*"Re: [threefoldtech/zos] k8s VM creation failed (#783)"
*then the nodes get rebooted

**Comment by zaibon** [comment]
Ok so this seems to be the same issue as https://github.com/threefoldtech/jumpscaleX_threebot/issues/701. Probably better to try to consolidate all info into one issue then.

**Comment by zaibon** [comment]
I've had an idea that might improve things a bit : https://github.com/threefoldtech/zos/issues/800

**Comment by joefoxton** [comment]
@hteibler can this be closed?
