### ISSUE TITLE
crystal simulator usable for data generation

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#707]
## what

- [x] check again with python code to see if no changes in logic
- [x] generate the data structures on disk like done now in python (the .json files)
- [x] generate graph images 
    - [x] see which graph library to use e.g. https://github.com/toddsundsted/ishi, is there nicer?
- [x] move all templates to crystal simulator (see templates dir)
    - [x] get other templates which are still in code (not using jinja2 yet), need to be ported
    - [x] use cjinja in crystal as templating language
    - [x] implement to fill in the templates (see how we do in python)
- [x] make usable as command line
    - [x] input is a toml file with the arguments
    - [x] arguments are the 4 ones we use on simulator.threefold.io
- [ ] change input for hardware (which is now python or crystal code) to become a toml file
    - [ ] toml file allows definition of components (bom)
    - [ ] toml file allows definition of devices (templates)
    - [ ] purpose is to allow a person to define new hardware config & run simulator which outputs the markdown files
- [x] output is like simulator on wiki
    - directory as we have in the simulator today (as used on simulator.threefold.io)
    - with data files and markdown files 

## requirements

- [ ] needs to be done < 1 week, if not we go to other plan
- [ ] code needs to be clean, let Kristof review
- [ ] users who can still change hardware layout & arguments don't need to compile

## what not to do

- no Jupyter integration

## phase 2 (not in this story)

- we will use this as backend for jupyter on js-ng
- so people can dynamically code again their simulation

**Comment by xmonader** [comment]
story moved to foundation https://github.com/threefoldfoundation/home/issues/64
