### ISSUE TITLE
Set up redundant explorer on same dns

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#71]
The Explorer machines crash sometimes. A part from the fact that we need to find out why they crash and have that fixed either way, we will still encounter explorer nodes to go belly-up just because the hardware fails.

We have several things in place already (the gateway templates and DNS) that we can leverage:

Set up a cluster where we have 2-3 Explorer nodes that catch up on the blockchain. These nodes are running stand-alone and as back-end for the 2 gateway nodes, of which one can fail. in both Gateway nodes, the Traefik daemon is configured to proxy sticky sessions to the Eplorer node(s)

eventually we can also add a monitor to the Traefiks, and update CoreDns to use only one Traefik in case one fails.

**Comment by zaibon** [comment]
First thing to do for this task is to have a proper network configure in the farm in lochristi.
Currently we cannot deploy web-gateway in this farm which prevent exposing any workload to the public internet. 

Once @delandtj  has the network layout setup, we need to see if there are some change to be done in the network configuration template we have.

Once we have all of this we can deploy the redundant setup for the blockchain

**Comment by Sacha96** [comment]
close #32
