### ISSUE TITLE
website environment issues

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#710]
- [x] authentication for 3bot connect should last for 1 week is same user logs in
- [x] there is a redis backend for the session manager (file system also works)
- [ ] use SSH deployment keys https://github.com/despiegk/threefold_web
- [x] when updating show errors if ussue
- [x] documentation of the git repo on docs.grid.tf, how to login, update, ...:  [ docs.grid.tf](https://docs.grid.tf/threefold/itenv_threefold_main) and [deployment docs](https://github.com/threebotserver/publishingtools/blob/development/deployment/deployment.md)

**Comment by xmonader** [comment]
because of deployment keys is only 1 per repo, we created threefoldagent user on github and its keys can be found at https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/info/sshkey and added into team agents (readonly) in the private repos.
