### ISSUE TITLE
tfweb small improvements

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#711]
- [x] in blogs include from wiki (any known wiki)
- [x] in blogs link to any wiki, website, blog
- [x] in wiki link to any wiki, website, blog

**Comment by despiegk** [comment]
when remote include:

- rewrite links to point to the other wiki
    - e.g. in matchmakers we include !!!include:sdk1:apage
    - e.g. in apage.md there is a link like ```[something](mypage.md)``` mypage is in the repo: sdk1 so the mypage is only there, this means the link need to be rewritten to ```[something](sdk1:mypage.md)```
    - this requires the links to work well
- rewrite images (links) to point to other wiki, otherwise images not shown
- rewrite includes to also still work, same logic as above

**Comment by xmonader** [comment]
all points checked

from development branch https://github.com/threebotserver/publishingtools/

```
feel free to pull on development and test

# Test

## include with images
!!!include:sdk:farm_setup_management.md


## links

#### from wiki
[grid](wiki2:grid.md)


#### from webbsite
[threefold why](threefold:why.html)

#### from blog
[blog post](tfblog2:threefold-creates-a-more-responsible-neutral-and-decentralized-internet-with-hewlett-packard-enterprise)

run as the following
```

```
bash runtfwebsitesandwikis.sh

```
