### ISSUE TITLE
wizards upgrade & documentation

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#715]
- [x] all using state
    - [x] need to make sure that anytime we open the deployment of a solution again, itgoes back to same state

# document chatflows in sdk

- e.g. is a nice one: https://github.com/threefoldtech/jumpscaleX_threebot/blob/374248fe7d7d91ea3732ba80f995f18f965e45c6/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py in sdk

**Comment by rkhamis** [comment]
docs here: https://github.com/threefoldfoundation/info_tfgridsdk/tree/development/src/5_admin/chatflows/solutions

**Comment by Pishoy** [comment]
verified in https://sdk2.threefold.io/#/solution_chatflows
