### ISSUE TITLE
3sdk checks: are we good enough

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#716]
# non expert mode

- [x] user can specify development or master branch, if branch is changed user needs to re-deploy container
- [x] can restart container from 3sdk 
- [x] can restart 3bot server from 3sdk 
- [x] can restart simulator from 3sdk
- [x] need minimal progress report (e.g. when checking out repo (pull)
- [x] be more informative to user, without showing all development things
- [ ] do upgrade on existing container in the existing branch (no change) : pull code & restart 3bot server

# expert mode

- [x] default don't do a pull (just use code dir's as how they are checked out)
- [x] --pull is option then soft pull, if changes ask what to do (don't change branch)
- [x] branch cannot be specified, its up to the developer to choose the right branch on his host
- [x] default branch used = development (only used when code does not exist yet on host)
- [x] will expect ssh-agent to be there, start it ...

# remove not used components

- [x] don't use sonic, don't start, put raise in BCDB when *** used in schema
- [x] don't start the workers

**Comment by grimpy** [comment]
@despiegk I have some questions/suggestions about the last 2 items to clear

-  --pull is option then soft pull, if changes ask what to do (don't change branch)
Can we make it simple and during pull when we detect changes give the user the option to either abort or to continue at his own risks?

- user can specify development or master branch, if branch is changed user needs to re-deploy container

Is it okday to solve it by the workflow underneed?
```
3sdk> threebot delete
3sdk> core branch development
3sdk> threebot start
```
is that ok or did you have something else in mind?

**Comment by grimpy** [comment]
Discussed the above with Kristof, the workflow for --pull stays as it does with the diffrence we don't change branches ever from the code itself.

For the 2nd point the flow described above is ok

**Comment by Pishoy** [comment]
pending on those issues https://github.com/threefoldtech/home/issues/732

**Comment by Pishoy** [comment]
- almost of all point are verified

- only point of `need to add known issues`  is not verified

**Comment by rkhamis** [comment]
@Pishoy updated the storycard. please close when verified

**Comment by Pishoy** [comment]
Verified
