### ISSUE TITLE
ipv6to4 openwrt

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#717]
use any openwrt router, to create tunnel to any of our endpoints
so there is local ipv6 so we can run local nodes

- [ ] manual, explain how to use a openwrt based router & wireguard client to get to our access points
- [ ] how many gateways do we have, document
- [ ] find solution to allow up to 64 nodes can be tunnelled over the wireguard into our IPV6 networks

**Comment by despiegk** [comment]
need to know specs, impact, tell despiegk what we can do

**Comment by despiegk** [comment]
other zero-os itself makes wireguard connect to closes by IPv4to6 gw

**Comment by despiegk** [comment]
are we sure that zerotier IPV6 adhoc mode is not usable
if we would run our own moons?

to me frankly I still have not seen enough proof that this is not the right path

if we need to do this ourselves its a big undertaking, we will need many, many webgateways, ...
and soon

we cannot keep on saying to people that they cannot farm if they don't have ipv6 yet
or we come up with tunneling infra soon or we need something else

**Comment by zaibon** [comment]
What is the end goal of this issue ?
If this is about enabling farmer that doesn't have IPv6 address for they nodes. Then the story about this already exists at https://github.com/threefoldtech/home/issues/638. Please work with @delandtj on the solution.

The solution proposed here is not possible using the 4to6 primitives provided by the WebGateway. The webgateway only handout a wireguard configuration for one single IPv6. It also doesn't handout public IPv6 address. 
For this solution to work, the web gateway should handout a fully routable /64 prefix that can be assigned to the openwrt so it can act as a gateway for the nodes behind. This is a different use case than what the webgateway has been created for.
