### ISSUE TITLE
better packaging for our crystal binaries & 3sdk

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#719]
suggest following

- [x] nsis on windows
- [ ] 1 bash script for Linux & osx (checks which os, if deps are there, downloads file, put on location)
- [ ] sign the binary on OSX, ask Peter to buy the developer account on Apple

**Comment by waleedhammam** [comment]
checking 3sdk packaging using nsis on windows

**Comment by waleedhammam** [comment]
Followed https://nsis.sourceforge.io/NSIS_Quick_Setup_Script_Generator

created the installer file using this configuration from 10.5.3 binary

![image](https://user-images.githubusercontent.com/10658229/82141676-c2614800-9837-11ea-8b78-542895504f4e.png)

![image](https://user-images.githubusercontent.com/10658229/82141677-cb521980-9837-11ea-91d0-bff97b324192.png)

![image](https://user-images.githubusercontent.com/10658229/82141680-d0af6400-9837-11ea-8275-f2a9e2b98cf5.png)

exe link: https://www.dropbox.com/s/azpu1erqyowm0hg/3sdk.exe?dl=0

logs and configuration link: https://www.dropbox.com/s/2coh3bqlw3272aw/3sdk_logs_configs.zip?dl=0

**Comment by waleedhammam** [comment]
To sign the bin on macOS as we use pyinstaller in this wiki https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing 

also we should build like this one https://pyinstaller.readthedocs.io/en/stable/usage.html#building-mac-os-x-app-bundles

adding -w to get a .app file

**Comment by waleedhammam** [comment]
Changelog: https://github.com/threefoldtech/jumpscaleX_core/commit/5bfefeaedc4b09f25ebb6c6affad76b4780e9cfa

* add nsis building for windows

* automate package.bat to use nsis

* update building windows script

![image](https://user-images.githubusercontent.com/10658229/82155492-995fa800-9875-11ea-98c8-a6690b80b261.png)

just install wine and run install/package_windows.sh to generate the bin

![image](https://user-images.githubusercontent.com/10658229/82155510-aed4d200-9875-11ea-9d3d-ce3d01baa0fb.png)

**Comment by waleedhammam** [comment]
can't continue without mac, generating certificate takes forever on vm

**Comment by waleedhammam** [comment]
Tried with @m-motawea  to sign the app on MacOS catalina by following pyinstaller tutorial here https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing but didn't work,
also generated a developer certificate using xcode https://help.apple.com/xcode/mac/current/#/dev154b28f09 and followed https://github.com/tlaplus/tlaplus/blob/master/general/docs/Notarization_in_macOS.md to sign the app but didn't work. with the following

![Screenshot from 2020-05-26 12-55-53](https://user-images.githubusercontent.com/10658229/82894387-c6d1e300-9f52-11ea-8d41-f865c678f39b.png)

![Screenshot from 2020-05-26 13-07-10](https://user-images.githubusercontent.com/10658229/82894376-c5081f80-9f52-11ea-8397-598fedfc1bd1.png)

**Comment by zaibon** [comment]
@despiegk @waleedhammam is this still in progress or even relevant for grid2.2 ?

**Comment by waleedhammam** [comment]
> @despiegk @waleedhammam is this still in progress or even relevant for grid2.2 ?

I don't think so it was for jsx
