### ISSUE TITLE
zos CLI integration in Jumpscale

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#72]
The first version [zos CLI prototype](https://github.com/threefoldtech/zos) showed some good things. People have been responding pretty positively to it.

It also showed the limit of nim (can read https://xmonader.github.io/nim/2018/12/06/nim-good-ok-hard.html for more about this). 
One of the main reason we want to create this tool is to be able to distribute a static tool to deal with 0-os.
Things is, we are now close to have a [sandbox](https://github.com/threefoldtech/home/issues/64) that we can distribute like a static binary. Having this would allow us to re-use all the code we already have in jumpscale 0-OS SAL for the zos CLI.

Goal of this story is to define if it is worth to move the new features of zos back to jumpscale and then re-create the CLI interface in python. This would allow to have all the features from 0-OS SAL.

Tagging people to start the disscusion: @despiegk @xmonader @rkhamis

**Comment by xmonader** [comment]
@zaibon pyzos was a backup option if we kept having unpredictable problems with zos (hanging sockets mainly on nil returns from 0-core) mostly because of a bug in [redisclient](https://github.com/xmonader/nim-redisclient/commits/master) and all of them are fixed already.

**Comment by zaibon** [comment]
@xmonader ha OK, I though they were issue in the python redis client. Ok make sense now

**Comment by rkhamis** [comment]
The two main advantages I can think of having this zos CLI in Jumpscale is nicer command  subgroups and that will be directly available with every Jumpscale
