### ISSUE TITLE
GE: K8S deployment failed

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#722]
Sorry your reservation 9513 has failed :
KUBERNETES: ```FAILED TO INSTALL K3S: COULD NOT RUN VM: 2020-05-18T12:49:41.427434552 [ANONYMOUS-INSTANCE:ERROR:SRC/FIRECRACKER/SRC/MAIN.RS:66] FIRECRACKER PANICKED AT 'ERROR CREATING THE KVM OBJECT: ERROR(19)', SRC/LIBCORE/RESULT.RS:1188:5
2020-05-18T12:49:41.427602601 [anonymous-instance:ERROR:src/firecracker/src/main.rs:76] stack backtrace: 0: 1: 2: 3: 4: 5: 6: 7: 8:

: failed to spawn vm machine process '9513-4'```

Full reservation info

**Comment by zaibon** [comment]
This is the exact same issue as https://github.com/threefoldtech/zos/issues/783.
This is not a 0-OS issue, there is nothing we can do about it. The farmer needs to fix the configuration of the BIOS from these nodes.
