### ISSUE TITLE
GE: Handle two NICs for redundancy

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#727]
In order to make our farms robust, our customer workloads safe, and our token earning capacity constant, we have install dual NICs on our servers, and dual routers in our farms.

However, ZeroOS does not currently support dual NICs.

We require dual NIC support to deliver our customers the level of service they require.

**Comment by zaibon** [comment]
Yep this feature is in the roadmap already, you can follow up at https://github.com/threefoldtech/zos/issues/408
