### ISSUE TITLE
GE: Limit types of workload based on node's characteristic

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#728]
Storage workloads should only be deployed on nodes that are configured for storage. Same with Compute.

In the Jumpscale dashboard and farm cockpit, it should be obvious which nodes are suitable for which kind of workload.

We should even limit reservations to those nodes that most suit the reservation, or at least provide warnings if someone is trying to reserve on an unsuitable node.

**Comment by OldhamMade** [comment]
As a stepping stone, would it be possible to add a `classification` attribute to nodes? This would allow us to manually manage our workloads (for now) by filtering on classification and using only those nodes for certain workloads. Right now we're doing this by hard-coding IDs, but as we grow our farms this solution will become a burden.

**Comment by OldhamMade** [comment]
Actually, thinking this through, a more generic `labels: List[str]` attribute may be more useful. We could then set labels for various administration purposes. For example, we could add `"performance"` and `"storage"` labels to specific nodes we want to target for a specific product/workload type.
