### ISSUE TITLE
GE: TFT Pricing Calculator

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#729]
In order to book capacity on behalf of our customers, we'll need to load up our greenedgeagent.3bot with enough TFT (or FreeTFT for trials) to reserve their capacity. As such, we'd love a tool that lets us calculate this for specific workloads.

Inputs could be:
- Storage needed (GB)
-- # storage slices
-- # parity slices
- RAM needed
- Cores needed
- Reservation duration

Outputs could be:
- TFT needed
- € equivalent
- $ equivalent

**Comment by zaibon** [comment]
Here is a link to the definition of the pricing: https://wiki.threefold.io/#/capacity_pricing_start?id=threefold-grid-capacity-pricing-promotion
This should give you all the information required to build your own price calculation tool.

We also some function in our code base that can be used as implementation example: https://github.com/threefoldtech/tfexplorer/blob/master/pkg/escrow/resource.go

**Comment by zaibon** [comment]
You can also just send a reservation to the explorer, it will send you back the amount to pay. Then just let it expire or cancel it.
