### ISSUE TITLE
GE: 3sdk doesn't show all my deployed solutions 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#735]
view from 3dk:
![image](https://user-images.githubusercontent.com/24313736/82661292-07b4b980-9c2c-11ea-87e7-180d49aa440b.png)

from explorer:
ID  next_action 3id  end-time name 
 
9146 3 130 2103-08-07 containers
 9210 3 130 2021-05-06 network
 9211 6 130 2021-05-06 network
 9265 3 130 2021-05-06 network
 9273 6 130 2021-05-06 network
 9457 3 130 2020-05-24 network
 9458 3 130 2020-05-24 network
 9459 4 130 2020-05-24 volumes zdbs
 9460 3 130 2020-05-24 network
 9461 3 130 2020-05-24 volumes zdbs
 9462 3 130 2020-05-24 volumes containers zdbs
 9463 3 130 2020-05-24 containers
 9467 3 130 2020-05-24 network
 9468 6 130 2020-05-24 kubernetes
 9475 6 130 2020-05-24 network
 9476 6 130 2020-05-24 containers
 9477 3 130 2020-06-28 network
 9478 3 130 2020-06-28 network
 9479 3 130 2020-06-28 containers
 9480 6 130 2020-06-28 network
 9506 3 130 2020-12-31 network
 9507 6 130 2020-12-31 network
 9508 3 130 2020-12-31 network
 9509 3 130 2020-05-31 containers
 9510 3 130 2020-12-31 network
 9511 4 130 2020-05-31 volumes zdbs
 9512 3 130 2020-12-31 network
 9513 6 130 2020-12-31 kubernetes
 9515 3 130 2020-12-31 network
 9516 3 130 2020-06-28 containers
 9518 3 130 2020-12-31 network
 9519 6 130 2020-06-28 volumes zdbs
 9524 4 130 2020-12-31 network
 9562 3 130 2020-12-31 network
 9563 3 130 2020-06-28 volumes zdbs
 9564 3 130 2020-06-28 volumes containers zdbs
 9569 3 130 2020-06-30 containers
 9578 3 130 2020-06-30 containers

**Comment by dmahmouali** [comment]
it already done in the new release updates.

**Comment by hteibler** [comment]
how to update?

**Comment by rkhamis** [comment]
@hteibler we should have a release candidate tomorrow, if you want to update then. or we'll have a stable release later this week
