### ISSUE TITLE
GE: A failed deployment killed all others in the same network 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#737]
tried to deploy a minio, which failed before asking about payment
now all other deployments are not reachable anymore
failed: 9579

not reachable anymore: 9578, 9569, 9563, 9564

**Comment by hteibler** [comment]
this is the corresponding wg config
```
[Interface]
Address = 100.64.26.1/32
PrivateKey = s25yosCNldq4CKDvgdYQrMmHHR0Uw5d2SRVLJGMR2No=
[Peer]
PublicKey = jd4866OoM4kyc+ZibvRW7zslQ+IUb5uOISXPQUlzVQM=
AllowedIPs = 172.26.0.0/16, 100.64.26.0/32
PersistentKeepalive = 25
Endpoint = 185.69.166.242:7805
```

**Comment by hteibler** [comment]
# same situation again
# total new SDK installation
deploy network : 9581, OK
deploy ubuntu: 9583, OK
deploy k8s: 9584 failed

# ubuntu not reachable anymore

```
[Interface]
Address = 100.64.21.1/32
PrivateKey = GBTYuO8YaFYK8Hymes/Az7/hipCRrxY52pltcKqpDes=
[Peer]
PublicKey = siYkBNlqfpa4oDWBAkP+Cwlshd+RVh2KkRevZrU/tVc=
AllowedIPs = 172.21.0.0/16, 100.64.21.0/32
PersistentKeepalive = 25
Endpoint = 185.69.166.242:2528
```

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/issues/701

Seems to be the same as this

**Comment by zaibon** [comment]
Indeed, I'll mark as duplicate so we consolidate threefoldtech/jumpscaleX_threebot#701

**Comment by hteibler** [comment]
yes same issue, still same problem
