### ISSUE TITLE
GE: How do Hardware upgrades effect Token earning/calculation

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/home#740]
We considering to upgrade the Ram in our Apollo Servers from 32GB to 128GB (or more)
That would change the number of cloud Units

This change is minor but we could also change our 16 Core CPUs with 64-Core Chips + 512GB Ram per CPU. Or swap the 60 12TB Hard-drives in our Apollos with 20TB Drives in 2 or 3 Years
Which would change the Token earning of a node significantly. 

How would that effect the token calculation?

Until the Hardware upgrade the Node had X amount of Cloud Units
After the Hardware Upgrade it has Y amount of cloud units 

Possible ways to do it:

- **Issuing tokens for Y amount for the Periode left of the 60 months** 
  The Grid wants capable Hardware for thew Users, this approach would discourage Upgrades 

- **Issuing for the X Amount for the original 60 plus the difference between X and Y for 60 after the 
     Hardware upgrade**
   This would encourage Upgrades cause there is a return in token calculate-able earning for it 
   upgrade. That would make it interesting an favorable to keep Servers running longer, getting more 
   use out of them and prevent still usable Hardware to become E-Waste
   
- **Re-registering the node as new**
  The node would then be valued at the current (probably higher Token price)
  This would also discourage Upgrades, cause the Farmer would lose there advantage of 
  participating Early at a low Token price.
  The earliest point where an upgrade makes sense then is close to the end or after the 60 months
  At that point the upgrade possibility`s are very cheap but probably not worth it anymore, due to 
 the rapid pace of development and the Age of the Server

I see the need or commercial validity of an Hardware upgrade after 2-3 Years.
At that point the prices for most powerful CPU, Ram and newer and bigger HDD and SSD`s have come down significantly. 
An upgrade can then make a lot of commercial sense.
With the right approach we can encourage the Farmers to run there Hardware longer and be greener.

**Comment by andhartl** [comment]
@guido once you upgrade the hardware this will be tracked immediately and from that time on the cu and su make up a higher cpr which leads to more tft. in the new tokenomics model the tft price is no longer fixed from the start.
