### ISSUE TITLE
GE: minio secret is exposed in cleartext

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#744]
https://explorer.grid.tf/explorer/reservations/9644

![image](https://user-images.githubusercontent.com/24313736/82879795-c3802c80-9f3d-11ea-9ec4-fb8106d82715.png)

**Comment by zaibon** [comment]
For sensitive information it is better to use the `secret_environment` field. It has the same role as `environment`, but the content is encrypted with the public key of the node.

There is a method in the zosv2 SAL to do this: https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/zosv2/crypto.py#L9

**Comment by hteibler** [comment]
how must I update my code?

**Comment by zaibon** [comment]
You can do something like:
```python
from JumpscaleLibs.sal.zosv2.crypto import encrypt_for_node 

# create your reservation
...

container = zos.container.create(
    reservation=reservation,
    node_id=node.node_id,
    secret_environment={
        "secret": encrypt_for_node(node.public_key_hex, "value"),
    })
```
