### ISSUE TITLE
GE: error deploying k8s

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#746]
whats wrong here?

https://explorer.grid.tf/explorer/reservations/9658

"could not set up tap device: could not add tap device: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy"

**Comment by zaibon** [comment]
Most probably this: https://github.com/threefoldtech/zos/issues/585

**Comment by joefoxton** [comment]
@hteibler Let's close this as a duplicate of threefoldtech/zos#585
