### ISSUE TITLE
Ge: Something wrong happened, please contact support

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#750]
creating a solution expose on
https://explorer.grid.tf/explorer/reservations/9688
Something wrong happened, please contact support

nothing more

**Comment by hteibler** [comment]
also failed
https://explorer.grid.tf/explorer/reservations/9691

**Comment by grimpy** [comment]
Could you add an export of the alerts?

**Comment by hteibler** [comment]
also
![image](https://user-images.githubusercontent.com/24313736/83347113-d8383800-a322-11ea-83c3-5f1f9e822289.png)
![image](https://user-images.githubusercontent.com/24313736/83347119-e5edbd80-a322-11ea-9643-5cb22cc5786b.png)

[error_9292_json.txt](https://github.com/threefoldtech/home/files/4707262/error_9292_json.txt)

**Comment by grimpy** [comment]
Extracted from the alerts:

AttributeError(\"'NoneType' object has no attribute 'add_node'\")
```
--TRACEBACK------------------
{DIR_BASE}/lib/jumpscale/Jumpscale/servers/gedis/GedisChatBot.py in wrapper
    264    getattr(self, step_name)()
{DIR_BASE}/lib/jumpscale/Jumpscale/core/BASECLASSES/Decorators.py in wrapper
    83    return func(*args, **kwargs)
{DIR_BASE}/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py in confirmation
    187    network.add_node(node_selected)
```

**Comment by m-motawea** [comment]
network named `Net-AP2` is deleted (https://explorer.grid.tf/explorer/reservations/9685).
chatflow is updated to show a better message

**Comment by hteibler** [comment]
that's strange
i still can deploy on this network
https://explorer.grid.tf/explorer/reservations/9701
online and working!!!

**Comment by hteibler** [comment]
and both networks should life long:
nr, next,user, created, expire, name
 9685 4 130 2020-05-29 2021-01-31 network|Net-AP2
 9691 4 130 2020-05-29 2071-06-24 network|Net-AP1
why are they deleted??????

**Comment by hteibler** [comment]
and in GUI I only see one of them???
![image](https://user-images.githubusercontent.com/24313736/83355293-e6a44500-a35e-11ea-965b-ccff44015ec0.png)
