### ISSUE TITLE
community.threefold.me

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#752]
- [x] copy of our CIA website
- [x] ambassadors (landing page) a markdown page (why to be ambassadors .. etc)
- [x] values (values from freeflowpages)
- the obj
    - [ ] circles (projects)
        - link to circles tool
    - [ ] users (identified by 3bot connect), if not identified then is external
    - [ ] tags: to be defined
- [ ] link to circle on circles tool
- [ ] link to forum
- [ ] link to wiki (our publish system)
- [ ] or circle is public or only accessible by identified list of people (3bot connect ids)
- [ ] if private circle then only the relevant users can see the circle (based on 3bot id)
- [ ] easy way to find circles (tags)
- [ ] user can be: coordinator, follower, member, contributor, stakeholder (only 1) per circle
- [ ] the membership type needs to be visible: circle in relation to person and other way around
- [ ] auth based on 3bot connect

ambassadors2.threefold.me

**Comment by rkhamis** [comment]
already done
