### ISSUE TITLE
GE: docker 2 flist not working

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#756]
converted 2 docker containers, both run perfect under docker 
but this is not working
https://hub.grid.tf/teibler02.3bot/hteibler-zabbix-1.0.8.flist
source is
hteibler/zabbix:1.0.8 

what must be done?

**Comment by grimpy** [comment]
@hteibler can you provide the original Dockerfile of this container to be able to advise you

**Comment by joefoxton** [comment]
@hteibler Can you provide the dockerfile? If not, let's close this.
