### ISSUE TITLE
GE: why have these networks "next-action" 4

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#758]
and both networks should life long:
nr, next,user, created, expire, name
9685 4 130 2020-05-29 2021-01-31 network|Net-AP2
9691 4 130 2020-05-29 2071-06-24 network|Net-AP1
why are they deleted??????
9685 is still working
9585 is dead, with all my test environment inside

**Comment by grimpy** [comment]
Related to https://github.com/threefoldtech/zos/issues/807
