### ISSUE TITLE
Zero-Robot DM Integration part 2

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#76]
- [ ] [Support jumpscale schema for template schema](https://github.com/threefoldtech/0-robot/issues/4) (6h)
- [ ] [Migrate all template to new schema]() (hopefully we'll be able to automate this)
- [ ] [Create a digital me package for 0-robot](https://github.com/threefoldtech/0-robot/issues/59) (2h)

**Comment by rkhamis** [comment]
This storycard is obsolete
