### ISSUE TITLE
Overflow for reserved_hru value reported by a node

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#767]
```
    green_edge_salzburg1 = 12775
    nodes_salzburg1 = zos.nodes_finder.nodes_search(farm_id=green_edge_salzburg1) # (IPv6 nodes)
```
![image](https://user-images.githubusercontent.com/24313736/83676358-d5676c80-a5da-11ea-88b1-3d72b65af764.png)

**Comment by grimpy** [comment]
@zaibon I assume this means we need to make hru and others I64?

**Comment by hteibler** [comment]
and this is a reserved value of HRU , which is actually zero not 17179869174
so the report is wrong

**Comment by zaibon** [comment]
> @zaibon I assume this means we need to make hru and others I64?

You shouldn't have to. This number should never be that big. The reason it's so big is an overflow of a signed integer on which we subtract from 0. Which mean there is a bug in zos code that left this overflow happens. (https://github.com/threefoldtech/zos/issues/766)

I"ll try to get to this error today and push a hot fix on the field today.

@hteibler in the mean this the node report proper value now, so you shouldn't be blocked.

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/zos/commit/b91faf50614e5cf4379b7014ec2a8f098942fd1d
