### ISSUE TITLE
GE: Minio error: "MinIO server is unreachable"

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#768]
minio got depolyed
web ui is reachable
https://explorer.grid.tf/explorer/reservations/9821

but when you create a bucket you get "MinIO server is unreachable"
![image](https://user-images.githubusercontent.com/24313736/83863036-0ce13080-a723-11ea-82ef-3720d42ce1a1.png)

**Comment by DylanVerstraete** [comment]
@hteibler Can you SSH to your machine and do `zinit log` ? Check for any error messages.

**Comment by muhamadazmy** [comment]
We can't be sure without the logs of this node. I am not sure the version that is running has the ssh server running or not. But you can try to ssh `ssh root@172.19.51.2` and see if u can get in. (that's of course if this installation is still running) 

Once inside, you can do 
`zinit log` 
to get last logs from minio. or u can try to upload again to trigger the error.

If this version does not have ssh, there is not much we can do to find the cause.

**Comment by hteibler** [comment]
need to rebuild to get this error again, but
* how can I enable SSH per default in minio ?
* which flist can I use?
* can I add the key like we do it with ubuntu?

**Comment by muhamadazmy** [comment]
If deployment is done via the js API, do the following:
- Use this flist `https://hub.grid.tf/tf-official-apps/minio:latest.flist` 
- add env variable `SSH_KEY=<rsa-public-key>` to the environment variables
- make sure to use an "empty" `entrypoint`. Just don't set it, the flist has an autostart.

If you are using the chat-flows:
- There is a step in the wizard where it will ask you to upload your public SSH key to it. 

After the deployment is complete, you can then ssh to the instance.

**Comment by rkhamis** [comment]
@hteibler the chatflow part that allows you to upload your public sshkey is on development (unreleased) yet.
so you can either switch to development branches or wait for the release next week.

**Comment by hteibler** [comment]
ssh into minio is now working, great

question: what does this mean : df -h  
/dev/sdk                  1.7T      2.9G      1.7T   0% /data

where/why are the 2.9G on a fresh install?
and I created 15*100 GB != 1.7 TB ?

will close now and open if I can repeat the error

**Comment by zaibon** [comment]
df is a tool that read the disks information from the kernel. What you see is the actual full disk capacity.
The reason you don't see you expected number is you are running a container, not a VM. So you see information from the underlying hardware.
