### ISSUE TITLE
GE: nodes reported as OK but unuseable, so whole farm can't be used

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#770]
When you choose farm ID: 118315
3 nodes are not working but used
so a deployment will fail

these are the node iDs
HnfviKvEtLXRh89uNC6MtEyg6PTbje3tNvUVBLAhWUmh
5W8VCwtMnHineriACfF4y6gzDcoN9QwqrgkQ4k3V67X2
4Bvocr4hRVikfh7ijs32Vx9zLytVZYfNAxyXkge84wFp

**Comment by hteibler** [comment]
need a better check if a node is online!!
zos.nodes_finder.filter_is_up(node) returns no error on this nodes!!!

**Comment by zaibon** [comment]
The fix for online nodes introduced in 0.3.3 had to be reverted back because it prevented the farming in certain nodes. Hopefully we can re introduce it as soon as possible

**Comment by hteibler** [comment]
OK

**Comment by gneumann333** [comment]
Why dont you show the status of IPv4 and IPv6 connectivity in the cockpit.
This would aslo help the Farmer to do troubleshooting

**Comment by zaibon** [comment]
> Why dont you show the status of IPv4 and IPv6 connectivity in the cockpit.

this information is already available in the nodes API. This is what is used to give you the network health status in the farm management dashboard btw.

**Comment by joefoxton** [comment]
Thanks @zaibon, I think this can be closed.
