### ISSUE TITLE
GE: S3 Salzburg1

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/home#772]
## S3 in Salzburg1

ID: 9859
after login:
error: Server not initialized, please try again

minio_master_node_id = '6chi1iSczxfF4U2iyCcJwkwWnwzcDgQHzCRExK9r4V1j'
zdb_nodes =['HugtVL51BFNLbZbbxnWu2GEe8hV97YVPac19zy5wwNpT',
            '9KAbX21NGbZYupBJ6EeeWx3ZTKDx7ADevr8qtmEa5WkC',
            '9kcLeTuseybGHGWw2YXvdu4kk2jZzyZCaCHV9t6Axqqx',
            '3h4TKp11bNWjb2UemgrVwayuPnYcs2M1bccXvi3jPR2Y',
            '5Pb5NMBQWLTWhXK2cCM8nS6JZrnP2HaTP452TfMMYT9p']

**Comment by hteibler** [comment]
rebuild it today, seams to be working now, but nothing changed on my side

**Comment by joefoxton** [comment]
We can close this issue then, I guess!
