### ISSUE TITLE
circles_reporting_tool

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#773]
- aggregates the stories, issues, ..etc from github & taiga
- login to a central point with 3bot connect
- github username is defined in circles.threefold.me
- js-ng website package
- vue js UI to list stories, issues, with relevant links..

# User experience
- allow user to see a grid with for himself or other user
    - stories 
    - issues
    - story checklist items
    - github issues (sorted per type, story, ...)
- allow user to filter based on
    - deadline (see what is overdue)
    - time since start (e.g. story open for +2 weeks)
    - type of issue (e.g story, bug, feature,.. etc)
    - source of issue/story/... (from github or taiga)

# remarks
- if data not fetched, fetch all stories, tasks, projects, epics ... into memory (nice model) and refetch every 5 min

**Comment by ahelsayd** [comment]
blocked on https://github.com/threefoldtech/Threefold-Circles/issues/10

**Comment by despiegk** [comment]
see #912
