### ISSUE TITLE
Create an online version of the 3sdk

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#776]
### Problem
Installing the 3sdk on local / laptop systems has proven to be difficult.  The development team has done well in terms of improving the experience but it is and will present challenges as we do not control the host systems and there are a million versions of windows, macOS, and Linux out there and not enough system administrators.

### Solution
Create an "on grid" version of the 3sdk environment.  Getting an on-grid version of the SDK should be simple and straightforward.

- Getting an on-grid 3sdk
  - get 3botconnect / crystal twin installed on your phone which holds your private / seed key and has your name.3bot
  - go to sdk.bootstrap.grid.tf and fill in a couple of details to prime your online 3sdk environment
    - enter your name.3bot
    - enter a derived (public) in a secure way.  This public key will allow the 3sdk on-grid to identify the rightfull person.
    - send / get a small amount of TFT's for the on-grid SDK to reserve capacity it needs to exists.
    - make a choice:  is the on-grid sdk publically accessible (public IP address) or not.. If not - additional information is provided for the secure WG tunnel to connect to the on-grid SDK. 
    - ......
    - When done a page is presented with all the required information to reach your on-grid 3sdk.

- Using the on-grid SDK
  - Based on your choice (Public or private accessible) go to your sdk with a web browser.
  - Use the 3botconnect 2FA to connect to the online 3sdk
  - Once authenticated the online sdk has all the capabilities to do things online as it now has access to the private key (derived or original) and can do anything.
   - At the end of the session the derived key (or access to the private key by using 2FA with 3bot connect is taken away from the ongrid sdk and it can safely wait for the next session and execute simple tasks. for which the private (derived) key is not needed.

**Comment by despiegk** [comment]
continues in https://circles.threefold.me/project/despiegk-tftech-software/us/103?no-milestone=1

**Comment by despiegk** [comment]
https://github.com/threefoldtech/home/blob/master/specs/personal%203bot%20on%20grid.md
