### ISSUE TITLE
crystal tools first usable version

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#778]
# deliverables

- [x] package as 'ct'
- [x] have as release on crystaltools repo
- [x] one line bash installer (linux/osx only for now I guess)
- [x] there are some things to be fixed in crystaltools/crystaldo
- [x] merge repo crystaltools/crystaldo but in such a way that crystal tools can be used as library as well in other crystal projects

# question

- [ ] does ct work on windows now (for the functions we need)?

**Comment by ashraffouda** [comment]
https://github.com/crystaluniverse/crystaltools/commit/8bea7e98e55cefdd6055dce8af0513dfbbd56487
