### ISSUE TITLE
Strange error: "Your identity does not exists on main please setup a new identity with 3sdk"

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#779]
In Jumpscale SDK, when I click on "Settings" in the menu, I see this error message: 

"Your identity does not exists on main please setup a new identity with 3sdk"

I'm not sure what this means. It seems everything is working ok, but I'm not sure.

![Screenshot 2020-06-15 at 12 00 00](https://user-images.githubusercontent.com/1249806/84644865-09f2f680-af00-11ea-814a-01529212fb31.png)

**Comment by grimpy** [comment]
@joefoxton is this happening without changing the network selection? Did you create your 3sdk on another network? Are you sure the same name/email combination exists on mainnet aswell?

**Comment by joefoxton** [comment]
Yes, this is happening without changing the network selection. My 3sdk was created on mainnet. Yes, this user exists on mainnet… its what I’ve been using for all our farm & wallet management.

**Comment by grimpy** [comment]
Based on what I can see this means you identity configured in the 3sdk is not in sync with what is configured in the explorer.

Could you place verify the following info for me:
`https://explorer.grid.tf/explorer/users?name=<your name>.3bot`
Check name and email and compare to
```3sdk
3sdk> threebot komos

#compare with these fields
j.me.tname
j.me.email
```

**Comment by joefoxton** [comment]
[{"id":152,"name":"joefoxton.3bot","email":"","pubkey":"8dc222cf54c465cd1b1a9772552dcc7fa118e61a900d2bf667b07f763939c176","host":"","description":"","signature":""}]


Email should actually be joefoxton@me.com <mailto:joefoxton@me.com> on both. Not sure why its blank on explorer, and incorrect on kosmos.

Its configured correctly on 3bot Connect.

**Comment by grimpy** [comment]
@joefoxton ok thx for the information:
Yes indeed in explorer it is as you said see: https://explorer.grid.tf/explorer/users?email=joefoxton@me.com
I forgot that in explorer the email is not returned by default for privacy concerns but if you know the email you can find the user (see url above) so this seems to be ok.

So it seems to be wrong in kosmos.

Can you try to fix at as follows and check your browser again:

```
3sdk
3sdk> threebot shell
3bot stop
kosmos -p
j.me.email = "joefoxton@me.com"
j.me.save()
exit()
3bot start
```
And check your browser again

**Comment by joefoxton** [comment]
Yep, correct now.

Now I get the error “Could not switch explorers” in the SDK browser

**Comment by joefoxton** [comment]
Restarted 3bot, now everything works fine

**Comment by grimpy** [comment]
@joefoxton one more followup question, could you give me an idea how old you 3sdk installation is (the first installation not the latest update)? Cause the newest install should prevent this from happening already. So I'm wonder if you installed this before we had these preventive measures in place.

**Comment by joefoxton** [comment]
My first install is months ago so you are probably right!

**Comment by grimpy** [comment]
As such I will close this issue as resolved.

feel free to open it again in case you notice this behavior in the future
