### ISSUE TITLE
GE: Errors when exiting kosmos shell

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#785]
After a short session in kosmos, I typed the command "exit" and got this output.

![Screenshot 2020-06-16 at 14 30 18](https://user-images.githubusercontent.com/1249806/84774395-0f267300-afde-11ea-9cfe-e793feae95a8.png)

**Comment by grimpy** [comment]
This is expected.. kosmos is a python shell. you need to type `exit()` without a space prepended
