### ISSUE TITLE
GE: Circles is spamming me

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#787]
Circles has sent me 30+ emails in the last hour, even though I am not subscribed to any email notifications. There is no way for me to unsubscribe.

![Screenshot 2020-06-16 at 6 45 59 PM](https://user-images.githubusercontent.com/1249806/84805256-4445bc00-b004-11ea-9b6b-60b4fbe0734b.png)
<img width="1440" alt="Screenshot 2020-06-16 at 7 03 06 PM" src="https://user-images.githubusercontent.com/1249806/84805264-4740ac80-b004-11ea-8753-86cc57d40396.png">

<img width="1440" alt="Screenshot 2020-06-16 at 7 03 06 PM" src="https://user-images.githubusercontent.com/1249806/84805294-50ca1480-b004-11ea-8f83-acb55bf925b6.png">

**Comment by Hamdy** [comment]
@joefoxton We apologize for this, there was a mistake we guess, you were added to some new circle that is why you kept seeing all these update emails coming to you
the problem should be fixed now ? if not please let me know!

**Comment by joefoxton** [comment]
Ok thanks Hamdy

**Comment by joefoxton** [comment]
This is now fixed!
