### ISSUE TITLE
Rework deployment tfchain 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#79]
- build flist for 
  - [x] tfchaind
  - [x] explorer
  - [x] explorer autostart
  - [x] bridge
  - [x] faucet + caddy
- Review/improve 0-robot templates
  - [x] [block_creator](https://github.com/threefoldfoundation/tfchain-templates/tree/master/templates/block_creator) (3h)
    - [ ] [the rivine/tfchain modules and api are not immediately available when ethvalidation is enabled](https://github.com/threefoldfoundation/tfchain/issues/297)
  - [x] Bridged (3h)
  - [x] [block_creator_status_reporter](https://github.com/threefoldfoundation/tfchain-templates/tree/master/templates/block_creator_status_reporter)
  - [x] [explorer](https://github.com/threefoldfoundation/tfchain-templates/tree/master/templates/explorer)
  - [x] [faucet](https://github.com/threefoldfoundation/tfchain-templates/tree/master/templates/faucet)

- tests/docs for
  - [x] blockcreator
  - [x] faucet
  - [x] explorer
  - [x] bridged
  - [x] block_creator_status_reporter

**Comment by xmonader** [comment]
- added flist for tfchain binaries https://hub.grid.tf/tf-autobuilder/threefoldfoundation-tfchain-bridge_tft_erc20_autostart-6bf508408f.flist with wip autostart.

- supported env interpolation in 0-core on this branch https://github.com/threefoldtech/0-core/tree/development_envinstartup and still testing it as I didn't get it to run against https://hub.grid.tf/thabet/redisautostart.flist.md yet.

**Comment by GlenDC** [comment]
Flists are merged (https://github.com/threefoldfoundation/tfchain/pull/276). Can this story be closed @zaibon / @robvanmieghem. If not, please define the remaining tasks so we can keep track of this.

**Comment by zaibon** [comment]
Edited the first comment

**Comment by xmonader** [comment]
I've initial work on [bridged template](https://github.com/threefoldfoundation/tfchain-templates/blob/master_autostar_templates/templates/bridged/bridged.py)  
and some clean up for block_creator to work with autostarts.

On the [SAL side](https://github.com/threefoldtech/jumpscale_lib/blob/45652f848f788691277618633ed10ef1ea115213/JumpscaleLib/sal_zos/tfchain/TfChain.py) now I can get rid of all of start/stop/is running functionality because it's ensured by 0-core. correct?

**Comment by zaibon** [comment]
> On the SAL side now I can get rid of all of start/stop/is running functionality because it's ensured by 0-core. correct?

Well we need to define what approach we're going to take.
With the new auto start flist, I think we can nearly get rid of the SAL altogether.
The template would just need to start/stop a container, so no need for special  code around that.
The question is more how are we going to manage these daemons ? Currently the SAL contains code
to unlock a wallet, add a peer manually, retrieve information about the peers list and stuff like that.
I believe all these things are expose in the API. So maybe we should just allow us to talk to the API over a secure network. So the template is really just a start/stop of a container, and the rest is done from else where.

**Comment by robvanmieghem** [comment]
>2- Role of tfchainc in templates?
A: replace with python requests to interact with the daemon, or whatever library available within jumpscale

Indeed

>3- What about the unencrypted wallet usage in templates?

This would allow autostart of a tfchaind when stsarting the container without the need to unlock it first

**Comment by zaibon** [comment]
Using plain `requests` ? Don't we have a fully capable client in Jumpscale now ? Why would we bother to re-implement another time the same stuff again. That's a bit the opposite of what Jumpscale tries to do.

**Comment by LeeSmet** [comment]
> 4- Why does the faucet template require starting its own tfchaind why not use an existing tfchaind container deployed separately?

The daemon API is only exposed on localhost by default. Although it can be exposed on another network interface, that requires password protecting it, and the faucet currently does not have support for using an authenticated API

**Comment by xmonader** [comment]
All of the templates been reviewed/improved, and manually tested, currently working on the tests and documentation and fixing whatever pops up during so

**Comment by xmonader** [comment]
Closed via https://github.com/threefoldfoundation/tfchain-templates/pull/2
