### ISSUE TITLE
GE: Pay as you go

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#790]
IaaS customer expect the ability to pay for capacity they utilise, rather than predicting what they might need and pre-paying. This is the industry standard, so we must comply. 

- Charge the customer at the end of each month for storage & compute used by active reservations, and reservations ended that month.
- Consider locking or escrow-ing tokens based on reservation (rather than charge them immediately).
- Note: Currently, if you create a reservation for a month, and it fails or becomes inaccessible after a shorter time, you can never get the TFT back. So far this has only happened with FreeTFT.
- This ask Partially covered by “Decouple payment & reservation”: https://github.com/threefoldtech/home/issues/749

**Comment by despiegk** [comment]
see #791

we expect this to be a layer on top of us

**Comment by joefoxton** [comment]
Great... if #791 can be implemented, then we don't need to encode pay-as-you-go into Jumpscale.
