### ISSUE TITLE
GE: Multi-point web gateway

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#792]
Ability to add & remove multiple redundant gateways to an overlay network, per ‘ultra redundancy’ section in Hercules Network documentation https://docs.google.com/document/d/1e2wIMAK2VHiNCUoS-TASIIp-eNcgwl5_LeXditwO8EI/edit?usp=sharing

**Comment by joefoxton** [comment]
Partially covered here https://github.com/threefoldtech/home/issues/681
and here https://github.com/threefoldtech/home/issues/720

**Comment by zaibon** [comment]
>Ability to add & remove multiple redundant gateways to an overlay network

You can do this already today. If you want, you can configure every single gateway that exists to provide a proxy for you solution effectively creating entry point to you overlay network from multiple location.
Or do I miss you point ?

**Comment by joefoxton** [comment]
That's perfect. @hteibler does this work for you?

**Comment by joefoxton** [comment]
I'm assuming yes! Thank you @zaibon , closing this.
