### ISSUE TITLE
GE: min.io server robustness

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#793]
Run redundant min.io servers, or provide a way for a min.io server to recover after crash.

Currently there is a single point of failure with a single min.io server. If it fails (which it has), then all data becomes inaccessible, and is for all intents and purposes, lost. This means that we would have to do a full backup of all customer storage, invalidating our "green" value propositions.

**Comment by zaibon** [comment]
Our minio solution actually allow you to run in master slave mode. One read/write master and any number of readonly slave. So there is no reason to have a single point of failure.

There is a new version of the minio solution being reviewed for release as we speak which also introduce a new healing API, better monitoring and improved documentation. I'll let you know when this is published to the public so you can see if you still need any additional features.

**Comment by joefoxton** [comment]
@zaibon That sounds great! I think we can close this, if Herbert agrees...

@hteibler We should run our min.io server with a slave. Does this make sense, and solve the probelm?

**Comment by hteibler** [comment]
a master and slave concept is of course the right way to do it,
but this also requires some sort of LoadBalancer in front

**Comment by zaibon** [comment]
>  Some sort of LoadBalancer in front

Indeed, and nothing prevent you from deploying any load balancer server today in front of your minio servers. But this is not a 0-OS primitive. You need to deploy it yourself, or you can leverage the gateways do to it.

**Comment by joefoxton** [comment]
> > Some sort of LoadBalancer in front
> 
> Indeed, and nothing prevent you from deploying any load balancer server today in front of your minio servers. But this is not a 0-OS primitive. You need to deploy it yourself, or you can leverage the gateways do to it.

This doesn't sound very "autonomous IT". But hey, we are willing to try this. Have you run any load balancers on the grid? Any recommendations? Maybe NGINX or Apache load balancer?

**Comment by joefoxton** [comment]
@zaibon What is your recommendation for a load balancer than runs nicely on the grid?

**Comment by joefoxton** [comment]
Even though there wasn't an answer to our question, I'm gonna close this... we'll work out which load balancer to use. However, we would certainly like to understand more about the "autonomous IT" promise, as so far its been quite manual.
