### ISSUE TITLE
GE: Ability to host multiple storage slices on a single node

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#794]
We would prefer to be able to host all slices in an erasure coding disk set on a single Apollo server. We see erasure coding as protecting against disk failure. We don't see it as a viable high-performance solution for spreading data across geographically redundant locations.

Currently we can only use one storage slice per node for a single reservation, forcing us to spread slices across multiple nodes, even though we have single nodes with a high amount of storage.

This does not allow for high performance use cases, and creates a scenario where all our disks will be underutilised.

**Comment by zaibon** [comment]
> Currently we can only use one storage slice per node for a single reservation,

This is not actually correct. You can create a reservation that request any number of 0-DB namespace one the same node. This is perfectly valid. The only thing that is not possible today is to define the spread of the 0-DB on different disks. 0-OS does the capacity planning of where to create the 0-DB namespace itself and try to optimize the storage as much as it can. 
Allowing users to choose the spread of disk is something we are thinking to add though. 

> This does not allow for high performance use cases, and creates a scenario where all our disks will be underutilised.

**Comment by despiegk** [comment]
this is the urrent design criteria for ZDB, ZDB is a backend storage device, it is not meant to be high performance, its meant to be used for scale out.
If people would put this on the same node there is no redundancy when the node goes down, this is what we want to avoid.

A feature request could be to allow reservations on same node which use different disks, we will put this on the roadmap.

**Comment by joefoxton** [comment]
Good to hear.

re. “backend storage device”. If we are to run application workloads like Artheon on our S3 (they are patiently waiting!), then we need to provide high performance Tier 1 backend storage, using a single device, or devices within the same data center connected on the same switch, then served over a high bandwidth, low latency connection.

We are also looking to sell Tier 2/3 nearline and backup storage, as well as high volume storage for  big data (machine learning & data analytics / business intelligence). Each has different priorities around performance, high availability + data robustness, and cost. For example, a big data use case cares much more about cost than high availability or performance, while an application cares more about performance.

In general, disk failure is a much higher risk than node failure. Disks fail far more frequently than servers. I know this from running massive farms for NBC Universal.

We see all these use cases as being important:

1. Multiple slices on the same node for high performance / application workloads
2. Slices on the same data center for good performance / high-availability (protection against disk failure)
2. Slices spread across multiple nodes for high availability / data protection & backup workloads

We are in the process of evaluating which use cases are the best fit for our products strengths, feature set, and our cost tolerance. Our best hypothesis right now is that big data use cases are our best target, as we have trouble justifying the CAC (cost of acquiring a customer) at the lower prices that Application developers typically pay. Your typical app developer is paying under 100/month for their S3, so there are no real cost savings for them, and diving head first into a risky new player just based on values/impact is a tough ask.

I’m a little concerned about the idea that ZDB is not meant to be high performance - would love to understand why you say this, and make sure we don’t head down a wrong path!

**Comment by joefoxton** [comment]
Maybe we are missing something, but we don't currently see a way to reserve multiple slices on a single node. @hteibler Please share more detail.

**Comment by hteibler** [comment]
deployed  minio:
15 disks with each 10TB on 5 nodes ( 3 per node )
policy is:
```
        env={
            "DATA":"10",
            "PARITY":"5",
            "ACCESS_KEY":"minioap3",
            },
```
can we guaranty that this deployment will survive? 
* 5 disks loss ( any disk, any node )
* 1 node + 2 disk on other nodes
 
if disks are lost and replaced, will zos rebuild the storage?

**Comment by zaibon** [comment]
The storage policy of 10/5 means you can loose up to 5 shards and still be able to read/repair your data. The 5 shards can be lost anywhere it doesn't really matter for the storage system.

> if disks are lost and replaced, will zos rebuild the storage?

0-OS itself doesn't repair anything, it's not his role. What will be available in the new version of minio is a healing API that allow your to trigger healing jobs that will repair/re-silver the list disks onto new one after you have make them available to minio.

**Comment by joefoxton** [comment]
We are concerned about location of the shards, as it affects performance. Our top priority is giving Artheon 10TB of high performance S3. For us, this means splitting the shards across disks in a single Apollo. This provides best possible performance, and protects against disk failure (way more likely than node failure).

When will the next version of min.io <http://min.io/> be integrated? We would absolutely love to test the self-healing.

**Comment by joefoxton** [comment]
So... this ticket has blown up in scope... let me bring it back to earth by breaking it up into our needs now vs later. Artheon have been incredibly patient, and we are extremely hungry to get them their 10TB and then learn from the experience... So...

NOW (ARTHEON)
What is the best way to set up a high performance 10TB S3 tenant on Zero OS, using a single Apollo? Our Apollos have 12T disks. Should we just assign 2x12TB disks with one as parity, just to get Artheon off the ground? Can 

LATER
We believe we'll need the ability to:
- Assign shards to disks and machines manually to ensure optimal architecture for the specific customer need, and to ensure maximum utilisation / minimum sunk hosting cost;
- See how much of each disk is assigned to shards, and capacity used in each shard;
- Have multiple shards on a single disk across different solutions;
- Have multiple shards on a single node across the same or different solutions;
- Have shards spread across multiple farms;

**Comment by zaibon** [comment]
> When will the next version of min.io <http://min.io/> be integrated? We would absolutely love to test the self-healing.

You can already test it today. The documentation is still being review but you can already have a look at it on the staging version of the sdk manual: https://sdk2.threefold.io/#/chatflow_hercule

> What is the best way to set up a high performance 10TB S3 tenant on Zero OS, using a single Apollo?

Create all your data shards (0-DB namespace) on the same node. So you avoid the network latency. Although if you have proper gigabyte network setup between your nodes, spreading the shards over multiple node located in the same DC shouldn't give you bad performance anyhow.

> Should we just assign 2x12TB disks with one as parity,

Not sure what you mean here. 

>See how much of each disk is assigned to shards, and capacity used in each shard;

Minio already reports storage usage by shards, so you should be able to have this data.

> Have multiple shards on a single disk across different solutions;

This is already possible today

> Have multiple shards on a single node across the same or different solutions;

This is already possible today

> Have shards spread across multiple farms;

This is already possible today

**Comment by zaibon** [comment]
We are also working on some grafana dashbaord to monitor minio metrics. I've published a preview of it at https://snapshot.raintank.io/dashboard/snapshot/XgM7rYItWR2Gd1gsE7UmNejIvQLdLrUF

Keep in mind this is still work in progress and there are more metrics you would be able to use and create graphs from

**Comment by joefoxton** [comment]
The Dashboard is perfect! 😍

Here's the problem... In order to access min.io after initial setup, we have to violate our privacy pact with our customer. We should only provision, hand them the keys and the min.io client, then let them manage access as suits their business needs. As a farmer, we should have any window into the workloads our our capacity users... this is fundamental to the security and privacy claims of the grid, as well as the "no hacking surface" claim.

As such, we need another way to get to usage data. IMO this should be provided at the Zero OS level. There should be a way to access raw resource usage metrics of workloads, without looking inside the workload.

**Comment by joefoxton** [comment]
btw... referring to the above, we have now deployed 15 shard on 5 nodes. So I believe this issue can be closed! We'll deal with the monitoring/billing privacy issues separately.
