### ISSUE TITLE
GE: Ability for multiple users to perform Farm Management

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#796]
We need multiple users (3bots) to be able to perform Farm Management functions & administration.

We are considering running a Jumpscale SDK instance on a workload w/ a 3bot accessible to all of us. However, it would be much better to have a web-based version of Jumpscale SDK.

**Comment by zaibon** [comment]
I think nothing prevent you from doing this already. In the setting page of the SDK, you have an administrator tab. There you can add as many administrator as you want so multiple people can connect and access the farm management dashboard. 

> However, it would be much better to have a web-based version of Jumpscale SDK.

Can you define what you call a web-based version of the SDK ? Cause everything is already web based.

**Comment by joefoxton** [comment]
If I add an administrator there (which I have), then that person has to remote into my iMac where I run the SDK in order to do any maintenance. This is not optimal (or possible with my privacy settings ;))

Ideally, there would be a public web-based solution where I could grant admin rights to Guido, and he could go in and do farm & wallet management. Ideally, I should be able to grant rights per area/menu item (view, read, edit)

**Comment by zaibon** [comment]
Well this is like this cause you run the sdk locally on your mac. I think nothing prevent you from running this online and make it accessible by all your administrator ?

**Comment by joefoxton** [comment]
@zaibon Once we are able to reliably run & access workloads on ThreeFold, we will run this on this grid. Until then, I don't think we should be spinning up any more non-ThreeFold workloads to run our business - that would be hypocritical.

I'm already feeling quite hypocritical by running our website on Prismic & Vercel... but it was the only option available to us at the time.

Note that Weynand already promised a web-based version of farm management. That said, we're more than happy to run it ourselves, once that becomes possible and trustworthy.

**Comment by joefoxton** [comment]
I think we can close this now... Its been made clear how we'll achieve multiple administrators.
