### ISSUE TITLE
GE: Expose Usability state of a Node in Farm Management

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#797]
For each node, show in Farm Management:
- What public ip addresses did the node receive IPv4/IPv6?
- Is this node ready to run workloads?
- What kind of workloads is it suitable for?

**Comment by zaibon** [comment]
I think all these information are already present. There is a button in the node info detail to show the network config of the node:
![2020-06-22_871x358_scrot](https://user-images.githubusercontent.com/303164/85259825-00bada00-b46a-11ea-9502-fa3e4d56fe51.png)
![2020-06-22_918x208_scrot](https://user-images.githubusercontent.com/303164/85259828-01537080-b46a-11ea-90b2-13f1b215f52c.png)

> Is this node ready to run workloads?

> What kind of workloads is it suitable for?

At the time of writing there is nothing in place to limit certain workloads on a node. This feature will be available at some point though.

> Is this node ready to run workloads?

This is also already present and show by the `status` of the node and the `network health`  column: 
![2020-06-22_668x209_scrot](https://user-images.githubusercontent.com/303164/85260131-79219b00-b46a-11ea-9455-5c7a3ce2734b.png)
If both are green, the node is ready to serve workloads. What else are you looking for ?

**Comment by joefoxton** [comment]
Perfect! Thank you! Closing...
