### ISSUE TITLE
need clear capacity visualization

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#798]
## to fix

- remove https://capacity.threefoldtoken.com/
- where is the grid v2 overview where we can see how much capacity there is
    - above link prob needs to show for v2 and then link back to v1
    - https://explorer.grid.tf/

**Comment by zaibon** [comment]
> where is the grid v2 overview where we can see how much capacity there is

This is actually https://explorer.grid.tf/

Regadring https://capacity.threefoldtoken.com/, I indeed need to update the home page with a message and a link to the new explorer. Will try to get to it today

**Comment by zaibon** [comment]
https://capacity.threefoldtoken.com/ has been updated with a message to invite people to the new explorer and farmer to migrate to v2.
