### ISSUE TITLE
 Virtual Scrum Teams IT System

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#80]
# Goal

- allow people to work together in virtual way per scrum team
    - have webcam's open all the time, can run in e.g. separate tablet

# Requirements

- low bandwidth <150-200 kbit/s per person
- aggregation per site (can be phase 2) e.g. if 10 people in cairo not 10 times outgoing for people in BE
- easy to start

# Remarks

- will require help from e.g. cairo to make soundlevel in office better

# Technical

- Jonas is also investigating
- webrtc prob best
- examples
    - https://jitsi.org/jitsi-meet/
    - https://janus.conf.meetecho.com/videoroomtest.html
    - ...

# Phase 1

- install server in cairo & ghent not meshed yet
- when starting the connection choose server in Ghent or Cairo

See also story on Trello: https://trello.com/c/htVN6i1D/140-virtual-scrum-teams-it-system-jan

**Comment by delandtj** [comment]
servers are installed, 
Cairo: 41.33.199.217
Gent: 185.69.166.32
Testing. & debugging

**Comment by sabrinasadik** [comment]
@delandtj @jdelrue Estimated time?

**Comment by sabrinasadik** [comment]
Tech is not ready
