### ISSUE TITLE
upgrade crystaltools/publishing tools to 0.3.5.1 crystal

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#801]

**Comment by xmonader** [comment]
- crystaltools upgrade: https://github.com/crystaluniverse/crystaltools/commit/e9c91b83ac340e0aa09cc62edd1e1cbfad65710e

**Comment by abom** [comment]
We used a temporary monkey-patch which is [mentioned here](https://github.com/kemalcr/kemal/issues/575#issuecomment-650387005) for now https://github.com/crystaluniverse/publishingtools/commit/bce315562e3420132671ecbee13d7453f6cae487.
