### ISSUE TITLE
GE: Kosmos can't handle objects with spaces in their names

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#809]
We have a wallet named "Green Edge Agent Wallet". We can't look into that wallet object in Kosmos shell because it can't handle object names with spaces.

![Screenshot 2020-06-24 at 10 29 55](https://user-images.githubusercontent.com/1249806/85522247-ab1b3480-b605-11ea-814b-d6e70ad0c33c.png)

**Comment by grimpy** [comment]
For such names you need to retreive the client in the traditional way
`j.clients.stellar.get("Green Edge Agent Wallet")`

**Comment by joefoxton** [comment]
Thanks @grimpy !!
