### ISSUE TITLE
Tool to generate html websites from google docs presentations

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#81]
Export google docs presentations as images and generate an html page using https://revealjs.com
Best to extend the current document generator

**Comment by xmonader** [comment]
I can see two ways

1- download the whole document as pdf and convert it to images using ImageMagick
or 
2- download each page in the presentation as jpg https://github.com/xmonader/presentation2html It doesn't download the pages correctly yet, but the most of the skeleton and generation is there.

**Comment by xmonader** [comment]
Code is good enough for initial version  https://github.com/xmonader/presentation2html and documented. Where should I transfer the repo?
