### ISSUE TITLE
GE: SDK Solution Expose: Something wrong happened, please contact support

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#810]
We were running a trial deploy of Artheon's workload this morning, and hit this Solution Expose snag. To reproduce, I selection "Solution Expose" from the menu, then "Create New", then I get the error in the screen shot below.
Please note this other symptom - not sure if its related: https://github.com/threefoldtech/home/issues/808

Here's the screenshot, and browser log:

![Screenshot 2020-06-24 at 15 52 34](https://user-images.githubusercontent.com/1249806/85569741-18918a00-b633-11ea-80ce-01a2dd7f1560.png)

[localhost-1593007070842.log](https://github.com/threefoldtech/home/files/4825807/localhost-1593007070842.log)

**Comment by weynandkuijpers** [comment]
```:4000/zerobot/admin/actors/wallet/get_wallets:1 Failed to load resource: the server responded with a status of 400 (Bad Request)```

Not being a developer but reading through the log report I think the absence of the wallets in the GUI are the cause.  The wallets should still be part of the container, you can check this by doing in the 3sdk executable:
```
threebot shell
```
which get you in the shell.  Open a kosmos shell:
```
kosmos
```
and then check the wallets available:
<img width="1283" alt="Screen Shot 2020-06-24 at 4 34 46 PM" src="https://user-images.githubusercontent.com/13766992/85576394-a91e9900-b638-11ea-86b7-c5074cf6f91c.png">
they should still be available in the container.

**Comment by joefoxton** [comment]
Yep they are still available… this is how we were able to get through the provisioning steps

**Comment by joefoxton** [comment]
This was caused by the errant entry of an invalid wallet secret. That problem has been fixed elsewhere, so closing this.
