### ISSUE TITLE
GE: Minimum resource requirements for performant min.io master/slave

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#811]
We are unsure what capacity to assign to a min.io master or slave container. Seeing as ThreeFold has built its own implementation under the min.io adaptor layer, we'd love to get a recommendation. This is our current standard:

    minio_master_container=zos.container.create(
        reservation=reservation_master_minio,
        node_id=minio_master_node_id,
        network_name=overlay_network_name,
        ip_address=minio_master_node_ip,
        flist=flist_url,
        interactive=False,
        entrypoint=‘/bin/entrypoint’,
        cpu=4,
        memory=4096,
        public_ipv6=True,
        env={
            “DATA”:”10”,
            “PARITY”:”5”,
            “ACCESS_KEY”:”minioap3”,
            },
        secret_env=secret_env,
    )

**Comment by joefoxton** [comment]
Similarly, what is the minimum requirement for a volume?

**Comment by zaibon** [comment]
You can find information in the hercule documentation: https://sdk2.threefold.io/#/code_hercule?id=capacity-requirements
(FYI this is still staging version of the documentation)

**Comment by joefoxton** [comment]
Ah perfect, closing.
