### ISSUE TITLE
GE: zos.volume.create() - What units is the "size" argument in?

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#812]
On this page: https://sdk.threefold.io/#/code_storage?id=prepare-and-deploy-the-s3-software-container

... in this calll
volume = zos.volume.create(reservation_storage,minio_node_id,size=10,type='SSD')

Is "size" in KBs? MBs? GBs?

**Comment by zaibon** [comment]
From https://sdk.threefold.io/#/capacity_vdisk?id=reservation-definition

> Size: the size of the volume in GiB

**Comment by joefoxton** [comment]
Awesome, thank you!
