### ISSUE TITLE
generic token holders poll wizard js-ng

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#817]
- voting is always anonymous (its a vote per stellar account)
- each poll has a specific id, which needs to be added to the voting result
- we guarantee that double voting cannot happen (so if same account votes again, we overwrite previous)

- login 3bot connect
- ask them to send 0.1 TFTA or TFT to our voting wallet(s) with a random short code
- keep on checking for transactions with that code
- keep showing the verifications done & amount of TFT behind
- ask every time if these are all the TFT
- if user says yes I am now voting with these nr of TFT we go to questions
   - now do something like favorite colour, just to have an example
- show the result of the vote
- the voting bot signs & sends minimal transaction with the hash to voting wallet
- at end we show %TFT token holders votes and overview of their votes

**Comment by waleedhammam** [comment]
## Progress

Working at: https://github.com/threefoldtech/js-sdk/tree/development_polls

- Added polls packages with 2 polls examples (example, foo)

## How to use

- just inherit from `Polls sal` and override `poll_name` and `QUESTIONS` in your chatflow in `polls/chats`

example:
![Screenshot from 2020-06-28 19-04-26](https://user-images.githubusercontent.com/10658229/85954956-9c24e100-b97b-11ea-8064-ba8bee0dd32d.png)

![Screenshot from 2020-06-28 20-15-45](https://user-images.githubusercontent.com/10658229/85955030-2ec58000-b97c-11ea-86b5-974f93cb86f0.png)

![Screenshot from 2020-06-28 20-14-37](https://user-images.githubusercontent.com/10658229/85955017-15bccf00-b97c-11ea-91d5-f418889fa390.png)

![Screenshot from 2020-06-28 20-14-43](https://user-images.githubusercontent.com/10658229/85955019-1a818300-b97c-11ea-8976-2477b299b925.png)


![Screenshot from 2020-06-28 20-09-31](https://user-images.githubusercontent.com/10658229/85954982-ca0a2580-b97b-11ea-9895-ad3d1dc59da2.png)

![Screenshot from 2020-06-28 20-09-41](https://user-images.githubusercontent.com/10658229/85955042-37b65180-b97c-11ea-8c8c-fe30cf0d6def.png)

## Blocking

- Test paying with threebot connect app on testnet and wallet with type "TEST"

## TODO

- Add docs for deploying, reverse proxy, configuring wallets

**Comment by despiegk** [comment]
## the poll questions should be or 

### predefined

- check basic primitives needed like in gforms (not all ofcourse)
- but at least big text
- multi choice
- single choice

### custom step

- where we ask interactive questions
- ask 1 thing, ask next thing, do a check, ask next thing ...
- all flexibility of our chat widget should be there

**Comment by waleedhammam** [comment]
## Progress Update

### Enabled payment via testnet 3bot application
  ![Screenshot from 2020-06-29 22-06-34](https://user-images.githubusercontent.com/10658229/86050976-f645a500-ba54-11ea-91ba-214dabb6adc9.png)

  ![image](https://user-images.githubusercontent.com/10658229/86050993-fcd41c80-ba54-11ea-8cfa-c7a45a075438.png)

![Screenshot from 2020-06-29 22-07-08](https://user-images.githubusercontent.com/10658229/86051141-41f84e80-ba55-11ea-87e1-071ecca47b4b.png)

### Added vote by TFT-shares weight

  ![image](https://user-images.githubusercontent.com/10658229/86051082-24c38000-ba55-11ea-881b-7a7fea52b25c.png)

### Added custom components and another methods of vote
  
  ![Screenshot from 2020-06-29 20-27-30](https://user-images.githubusercontent.com/10658229/86051248-694f1b80-ba55-11ea-926e-0c39bfa29b7a.png)

  
  ![Screenshot from 2020-06-29 20-56-24](https://user-images.githubusercontent.com/10658229/86051229-62c0a400-ba55-11ea-8fb4-7b83dcaec0ec.png)

- It's just simple as override `custom_vote` method and do what you want


![Screenshot from 2020-06-29 22-11-57](https://user-images.githubusercontent.com/10658229/86051356-913e7f00-ba55-11ea-8748-af0e46ab0405.png)

## Note: If user is registered already he can change his vote but will pay only once

![Screenshot from 2020-06-29 22-12-47](https://user-images.githubusercontent.com/10658229/86051432-b16e3e00-ba55-11ea-95ed-188cb68b9e4d.png)

![Screenshot from 2020-06-29 22-12-51](https://user-images.githubusercontent.com/10658229/86051443-b632f200-ba55-11ea-8e58-4e2052743d15.png)


# TODO

- Update vote results to be more pretty
- deploy test instance

**Comment by waleedhammam** [comment]
updated and deployed example at: https://waleed.threefold.io/polls/chats/example2#/

**Comment by despiegk** [comment]
POLL CONTENT:
https://docs.google.com/document/d/1Dg3Mp7oN7F6PCTgDcHAIC_sQqPAo2p0Ku9qP0reHmbE/edit
