### ISSUE TITLE
Use 3bot connect login with onlyoffice

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/home#818]
Make fork of OnlyOffice and be sure we can use 3bot connect login.

 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/2
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/3
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/4
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/5
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/6
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/7
 - [ ] https://github.com/threefoldtech/onlyoffice_3botlogin/issues/8

**Comment by xmonader** [comment]
> Make fork of IYO and be sure we can use 3bot connect login.

is IYO a typo here?

**Comment by jdelrue** [comment]
@tobiaschielens Please link issues here with  tickers

**Comment by ken-de-moor** [comment]
This was already done, old ticket no longer on the right place, will close.
