### ISSUE TITLE
some I9 services

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#819]
- choose low hanging fruit
- prepayment, as long as they have money

**Comment by xmonader** [comment]
- We can do a package that renders the list of solutions in some nice way
- Keep track of the user reservations as we do now
- No need for the wallet of the user to be configured, we can immediately show QR code to submit the reservations

We can immediately have that for 
- network
- ubuntu
- s3
- k8s
- gitea
- domains

**Comment by despiegk** [comment]
i think sending money to it and keeping it in wallet for customer is 1 thing
then when deploying as long as there is money its ok

**Comment by xmonader** [comment]
After discussion with @rkhamis  and @grimpy our current options are

1- central marketplace with specific wallet the user can send money to and using that wallet we creates reservation and does everything on behalf of the authenticated user as long as there's enough funds he sent.
2- browser (to save the private key in the user the browser "and that never gets sent to server side" and from there we sign a specific payload)
3- 3bot app to sign the payload and push to explorer (we send a payload with next_url for 3bot connect app to sign and push to next url)
4- gifted concept in explorer (the explorer allows central place to make reservation but then gifts the reservation to a specific user, this will requires user to accept that gift)

**Comment by m-motawea** [comment]
Current Progress:
1- Chatflows has been added to marketplace package
2- tested basic usage for all chatflows

TODO:
1- add a nice ui for listing and deleting reservations
2- do some code cleaning in the deployer sal used for market place

**Comment by xmonader** [comment]
it's live on mainnet now.
