### ISSUE TITLE
unify docker images repos

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#820]
- [ ] tf-images https://github.com/threefoldtech/tf-images
- [ ] builders https://github.com/threefoldtech/builders
- [ ] apps https://github.com/threefoldtech/apps

**Comment by muhamadazmy** [comment]
Well it's really good that you brought this up. What we need with a builder
- Automated build
- Unified method to build multiple kind of apps
- Clean and unified base
- Builders should build directly to flist 

From what I see the `apps` repo has better potentials
- It auto build using github actions
- It already provide to base images that has zinit and ssh (alpine and ubunut) so other apps can reuse them
- zinit is pretty stable, and easy to add more services to it, so configuring apps to start is as easy as adding a file to the flist.
- no need to set entrypoint so base uses zinit as entrypoint by default.

**Comment by Pishoy** [comment]
checking with Thabet, we are still waiting for Azmy confirmation about tf-images
