### ISSUE TITLE
GE: Ability to scale up number of worker nodes and size

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#823]
Currently there is a ceiling on K8s scaling, set by the number of nodes pre-reserved. This defeats the purpose of K8s auto scaling.

Currently only 2 sizes, largest with 2 cpu and 4gb ram, 100gb disk available.

**Comment by joefoxton** [comment]
From Weynand: Sounds like a misunderstanding: more capacity can be done by reserving (same secret) more worker nodes. Do you need bigger sizes to be deployed this can be done and made available as well.

**Comment by joefoxton** [comment]
I'm not sure I fully understand the solution you are proposing. Can you please share more detail?

**Comment by zaibon** [comment]
> Currently there is a ceiling on K8s scaling, set by the number of nodes pre-reserved. This

This statement is wrong. You can add as many worker to any exiting cluster as you want. There is no limit.

**Comment by joefoxton** [comment]
Sounds like this was a misunderstanding on our side. Closing.
