### ISSUE TITLE
crystaltools support tfweb

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#826]
create

```
ct tfweb start
ct tfweb reload
ct tfweb stop
ct tfweb build
```

will do:

- [ ] check docker installed, if not give url where to go
- [ ] launch a container with crystal & build (if not launched yet)
- [ ] map ~/code to /root/code
- [ ] whatever pub keys used in ssh-agent get authenticated on the container: ssh-agent -L: check if already there
- [ ] start tfweb

reload < 1 sec, its basically reloading the tfweb

build: pull publisher & rebuild & restart

**Comment by xmonader** [comment]
for 0.34 on mac

@Hamdy managed to do it as follows
- I managed to install crystall 0.34 on mac
- I compiled conscious internet as well
- and I can get the json data from the mac

```
brew install crystal   # to install deps
brew uninstall crystal # remove crystal
wget -c https://github.com/crystal-lang/crystal/releases/download/0.34.0/crystal-0.34.0-1.pkg
sudo installer -pkg  crystal-0.34.0-1.pkg -target /
and u might need for libs like libssl  and so on
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig

```

right now checking if it works with 0.35.1 without problems then we drop the docker complications

**Comment by sasha-astiadi** [comment]
hamdy says its obsolete. closing
