### ISSUE TITLE
TFTA sales bot 

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#827]
# requirements

- [ ] any TFTA holder can register their request for selling TFTA as TFT
- [ ] need to be in line with specs on wiki:
    - the bot does orders per 1000 USD (is done in BTC/XLM)
    - everyone who has sales order (login per 3bot connect) gets equal part of the BTC/XML sold, if 10 people then everyone 1/10 of the 1000 USD worth of XLM/BTC sold
    - sales price: 0.15 + 2% per month
- [ ] for Stellar, Liquid & BTC Alpha

**Comment by despiegk** [comment]
## possible solution JS-NG wizard

- create JS-NG wizard where people login using 3bot-connect
- they transfer the TFTA they want to sell to the 3bot-connect wallet (max 10k USD per attempt)
- they specify how long to try (max 4 weeks), if in 4 weeks not sold we send back
- they can always go back to the tool and people how have open orders can see how much people put in in the orderbook (based on 3bot connect)
- if the avg price from our marketmaker in the week is 0.15+2% per month then we distribute the return (BTC) over the people in the orderbook

**Comment by robvanmieghem** [comment]
phase1: TfTA selling service phase1 #830
