### ISSUE TITLE
GE: Remove dead nodes

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#831]
We have a bunch of nodes in our network that are dead / no longer needed. These were nodes that were registered incorrectly, or re-registered elsewhere and now need to be removed. These nodes are displayed on farm management and tokens earnings reports, but do not map to any real nodes. It would be ideal if we could remove these nodes in the SDK dashboard via Farm Management.

**Comment by joefoxton** [comment]
An example is farm ID 173611. There are 9 nodes listed, but only 3 are valid.

**Comment by zaibon** [comment]
@DylanVerstraete I know you implement the delete of the nodes in the explorer API. Did you also updated the jsx client and farm farm management with it ?

**Comment by DylanVerstraete** [comment]
@zaibon 

Explorer API: https://github.com/threefoldtech/tfexplorer/commit/e89505f96b1a539be9dfd1289a6fd9ceca7e4e61

Explorer client: https://github.com/threefoldtech/jumpscaleX_libs/blob/f74715a3360a1e64f5e7baf91a30e32b4ac1eab4/JumpscaleLibs/clients/explorer/farms.py#L69

Farm management dashboard PR still open.. : https://github.com/threefoldtech/jumpscaleX_threebot/pull/727

**Comment by zaibon** [comment]
:+1: great !
@joefoxton so you have it all available.

**Comment by joefoxton** [comment]
Fantastic! Thank you!

**Comment by joefoxton** [comment]
Checking in on this - when will this be available in the farm management dashboard?

I assume I can already script this?

**Comment by zaibon** [comment]
This feature is now available from the 3Bot farm management page. More information ca be found at https://manual.threefold.io/#/3bot_farm_mgmt?id=deleting-a-dead-node
