### ISSUE TITLE
Personal 3bot on the grid as a solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#839]
# 3bot : your personal system administrator & sdk 

### Provisioning 
- JS-NG based
- in the 3bot deployer (user is already identified by 3bot connect) we ask in a chatflow
  - node id or farmer id, otherwise use pool in Ghent 
  - specifying the branch to start the 3bot from
  - the resulting url should be $username.$TBD maybe $username.3bot?
  - redirect the user to initialize page of the 3bot

### Initialization 
 - login using 3bot connect
 - ask the secret
 - check on the 2 central backup servers if the account exists? can we login
  - is yes, restore the data using restic
  - after the restore the 3bot is all back with all info, scripts, wallets, ...

### Post initialization

 - if first time, so 3bot did not exist yet (create wizard)
  - create account on stellar + dash(\*) + dgb(\*) for this 3bot (need helper service for this) (to be later)
  - create the wallets on the 3bot
  - ask user to send some money (tft(a) or dgb or dash) to their 3bot
  - wizard waits till money is there, keeps on asking user if ok
  - do an initial backup

### Backup 
 - each user gets an account on 2 central linux servers (ssh non shell access), login = 3bot name
 - user has secret (passwd of non shell access on the 2 linux servers)
 - backup/restor using restic (same secret used for encryption)
 - backup to home folder on the 2 linux servers (so always 2 backups)
- in admin pannel 3bot user can do following
 - stop 3bot (means gets deleted, container gone, backup done first)
 - backup (manual backup action) ? possible via public actor
 - check last time backup was done ? possible via public actor 

# General remarks
 - js-ng config system is on filesystem
 - backup happens after every provisoning action
 - backup happens every 24h
 - backup destination

## Story checklist

- [x] [Provisioning](https://github.com/threefoldtech/js-sdk/issues/225)
- [x] [Initialization](https://github.com/threefoldtech/js-sdk/issues/234) 
- [x] [Backup](https://github.com/threefoldtech/js-sdk/issues/235)

**Comment by BolaNasr** [comment]
I think we need to backup and restore in minio or something like that , because if container gone i can't restore data anymore

**Comment by rkhamis** [comment]
Verified and deployed.
