### ISSUE TITLE
Make the tft-erc20 bridge more resilient to eth forks

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/home#84]
Currently this is not supported, requiring us to have the block ID in the Tx. It is however possible that due to a _rare_ 25+ block fork, the block ID changes as the valid Tx might have moved to another block.

Since LES/v2, the current version of the Ethereum Light Client Protocol, it supports the `TxStatus` Get/Resp message, which should allow to get the height+blockID for a given TxID. As can be seen at <https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29#transaction-relaying-and-status-retrieval>.

Go-ethereum implements server support for it, but is missing the client support, so perhaps we can support it from the client side from our side, and be able to get the status that way. I probed some peers a couple of weeks ago, and seems that all peers that were connected to me or to which I was connected, were indeed using the LES/v2 protocol, so should be OK.

Once we do support this Status, we could handle the cases in which the block ID has changed. Again, it would be a rare situation, but a possibility none the less.

**Comment by robvanmieghem** [comment]
Given the change in how ethvalidation is done ( https://github.com/threefoldfoundation/tfchain/commit/9c6333a65461635751d549f8649a27d8217fc015 and https://github.com/threefoldfoundation/tfchain/commit/e3da7c43744619c3b1092d9ccf96645ba740fe8b), I think, the blockid can just be dropped since it is no longer required fot tx lookup.

**Comment by LeeSmet** [comment]
blockid is still used to look up the parent transaction which fired the event, as that way we can validate that enough blocks have passed (25 block wait time).

**Comment by robvanmieghem** [comment]
Looking at the code from https://github.com/threefoldfoundation/tfchain/commit/9c6333a65461635751d549f8649a27d8217fc015 , the blockid can be fetched from the past withdraws, not requiring us to store it in the transaction on the chain itself

**Comment by GlenDC** [comment]
Please ellaborate @robvanmieghem, not sure I follow?
