### ISSUE TITLE
GE: Chatflow failing on step 1

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#848]
Whenever I try to start Chatflow for any Solution, I see the same result (see below). This is on 3sdk 10.7.

![Screenshot 2020-07-15 at 13 15 58](https://user-images.githubusercontent.com/1249806/87539032-80207f80-c69d-11ea-9221-cdd8637eefe4.png)

**Comment by waleedhammam** [comment]
Please provide an export from the alerts in admin dashboard

**Comment by joefoxton** [comment]
I’m in Austria for three days, so sadly this will have to wait until Thursday when I return.

**Comment by joefoxton** [comment]
There were two errors, one when I started the threebot this morning, and one when I first tried to run the chatflow for Minio. Note that there are no alerts when I tried to start chatflows after the first attempt.

[Archive.zip](https://github.com/threefoldtech/home/files/4964618/Archive.zip)

**Comment by joefoxton** [comment]
Are there any updates on this case? I tried again this morning, with two different threebots. Same results. See alerts inside this zip:

[Archive.zip](https://github.com/threefoldtech/home/files/4971493/Archive.zip)

**Comment by waleedhammam** [comment]
From what I see here you have initialized your identity with `joefoxton.3bot` which exists on explorer `mainnet`.

But you have signed in with 3bot connect using `greenedgeagent.3bot` which doesn't exist on explorer `mainnet`

To use solutions identity should be registered on the explorer

So we can sign in using `joefoxton.3bot` or register `greenedgeagent.3bot` new identity on `mainnet`

**Comment by joefoxton** [comment]
I did that this morning. Same result. Tried again now, same result. Here are the most recent alerts:
[Archive 2.zip](https://github.com/threefoldtech/home/files/4971861/Archive.2.zip)

How does one register greenedgeagent.3bot on mainnet? This is the 3bot we will use for all our commercial reservations on behalf of our customers.

**Comment by weynandkuijpers** [comment]
IMHO registering happens automatically when you install the SDK on your local machine.  When you re-start ```threebot stop``` and then ```threebot start``` it ask you for the identity to use for the threebot.  First time when you use a new ```xxxxxx.3bot```` account it registers.

Did you do that for the greenedgeagent.3bot?

**Comment by joefoxton** [comment]
I did it as joefoxton.3bot. I've now tried the process with both threebots. Same results unfortunately.

**Comment by joefoxton** [comment]
btw. Please share the process to 100% delete a 3sdk install, so I can restart, and register it under the correct threebot.

**Comment by joefoxton** [comment]
Today I 100% deleted the SDK (sandbox folder) from my machine and restarted. I logged in from the beginning as greenedgeagent.3bot. When clicked on Solutions -> Create Network, I got the same result as in the past. Please see the logs here:

[Archive.zip](https://github.com/threefoldtech/home/files/4982124/Archive.zip)

**Comment by joefoxton** [comment]
This was resolved by completely cleaning out my machine, running "threebot delete", removing all traces of docker, removing the sandbox folder, and starting again.
