### ISSUE TITLE
GE: Refund for failed reservations

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#849]
One of our reservations has become unusable due to a bug in TF Tech's minio code. We spent 80k+ tokens on this 1PB reservation. How can we cancel the reservation, free up the significant amount of resources & space, and get a refund?

**Comment by joefoxton** [comment]
**Reservation details:**
Reservation: 10260 (10258, 10259)
https://explorer.grid.tf/explorer/reservations/10260
TFT Cost: 88,300+95.2415+82.9646
IPV6: 2a02:16a8:1000:0:f4a7:e4ff:fe8d:2f2c
IP4: 10.21.10.4

**Comment by joefoxton** [comment]
**### Please confirm with me before making any changes to the above reservation.**

**Comment by zaibon** [comment]
Well from what I can see from your reservation the only "costly" reservation was the one made for the 0-db storage: https://explorer.grid.tf/explorer/reservations/10259 This one you should not cancel ! this is where your data lives.

The one you will have to replace is the one where you provision the minio container: https://explorer.grid.tf/explorer/reservations/10260. Which is deployed on a node from GreenEdgeAustria-Salzburg1 farm. Which, if I'm not mistaken, is your own farm. So to me it looks the tokens just always stayed in your own hands.

**Comment by joefoxton** [comment]
Indeed, we were able to create a new Minio server reservation to connect with these zdbs. So we were indeed able to resuscitate the reservation.

In this particular case, we are indeed reserving our own capacity, and have the tokens, minus the 15% fees. However, as grid users start booking our capacity, they will expect refunds for any reservations that become unusable due to bugs or unexpected behaviours.

As such, we believe there should be a method to cancel a reservation, free up the resources, and get a refund.

**Comment by zaibon** [comment]
> As such, we believe there should be a method to cancel a reservation, free up the resources, and get a refund.

I recommend you read https://forum.threefold.io/t/decoupling-payment-of-the-capacity-from-workloads-deployment-new-specification/537 to see what is the approach that will be coming in the next release.

**Comment by joefoxton** [comment]
I have read this and fully understand the approach. However, we do not find the solution to be commercially viable. We’d like to discuss this solution with you, and move towards and approach that can work from a commercial perspective for dApp developers and grid users.

**Comment by zaibon** [comment]
That's why the forum thread is there. If you have any comment or remark feel free to start the discussion there.
