### ISSUE TITLE
tft-erc20 support from tfapp  

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/home#85]
Follow up from https://github.com/threefoldtech/home/issues/56

- [x] [Open questions and documentation updates to support erc20 from tfapp](https://github.com/threefoldfoundation/tfchain/issues/251)
- [ ] withdrawal address registration ( Mobicage)
- [ ] Receive erc20 tokens on an ethereum adress ( Mobicage)
- [ ]  Send tft to an ethereum address (by scanning eth address qr code) (Mobicage )
- [ ] Process  erc20 to tft coin creation transaction outputs  for the current balance and be able to spend them ( Mobicage)

Mobicage work was estimated at 3 days

**Comment by robvanmieghem** [comment]
@sabrinasadik Can we have the link to the apk to test on Android?

**Comment by GlenDC** [comment]
@sabrinasadik please update story, what has happened, what will happened.... dates...

**Comment by sabrinasadik** [comment]
https://storage.googleapis.com/oca-apps/builds/android/4797/artifacts/em-be-threefold-staging-2.1.4797-release.apk

Link to the apk to test on android

**Comment by sabrinasadik** [comment]
apple developer account is done - Mobicage is on it

**Comment by sabrinasadik** [comment]
Mobicage has no time to do IOS
@robvanmieghem pls test APK for Android

**Comment by sabrinasadik** [comment]
@robvanmieghem APK tested?
