### ISSUE TITLE
GE: S3 Feature Request: Object Versioning

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#850]
This week, MinIO released Object Versioning, a feature of Amazon S3 that they had previously not implemented. They have documented the feature here: https://docs.min.io/docs/minio-bucket-versioning-guide.html. This is also a native feature of Amazon S3.

We request that Object Versioning be put on the roadmap. Many users see this feature as important. Plus it will result in multiples of capacity utilisation.

**Comment by despiegk** [comment]
we will not implement this, our storage architecture is being changed
