### ISSUE TITLE
GE: S3 Feature Request: Immutability

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#851]
An important feature for backup use cases is Object Locking & Immutability, preventing the overwrite of essential files. Minio have implemented these features as documented here: https://docs.min.io/docs/minio-bucket-object-lock-guide.html

This feature depends on Object Versioning: https://github.com/threefoldtech/home/issues/850

**Comment by despiegk** [comment]
our storage architecture changes will allow this for anyone deploying S3 server on top
