### ISSUE TITLE
Extend solutions in js-ng

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#852]
solutions:

- [x] [taiga](https://github.com/threefoldtech/tf-images/issues/14)
- [ ] zeroci
- [x] foruum
- [x] mastodon
- [ ] couchdb

flists will be created for each of these solutions and promoted when validated

#### ALL solutions need to be tested against generic container in threebot (tested against zos conatiner)

**Comment by abdulgig** [comment]
Checking couchdb . .

**Comment by siddiquagig** [comment]
Will check Taiga

**Comment by Pishoy** [comment]
will check forum

**Comment by AhmedHanafy725** [comment]
For zeroci
It can't to be in flist, it needs k8s cluster.
[here](https://github.com/threefoldtech/zeroCI/blob/development/docs/installation.md#installation) is the installation steps.

**Comment by Pishoy** [comment]
As agreed will continue in taiga + 3bot, are already have circles but it depended on caddy as a reverse proxy 
will work for integrating Nginx as a reverse proxy in taiga to be all-in-one solution ( taiga + 3bot + https)

**Comment by Pishoy** [comment]
taiga flist ready all in one (taiga + 3bot + https)
https://hub.grid.tf/bishoy.3bot/threefolddev-taiga_all_in_one-latest.flist

**Comment by siddiquagig** [comment]
Working on mastodon , installed the required configs , but unable to start the mastodon service in the container, checking

**Comment by abdulgig** [comment]
## Details for CouchDB solution / flist herein

**flist = https://hub.grid.tf/arehman/v2-couchdb-0-2.flist**

**Environment variables**

- pub_key (your ssh key)
- db_admin (couchdb admin)
- db_pass (couchdb admin passwd)

> NOTE : Default DB admin user and password =  admin / test9278

**For data persistence, you can mount a volume to the following directory,**

/opt/couchdb/data

**Couchdb configuration directory**

/opt/couchdb/etc

**Couchdb logs directory**

/opt/couchdb/log


## How to verify ?

http://172.17.10.35:5984/_utils

Login with DB admin and password and go to http://172.17.10.35:5984/_utils/#/verifyinstall

![image](https://user-images.githubusercontent.com/25789764/88478523-18e6b300-cf5a-11ea-80f2-2a03f68b83fe.png)

Docs under this link => https://github.com/threefoldtech/tf-images/blob/master/couchdb/README.MD

**Comment by Pishoy** [comment]
we could start mastodon all-in-one in one container but still working in automate that on flist by environment variables and supervisord
https://github.com/threefoldtech/tf-images/tree/master/mastodon

**Comment by PeterNashaat** [comment]
- trying to create container on freefarm with tft or freetft is failling 
 - tft error
<img width="1022" alt="Screen Shot 2020-08-03 at 3 58 30 PM" src="https://user-images.githubusercontent.com/13523434/89191669-8e2e3580-d5a3-11ea-9613-2c4dfe15ccca.png">

- freetft error is due to no resources available

**Comment by Pishoy** [comment]
env variables and supervisor has been implemented successfully , mastodon flist is ready and working well as below picture , something unknown that when I create the admin account, mastodon should send a verification link to admin mail but it does not, checked logs, logs says mail send successfully , checked SPAM but not exist,  will check that .

![image](https://user-images.githubusercontent.com/21987477/89316273-2b5c9d00-d67c-11ea-92da-33a8bab80f90.png)
![image](https://user-images.githubusercontent.com/21987477/89316326-3ca5a980-d67c-11ea-9f3d-cda01c534d8e.png)
 - sever logs 

![image](https://user-images.githubusercontent.com/21987477/89316151-049e6680-d67c-11ea-83e5-587242a7b5e2.png)

**Comment by PeterNashaat** [comment]
i'm trying to create new container now and getting this error.
```
"failed to load network resource: failed to create veth pair in namespace (464213-1): container veth name provided (eth0) already exists"
```

**Comment by xmonader** [comment]
I'm moving this back in progress 
- couchdb 
- taiga

and don't include any self signed certs in the flists, why would we do that???

peertube, publishing tools are handled by the dev team, removed them from the list

**Comment by Pishoy** [comment]
> and don't include any self signed certs in the flists, why would we do that???
> 
we need for solutions that using 3bot, 3bot login, required https

**Comment by Pishoy** [comment]
for mastodon , i test with SMTP Gmail and works fine, old was using SendGrid , may SendGrid need additional configuration

**Comment by xmonader** [comment]
> > and don't include any self signed certs in the flists, why would we do that???
> 
> we need for solutions that using 3bot, 3bot login, required https

requires real https sure, not self signed certificates.

**Comment by Pishoy** [comment]
> > > and don't include any self signed certs in the flists, why would we do that???
> > 
> > 
> > we need for solutions that using 3bot, 3bot login, required https
> 
> requires real https sure, not self signed certificates.

3bot use it is one SSL certification, i mean we click on 3bot login it redirects me to a URL 
for example gitea use port 3000 while 3bot usually use appid=127.0.0.1:300 so,  i used nginx to fix this redirection for port 3000
am using nginx as a proxy than self singed, not sure if use http only 3bot redirect  gonna work or not 

![image](https://user-images.githubusercontent.com/21987477/90399569-707cc800-e09b-11ea-97f9-85642c958aa4.png)

**Comment by Pishoy** [comment]
closing as all done
