### ISSUE TITLE
GE: Web Gateways no longer accessible

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#857]
Today I attempted to run a test deployment to verify that our 2.2 grid upgrade worked. However the web gateway in Belgium is no longer accessible.

Check here:
https://explorer.grid.tf/explorer/nodes/9L5jR9sYjysKdpcbV1phRRmqwTCwg4SBcym5ppMLz4zT

**Comment by zaibon** [comment]
Looking for https://explorer.grid.tf/explorer/gateways/9L5jR9sYjysKdpcbV1phRRmqwTCwg4SBcym5ppMLz4zT maybe ?

**Comment by joefoxton** [comment]
As far as I can work out, its actually your provisioning code that is looking for this... I'm just calling it. Maybe I'm doing something wrong here?

https://gist.github.com/joefoxton/183d07e3c866fa648d482611dd997290

**Comment by joefoxton** [comment]
This is no longer relevant... closing
