### ISSUE TITLE
Create platform for digitalyouonline

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/home#858]
A platfrom for the new digitalyouonline should be created. This should include the following:

### Base Project
- [ ] Set up the base project in the repo
- [ ] Make sure settings can be applied through environment variables

### File browser
- [ ] Support Sharing https://github.com/crystaluniverse/crystalstore/issues/1 
- [ ] Add Support for links https://github.com/crystaluniverse/crystaldrive/issues/1
- [ ] File permission (read, comment, write)
- [ ] Link onlyoffice
    - [ ] Be able to edit the document
    - [ ] Catch callback of documentserver
  - [ ] Tweak filebrowser for our purpose

### Freeflow connect
- [ ] Make available through marketplace
- [ ] Link freeflowconnect ( iframe? ) 

### Jimber Browser
- [ ] Make available through marketplace
- [ ] Link Jimber Browser ( iframe? )

**Comment by jdelrue** [comment]
Lets make separate ticket for Jimber Browser, will be some work...

**Comment by ken-de-moor** [comment]
Will be followed up here in its own repo

https://github.com/digitalyouonline/home/issues/2
