### ISSUE TITLE
Unify Threebot connect DB & Explorer DB

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/home#859]
Currently a 3bot connect user is not by default registered in explorer
3 bot connect users have no ids by default (only usernames) and some solutions like bcdb ACLs use numeric ids to identify users
we need a way to do the explorer registration automatically and being able to retrieve the user ID in the payload/encrypted data coming back from 3bot connect, otherwise will need to do this independently for each service we have and will be a hassle

TODO:

Some questions and todo's:

- [ ] We make a dump of both and compare if there is overlap, we need an idea of how many people have overlap so we can decide on the approach @MathiasDeWeerdt 
- [ ] Make sure no conflicted records are added in explorerDB @zaibon 
- [ ] Make sure conflicted records are added to 3bot_connect @coeneivan 
- [x] Merge all calls from DB to backend TBD
- [ ] Insert a dump from 3bot_connect db to explorer so all users are known, just before conversion from DB to explorer

**Blocking issue:**
We cant merge the existing threebot connect database with the explorerDB, because we need the email constraint to be removed. There are multiple users who are using 2 / 3 different accounts. Or have used accounts in the past and not anymore.

See https://github.com/threefoldtech/home/issues/884

**Comment by xmonader** [comment]
That was mentioned multiple times already, there're two sources of truth (login.threefold.me and explorer) if that's a hard requirement, 3bot needs to sync their registrations to explorer or merge the two databases. the user identity can be registered on the system using the sdk, but it can't be done using online service (where the user share their mnemonics)

**Comment by jdelrue** [comment]
Lets meet tomorrow for this?

**Comment by ken-de-moor** [comment]
Do a call to the explorer from 3botconnect
Possible issue with seed phrase being needed?

**Comment by jdelrue** [comment]
Some questions and todo's:

- In which format is the public key stored in 3botconnect db?
- In which format is the public key stored in explorer db?
- Can we make a dump of both and compare if there is overlap, we need an idea of how many people have overlap so we can decide on the approach

- How hard is it for the 3bot connect to use the explorer API, seems the quickest fix atm
- How hard is it that for now we do check at register in the explorer DB if the public key is in sync with the one on 3bot connect, preventing account hijack?

**Comment by zaibon** [comment]
> In which format is the public key stored in 3botconnect db?

base64 as far as I know

> In which format is the public key stored in explorer db?

Hexadecimal

> How hard is it that for now we do check at register in the explorer DB if the public key is in sync with the one on 3bot connect, preventing account hijack?

Shouldn't be hard at all and seems like a good idea

**Comment by xmonader** [comment]
that's the flow used in the js-sdk https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/core/identity/__init__.py#L100

**Comment by ken-de-moor** [comment]
Issue created for email uniqueness problem.

https://github.com/threefoldtech/home/issues/884
