### ISSUE TITLE
Migrate internal IT environment 1.1 TF Grid

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#86]
Migrate all from our 1.0.0 environment into Zero-OS boxes running on TF Grid.

**Comment by christopherhutton** [comment]
@delandtj ... will this be completed by month end ? pls advise

**Comment by PeterNashaat** [comment]
- For our internal it , we will migrate content to use lua/nginx framework.
  - samar and Ehab ready for integrating the websites once we find a good md parser to integrate , reem and andrew are working on that as we speak .

##### For progress of migrating websites in [ticket](https://docs.grid.tf/threefold/org_support/issues/11)

**Comment by sabrinasadik** [comment]
List what services of ours are still running @ GIG

**Comment by sabrinasadik** [comment]
Full list see: https://docs.grid.tf/threefold/org_support/issues/11
