### ISSUE TITLE
It should be possible to send notifications to all users that have 3bot connect installed

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#860]
- [x] Research method/technology for doing this
- [x] Implement the notifications
- [x] Make sure notifications are only sent to the correct environment ( no test notifications can ever go to production )
- [x] Make them work in Android
- [x] Make them work in iOS
- [x] Show them on multiple devices (if logged in on multiple devices)

**Comment by ken-de-moor** [comment]
To be discussed on standup: How will we provide an admin interface for somebody to type and send a notification? This is not a permissin that can be granted lightly

**Comment by coeneivan** [comment]
@ken-de-moor 
I understood it like this:
The notifications will ben sent from the backend. Nobody (but the backend) can send notifications.
Notifications will be used to alert a single user when there is a login attempt for him/her so they can quickly access the app.

**Comment by coeneivan** [comment]
- [ ] request device id on startup
- [ ] compare with your own device id
- [ ] if no match -> send signed device id and go to 1

**Comment by MathiasDeWeerdt** [comment]
Notifications have been dropped in the latest 2.0.0 release due to issues and it not being needed yet.
