### ISSUE TITLE
cannot install any package in ubuntu solution  

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/home#865]
- I got this error when trying to install any package using ``` apt install PACKAGE_NAME``` in ubuntu **18.04** **19.10** **20.04**

![ff](https://user-images.githubusercontent.com/21218053/89305760-55f42900-d66f-11ea-8458-3ddea91dfc45.png)

![error](https://user-images.githubusercontent.com/21218053/89305848-6efcda00-d66f-11ea-9d63-bcbacada0a2a.jpg)

**Comment by BolaNasr** [comment]
It works Fine using chatflow : 
![image](https://user-images.githubusercontent.com/10259267/89894849-12536f00-dbdb-11ea-82bd-acc80497df48.png)
 and Please make sure about size of your container please.
