### ISSUE TITLE
Migrate Gitea to use 3bot login

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/home#866]
- [ ] change gitea login fro IYO to 3bot login
- [ ] make sure the backup/restore working OK
- [ ] make sure all old usres from IYO can login with 3bot and can access there stuff
- [ ] update ITEnv with all the needed docs and information about the new gitea installation, backup and restore
- [ ] add steps how to fix in case of failure at anytime

related issues:
- tf-gitea: https://github.com/threefoldtech/home/issues/822
- https://circles.threefold.me/project/saeedr-it-support/issue/54

**Comment by Pishoy** [comment]
related issue https://github.com/threefoldtech/js-sdk/issues/388

**Comment by hossnys** [comment]
just created 3 containers using Gitea solution and can't reach any of them and tried this with two different networks .
![Screenshot from 2020-08-05 13-10-48](https://user-images.githubusercontent.com/26298009/89413377-0c681480-d729-11ea-95ac-1ef089f0e6ae.png)
![Screenshot from 2020-08-05 13-29-19](https://user-images.githubusercontent.com/26298009/89413381-0e31d800-d729-11ea-8463-f9c0c84c791d.png)
![Screenshot from 2020-08-05 13-43-43](https://user-images.githubusercontent.com/26298009/89413384-0eca6e80-d729-11ea-899c-1bafd4c8fdad.png)

**Comment by xmonader** [comment]
@hossnys did you use wireguard configurations you retrieved or exposed the solution on a domain???

**Comment by hossnys** [comment]
Just used wireguard configurations I got from chatflow.

**Comment by Pishoy** [comment]
test with  generic flist works well , checking with Bola of gitea container ..

**Comment by Pishoy** [comment]
after multiple reservation, suddently i got internal server error , not sure why ?!
![image](https://user-images.githubusercontent.com/21987477/89528343-2833ef00-d7eb-11ea-983e-c115fcd9b369.png)

**Comment by Pishoy** [comment]
Threebot server fixed by Bola 
Gitea server setup successfully as below but will check why got the blow, seems nginx redirection issue ..
![image](https://user-images.githubusercontent.com/21987477/89548969-05fc9a00-d808-11ea-95bc-f9da7c410f0d.png)

**Comment by Pishoy** [comment]
- I have update Nginx config, and docker working fine,
tried to test on generic flist but when select I choose IP on my env and then trying to choose it from IP range,  it does not show 
- here is bug https://github.com/threefoldtech/js-sdk/issues/414

- I suggest that selecting IP , be before setting the env variables

**Comment by Pishoy** [comment]
the new flist is updated with more nginx enhancement https://hub.grid.tf/bishoy.3bot/threefolddev-gitea_all_in_one-latest.flist

wiating maxium to confirmmation

**Comment by Pishoy** [comment]
maxime update image yesterday, still same , when i test again using my updated  flist with generic flist,  still can not figure what happen below with zos container while on docker works, need a help from Dev team 
![image](https://user-images.githubusercontent.com/21987477/90029797-8f561580-dcbb-11ea-9367-132ced496fb1.png)

**Comment by hossnys** [comment]
also when trying using this promoted flist with gitea solution i got this error 

![Screenshot from 2020-08-12 22-59-56](https://user-images.githubusercontent.com/26298009/90068115-6b60f700-dcf0-11ea-9c45-4f67216b1a92.png)

![Screenshot from 2020-08-12 22-57-48](https://user-images.githubusercontent.com/26298009/90068113-68fe9d00-dcf0-11ea-8b94-2d21f5dc4b81.png)

**Comment by BolaNasr** [comment]
Now gitea chatflow  it works good at branch ```development_capacitypool_apps``` with 3bot login 
Thanks @Pishoy 
![image](https://user-images.githubusercontent.com/10259267/90539303-f1ad8b00-e17f-11ea-92d3-eb64eae15c7c.png)

**Comment by Pishoy** [comment]
Gitea now working with domain delgation , Thanks @BolaNasr 
![image](https://user-images.githubusercontent.com/21987477/90618070-bf4b6e80-e20f-11ea-904b-0bfd0465698b.png)

**Comment by Pishoy** [comment]
- still getting an issue , I can not connect to gitea for soultions, Please verify the gitea flist that is used 
the working one of mine https://hub.grid.tf/bishoy.3bot/threefolddev-gitea_all_in_one-latest.flist

- chatflow 
````
root@tfwallet-prod:~# cd /opt/js-sdk/
root@tfwallet-prod:/opt/js-sdk# git log -1
commit 9821a780024b4323c4a61f4b5818574f20990236 (HEAD -> development_capacitypool, origin/development_capacitypool)
Merge: 9725758 180a254
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Mon Aug 24 16:43:54 2020 +0200

    Merge pull request #590 from threefoldtech/development_cp_fix_marketplace_filtering
    
    fix marketplace filtering
```

**Comment by Pishoy** [comment]
to be followed https://github.com/threefoldtech/js-ng/issues/446

**Comment by Pishoy** [comment]
move it to next milstone as it is pasued right now ( migration docs.grid.tf)

**Comment by Pishoy** [comment]
now gitea container has been created on ovh, we are working on migrating data from old docs.grid.tf to new container on ovh
