### ISSUE TITLE
more content on info_tfgrid22_testgroup

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/home#867]
Manual to help onboard people

manual should include:
  - [x] [intro](https://github.com/threefoldfoundation/info_gridmanual/blob/development_ng/src/intro.md)
  - [ ] wallet management
       - [ ] working with testnet
            - [ ] create wallet on interstellar directly (for end users on http://interstellar.exchange/)
            - [ ] install sdk
       - [x] [add funds through sdk](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/add_funds_to_wallet.md)
       - [ ] [add funds through dashboard](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/add_funds_to_wallet_dashboard.md)
  - [ ] deploy threebot:
       -  [x] [from marketplace](https://github.com/threefoldfoundation/info_manual_tfgrid_testnet/blob/master/src/threebot.md)
       -  [x] [from sdk](https://github.com/threefoldfoundation/info_gridmanual/blob/development_ng/src/2_gettingstarted/gettingstarted.md)

   - [x] [admin panel tour](https://sdk.threefold.io/#/3bot_admin) 

   - [ ] provisioning solutions
       - [x] get tutorials from marketplace docs: (https://github.com/threefoldfoundation/info_manual_tfgrid_testnet/blob/master/src/README.md)
       - [x] solutions from admin

   - [ ] payment flow on testnet until live
      "in grid 2.2., capacity pool is introduced where resource reservation is decoupled from workloads and compute and storage resources are reserved ahead"
     -  [ ] more information on capacity pool (https://github.com/threefoldtech/tfexplorer/blob/master/specs/modify_IT_contract_over_time.md)

   - [x] [community](https://sdk.threefold.io/#/community)
   - [x] [farm setup and management] (https://sdk.threefold.io/#/farm_setup_management)

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldfoundation/info_manual_tfgrid_testnet/pull/3 
- [ ] All chatflows docs
- [ ] How to use marketplace on production net

**Comment by despiegk** [comment]
note there is work on see https://github.com/threefoldfoundation/info_gridmanual/projects/3
ONLY this has prio now

**Comment by despiegk** [comment]
its also not a community manual, its the getting started github repo where we can collaborate with some people around 2.2 on testnet, see the chat group

lets try and get most content to the development_testnet on our manual repo
