### ISSUE TITLE
TLS termination and too many issuances for gateway.tf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#875]
When generating certificates for subdomains on gateways eg `instancename-tfgw-testnet01.gateway.tf ` we get `too many issuances for gateway.tf`.
https://letsencrypt.org/docs/rate-limits/

```
For instance, in the name www.example.com, the registered domain is example.com. In new.blog.example.co.uk, the registered domain is example.co.uk. We use the Public Suffix List to calculate the registered domain. Exceeding the Certificates Per Registered Domain limit is reported with the error message too many certificates already issued, possibly with additional details.
```

What we agreed on a long time ago, is Apps/3bots would terminate TLS not some central proxy and having the TLS termination on the gateway isn't an option, that's why TCP router clients are in place to forward the traffic to the application proxy that does the TLS termination, certificates are supposed to be bundled with the deployed application by design.

current registered: https://crt.sh/?q=gateway.tf (it doesn't help to have 100 gateways if they are on the same domain....)

maybe we can reach out to let's encrypt https://letsencrypt.org/docs/rate-limits/#a-id-overrides-a-overrides ?

**Comment by OmarElawady** [comment]
This is a proposal based on the [Cloudflare's full strict SSL mode](https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options#h_8afd8a8d-382d-4694-a2b2-44cbc9f637ef).
![domains](https://user-images.githubusercontent.com/13040543/90508084-4e488000-e157-11ea-89b4-c25c904d709e.png)

A central reverse proxy is created for each gateway. This reverse proxy have a wildcard certificate installed on it for all subdomains registered on this gateway domain. Behind this proxy reside all the deployed solutions and the reverse proxy multiplexes them using the host name. But we face the issue that the traffic between the proxy and the solutions is not encrypted. We can resolve this by creating a certificate authority and sign a new certificate for each solution and forward the traffic in a new TLS encrypted channel using this certificate. This CA of course is not trusted by anyone except us, but it doesn't matter as it is involved in communications between Threefold's proxy and the containers on Threefold's grid so what matters is that Threefold trusts it.

The downside of this approach is that the traffic gets decrypted on the reverse proxy, so if it ever gets compromised, the intervener can intercept the decrypted traffic to these solutions.

This can be provided with the alternative for the user to create a custom domain with his own certificate without any decryption in the middle.

**Comment by xmonader** [comment]
Right now, we started with scaling more gateways, but won't block the grid release anymore

**Comment by xmonader** [comment]
more context:

Discussion of today with @despiegk @delandtj @robvanmieghem yielded agreement on checking zerossl and how it can help us around the current problems e.g its relaxed ratelimits

**Comment by robvanmieghem** [comment]
Other options are:
- use a free ssl provider that does not limit on subdomains
- Have a commercial subscription with an ssl provider and buy certificates for the 3bots( generated from the 3bot off course
- be our own CA for the 3bot subdomain

**Comment by robvanmieghem** [comment]
Getting a subordinate CA will be hardly impossible. 
Here's [an example](https://bugzilla.mozilla.org/show_bug.cgi?id=1390981#c2) of Comodo being held responsible for bad certificates Intel issued with such a [name-constrained CA certificate](https://crt.sh/?sha1=d50c68fdcb0c3315eb9951f2444fd9e48ba34829). Given that the issuing CA is responsible for any bad certificates you issue, I'm not surprised that it's very hard to obtain

**Comment by robvanmieghem** [comment]
When going for option 2 it would be nice to run an acme proxy that forwards  our  the requests to the provider's acme server with our account's credentials. This way standard acme client plugins can be used and we have zero-admin besides keeping the account alive off course.

With zerossl for example, a basic account has unlimited domains: https://zerossl.com/pricing/

**Comment by robvanmieghem** [comment]
Being a man-in-the-middle might be harder than /i initially thought. 
From the ACME spec:
> All ACME requests with a non-empty body MUST encapsulate their
   payload in a JSON Web Signature (JWS) [[RFC7515](https://tools.ietf.org/html/rfc7515)] object, signed using
   the account's private key unless otherwise specified

Looks like security guys worked on this spec

**Comment by robvanmieghem** [comment]
We are going for option number 2: Have a commercial subscription with an ssl provider and buy certificates for the 3bots( generated from the 3bot off course)
