### ISSUE TITLE
Questions based on call with Weynand (28.08.2020)

### ISSUE THREAD

**Issue by AnneHuesges** [threefoldtech/home#881]
Goal: We want to manage our overlay-network incl. Kubernetes Cluster and expose-solution from inside an application already running on the Kubernetes Cluster on the grid

1.	How to install Jumpscale library locally to run Python scripts?
2.	How to install Jumpscale library to run Python scripts inside a container on the grid?

> a.	Desired functionalities of Python script: 
> > i.	add nodes as workes based on specific location to an existing K8s
> > ii.	create individually configured gateways to an existing network automatically to expose on-demand deployed applications 

3.	Is it possible to deploy multiple workloads from different people on one node?
4.	What functionality have the service-loadbalancer pods (svclb) when loadbalancing an application? Is it possible to run them on another port than 80?

We appreciate any help. Thanks and kind regards.

**Comment by xmonader** [comment]
@AnneHuesges Hello 

1- https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md this guide gives you a local threebot (including the jumpscale sdk + application server + admin panel)
2- You can use a 3bot flist or can start from ubuntu container and on there you follow the quick_start document in answer to 1


I'll leave the more accurate response to @zaibon  for the k8s status

**Comment by AnneHuesges** [comment]
> @AnneHuesges Hello
> 
> 1- https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md this guide gives you a local threebot (including the jumpscale sdk + application server + admin panel)

Hi, thanks for your response. Is it only possible to run the J-SDK from within the Threebot container? Weynand mentioned that it might also be possible to include Jumpscale into the local Python library and to run the scripts without the need of the Treebot. That is actually the goal, we want to achieve.

**Comment by xmonader** [comment]
@AnneHuesges JS-SDK is a framework that happens to include the code for 3bot server, you can install it locally in your machine or on any container as long as it has the python dependencies. If you only seeking the SALs to work with the grid or the explorer they're available.  you don't need to run threebot to have that functionality :)

**Comment by AnneHuesges** [comment]
> @AnneHuesges JS-SDK is a framework that happens to include the code for 3bot server, you can install it locally in your machine or on any container as long as it has the python dependencies. If you only seeking the SALs to work with the grid or the explorer they're available. you don't need to run threebot to have that functionality :)

Hi, thanks. That is exactly what we need. So we tried to install it locally on wsl and ubuntu machine (release 20.04) according to following link: https://github.com/threefoldtech/jumpscale9_core 
Unfortunately, we get the error [-] something went wrong: ssh keyscan.

**Comment by xmonader** [comment]
Oh that link shouldn't be used that's js9, we had multiple iterations afterwards jsx and [js-sdk ](https://github.com/threefoldtech/js-sdk/ )rightnow

https://manual2.threefold.io/#/local_3bot this is the most updated version

**Comment by AnneHuesges** [comment]
> Oh that link shouldn't be used that's js9, we had multiple iterations afterwards jsx and [js-sdk ](https://github.com/threefoldtech/js-sdk/)rightnow
> 
> https://manual2.threefold.io/#/local_3bot this is the most updated version

Thank you, but this link seems to be for the 3Bot, not for the SAL. However, if we understood the earlier response correctly, we only need the SAL and want to use it without using a 3Bot.  What are the right commands / appropriate documentation when we only need the SAL without the 3Bot?

**Comment by abom** [comment]
@AnneHuesges Once you install `js-sdk`, you'll have the whole `jumpscale` library in your path, including the `sals`, you can try the following for example after installation (in any python shell or in jsng shell itself):

```
from jumpscale.loader import j

j.sals.fs.exists("/home")
```

**Comment by Leschge** [comment]
So we installed it and use VS Code. The import was successful but there seems to be no autocomplete for your library ... is there a documentation because the link "API Doc" in https://github.com/threefoldtech/js-sdk/ is broken ..

**Comment by xmonader** [comment]
> So we installed it and use VS Code. The import was successful but there seems to be no autocomplete for your library ... is there a documentation because the link "API Doc" in https://github.com/threefoldtech/js-sdk/ is broken ..

- It should be working fine now https://threefoldtech.github.io/js-sdk/wiki 
- as for the autocompletion, you can use vscode and the shell

shell:
![image](https://user-images.githubusercontent.com/64129/92077153-2181a300-edbc-11ea-9a7a-fd575793529f.png)

Looks like vscode is without virtualenvs something like
![image](https://user-images.githubusercontent.com/64129/92077390-9e148180-edbc-11ea-965c-de9827f20d13.png)


You can use the python.venvPath variable in vscode


for my settings
```
~> poetry config virtualenvs.path
➜  js-sdk git:(development) poetry config --list
cache-dir = "/home/xmonader/.cache/pypoetry"
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/xmonader/.cache/pypoetry/virtualenvs
```

![image](https://user-images.githubusercontent.com/64129/92077539-ec298500-edbc-11ea-8c2f-48beea05c4bb.png)

once everything is ok you can do select interpreter

![image](https://user-images.githubusercontent.com/64129/92077832-7f62ba80-edbd-11ea-93c9-0daf472e85d9.png)

after updating your configurations to use the interpreter in the virtualenv

![image](https://user-images.githubusercontent.com/64129/92078065-f435f480-edbd-11ea-9f6e-d6b49a003c89.png)

Also now it's referenced in the wiki https://threefoldtech.github.io/js-ng/wiki/#/./editor_setup

**Comment by muhamadazmy** [comment]
I will try to answer some of the question here:

> - Desired functionalities of Python script ?
>   - add nodes as workes based on specific location to an existing K8s
> 

Each k8s reservation deploys one single k8s machine. If you create multiple reservation with the same cluster secret and using the same network. The those nodes will be able to connect and reach each other. 

Hence it's up to the cluster admin to login to the master k8s node of the cluster, and add the other nodes to his cluster, hence extending a cluster is not an issue.

----

> Is it possible to deploy multiple workloads from different people on one node?

Yes, the node on the grid is not reserved to a single user. A workload deployed only consumes some resources but the remaining of the resources are available for other users to consume. Hence multiple reservations from same or multiple users can be deployed on the same node.

Note that, k8s VMs are kind different, currently you can NOT deploy multiple k8s VMs on the same NODE and same NETWORK for the same USER. So the same user can deploy multiple vms on the same node if each belongs to a different network. I am not sure if this limitation is due to some actually limitations in the network setup, but it makes sense from a 'cluster' point of view because you don't want all your cluster to be on the same node, otherwise if the node crashes your cluster will not be reachable.
----

> What functionality have the service-loadbalancer pods (svclb) when loadbalancing an application? Is it possible to run them on another port than 80?

I think this is one of the k8s services, it's completely up to the cluster admin to decide what to run on the node once the k8s is installed.

**Comment by Leschge** [comment]
thanks, so we have changed our settings to this:
> You can use the python.venvPath variable in vscode
> for my settings
> ```
> ~> poetry config virtualenvs.path
> ➜  js-sdk git:(development) poetry config --list
> cache-dir = "/home/xmonader/.cache/pypoetry"
> virtualenvs.create = true
> virtualenvs.in-project = true
> virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/xmonader/.cache/pypoetry/virtualenvs
> ```
But we do not have that folder "wspace/js/js-sdk" or a ".venv" file in general.
> ![image](https://user-images.githubusercontent.com/64129/92077539-ec298500-edbc-11ea-8c2f-48beea05c4bb.png)
> 
> once everything is ok you can do select interpreter
> 
> ![image](https://user-images.githubusercontent.com/64129/92077832-7f62ba80-edbd-11ea-93c9-0daf472e85d9.png)

We only have the "Python 3.8.2 64-bit" interpreter but none with venv

**Comment by xmonader** [comment]
> But we do not have that folder "wspace/js/js-sdk" or a ".venv" file in general.

is the directory I cloned the js-sdk repository to and xmonader is my username on the system. sorry for confusing you.

**Comment by Leschge** [comment]
Thanks for the reply. Sorry for beeing unclear. We also do not have a _.venv_ in our cloned repository.
I just checked the Repo. The _.venv_ is listed in the _.gitignore_

**Comment by xmonader** [comment]
> Thanks for the reply. Sorry for being unclear. We also do not have a _.venv_ in our cloned repository.
> I just checked the Repo. The _.venv_ is listed in the _.gitignore_

No worries, poetry will create it once you do poetry shell and poetry update and poetry install if you have configured poetry to use these configurations

```
virtualenvs.create = true
virtualenvs.in-project = true
```

**Comment by Leschge** [comment]
So Anne and me both testet your suggestion but still no _.venv_
Our files/output looks like this. No matter if we do "poetry shell" first or not.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/44225383/92217213-aee5f580-ee97-11ea-8df8-cc129bdb24b4.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/44225383/92217210-ae4d5f00-ee97-11ea-95f0-bed87b3f2b54.png)

**Comment by xmonader** [comment]
@Leschge Hi We updated our docs with a step by step document for IDE completion
https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/editor_setup.md

**Comment by Tuffels** [comment]
> @Leschge Hi We updated our docs with a step by step document for IDE completion
> https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/editor_setup.md

@xmonader Thank you, however we already tried these steps. The problem might be that poetry already has installed all dependencies and thus does not change anything? We're not sure, but either way, as mentioned before, it does not create the .venv

![image](https://user-images.githubusercontent.com/52570398/92570840-aa984e80-f282-11ea-905e-bf86eeb43221.png)

We have also uninstalled and reinstalled the js-sdk after updating the poetry config, with no effect.

**Comment by abom** [comment]
@Tuffels I think you already have a virtual environment in `~/.cache/pypoetry`

Could you please try removing it first?

First, make sure you are outside the virtual env shell, when doing `poetry env list`, it should output something like:

```
➜  js-sdk git:(development) poetry env list
js-sdk-2MKXmKJD-py3.6 (Activated)                                                                                                                    
```

Now we can remove this env:

```
➜  js-sdk git:(development) poetry env remove js-sdk-2MKXmKJD-py3.6                                                          
Deleted virtualenv: /home/abom/.cache/pypoetry/virtualenvs/js-sdk-2MKXmKJD-py3.6
```

Then after that, we can do `poetry install` and it will create a new environment inside the project `.venv`:

```
➜  js-sdk git:(development) poetry install                                                                                                           
Creating virtualenv js-sdk in /home/abom/projects/jumpscale/js-next/js-sdk/.venv                                                                     
Installing dependencies from lock file                                                                                                               
                                                                                                                                                     
                                                                                                                                                     
Package operations: 122 installs, 0 updates, 0 removals                                                                                              
                                                                                                                                                     
  - Installing pycparser (2.20)                                                                                                                      
  - Installing cffi (1.14.2)                                                                                                                         
  - Installing six (1.15.0)                                                 
...
```

**Comment by Tuffels** [comment]
@abom Thanks, I tried this but now i get the following error when trying to do poetry install:

![image](https://user-images.githubusercontent.com/52570398/92579509-9017a280-f28d-11ea-8516-d82495423510.png)

**Comment by Tuffels** [comment]
@abom Thank you so much, this seems to have worked!

**Comment by abom** [comment]
It's also mentioned in the docs now:

https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/editor_setup.md#removing-old-virtual-environment-in-cache-directory
