### ISSUE TITLE
Merging threebotconnect backend with explorerDB

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/home#884]
We need to unify the threebotconnect backend with the explorerDB and this introduces some difficulties.

**Issue 1 - The threebotconnect backend does not enforce unique emails while the explorerDB does.**
Users on threebotconnect have created multiple accounts with the same email address, which makes it impossible for us to determine which account to migrate to the explorerDB.

**Issue 2 - Email verification is entirely controlled by the user** 
We can't just migrate all the accounts over to the explorerDB because we cannot validate that they have a valid email, this is managed by the app. (SEI integration: Basically a signed object by openKYC which verifies that this user has a valid email. And this SEI is stored in the app.)

**Open questions:**
- How do users remove themselves from the explorerDB?
- How do users update their own email address on the explorerDB?
- Are the existing users in the explorerDB verified?
- How do we enforce email 'uniqueness' with services like google and others? hello.mail@gmail.com is the same email as hellomail@gmail.com and this implementation differs from email provider to email provider.

**Possible solution**
We update the app and add the following implementation:

Each user that opens the new application is automatically migrated to the explorerDB. If this user his email adres already exists on the explorerDB the app will display an error in the settings page nearby the email verification status, with the following message: "Duplicate email detected". Upon clicking this new entry they can read what has happened and act accordingly. The wallet within the app will stay functional for all users, other users with the duplicate email warning will not be able to login anymore. (This functionality will have to be enforced, because by default the user will still have a valid SEI inside the application and be able to login anywhere.)

**Comment by ken-de-moor** [comment]
We're going to apply the solution proposed under "Possible solution"

**Comment by zaibon** [comment]
> How do users remove themselves from the explorerDB?

They don't, There is no API to delete a user.

> How do users update their own email address on the explorerDB?

Can you give more detail about what information you need here ? Yes the user is able to change its information.

> Are the existing users in the explorerDB verified?

What do you mean by verified ? verification of the email address specified ? At the moment the address is not verified no.

>  How do we enforce email 'uniqueness' with services like google and others? hello.mail@gmail.com is the same email as hellomail@gmail.com and this implementation differs from email provider to email provider.

We mark the email field as unique in our db model: https://github.com/threefoldtech/tfexplorer/blob/5b95bd5659ad3736f5394623a75e3bea9dcdf6ea/pkg/phonebook/types/setup.go#L23
