### ISSUE TITLE
Migrate Ovh node to Zos V2

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/home#885]
- select node with lease deployed resources.
- Create a PXE script to install zos V2.

**Comment by hossnys** [comment]
now we have one ovh node free to use ```10.102.251.225```, @PeterNashaat  and @Pishoy  moved all stuff away of it 

so we need to agree on this steps before migrate to it 

- create new farm with a 3bot account which all of us have access to it.
- create zos-v2 image then install the node using it.
- align with development team to get green light that we can deploy our production stuff using new admin panel .
- start with deploying some staging websites there first to test how it's going on . 
- if things going well  deploy production stuff there.
- move the rest of ovh nodes to zos-v2 if needed.

**Comment by ramezsaeed** [comment]
postponed till we get green light that we can deploy on the grid.

**Comment by rkhamis** [comment]
shouldn't this be blocked instead of closed? or are we abandoning this plan altogether?

**Comment by ramezsaeed** [comment]
Yes abandoned for now
