### ISSUE TITLE
Convert tfta to tft issue

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/home#887]
Complaint over Crisp chat

- TFTA to TFT conversion contract is not working anymore
please see: last two transactions were not converted: https://stellar.expert/explorer/public/account/GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2?order=desc

issue :- 

- There were no back transactions to the incoming transfers of TFTA

**Comment by nbabenko** [comment]
works now.. there were some delay..
