### ISSUE TITLE
 TF Grid demo blog issue

### ISSUE THREAD

**Issue by mveplus** [threefoldtech/home#890]
Hello TF gurus,

Just wanted to drop a message with thanks for TFGrid 2.2 looks awesome! It's very easy to use!  
I'm playing around with it and deploying Blog on demo.testnet.grid.tf spit this out: 

`Failed to initialize blog, please contact support with this information: Node: 3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF, IP Address: 10.100.3.2, Reservation ID: 478720, Pool ID: 1841, Domain: ml-blog-myfirstfgridblog.tfgw-testnet-01.ava.tf . Please use the refresh button on the upper right to restart the chatflow
`
Used a test page on my github and a master branch. If you have any suggestions how to pass that let me know?

**Comment by xmonader** [comment]
Hello @mveplus  

I think the documentation for the blog isn't there yet, here's an example of a blog repo https://github.com/threefoldfoundation/blog_threefold

Here is the description of the repository layout needed for a blog, website and a wiki
https://github.com/crystaluniverse/publishingtools/blob/development/docs/repo_layout.md (will be compiled in the manual info very soon)


Here are some examples you can test out

- website https://github.com/xmonader/www_incubaid
- blog https://github.com/threefoldfoundation/blog_threefold
- wiki https://github.com/threefoldfoundation/info_gridmanual
