### ISSUE TITLE
GE: Jumpscale can't find network

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#891]
I am trying to create an S3 reservation for performance testing in preparation for the Kapsch account. We are doing this in our Vienna2 data centre.

I created the network reservation just fine: 
https://explorer.grid.tf/explorer/reservations/11540
Network name: perftest-vie2

However, when I then try to create the Minio+ZDB reservations, Jumpscale can't find the network. I get this error:
`error: no network found for: perftest-vie2`

See the script I used attached. Its running the create_minio() method.

[auto_depl_perftest.py.txt](https://github.com/threefoldtech/home/files/5217982/auto_depl_perftest.py.txt)

**Comment by joefoxton** [comment]
I think i found a problem... the node I'm trying to use as the main minio node is listed in the network reservation output as a "bad node"

CpssVPA4oh455qDxakYhiazgG6t2FT6gAGvmPJMKJL2d

Investigating more...

**Comment by zaibon** [comment]
Can you double check if the user that created the network is the same that is creating the containers ?
In https://explorer.grid.tf/explorer/reservations/11540 we can see it's user [greenedgeagent.3bot](https://explorer.grid.tf/explorer/users/234). Is the same user is used to create the containers ?

**Comment by joefoxton** [comment]
Yes it is the same user. We have just discovered that the node I tried to use has actually been taken off the grid, and our hardware inventory was not yet updated. Stand by while we fix this and try again.

**Comment by joefoxton** [comment]
This ended up being caused by Node ID changes not being recorded in our inventory sheet. The Node IDs were updated when we took nodes of the grid and re-added them. Closing this.
