### ISSUE TITLE
expiration date not ok on capacity pool

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#894]
![image](https://user-images.githubusercontent.com/6021844/93347792-c7f68b00-f835-11ea-8c16-7b1a8e3f46cf.png)

I bought for 1cu/su for 1 day

now it says years, so cannot be true

**Comment by zaibon** [comment]
it can if the workloads you deployed comsume less the 1CU and 1SU

**Comment by zaibon** [comment]
From the number show it look correct to me. You have only `0.00104` active SU and you have a 86399 SU available:
```python
active = 0.00104
available = 86399
seconds = available / active
years = seconds / 31556952 = 2.63
```
So at this rate you have enough for 2.6 year which seems to match the expiration date in 2023.
