### ISSUE TITLE
Hosted 3Bot should be able to track deployed solutions and take actions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#896]
Hosted 3Bot is getting deployed and backed up using [3Bot deployer](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/threebot_deployer/threebot_deployer.md).  The current situation is 
- 3bot connect user logs into the 3bot deployer website
- ask to provision a new 3bot around 3 or 4 workloads
- 3bot deployer creates a pool and a network for that user e.g `username.3bot_apps`, this pool and the network and all of the workloads needed for a 3bot are `owned` by the 3bot deployer
- hosted 3bot gets initialized and backup is restored if any
- user can access the hosted 3bot

What we are trying to achieve is that hosted 3Bot can monitor/track/take actions on the solutions that will get deployed from it. Typically what needs to be done is to have these solutions and the 3Bot in the same network

Current blockers are
- the network of the hosted 3bot is owned by the `3bot deployer` website (you can't transfer the pool and network afterwards to the newly created identity and we don't know it ahead of time)
- You can't add a new network in runtime to the container

## Suggest solution: 3bot delegate

3bot delegate: is an API server exposed on public internet to be reachable from the 3bot, only reports the status of the solutions it tracks (either push if 3bot is reachable online or pull if not) with some identification so it doesn't get abused/faked

With one more level of indirection we can probably solve that problem, we create a new solution `3bot delegate`, that will be part of a mgmt network and when deploying solutions you can ask to add self-healing to it which is basically allowing a `3bot delegate` to be part of its network. 3bot can have delegates across multiple networks too if needed

## Suggested solution from despiegk 

We create the identity of the user in the (threebot deployer) and use it to sign the workloads of that 3Bot and delete it from the deployer after the 3bot is initialized (requires explorer client changes to use different identity while deployment)

**Comment by xmonader** [comment]
# Suggested solution from @despiegk 

We create the identity of the user in the (threebot deployer) and use it to sign the workloads of that 3Bot and delete it from the deployer after the 3bot is initialized

**Comment by zaibon** [comment]
> the network of the hosted 3bot is owned by the 3bot deployer website

To me this is the biggest problem. In term of true decentralization we or any other party should not end up owning any of the capacity or workloads or private key from another user.

To solve this issue I see 2 things we could do:
- Provide the tool for the user to create its own pool and reservation and let him deploy its own 3Bot. This is the safest and the best solution in therm of decentralization. It also probably has the least easy UX. And even though we said 3Bot are for technical user, we know the target audience is actually anyone with or without any technical background.
So or we create this through the 3bot app with a minimum action required by the user, or maybe we can investigate something like metamask which allow to sign payload from your phone or browser while keeping your private keys safe.

- Second idea is to modify a bit the explorer API and let anyone create pools and workloads on behalf on anyone else. 
For the pool, the user would then just have to send some token to the required address.
For the the workload, it would be marked as own by the 3Bot identity, but without its signature. The user would then only need to sign the workload afterwards to authorize the deployment of its 3Bot.
In this solution again we are not in the middle, we do not at any time have access to the 3bot private key and the user own everything from its own deployments.

> 3Bot delegate API proposal

I do find this quite cumbersome and it seems this solution is the one that requires the more work. It also requires some rethinking of the smart contract for IT protocol, which I would love to avoid.

>  solution from despiegk

This to me doesn't match the basic requirement to not be in possession of another user private key. This alone is a show stopper.

> You can't add a new network in runtime to the container

This blocker will most probably remains, There is no way to "edit" a container at runtime at the moment and there is no plan to change this. Again the smart contract for IT doesn't have this concept.

**Comment by m-motawea** [comment]
for connecting the deployed 3bot to another network (mgmt), I tried connecting two network resources with different network ids but same network range same way as we add access to users by adding a wireguard peer between them but still no reachability.
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/488161
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/488160

after reaching out to @delandtj, this approach is not possible as well.

**Comment by xmonader** [comment]
not for discussion anymore
