### ISSUE TITLE
GE: Haven't been able to deploy a hosted 3bot (mainnet)

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#897]
After multiple tries by multiple people from different places with different wallets, we have yet been unable to deploy a hosted 3bot on mainnet. We consistently get the following error:

`Failed to create container on node Aiux6s3V8wg398FHzWWy3LC81C8vuP4JLkck7uR9T3pD 18075. The resources you paid for will be re-used in your upcoming deployments.. Please use the refresh button on the upper right to restart the chatflow`

![Screenshot 2020-10-05 at 18 48 48](https://user-images.githubusercontent.com/1249806/95108407-8c1b5b00-073b-11eb-8d82-527a5b6d6c51.png)

**Comment by xmonader** [comment]
https://explorer.grid.tf/api/v1/reservations/workloads/18075 

message: "failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd",


the issue is in progress https://github.com/threefoldtech/zos/issues/910

**Comment by joefoxton** [comment]
Thanks @xmonader. We'll close this issue and follow #910
