### ISSUE TITLE
GE: Unable to install threebot_deployer: Certificate Issues (2.1)

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#898]
When we try to install the threebot_deployer package via the 3bot Admin Dashboard on mainnet 2.1, we get the below error. 

Please note that the certificate domain is testnet rather than mainnet - maybe this is the problem?

`127.0.0.1 - - [2020-10-08 07:48:24] "POST /admin/packages/add_package HTTP/1.0" 500 212 9.743754
127.0.0.1 - - [2020-10-08 07:49:08] "GET /authorized HTTP/1.0" 200 230 0.004586
2020-10-08 07:49:08.474 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method add_package from actor admin_packages to client ('127.0.0.1', 48384)
2020-10-08 07:49:17.870 | ERROR    | jumpscale.sals.nginx.nginx:generate_certificates:186 - Generating certificate failed IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: deploy3bot.testnet.grid.tf
   Type:   unauthorized
   Detail: Invalid response from
   https://deploy3bot.testnet.grid.tf/auth/login?next_url=/.well-known/acme-challenge/FCsHMe1HGGzG4d_Du_pQxlqPd-sAV7iHj7TqPNP7mvU
   [104.248.47.158]: "<!DOCTYPE html>\n<html lang=\"\">\n\n<head>\n
   \n    <meta charset=\"utf-8\">\n    <meta
   http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

Saving debug log to /root/sandbox/var/log/certbot/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for deploy3bot.testnet.grid.tf
Using default address 80 for authentication.
Waiting for verification...
Challenge failed for domain deploy3bot.testnet.grid.tf
http-01 challenge for deploy3bot.testnet.grid.tf
Cleaning up challenges
Some challenges have failed.`

**Comment by xmonader** [comment]
It's one of threefold packages, that's going to be moved into its own project in its own repository, it requires more configurations other than just installing the package https://www.github.com/threefoldtech/js-sdk/tree/development/docs%2Fwiki%2Fthreebot_deployer%2Fthreebot_deployer.md it's only interesting if you want to run your own threebot deployer service

**Comment by joefoxton** [comment]
Ok I think I understand...

We are currently writing our own deployment scripts on Zaibon’s advice. I assume this means that we’ll use ThreeFold’s deployer service, and not need to deploy our own. Is that right?

Out of curiosity, in what case would we want to run our own deployment service?

(closing the ticket)
