### ISSUE TITLE
GE: Where is threebot shell?

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#899]
In SDK 2.0, we could launch "threebot shell" so we run our python deployment scripts. Now it appears that threebot shell is no longer available, or hidden somewhere that we can't find. Where is it?

**Comment by xmonader** [comment]
It's called jsng right now, but probably we can alias it too under threebot shell :)

**Comment by joefoxton** [comment]
Zaibon has now educated us on how to run our deployment scripts in 2.1/2. Closing!
