### ISSUE TITLE
Define MVP for grid launch

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/home#90]
The document : https://docs.google.com/document/d/1UssLf_eE-ojCx66kkfCcQrGGI09yi1IDHXt5oh0vT9g/edit
describe the idea kds has regarding how we could implement the different types of 3Bots required to make the grid reality.

We should all go over it and takes notes about what we think about this document:
- What is doable
- What is not or not a good idea
- Technology wise, what do we have, what still to be done

How of these notes, we should build a real feasible goal if what we want to have for end of this sprint.

**Comment by zaibon** [comment]
Question that needs to be anwered:
- [ ] Which version of jumpscale ?
- [ ] Status of DigitalMe framework
  - [ ] Schemas
  - [ ] BCDB
  - [ ] Gedis
  - [ ] OpenResty
  - [ ] Integration of all the above into a usable framework
- [ ] Blockchain
  - [ ] JS client

**Comment by GlenDC** [comment]
Will already look into JSX, as I have a feeling that one will be the required one.

**Comment by zaibon** [comment]
Required primitives defined in :https://docs.google.com/document/d/1_IhmwzF6pNmYM_LgKab7WeUlARcixFLmvNXjYYYLVBw/
