### ISSUE TITLE
should warn which browser to use

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#901]
![image](https://user-images.githubusercontent.com/6021844/95474648-a5afe300-0985-11eb-82b3-2907e7e93197.png)

if people open browser this way we should show them intermediate page where we tell them to use a browser in non protected mode safari and what to do, we need to give them info

because now 99% of people will get stuck !

**Comment by robvanmieghem** [comment]
Let's fix the problem decently:  https://github.com/threefoldtech/home/issues/902
