### ISSUE TITLE
Capacity Pool Creation should allow setting a "reference"/name for the pool.

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#914]
Currently, the code to create a pool is as follows:

```python
j.sals.zos.pools.create(cu, su, farm_name, PAYMENT_TYPES)
```

This returns an ID for the pool.

However, this is going to be troublesome for management if a farm has many capacity pools and no way to know which one is which. With the solution above, farmers must manage a table of pool/customer references. If this table is lost, or becomes corrupt, there is no way to identify pools.

A preferred approach would be something like:

```python
j.sals.zos.pools.create(cu, su, farm_name, PAYMENT_TYPES, reference="MYCUSTOMID1")
```

This would allow farmers to assign their own references, which would provide more options: refs based on patterns, customer-names as refs, refs linked with billing references, etc.

**Comment by xmonader** [comment]
probably related to metadata request from earlier too? @zaibon https://github.com/threefoldtech/js-sdk/issues/382#issuecomment-671038618
