### ISSUE TITLE
Jupyter notebook does not execute Jumpscale scripts

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#920]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/13766992/97855974-062c0900-1d15-11eb-95b1-8fac13692c57.png">

In my 3bot online on testnet I tried to create a simple notebook to check (and hopefully improve) the jumpscale code examples in the manual.  I encountered the above error and Thabet explained to me that "create an issue, it basically means jupyter is using global python instead of making it use the jsenv python"

So can you please update the jupyter notebook to use the jsenv environment?  

Secondly - can I fix this in my threebot or do I have to do a pull request for some (updated) code?

**Comment by dmahmouali** [comment]
Typo in the `import` should be `from jumpscale.loader import j` as below:
![image](https://user-images.githubusercontent.com/36021484/97869169-a3893c00-1d19-11eb-919e-f7d657e7b32f.png)

And there is another [issue](https://github.com/threefoldtech/js-sdk/issues/1591) related to the notebooks package, will fix it.
