### ISSUE TITLE
Review how cloud units are computed from workload definition

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#922]
Sub-task:
- [x] https://github.com/threefoldtech/js-sdk/issues/1423
- [x] [Update tfexplorer](https://github.com/threefoldtech/tfexplorer/issues/207)

**Comment by zaibon** [comment]
Small simulator to play with the new formulas: https://gist.github.com/zaibon/d7d3ed58be2ec2792bd3284f28604266
This requries to checkout the branch https://github.com/threefoldtech/js-sdk/pull/1492

**Comment by andhartl** [comment]
looks good.
