### ISSUE TITLE
Create a unify view showing all the nodes running 0-OS

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/home#924]
at the moment we are showing node at 3 different explorer:

devnet: explorer.devnet.grid.tf
testnet: explorer.testnet.grid.tf
mainnet: explorer.grid.tf

As a user I want to go to one domain / website and see all existing nodes and be able to filter per network.

Propose solution for this:
- extract the fronted code of the explorer
- modify the fronted so it gets its data from the 3 different explorer APIs.
- add some filtering and color code to differentiate nodes from different network

**Comment by sasha-astiadi** [comment]
who can be the owner for this @zaibon

**Comment by xmonader** [comment]
it's live now on https://explorer.threefold.io/
