### ISSUE TITLE
GE: S3 permanent object delete (including version history)

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#930]
It should be possible to permanently delete a version of an object, or all versions of an object, through the web UI and via any client that supports that part of the API.

**Comment by muhamadazmy** [comment]
This functionality is supported by the API already (standard S3 protocol) all compatible clients can do it. the UI on the other hand is again built as a "minimalistic" file browser view on top of this API hence it does not support it (and it will not support it). 

What you suggest is a new complete file browser that uses the full capabilities of S3 protocol, which is out of scope of our implementation
