### ISSUE TITLE
GE: S3 version restore

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#931]
It should be possible to review the list of versions for an object using the web UI, and to select one to be restored.

Restoration should roll *forwards*, creating a new version on top of the current one which is a clone of the version selected for restore. For example:

```gherkin
Given I have versions [A, B, C, D]
When I restore version B
Then I will have versions [A, B, C, D, E]
And the objects at versions B and E are the same
```

**Comment by muhamadazmy** [comment]
This operation not even supported by the S3 API ? are we diverting from S3 ? 
As commented on issue #930 changes to the UI is out the scope of this project.

**Comment by muhamadazmy** [comment]
While the implementation you suggest is actually doable in our backend, the S3 API does not have a call that we can handle to do this operation. It means we need to add a new standard call that does this, hence it's not compatible with any of the standard s3 clients.
