### ISSUE TITLE
GE: Minio transaction log replication/distribution

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/home#935]
Currently the minio tlog is a single point of failure; if the Zdb which contains the tlog is lost, there is no way to recover.

We need to have these tlogs actively duplicated, replicated, or distributed so that the SPOF is eliminated.

**Comment by muhamadazmy** [comment]
related to #932

**Comment by gmachtel** [comment]
The current system is already master/slave failover capable, meaning that if primary goes away, you can go to secondary and continue. So the statement that there is a single point of failure is wrong. 
The question is how to then regenerate the data again. 
- In the current setup it requires a copy to a third location and then power on so there is no risk for data loss afterwards. 
- tests are ongoing with fuse layer to make this whole process more robust, based on the test results we'll see whether this is viable solution.
