### ISSUE TITLE
GE: Can't use Backup service

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#953]
When we try to use the backup service in our greenedgeagent.3bot hosted on Digital Ocean, we get the following below error message. Two questions:
- We never set a password - what could it be?
- Why is this not available when we host our own 3bot?

![Screenshot 2020-11-11 at 13 50 38](https://user-images.githubusercontent.com/1249806/98813766-06b75480-2425-11eb-9b0d-6a8def128221.png)

**Comment by xmonader** [comment]
You want to use the minio option not the marketplace option

**Comment by joefoxton** [comment]
What’s the password? You don’t get a password with Minio, only access key and secret key.

**Comment by xmonader** [comment]
@joefoxton yes, it's restic password. Should add some more tooltips https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#minio-server

**Comment by joefoxton** [comment]
Ah so the password field in the dialog is meant to set the password?

**Comment by xmonader** [comment]
> Ah so the password field in the dialog is meant to set the password?
> […](#)
> On 11 Nov 2020, at 4:52 PM, xmonader ***@***.***> wrote: ﻿ @joefoxton yes, it's restic password. Should add some more tooltips https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#minio-server — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, exactly

**Comment by joefoxton** [comment]
@xmonader Maybe you should change the field name to "New Password" or "Set the Password"

Closing this
