### ISSUE TITLE
Showstoppers for delivering VDC project at EOM Nov

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/home#955]
Elements not cleared out or on critical path for for delivering  VDC at end of November: 
- [ ] K8S Admin panel : QT one ? Status ? 
- [ ] K8S IP setup in K8S
- [ ] Make the flow as lightweight as possible

**Comment by xmonader** [comment]
to be followed in the project https://github.com/orgs/threefoldtech/projects/121
