### ISSUE TITLE
deploy 3bot online results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/home#957]
![image](https://user-images.githubusercontent.com/13766992/99935866-22065600-2d7b-11eb-95e0-bc4f5d91f5b9.png)

But 3bot is reported live in overview
![image](https://user-images.githubusercontent.com/13766992/99935909-419d7e80-2d7b-11eb-80c5-d87eea911796.png)

**Comment by waleedhammam** [comment]
It was resolved in https://github.com/threefoldtech/js-sdk/issues/1721

- Happened because change in rust version leaded to unexpected errors in zinit, it's live now and works ok
