### ISSUE TITLE
GE: Versioning per bucket + Can delete objects completely

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#962]
S3 versioning has been implemented as always-on, rather than configurable per bucket. One of the consequences is that it has become impossible to fully delete objects, which will result in unexpected storage use. To be S3 compliant, we should allow:
- Can switch versioning on or off per bucket (Its ok for this to be a permanent config, not able to be switched off)
- Can delete objects completely when versioning is off

**Comment by gmachtel** [comment]
Status now: Code has been made on deletion but this needs to be tested very thoroughly, as there is a risk for data loss. Activation of code not yet planned.

**Comment by joefoxton** [comment]
Just to clarify: are you enabling a versioning on/off switch for each bucket? Or for an entire reservation?

A DELETE request has the following use cases:

When versioning is enabled, a simple DELETE cannot permanently delete an object.
Instead, Amazon S3 inserts a delete marker in the bucket, and that marker becomes the current version of the object with a new ID. When you try to GET an object whose current version is a delete marker, Amazon S3 behaves as though the object has been deleted (even though it has not been erased) and returns a 404 error.
The following figure shows that a simple DELETE does not actually remove the specified object. Instead, Amazon S3 inserts a delete marker.

To permanently delete versioned objects, you must use DELETE Object versionId.
The following figure shows that deleting a specified object version permanently removes that object.



https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingObjectVersions.html
