### ISSUE TITLE
GE: Enable hardware monitoring in ZeroOS

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/home#963]
Ability to monitor the health of our hardware, including but not limited to CPU, Disk, Memory, Network usage, health, temperature.

Support and enable HPE ILO

**Comment by gmachtel** [comment]
As it suggested to have snmp enabled in zero-OS, I will try to explain why we see it as NOT the path forward for implementing monitoring on zero-OS. 
Main counterarguments are:
- snmp uses MIBs (management information bases) to describe system status and information. This is a pretty heavyweight setup which goes against our ambition to keep zero-OS as lightweight as possible. Moreover these MIB would need to be adapted to generate the right metrics. 
- snmp would need quite a lot of customized development to make it fit into the zero-OS: bridge, all to be put into namespaces, an snmp daemon in each of these namespaces (and running daemons within each of these namespaces). Running daemons within zero-OS is not in line with the lightweight architecture of zero-OS. 
- Many security issues have been reported on snmp, example on https://www.cvedetails.com/product/2253/Net-snmp-Net-snmp.html?vendor_id=1293 . When integrating snmp into zero-OS, this would not only be harmful to the monitoring on its own but could also induce security flaws into zero-OS itself, whcih is something that we want to avoid at any price.
