### ISSUE TITLE
Z-STOR needs to be usable for more usecases

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#966]
## deliverables

- [ ] see https://github.com/threefoldtech/0-stor/milestone/3
- [ ] JS-NG script which provisions ZDB's for the example
- [ ] JS-NG script as example to stor/retrieve some big file using erasure coding
- [ ] JS-NG script as example to stor/retrieve some small file using 3x replication (does zerostor support this?)

**Comment by xmonader** [comment]
moved back to the right repo
