### ISSUE TITLE
Preparing production server migration

### ISSUE THREAD

**Issue by maxux** [threefoldtech/home#97]
The production server hosting hub, etc. still runs an Ubuntu with Docker based isolation. It's time to move to Zero-OS and flist-containers.

In order to achieve a fully working production environment, issue https://github.com/threefoldtech/0-core/issues/63 **needs** to be solved.

This story is about:
- [ ] Create different flists:
  - [x] Create rebuildable flist for `frontend (caddy)` service
  - [x] Create rebuildable flist for `0-hub` stuff
  - [ ] Create rebuildable flist for `0-bootstrap` stuff
  - [ ] Create rebuildable flist for `geoip` service
  - [ ] Create rebuildable flist for `capacity-server` service
  - [ ] Create rebuildable flist for `mongodb` service
- [ ] Test compatibilty with Zero-OS container
  - [ ] Get a working `frontend `
  - [x] Get a working `0-db` backend
  - [x] Get a working `0-hub` (depends on zdb backend)
  - [ ] Get a working `0-bootstrap`
  - [ ] Get a working `geoip`
  - [ ] Get a working `mongodb-server`
  - [ ] Get a working `capacity-server` (depends on mongodb)

**Comment by zaibon** [comment]
@rkhamis can you have a look and already mark what builders we already have or not.
Also, is there any documentation about how building is supposed to work since jsx ?
