### ISSUE TITLE
Add smaller VM size

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/home#977]
Please add smaller VM size: 1 vCPU, 1 RAM(GiB), 25 Storage (GiB). Is needed for VDC sizing and cost.
https://manual.threefold.io/#/capacity_kubernetes?id=vm-sizes

**Comment by DylanVerstraete** [comment]
Tasks: 

- [ ] Update zos provisioning code to support new sizes: 
- [ ] Update explorer to support new size 
- [ ] Update SDK to support new size: 
- [ ] Update documentation:
