### ISSUE TITLE
tfagent tool

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/home#979]
Create a `tfagent` tool:

- ability to load a stellar wallet
- connect to the libp2p network, with peer ID derived from the wallet
- send commands over libp2p to other nodes:
  - get wallet address
  - get workload status
  - deploy workload
- toml config file
- use existing json formats for workloads as used by explorer
- save deployed workloads somehow (local file?)
- 

As a farmer:
- config needs one ore more hosting policy, containing info for nodes such as how much to charge, to what address, ...
- ...

The main tool will need to run in server mode as it needs to periodically perform payments. However we also need some ability to modify its state at runtime. Suggested we create 2 tools: a main `tfagent` server, and a `tfagentctl` command line tool. Communication for now can happen over a http server exposed on localhost by the `tfagent`, functioning as some kind of admin interface.

There will also need to be logging (to file and to telegram). For now, lets start with a simple logger interface, and a NOOP impl, we can easily add logging functionality once this core functionality is done.

**Comment by despiegk** [comment]
need to revisit specs, because looks like this approach won't bring us there
