### ISSUE TITLE
use real TFT on mainnet /  testnet / devnet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/home#988]
use real TFT asset on mainnet and testnet, devnet 

- [x] tfexplorer https://github.com/threefoldtech/tfexplorer/pull/259
- [x] js-sdk https://github.com/threefoldtech/js-sdk/pull/2071
- [x] testnet reset
- [x] testnet farms reboot with main TFT wallets
- [x] devnet farms reboot with main TFT wallets

- [x] wikis remove all references for testnet TFT

for explorer changes needed are divide by 10 for the prices in case of testnet and by 100 in case of devnet

**Comment by LeeSmet** [comment]
Explorers are updated with the network discount code and the devnet and testnet explorers systemctl services have been reconfigured to use mainnet. All explorers send their funds to the same foundation wallet. Existing escrow accounts have been flushed on both devnet and testnet to ensure that everyone will get a new mainnet escrow on his/her next reservation.

Together with this, "freefarm" on both devnet and testnet has had its wallet address changed (also to the foundation address for now, owners of these farms can change that if so required) to mainnet, so reservations on those can proceed. Owners of other farms on these networks will need to update their wallet address manually. For devnet, this will the devs (mostly belgium team) when booting ephemeral vms to test some new stuff. For testnet, I'm not sure if there are other farms, but if there are, these are likely owned by actual unrelated farmers, and they will need to be notified to update their wallet address linked to the farm to now be a mainnet address before capacity can be reserved again on those farms.

FYI, priorly purchased existing capacity on dev and testnet can still be used

**Comment by sasha-astiadi** [comment]
I will take care of wikis and manuals

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-sdk/pull/2071

**Comment by sasha-astiadi** [comment]
tuesday: reset

**Comment by sasha-astiadi** [comment]
tesnet is reset

**Comment by sasha-astiadi** [comment]
reset done
