### ISSUE TITLE
Jimber: All marketplace apps should be using TFConnect as an SSO login system.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/home#990]
This is only for apps that don't have ThreeFold Connect login integrated yet. If it already has ThreeBot Connect as the ONLY valid authentication method, this should not be implemented and the checkbox can simply be marked finished.

For questions or assistance with implementation, you can ask @tobiaschielens 

How to implement threebotlogin: 
 - Example SAML integration can be found here: https://github.com/JimberSoftware/threefold-login-saml
- Change application and use 
Javascript SDK https://github.com/threefoldtech/threefold-login-js-sdk
- Change app to use python https://github.com/threefoldtech/threefold-login-python-sdk
Implement in the following apps:

Todo Jimber:
 - [x] Explore how we can use the SAML integration for each application
- [x] Create standardisation model for the SAML integration
- [x] Create pip package for threebot login 
- [ ] Implement SSO or ThreeFold Connect auth for all jimber apps

**Comment by sasha-astiadi** [comment]
issue needs to stay on home repo / cant be moved to vdc-solution-chart repo because it involves different repos. as solution I create a note issue on vdc chart repo here.

**Comment by sasha-astiadi** [comment]
removed bc nodes from list of apps

**Comment by sasha-astiadi** [comment]
i divide this into 2 issues. this is for jimber. other one is created for egyptr.

**Comment by tobiaschielens** [comment]
Python pip package can be found here: https://pypi.org/manage/project/threefoldlogin/releases/
Documentation: https://github.com/threefoldtech/threefold-login-python-sdk

**Comment by xmonader** [comment]
@ken-de-moor @tobiaschielens what is the status here? do you have any apps from Jimber with tf connect authentication?

**Comment by ken-de-moor** [comment]
We can close this specific issue, all our apps already have TF connect integrated now, the issue itself is that file browser & office stuff still needs bug fixes and implementation changes. But the TF connect itself is implemented.
