### ISSUE TITLE
VDC: All marketplace apps should be using TFConnect as an SSO login system.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#991]
related story from jimber's side: https://github.com/threefoldtech/home/issues/990

This is only for apps that don't have ThreeFold Connect login integrated yet. If it already has ThreeBot Connect as the ONLY valid authentication method, this should not be implemented and the checkbox can simply be marked finished.

For questions or assistance with implementation, you can ask @tobiaschielens

How to implement threebotlogin:

- Example SAML integration can be found here: https://github.com/JimberSoftware/threefold-login-saml
- Change application and use
Javascript SDK https://github.com/threefoldtech/threefold-login-js-sdk
- Change app to use python https://github.com/threefoldtech/threefold-login-python-sdk
Implement in the following apps:

Python pip package can be found here: https://pypi.org/manage/project/threefoldlogin/releases/

Documentation: https://github.com/threefoldtech/threefold-login-python-sdk

 Implement SSO or ThreeFold Connect auth for all marketplace apps:
 Possibly a lot of these already have ThreeFold Connect as only login method, just mark checkbox if they do
 
- [ ] Cryptpad
- [ ] etcd
- [ ] Gitea
- [ ] Kubeapps
- [ ] Mattermost
- [ ] monitoring-stack
- [ ] Peertube
- [ ] Publishingtools
- [ ] Taiga
- [ ] Tomochain
- [ ] ZeroCI

**Comment by ken-de-moor** [comment]
Python pip package can be found here: https://pypi.org/manage/project/threefoldlogin/releases/

Documentation: https://github.com/threefoldtech/threefold-login-python-sdk

**Comment by xmonader** [comment]
closing in favor of 
https://github.com/threefoldtech/js-sdk/issues/2584 and https://github.com/threefoldtech/js-sdk/issues/2585
