### ISSUE TITLE
need release note on components for 3bot 2.4

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#993]
- [x] js-sdk 11.1

- [x] js-ng 11.1

- [x] marketplace 2.4 / vdc charts 2.4 repo
- [ ] tft stellar v1.2.1

**Comment by rkhamis** [comment]
js-ng: https://github.com/threefoldtech/js-ng/releases/tag/untagged-58f0e2103417eb38c211
js-sdk: https://github.com/threefoldtech/js-sdk/releases/tag/untagged-e4d0a96a07211923c50b

marketplace and vdc are included in the sdk release notes

**Comment by sasha-astiadi** [comment]
@rkhamis marketplace needs its own release on vdc chart repo.
i will create one including filebrowser, tf meet and blockchain node validators and request your review

**Comment by sasha-astiadi** [comment]
@rkhamis pleas review. https://github.com/threefoldtech/vdc-solutions-charts/releases/edit/untagged-9caecc8346098f3e5db4

and unassign yourself if its reviewed and ok

**Comment by rkhamis** [comment]
@sasha-astiadi looks good.

**Comment by sasha-astiadi** [comment]
later for tft stellar
