### ISSUE TITLE
need to define tfgrid_2.5 project

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/home#995]
- also with new version nr's for all components which require an update
- the wiki's in home repo need update for the upcoming 2.5 release (link to components)

do it as a pull request ask my feedback please (kristof)

make sure we have all open issues on component versions related to 2.4 or 2.5 or on later or next

lets define the next release

**Comment by sasha-astiadi** [comment]
high level task,
release versioning of product components for 2.5 will be tracked here on this [2.5 product sheet](https://docs.google.com/spreadsheets/d/1xrzsHZzGyUgQyfgXh5B54N7KLMk3lpf1FJKtLbfSl60/edit?usp=sharing)

**Comment by sasha-astiadi** [comment]
[circle stories]( https://circles.threefold.me/project/team_product/taskboard/january-2021?milestone=73)
[3bot 2.5 project](https://github.com/orgs/threefoldtech/projects/132)
[tfgrid 2.5 project ](https://github.com/orgs/threefoldtech/projects/133)
[2.5 product sheet](https://docs.google.com/spreadsheets/d/1xrzsHZzGyUgQyfgXh5B54N7KLMk3lpf1FJKtLbfSl60/edit?usp=sharing
)

[PR For home repo - grid and 3bot 2.5 edits](https://github.com/threefoldtech/home/pull/996)
