### ISSUE TITLE
STORY: Clean up digital ocean account, there should be 0 left

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#997]
for the ones we are not sure
make list and make sure kristof his key is in as ssh key
we can make backups of right directories where we are not use
can use restic/ssh (kristof can make tool to do it)

**Comment by sabrinasadik** [comment]
Already on it, see https://github.com/threefoldtech/tf_operations/issues/1237

**Comment by sabrinasadik** [comment]
Removed everyone's access so no deployments happen outside of the Grid.
