### ISSUE TITLE
Create more test use cases for evdc on testlodge

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/home#999]
I created a manual on how to become a grid tester (by invitation only for now) on our testing platform Testlodge. 
https://manual2.threefold.io/#/test_grid

next steps on QA:| @weynandkuijpers @arrajput 
create more test use cases for 3bot deployer and evdc on testlodge

**Comment by weynandkuijpers** [comment]
- kubtectl (find some example ones on the Internet and deploy
- planetary filesytems - loca linstall with TF Grid DB disks

**Comment by abdulgig** [comment]
For a new eVDC, we have a test suite here => https://threefold.testlodge.com/projects/40893/suites/179639

**Comment by despiegk** [comment]
lets close this one, make sure we know what we will test for TFGrid 2.7

see #1040

**Comment by weynandkuijpers** [comment]
Trasafer testplan knowledge to the wiki - make the wiki the master source of test plan information and position testlodge as the execution engine of it.
- [] create all testplan content in wikis.  extract existing information from testlodge
- [] extract tesplan logic to testlodge (automation?)  If nto possible cancel testlodge.
- [] make wikii version the master
- [] if testlodge extraction is not possible -> use github issues + projects as testing tools.
